### ISSUE TITLE
[BUG] 一加5 phoenix ROM Andriod P开机卡第二屏

### ISSUE THREAD

**Issue by NewLife850** [ElderDrivers/EdXposed#101]
卡在第二屏无法开机

无模块

EdXposed:2.20

Riru:0.2.9.9

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[xposed_error_20190222_221837.log](https://github.com/ElderDrivers/EdXposed/files/2894419/xposed_error_20190222_221837.log)

**Comment by NewLife850** [comment]
beta2依旧翻车。。这是beta2的日志
[xposed_error_20190222_233035.log](https://github.com/ElderDrivers/EdXposed/files/2894642/xposed_error_20190222_233035.log)

**Comment by solohsu** [comment]
Fixed with 921ac4d095457208d0b61673b0627dded1386bba
Try this SNAPSHOT build:
[magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip](https://github.com/ElderDrivers/EdXposed/files/2948136/magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip)
