### ISSUE TITLE
Previously working module no longer works after upgrade

### ISSUE THREAD

**Issue by bggold** [ElderDrivers/EdXposed#102]
previously working modules no longer work after upgrading to 2.9.9-beta2 from 2.9.8.

Tried 2 different modules and neither is working.
[xposed_error_20190222_084810.log](https://github.com/ElderDrivers/EdXposed/files/2894934/xposed_error_20190222_084810.log)

**Comment by solohsu** [comment]
02-22 08:39:58.316   739   739 E EdXposed-Bridge:   File does not exist
Try to uncheck and check again the modules in the module list. And reboot.

**Comment by bggold** [comment]
I did and even removed and reinstalled them.

**Comment by solohsu** [comment]
No, you have to uncheck and check it yourself unless installer has sent a notification to notify update done.

**Comment by bggold** [comment]
I did uncheck and check the module and that did not work.  I also uninstalled and reinstalled the module and that did not work.

**Comment by solohsu** [comment]
OK, but I can't get more useful info from the logs.

**Comment by bggold** [comment]
So logs do not show anything?

**Comment by bggold** [comment]
Very strange I can install new modules and they work.  If I try to reinstall any module that was installed since 2.9.8 they just dont work.  Is there any residual files or folders that dont get cleaned up after uninstalling the xposed installer and 2 magisk modules?

Thanks

**Comment by solohsu** [comment]
Which installer app you are using?

**Comment by bggold** [comment]
2.2.0 also tried 2.0.0 and original by dvdandroid.  It is very strange.  I can install modules that I have never used before and they work but the ones I have installed before do not.

**Comment by cwkfr** [comment]
I can confirm this but after compiling c94f5543c04e5469de27a055b3bce2d36f0ea9ea with Riru Core v15 and EdXposed Installer v2.2.0, in my case Xinsta start to work normally. I forgot which commit of EdXposed I was using before.

**Comment by bggold** [comment]
Yeah I grabbed the one on XDA that had 3 additional commits than beta 2 and I was able to get one of the modules to work that did not on beta 2.  Hopefully beta 3 will fix the other one.  I'm glad C3C0 stepped in with the issue.

**Comment by bggold** [comment]
It seems that the first module that worked is not going to work.  It fails to load and looks like it is referencing the original xposed by name.  The second module is working now.
