### ISSUE TITLE
[BUG] 微信“收藏”引起闪退

### ISSUE THREAD

**Issue by rxzcums** [ElderDrivers/EdXposed#111]
**什么情况/What happened?**

使用微x时，点击微信-我-收藏，崩溃。
我的微信版本6.6.7

**Xposed模块列表/Xposed Module List**
![screenshot_2019-02-26-19-53-44-851_com solohsu android edxp manager](https://user-images.githubusercontent.com/11990604/53411123-a4c07c80-3a00-11e9-9916-9469f86d7bd9.png)

**Magisk模块列表/Magisk Module List**
![screenshot_2019-02-26-19-53-34-310_com topjohnwu magisk](https://user-images.githubusercontent.com/11990604/53411136-ad18b780-3a00-11e9-86a5-17997091800a.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.2.9.9.b2

Riru: v15

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by rxzcums** [comment]
微信升级到7.0.3不闪退了，先关了，后面发现再说。

**Comment by soulpursuit** [comment]
我也是同样的问题

**Comment by soulpursuit** [comment]
问了一圈，大家都有这个情况

**Comment by rxzcums** [comment]
@soulpursuit 也有可能微x的问题，因为7.03不会，升到7.03啊

**Comment by soulpursuit** [comment]
@rxzcums 7.0.3是不会，但是7.0.3无法修改微信来消息铃声，这点比较烦人，我是miui10，点微x里面的替换微信本身铃声也会闪退

**Comment by rxzcums** [comment]
@soulpursuit 这功能我没用过。你看看是下图这个设置吗？
![Screenshot_2019-03-19-14-56-23-140_com tencent mm](https://user-images.githubusercontent.com/11990604/54586178-36973480-4a57-11e9-8508-44f39497744b.png)
