### ISSUE TITLE
[BUG] 最新版引起miui10 小米6设置什么的错误。进程停止运行

### ISSUE THREAD

**Issue by Lockey-J** [ElderDrivers/EdXposed#113]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by Lockey-J** [comment]
[BUG] 最新版引起miui10 小米6设置什么的错误。进程停止运行

**Comment by solohsu** [comment]
v0.3.0.0_b2 已修复。
