### ISSUE TITLE
[BUG] 多用户模式报错

### ISSUE THREAD

**Issue by sus390** [ElderDrivers/EdXposed#117]
用shelter建立的工作账户之内给Root运行EdXposed激活模块以及编辑白名单时报错。
错误日志：Cannot read log/data/user_de/0/org.meowcat.edxposed.manager/log/error.log (No such file or directory)
EdXposed报错：
![screenshot_2019-03-02-15-18-37](https://user-images.githubusercontent.com/45599844/53679009-c754dd00-3d01-11e9-8797-334acf662fc7.jpg)
更改模块报错：
![screenshot_2019-03-02-15-22-12](https://user-images.githubusercontent.com/45599844/53679010-c7ed7380-3d01-11e9-8a1b-3fd5a899e723.jpg)
Magisk:
![screenshot_2019-03-02-15-44-06](https://user-images.githubusercontent.com/45599844/53679079-8c06de00-3d02-11e9-99c1-9a1fd9bbf80e.jpg)

**Comment by Ali-Javadi** [comment]
You should Use EdXposed Installer 2.2.1. you are using EdXposed Manager.

**Comment by sus390** [comment]
The same problem appeared after I had switched  to Edxposed installer 2.2.1.

**Comment by NewBugger** [comment]
but.. actually even today Edxposed does not provide a list support for Work Profile apps. great wishes for this feature.
