### ISSUE TITLE
Latest beta causes temp IMEI loss

### ISSUE THREAD

**Issue by DanGLES3** [ElderDrivers/EdXposed#118]
On the latest 3.0.0 beta my IMEI show as unknown and my sim card isn't recognized,on beta 2.9.9 it works just fine

**Comment by Yihao-G** [comment]
How did you fix it?

For me, looks like some modules caused the issue: 
- android phone vibrator 
- app settings

Do you have any other modules installed causing this problem as well? Did they work well back to version 2.9.9? If so, I suggest you reopen the issue.

**Comment by switchtegrax1** [comment]
Nah,I've just modified the EDXposed to remove a custom sepolicy that was conflicting with my device's imei

**Comment by Yihao-G** [comment]
May I ask what custom sepolicy you removed?

**Comment by switchtegrax1** [comment]
I removed this one supolicy --live "attradd {system_app platform_app} mlstrustedsubject"

**Comment by Yihao-G** [comment]
Thanks.

Btw, this issue looks similar to #131

**Comment by switchtegrax1** [comment]
Yeah,I believe some sepolicies don't play very well with all devices,the dev really needs to find a better alternative to those policies

**Comment by Yihao-G** [comment]
@XspeedPL says it's a bug in Riru. Not sure how he turned out that conclusion though. 

Maybe just reopen it and see what the dev say...

**Comment by XspeedPL** [comment]
The aforementioned policy crashed my device, but only if Riru is active.
It's not directly related to EdXposed, you can put this sepolicy line in whichever Magisk module and it will crash the device.

But it's actually a more complicated issue, related to how the device handles zygote restarts.
Riru uses a binary called zygote_restart that does some black magic in case Riru isn't being loaded normally for some reason.
This "black magic" causes some sepolicies to become unstable (?) like the one mentioned, effectively crashing the device or causing tons of other problems (apps crashing, randomly denied file accesses).

I discovered you can try doing two things:
- disable the Riru `zygote_restarter` by removing it from Riru's `post-fs-data.sh`
- remove the problematic policies from EdXposed's `post-fs-data.sh` and using `setenforce 0` instead

**Comment by XspeedPL** [comment]
You might want to try out the new Magisk 20.2 with latest EdXposed canary version, works like a charm so far for me even with SELinux in enforcing mode.
