### ISSUE TITLE
[BUG] 刷入最新0.3.0.0 beta1 后bootloop

### ISSUE THREAD

**Issue by hineH** [ElderDrivers/EdXposed#119]
**什么情况/What happened?**

无法开机，bootloop

**Xposed模块列表/Xposed Module List**

x-apm ， xprivacyLua ， 全局复制

**Magisk模块列表/Magisk Module List**

riru-core-v15 riru-storageredirect 

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.0.0 beta1

Riru: v15-mod

**相关Logcat/Logcat**

[magisk.log](https://github.com/ElderDrivers/EdXposed/files/2922228/magisk.log)

从rec中提取出的magisk开机log,禁用模块后依旧无法开机，卸载后才能正常使用。
还原回 riru-v15 和 0.2.9.9 beta2 正常使用

**Comment by solohsu** [comment]
v0.3.0.0_b2 应该已经修复了这个问题，有问题可以再重新报
