### ISSUE TITLE
[BUG] Module conflict: MagiskHidePropsConf module and EdXposed module can not be used at the same time. If one module is disabled, another module can be used. The attached file is the log of MagiskHidePropsConf.

### ISSUE THREAD

**Issue by 2220209876** [ElderDrivers/EdXposed#120]
**什么情况/What happened?**
Module conflict: MagiskHidePropsConf module and EdXposed module can not be used at the same time. If one module is disabled, another module can be used. The attached file is the log of MagiskHidePropsConf.
————————————————————————————————————————————
模块冲突：MagiskHidePropsConf模块与EdXposed模块同时启用两者都不能使用，如果禁用一个模块另一个模块可以使用，附件里是MagiskHidePropsConf的日志。

[propslogs 2019-03-02 23-27-05.zip](https://github.com/ElderDrivers/EdXposed/files/2922231/propslogs.2019-03-02.23-27-05.zip)

**Comment by 2220209876** [comment]
MagiskHidePropsConf： https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf
EdXposed ： https://github.com/ElderDrivers/EdXposed

**Comment by 2220209876** [comment]
[
![2019-03-02_23-21-58](https://user-images.githubusercontent.com/7346652/53684030-369ef100-3d43-11e9-82c2-235563c280e3.png)
](url)

**Comment by 2220209876** [comment]
MagiskHidePropsConf开发者回应与一些日志
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/18#issuecomment-469226193

**Comment by JarlPenguin** [comment]
Cannot confirm.

**Comment by 2220209876** [comment]
> Cannot confirm in Moto G5S.
> 
> Running Android Pie

Are the latest versions of the module?

**Comment by JarlPenguin** [comment]
> > Cannot confirm in Moto G5S.
> > Running Android Pie
> 
> Are the latest versions of the module?
> 
> EdXposedInstaller_v2.2.1-release.apk （Black and white list mode is enabled，No resource hooks disabled）
> magisk-EdXposed-v0.3.0.0_beta1-release.zip
> magisk-riru-core-v16.zip

Yes.

**Comment by 2220209876** [comment]
> > > Cannot confirm in Moto G5S.
> > > Running Android Pie
> > 
> > 
> > Are the latest versions of the module?
> > EdXposedInstaller_v2.2.1-release.apk （Black and white list mode is enabled，No resource hooks disabled）
> > magisk-EdXposed-v0.3.0.0_beta1-release.zip
> > magisk-riru-core-v16.zip
> 
> Yes.
Is there any function to enable MagiskHidePropsConf in the terminal?
"su", "props"

**Comment by 2220209876** [comment]
@solohsu v0.3.1.7_beta 解决系统与其他Magisk模块的冲突
未修复和MagiskHidePropsConf 模块的冲突，终端里还是无法运行 "su"- "props"
