### ISSUE TITLE
Dalvik-main space deleted

### ISSUE THREAD

**Issue by QkiZMR** [ElderDrivers/EdXposed#121]
I moved from Xposed to edXposed and from time to time when I'm trying to run some application it finished with following stack trace: 
![Stack trace](http://image.qkiz.pl/di/P3PI/Screenshot_20190228-164121.png)
That is all from stack trace. Sorry for a screenshot but I can't copy from stack trace window.

**Comment by solohsu** [comment]
This should have been fixed with [v0.3.0.0_b2](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.3.0.0_b2)
