### ISSUE TITLE
[BUG] RR-N 卡在开机动画

### ISSUE THREAD

**Issue by eebssk1** [ElderDrivers/EdXposed#122]
**什么情况/What happened?**

Android Nougat 7.1.2 r36 
CyanogenMod 14.1
ResurrectionRemix v5.8.5

刷入后开机开在动画

**Xposed模块列表/Xposed Module List**

无/未安装管理器

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

Busybox
Riru core
EdXposed

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.9_beta2

Riru: v15

**相关Logcat/Logcat**

暂未抓取/以后提供

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by eebssk1** [comment]
v3.0.0.0/b1
SELInux已临时禁用,否则无法深入调查,原因见log
所用命令行 adb  logcat *:S art Riru EdXposed-Core-Native libc app_process32 app_process64 DEBUG AndroidRuntime Zygote > 2.log
抓取时长 16秒
[https://gist.github.com/eebssk1/a30847e1d55341f99df33d8b4d5b3db4/raw/7d1c509d7aaa7864ace04f7f7360660c709915ae/8hhf7336w8df4.log](url)

**Comment by solohsu** [comment]
日志文件打不开，试试 v0.3.0.0_b2 还有没有问题。
