### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by fudgepack** [ElderDrivers/EdXposed#123]
**What happened?**
Stuck on boot. Uninstalling the module, the boot is normal.

**Xposed Module List**
None (because EdXposed is not working)

**Magisk Module List**
EdXposed 0.3.0.0 beta1
Riru ​​v15-mod

**Versions of EdXposed and Riru**

EdXposed: 0.3.0.0 beta1

Riru: ​​v15-mod

**Logcat**
[bootlog_syberia_80s.log](https://github.com/ElderDrivers/EdXposed/files/2924111/bootlog_syberia_80s.log)

**Comment by rxzcums** [comment]
try new version:
EdXposed 0.3.0.0 beta2
Riru ​​v16

**Comment by solohsu** [comment]
Same with #101

**Comment by solohsu** [comment]
Fixed with 921ac4d095457208d0b61673b0627dded1386bba
Try this SNAPSHOT build:
[magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip](https://github.com/ElderDrivers/EdXposed/files/2948136/magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip)
