### ISSUE TITLE
[BUG] 日志界面点击分享导致闪退

### ISSUE THREAD

**Issue by monkey000** [ElderDrivers/EdXposed#124]
**什么情况/What happened?**

LinageOS16(Android9.0)在日志页面点击顶部的分享图标会闪退

**Xposed模块列表/Xposed Module List**

应用变量

**Magisk模块列表/Magisk Module List**

rriu-core
rriu-edXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.3.0.0_beta1

Riru:v15

**相关Logcat/Logcat**

[bootloop-2019-03-04-16-36-00.log](https://github.com/ElderDrivers/EdXposed/files/2924927/bootloop-2019-03-04-16-36-00.log)

**Comment by solohsu** [comment]
Fixed with https://github.com/solohsu/XposedInstaller/commit/2fae1a663af997da29514b1e3aee0df767fdd7b0.
下次再有Xposed Installer的bug，麻烦提交到Xposed Installer的issue吧。
