### ISSUE TITLE
[BUG] RR-P卡在开机动画

### ISSUE THREAD

**Issue by x4455** [ElderDrivers/EdXposed#125]
**什么情况/What happened?**

卡在开机动画
ResurrectionRemix v7.0.0

**Xposed模块列表/Xposed Module List**

![screenshot_20190304163826](https://user-images.githubusercontent.com/34204709/53720627-2b130d80-3e9c-11e9-82f4-1b41c7285a1a.jpg)

**Magisk模块列表/Magisk Module List**

仅启用
riru-core-v15-mod
EdXposed-v0.3.0.0_beta1
riru-storage-redirect-v17

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.3.0.0-b1
Riru:v15-mod

**相关Logcat/Logcat*

管理器log 
[error.log](https://github.com/ElderDrivers/EdXposed/files/2924959/error.log)
liveboot log 
[liveboot.log](https://github.com/ElderDrivers/EdXposed/files/2924961/liveboot.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
Same with #101

**Comment by solohsu** [comment]
Fixed with 921ac4d095457208d0b61673b0627dded1386bba
Try this SNAPSHOT build:
[magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip](https://github.com/ElderDrivers/EdXposed/files/2948136/magisk-EdXposed-v0.3.0.0_beta3-SNAPSHOT-release.zip)
