### ISSUE TITLE
[BUG] 与 Riru: storage-redirect-v17 冲突

### ISSUE THREAD

**Issue by VeroFess** [ElderDrivers/EdXposed#126]
**什么情况/What happened?**

在刷入EdXposed可以确定开机之后继续刷入magisk-riru-storage-redirect-v17重启后bootloop

**Xposed模块列表/Xposed Module List**

未成功启动

**Magisk模块列表/Magisk Module List**

Riru
EdXposed
magisk-riru-storage-redirect-v17

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed :v0.3.0.0_b1

Riru: v15

**相关Logcat/Logcat**

[bootlog.log](https://github.com/ElderDrivers/EdXposed/files/2926014/bootlog.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by RikkaW** [comment]
应该是这里的 Riru v15 mod 的问题

03-04 18:43:00.063  2077  2077 F DEBUG   :     #00 pc 0000000000000000  <unknown>
03-04 18:43:00.063  2077  2077 F DEBUG   :     #01 pc 000000000000fc30  /system/lib64/libmemtrack.so
03-04 18:43:00.063  2077  2077 F DEBUG   :     #02 pc 00000000003d31a0  /system/framework/arm64/boot-framework.oat (offset 0x3a0000)

pr 给 Rikka 的那段是有问题的

换上 Riru v16 应该就可以了

**Comment by VeroFess** [comment]
更换Riru v16解决问题
