### ISSUE TITLE
Make a uninstaller in case install edxposed fails

### ISSUE THREAD

**Issue by offferu** [ElderDrivers/EdXposed#132]
oneplus 5T，magisk 18.1, installed core 16, edxposed 3.0, failed to boot. 
Reinstalled ROM, but once flash magisk, cannot boot successfully. I think it is because load of edxposed, could you make an uninstaller for use I  twrp so that I can clear the file and install magisk successfully?

**Comment by cwkfr** [comment]
You can run this script and uninstall edxposed easily
https://github.com/Magisk-Modules-Repo/mm/blob/master/mm

**Comment by offferu** [comment]
> You can run this script and uninstall edxposed easily
> https://github.com/Magisk-Modules-Repo/mm/blob/master/mm

Sorry, could you direct how to run this scrip?  Thanks!

**Comment by offferu** [comment]
I already lost root, cannot flash it in magisk, I can only flash a twrp module

**Comment by cwkfr** [comment]
Download the script and put it in your device, open your twrp terminal and navigate to the script directory then execute `chmod +x mm`. Run the script with `./mm`

You can extract the 'mm' script from this https://github.com/Magisk-Modules-Repo/mm/archive/master.zip

    I already lost root, cannot flash it in magisk, I can only flash a twrp module

You can flash magisk module via recovery anyway

**Comment by solohsu** [comment]
I just made a uninstaller flashable and it works on TWRP as I have tested, please give it a try.
[EdXposedUninstaller.zip](https://github.com/ElderDrivers/EdXposed/files/2942177/EdXposedUninstaller.zip)
