### ISSUE TITLE
[BUG] 日志显示不全

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#135]
**什么情况/What happened?**

日志显示不全

edxposed中载入日志经常只显示了一部分，剩余一部分没了
点击右上角菜单的重新载入也还是没有全部显示

**Comment by coderstory** [comment]
MIUI10 
 小米9 
android P

**Comment by rxzcums** [comment]
你们有日志，我现在用着0.3.0.0.b2 & edxposed installer 2.2.1。
![screenshot_2019-03-07-16-43-08-604_com solohsu android edxp manager](https://user-images.githubusercontent.com/11990604/53943606-61e55f80-40f8-11e9-9ce9-a8254368e3b9.png)

**Comment by solohsu** [comment]
@MlgmXyysd

**Comment by MlgmXyysd** [comment]
暂时定位为重定向stdout的问题，下次更新取消使用重定向。
