### ISSUE TITLE
[BUG] EdXp 0.3.0.0 b2 版本使用无法正常使用Q++

### ISSUE THREAD

**Issue by PianCat** [ElderDrivers/EdXposed#139]
**什么情况/What happened?**

当Q++生效时，QQ无法正常开启，一开启就强制停止

**Xposed模块列表/Xposed Module List**

哔哩布丁 - 1.5.6
绿色守护 - 4.6.3
QX模块 - 1.21
微X模块 - 1.25
QQ净化 - 3.5.0
Q++

**Magisk模块列表/Magisk Module List**

Riru Core V16
EdXposed 0.3.0.0. beta2

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.3.0.0 beta2

Riru:V16

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by coderstory** [comment]
这个不应该找插件作者么？

**Comment by solohsu** [comment]
应该是 8.x 的问题，等待修复。
下次请附上日志，不然连你用的什么系统版本都不知道。

**Comment by PianCat** [comment]
@solohsu 系统是Android 9.0
我觉得可能是这边的数据问题……我再去试试

**Comment by solohsu** [comment]
试试新版本。
