### ISSUE TITLE
[BUG] 验证码提取器（xposed）在没有开启去除系统代码优化的情况下没有效果

### ISSUE THREAD

**Issue by DandanIS** [ElderDrivers/EdXposed#140]
**什么情况/What happened?**

验证码提取器（xposed）在没有开启去除系统代码优化的情况下没有效果

**Xposed模块列表/Xposed Module List**

微X-1.25
Qx-1.21
chimi-2.2.27.1

**Magisk模块列表/Magisk Module List**

riru-Ed Xposed v0.3.0.0_beta2
riru-core   v16

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.0.0_beta2

Riru:v16

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by rxzcums** [comment]
我测试过，该模块正常，需要给自启权限，电池不优化。
miui10 8.1

**Comment by solohsu** [comment]
麻烦尝试下最新版本，如有问题再来反馈，下次注意附上日志。
