### ISSUE TITLE
[BUG]更新edxposed后xposed失效

### ISSUE THREAD

**Issue by DaFeiMao233** [ElderDrivers/EdXposed#141]
![如图所示](https://ooo.0o0.ooo/2019/03/08/5c81bcc84ea7f.png)如图所示![第三方edxposed控制端](https://ooo.0o0.ooo/2019/03/08/5c81bd1988be5.png)模块已经激活![面具模块列表](https://ooo.0o0.ooo/2019/03/08/5c81bd62a6927.png)，0.3.0.0beta1没有这个bug，刷了0.3.0.0beta2后出现这个问题。

**Comment by rxzcums** [comment]
同时用2个管理器？优先级靠后的会这样吧

**Comment by solohsu** [comment]
没有日志？

**Comment by DaFeiMao233** [comment]
@solohsu 刚刷的MIUI，还没来得及装logcat:disappointed_relieved:

**Comment by DaFeiMao233** [comment]
@rxzcums 这跟管理器没关系:disappointed:，以前都是两个管理器
