### ISSUE TITLE
[BUG] 0.3.0.0、0.3.1.2对网易云音乐无效

### ISSUE THREAD

**Issue by Howard20181** [ElderDrivers/EdXposed#144]
**什么情况/What happened?**

模块无效
对网易云音乐的所有模块无效

**Xposed模块列表/Xposed Module List**

> 网易云音乐插件2.8.2
微信学英语
微信增强
微X
音量增强器0.0.30
云村清洁工2.7.0
指纹支付
MusicNotification
QQ净化
QX

**Magisk模块列表/Magisk Module List**

> ADB & Fastboot for Android NDK
Busybox for Android NDK
Log Catcher15
Magisk管理器Recovrey版
MIUI通知栏去白边+分块
Riru-Core17.1
Riru_Edxposed
Systemless Hosts
通用GMS打盹

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:3.1.2

Riru:17.1

**相关Logcat/Logcat**
[logcat.log](https://github.com/ElderDrivers/EdXposed/files/2944590/logcat.log)
[error.log](https://github.com/ElderDrivers/EdXposed/files/2948555/error.log)

**Comment by dna1982** [comment]
一模一样的问题，我还以为是我姿势不对…

**Comment by Howard20181** [comment]
> 一模一样的问题，我还以为是我姿势不对…

qx微x都可以完美支持，网易云只能用exp299，怀疑是网易云屏蔽

**Comment by Howard20181** [comment]
网易云是5.9

**Comment by Ninlives** [comment]
你确认一下log是不是最新的？我翻了一下里面的信息显示edxposed找不到module.list因此没有加载任何模块

**Comment by Howard20181** [comment]
重新抓了一份，前面有

> 03-09 06:33:08.785 E/EdXposed-Bridge(11780): Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found

但后面又有加载模块
[logcat.log](https://github.com/ElderDrivers/EdXposed/files/2947712/logcat.log)

**Comment by solohsu** [comment]
应该是 8.x 上会出现的问题，等待修复吧。
不过音量增强也用不了？

**Comment by Howard20181** [comment]
> 应该是 8.x 上会出现的问题，等待修复吧。
> 不过 0.0.30 版本的音量增强也用不了？

是的，也用不了

**Comment by rxzcums** [comment]
> > 应该是 8.x 上会出现的问题，等待修复吧。
> > 不过 0.0.30 版本的音量增强也用不了？
> 
> 是的，也用不了

我的miui10也是8.1的，音量放大器和云村工具箱都能用。

**Comment by rxzcums** [comment]
magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。

**Comment by Howard20181** [comment]
> magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
一样的，用不了
这是日志
[error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)

**Comment by dna1982** [comment]
> > magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
> 
> 一样的，用不了
> 这是日志
> [error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)

研究了一下，发现只要把网易云音乐加入到Magisk Hide，音量和云村就会失效。
把网易云音乐从Magisk Hide里去掉，音量和云村就生效了。
你试试。

**Comment by Howard20181** [comment]
> > > magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
> > 
> > 
> > 一样的，用不了
> > 这是日志
> > [error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)
> 
> 研究了一下，发现只要把网易云音乐加入到Magisk Hide，音量和云村就会失效。
> 把网易云音乐从Magisk Hide里去掉，音量和云村就生效了。
> 你试试。

关了对网易云的Magisk Hide后就无法正常扫描本地音乐了

**Comment by rxzcums** [comment]
> > > magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
> > 
> > 
> > 一样的，用不了
> > 这是日志
> > [error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)
> 
> 研究了一下，发现只要把网易云音乐加入到Magisk Hide，音量和云村就会失效。
> 把网易云音乐从Magisk Hide里去掉，音量和云村就生效了。
> 你试试。

我的网易云就是勾选magisk hide的，音量和云村都正常。

**Comment by rxzcums** [comment]
> > > > > magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
> > > > 
> > > > 
> > > > 一样的，用不了
> > > > 这是日志
> > > > [error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)
> > > 
> > > 
> > > 研究了一下，发现只要把网易云音乐加入到Magisk Hide，音量和云村就会失效。
> > > 把网易云音乐从Magisk Hide里去掉，音量和云村就生效了。
> > > 你试试。
> > 
> > 
> > 我的网易云就是勾选magisk hide的，音量和云村都正常。
> 
> 请报一下你使用的Magisk、riru core、edxposed版本

18.1，16，0.3.1.0.b1.snap（0.3.0.0也是正常的）

**Comment by dna1982** [comment]
> > > > > > magisk只留ed和riru-core, xposed只留音量和云村，再测了过来回复。
> > > > > 
> > > > > 
> > > > > 一样的，用不了
> > > > > 这是日志
> > > > > [error.log](https://github.com/ElderDrivers/EdXposed/files/2948575/error.log)
> > > > 
> > > > 
> > > > 研究了一下，发现只要把网易云音乐加入到Magisk Hide，音量和云村就会失效。
> > > > 把网易云音乐从Magisk Hide里去掉，音量和云村就生效了。
> > > > 你试试。
> > > 
> > > 
> > > 我的网易云就是勾选magisk hide的，音量和云村都正常。
> > 
> > 
> > 请报一下你使用的Magisk、riru core、edxposed版本
> 
> 18.1，16，0.3.1.0.b1.snap（0.3.0.0也是正常的）

和我用的版本也一样，好奇怪哦。
你的ROM是类(AOSP)的Android 9吗？

**Comment by rxzcums** [comment]
@dna1982 miui10，安卓8.1，不一样。

**Comment by leolife** [comment]
PE magisk hide 正常

**Comment by Howard20181** [comment]
0.3.1.2依然存在这个问题

**Comment by dna1982** [comment]
Device: Pocophone F1 (beryllium)
Rom: RR-P-v7.0.0-20190302-beryllium-Official (Android 9.0)
Magisk: 18.1
Riru Core: 17
Edxposed: 0.3.1.2_beta
PureNeteaseCloudMusic: 2.6.2
Unblock163MusicClient: 0.0.30
这是我现在的环境，只要把网易云音乐加入到 Magisk Hide，PureNeteaseCloudMusic和Unblock163MusicClient就会失效。

**Comment by Howard20181** [comment]
补充
设备：小米5
系统：MIUI 10.2 Android8.0

Magisk：18.1(18100)
Magisk Manager：7.0.0(185)
Riru Core：17.1

Riru模块仅有Ed Xposed

单一变量 仅将Edxposed降级到0.2.9.8，所有模块正常工作
0.2.9.9及以上无论对网易云音乐的Magisk Hide是否打开都对它无效
但其他模块如微X、QX都正常

@solohsu 

回0.2.9.8养老 3个月后再来

**Comment by Howard20181** [comment]
> 补充
> 设备：小米5
> 系统：MIUI 10.2 Android8.0
> 
> Magisk：18.1(18100)
> Magisk Manager：7.0.0(185)
> Riru Core：17.1
> 
> Riru模块仅有Ed Xposed
> 
> 单一变量 仅将Edxposed降级到0.2.9.8，所有模块正常工作
> 
> 0.2.9.9及以上版本无论对网易云音乐的Magisk Hide是否打开都对它无效
> 但其他模块如微X、QX都正常
> 
> @solohsu
> 
> 回0.2.9.8养老 3个月后再来

还有个问题，在使用Edxposed 0.3.1.2在Installer2.2.3无法查看日志(权限不足)，只能直接去日志目录复制出来

**Comment by solohsu** [comment]
> > 补充
> > 设备：小米5
> > 系统：MIUI 10.2 Android8.0
> > Magisk：18.1(18100)
> > Magisk Manager：7.0.0(185)
> > Riru Core：17.1
> > Riru模块仅有Ed Xposed
> > 单一变量 仅将Edxposed降级到0.2.9.8，所有模块正常工作
> > 0.2.9.9及以上版本无论对网易云音乐的Magisk Hide是否打开都对它无效
> > 但其他模块如微X、QX都正常
> > @solohsu
> > 回0.2.9.8养老 3个月后再来
> 
> 还有个问题，在使用Edxposed 0.3.1.2在Installer2.2.3无法查看日志(权限不足)，只能直接去日志目录复制出来

没给installer root权限？

**Comment by solohsu** [comment]
@Howard20181 你这个问题最好附上网易云音乐启动时的完整的系统日志，仅从xposed的日志看不出原因。

**Comment by Howard20181** [comment]
> > > 补充
> > > 设备：小米5
> > > 系统：MIUI 10.2 Android8.0
> > > Magisk：18.1(18100)
> > > Magisk Manager：7.0.0(185)
> > > Riru Core：17.1
> > > Riru模块仅有Ed Xposed
> > > 单一变量 仅将Edxposed降级到0.2.9.8，所有模块正常工作
> > > 0.2.9.9及以上版本无论对网易云音乐的Magisk Hide是否打开都对它无效
> > > 但其他模块如微X、QX都正常
> > > @solohsu
> > > 回0.2.9.8养老 3个月后再来
> > 
> > 
> > 还有个问题，在使用Edxposed 0.3.1.2在Installer2.2.3无法查看日志(权限不足)，只能直接去日志目录复制出来
> 
> 没给installer root权限？

给了，甚至转换成系统程序了

**Comment by Howard20181** [comment]
> @Howard20181 你这个问题最好附上网易云音乐启动时的完整的系统日志，仅从xposed的日志看不出原因。

[logcat_netease_music_withEd298.log](https://github.com/ElderDrivers/EdXposed/files/2973463/logcat_netease_music_withEd298.log)
[logcat_netease_music_with_Ed312.log](https://github.com/ElderDrivers/EdXposed/files/2973469/logcat_netease_music_with_Ed312.log)
@solohsu

**Comment by Howard20181** [comment]
> > @Howard20181 你这个问题最好附上网易云音乐启动时的完整的系统日志，仅从xposed的日志看不出原因。
> 
> [logcat_netease_music_withEd298.log](https://github.com/ElderDrivers/EdXposed/files/2973463/logcat_netease_music_withEd298.log)
> [logcat_netease_music_with_Ed312.log](https://github.com/ElderDrivers/EdXposed/files/2973469/logcat_netease_music_with_Ed312.log)
> @solohsu

好像我理解错了w

**Comment by solohsu** [comment]
> > > @Howard20181 你这个问题最好附上网易云音乐启动时的完整的系统日志，仅从xposed的日志看不出原因。
> > 
> > 
> > [logcat_netease_music_withEd298.log](https://github.com/ElderDrivers/EdXposed/files/2973463/logcat_netease_music_withEd298.log)
> > [logcat_netease_music_with_Ed312.log](https://github.com/ElderDrivers/EdXposed/files/2973469/logcat_netease_music_with_Ed312.log)
> > @solohsu
> 
> 好像我理解错了w

不太行。不完整。需要杀掉网易云，开机记录日志，打开网易云。

**Comment by Howard20181** [comment]
> > > > @Howard20181 你这个问题最好附上网易云音乐启动时的完整的系统日志，仅从xposed的日志看不出原因。
> > > 
> > > 
> > > [logcat_netease_music_withEd298.log](https://github.com/ElderDrivers/EdXposed/files/2973463/logcat_netease_music_withEd298.log)
> > > [logcat_netease_music_with_Ed312.log](https://github.com/ElderDrivers/EdXposed/files/2973469/logcat_netease_music_with_Ed312.log)
> > > @solohsu
> > 
> > 
> > 好像我理解错了w
> 
> 不太行。不完整。需要杀掉网易云，开始记录日志，打开网易云。

[logcat_system_with_Edxp312.log](https://github.com/ElderDrivers/EdXposed/files/2973743/logcat_system_with_Edxp312.log)

@solohsu

**Comment by Howard20181** [comment]
再来一遍
[logcat_system_with_Edxp312.log](https://github.com/ElderDrivers/EdXposed/files/2973747/logcat_system_with_Edxp312.log)
@solohsu

**Comment by solohsu** [comment]
@Howard20181 
- 看了下你开启了动态模块列表+黑白名单，在这种情况下，每个app进程会独立进行代码的注入
- 然后你把网易云加入magiskhide之后，会限制它读取系统目录下的文件，导致无法读取到EdXp的代码文件，也就无法进行注入及后续的hook了
解决方法就是关掉动态模块列表功能。

**Comment by Howard20181** [comment]
> @Howard20181
> 
> * 看了下你开启了动态模块列表+黑白名单，在这种情况下，每个app进程会独立进行代码的注入
> * 然后你把网易云加入magiskhide之后，会限制它读取系统目录下的文件，导致无法读取到EdXp的代码文件，也就无法进行注入及后续的hook了
>   解决方法就是关掉动态模块列表功能。

在3.0.0时试过，关了动态模块列表后bootloop了

**Comment by solohsu** [comment]
@Howard20181 bootloop的话就是另外的问题了，可以重新开贴描述。
关于这个问题，暂时没办法解决，本身动态模块列表功能只是为了方便测试用的功能，十分不建议开启。

**Comment by Howard20181** [comment]
312关闭动态模块可以了，但有一个模块用不了 
>网易云音乐插件

@solohsu

**Comment by Howard20181** [comment]
试着联系模块作者

**Comment by Howard20181** [comment]
有个问题想请教一下，一直以来我开启白名单和动态模块列表又开启对微信的Magisk Hide，为什么对微信的各个插件如微X、指纹支付、MD化都可以？难道有什么特殊的魔法？？ @solohsu 
还有，
> 网易云音乐插件

这个模块在0.2.9.8生效，但不知道为什么在0.3.1.2就不行了
非常感谢！
