### ISSUE TITLE
3.0.0beta2云闪付打不开

### ISSUE THREAD

**Issue by yoozyy** [ElderDrivers/EdXposed#146]
云闪付一直在启动界面进不了，加入黑名单也一样

**Comment by rxzcums** [comment]
用play版云闪付啊，酷安评论区。

**Comment by Crescendo-BLYAT** [comment]
This ver always says not installed after second reboot on Syberia OS - Android 9.0 - Mi 5s Plus - Magisk 18.1 Stable (tried Canary, same result).

v3.0.0.b1 working OK.

Anything to help you with this?

**Comment by solohsu** [comment]
Fixed with 47c500b96ded4da92aa59b7b8336ba556afa3716.
