### ISSUE TITLE
Logs are not populating

### ISSUE THREAD

**Issue by TechnoSparks** [ElderDrivers/EdXposed#148]
I am not sure if this is Xposed issue or the Xposed Installer issue, but since the EdXposed installer GitHub issues is locked, I left with no other option but to post here.

I am basically having a problem where the installer is not populating logs. Modules however work fine (like if it works as intended without looking at logs)

This is difficult if I am trying to precisely troubleshoot if a certain module is working or not.

This is how it looks like
![](https://i.imgur.com/1Vksvrj.png)

**As seen on:** 
- Magisk: 17.3
- Riru: 15 and 16
- EdXposed: 3.0.0 beta 1 and beta 2

**Comment by AJsama** [comment]
yes, i met this problem too ...quite annoyed me when i was helping test a xposed module...

**Comment by solohsu** [comment]
Fixed with 2c49377ba2b3ccb4e74f7ff2d717544b22080c52 and 3097077261af62a042eacbfa0fbae45242135b26.
