### ISSUE TITLE
[BUG] XSharedPreferences are not working from hooks

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposed#149]
https://github.com/ElderDrivers/EdXposed/issues/130#issuecomment-471281625

Can't make XSharedPreferences work inside any hooks. Tried adding selinux policies, tried switching to permissive - nothing helps, I don't even have avc messages in log, it just fails silently.

For example, hook **android.widget.Toast.makeText()** in initZygote() and try to get module's preferences there:
```
XSharedPreferences pref = new XSharedPreferences(modulePkg, prefsName);
XposedBridge.log(pref.getAll().toString());
```
It only returns an empty result. If I create XSharedPreferences in initZygote() directly and assign it to static class var, then I can use it in hooks, but only until reload() is called, then it becomes empty again.
I also tried to call `pref.makeWorldReadable()`, xml permissions are 664 currently.

**Comment by C3C0** [comment]
It's like that even in official Xposed since Oreo. In Android package it is not possible to read nor reload preferences. You have to choose a different strategy if you need to update prefs during runtime in Android package.

**Comment by Mikanoshi** [comment]
By different strategy you mean ditch SharedPreferences altogether?)
They can only be obtained by owner or zygote process, so no way to make them dynamic.

**Comment by C3C0** [comment]
Read them once in zygote and runtime changes handle using broadcasts. That's the simplest way.

**Comment by Mikanoshi** [comment]
That means broadcast receiver in every single app you hook? Nah, this seems to be better :) Single method to get any content:
```
ContentResolver resolver = ((Context)param.args[0]).getContentResolver();
Uri uri = Uri.parse("content://name.mikanoshi.app.provider.sharedprefs/string/pref_key_system_toasts");
Cursor cursor = resolver.query(uri, null, null, null, null);
if (cursor != null) {
	cursor.moveToFirst();
	String prefValue = cursor.getString(0);
	cursor.close();
}
```

**Comment by Mikanoshi** [comment]
That means broadcast receiver in every single app you hook %)
This seems to be better :) Single function to get any content:
```
ContentResolver resolver = ((Context)param.args[0]).getContentResolver();
Uri uri = Uri.parse("content://name.mikanoshi.app.provider.sharedprefs/string/pref_key_system_toasts");
Cursor cursor = resolver.query(uri, null, null, null, null);
if (cursor != null) {
	cursor.moveToFirst();
	String prefValue = cursor.getString(0);
	cursor.close();
}
```

**Comment by C3C0** [comment]
Yes, although I meant receiver within Android package only.

**Comment by Mikanoshi** [comment]
And how to use it from other hooked apps?

**Comment by Mikanoshi** [comment]
Checked SystemUI, XSharedPreferences is not working there either, it's also empty.

**Comment by Mikanoshi** [comment]
Did ContentObserver for now :)

String/Integer observer:
```
public static class SharedPrefObserver extends ContentObserver {

	enum PrefType {
		String, Integer
	}

	PrefType prefType;
	Context ctx;
	String prefName;
	String prefDefValueString;
	int prefDefValueInt;

	public SharedPrefObserver(Context context, Handler handler, String name, String defValue) {
		super(handler);
		ctx = context;
		prefName = name;
		prefType = PrefType.String;
		prefDefValueString = defValue;
		registerObserver();
	}

	public SharedPrefObserver(Context context, Handler handler, String name, int defValue) {
		super(handler);
		ctx = context;
		prefType = PrefType.Integer;
		prefName = name;
		prefDefValueInt = defValue;
		registerObserver();
	}

	void registerObserver() {
		Uri uri = null;
		if (prefType == PrefType.String)
			uri = stringPrefToUri(prefName, prefDefValueString);
		else if (prefType == PrefType.Integer)
			uri = intPrefToUri(prefName, prefDefValueInt);
		if (uri != null) ctx.getContentResolver().registerContentObserver(uri, false, this);
	}

	@Override
	public void onChange(boolean selfChange) {
		if (selfChange) return;
		if (prefType == PrefType.String)
			onChange(prefName, prefDefValueString);
		else if (prefType == PrefType.Integer)
			onChange(prefName, prefDefValueInt);
	}

	public void onChange(String name, String defValue) {}
	public void onChange(String name, int defValue) {}
}
```
Get current pref value:
```
public static int getSharedIntPref(Context context, String name, int defValue) {
	Uri uri = intPrefToUri(name, defValue);
	Cursor cursor = context.getContentResolver().query(uri, null, null, null, null);
	if (cursor != null) {
		cursor.moveToFirst();
		int prefValue = cursor.getInt(0);
		cursor.close();
		return prefValue;
	} else if (MainModule.pref != null)
		return MainModule.pref.getInt(name, defValue);
	else
		return defValue;
}

...

mObject.setParam(getSharedIntPref(mContext, "pref_key_param", 0));
```

Get content updates:
```
new SharedPrefObserver(mContext, mHandler, "pref_key_pram", 0) {
	@Override
	public void onChange(String name, int defValue) {
		mObject.setParam(getSharedIntPref(mContext, name, defValue));
	}
}.onChange(false);
```

And notify about that shared prefs updates:
```
sharedPrefs.registerOnSharedPreferenceChangeListener(new OnSharedPreferenceChangeListener() {
	@Override
	public void onSharedPreferenceChanged(SharedPreferences sharedPrefs, String key) {
		Object val = sharedPrefs.getAll().get(key);
		String path = "/";
		if (val instanceof String)
			path = "/string/";
		else if (val instanceof Integer)
			path = "/integer/";
		getContentResolver().notifyChange(Uri.parse("content://" + SharedPrefsProvider.AUTHORITY + path + key), null);
	}
});
```

**Comment by Mikanoshi** [comment]
@C3C0 Well, shit :)
```
[03-29 22:44:59.882 15093:15361 W/XSharedPreferences]
getSharedPreferences
java.io.IOException: Permission denied while reading /data/data/name.mikanoshi.customiuizer/shared_prefs/customiuizer_prefs.xml
	at de.robv.android.xposed.services.ZygoteService.statFile(Native Method)
	at de.robv.android.xposed.services.ZygoteService.readFile(ZygoteService.java:21)
	at de.robv.android.xposed.services.BaseService.getFileInputStream(BaseService.java:148)
	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:122)
	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
```

Not even from initZygote() it is guaranteed to work on some devices... SELinux problem?
I doubt that content observers are available at that time, and there is no context anyway.

**Comment by C3C0** [comment]
Zygote hooks are propagated to all loaded packages so most likely it is about particular app not having permission accessing preferences, not zygote itself. Isn't it that case? You should be able to verify by logging calling package uid.

**Comment by solohsu** [comment]
@Mikanoshi Looks like you were using original Xposed? ZygoteService is never used in EdXposed.

**Comment by Mikanoshi** [comment]
Yes, it's not EdXposed, it's on Android 8.0. User reported that module preferences are not working at all.

@C3C0 initZygote() should be called only once, no? Not every time it forks to another process. Anyway, prefs are not working completely, so it's never able to read the file.

**Comment by C3C0** [comment]
Yes, I was mislead with issue title which mentions reading prefs INSIDE HOOKS created in zygote.

**Comment by Mikanoshi** [comment]
customiuizer_prefs.xml has 777 permissions, no avc errors anywhere near the permission error in logcat. Mystery.

**Comment by C3C0** [comment]
What about permissions of containing folders? (shared_prefs, app data folder itself)

**Comment by Mikanoshi** [comment]
This method is executed after every pref change:

```
@SuppressLint({"SetWorldReadable", "SetWorldWritable"})
private void fixPermissions() {
	File sharedPrefsFolder = new File(getDataDir().getAbsolutePath() + "/shared_prefs");
	if (sharedPrefsFolder.exists()) {
		sharedPrefsFolder.setExecutable(true, false);
		sharedPrefsFolder.setReadable(true, false);
		File f = new File(sharedPrefsFolder.getAbsolutePath() + "/" + Helpers.prefsName + ".xml");
		if (f.exists()) {
			f.setReadable(true, false);
			f.setExecutable(true, false);
			f.setWritable(true, false);
		}
	}
}
```

shared_prefs permissions are 775, app data is unchanged and is 700.

**Comment by C3C0** [comment]
App data folder being 700 might be an issue. Try making it executable for all.

**Comment by Mikanoshi** [comment]
Same error... What's a protected storage?) Encrypted data partition?

**Comment by C3C0** [comment]
https://android-developers.googleblog.com/2016/04/developing-for-direct-boot.html?m=1

Pay attention mainly to "Using the device protected storage area"

**Comment by Mikanoshi** [comment]
But it cannot read file in /data/data/ specifically, not the /data/user_de/.
Zygote runs under root, it shouldn't care about Android contexts, only SELinux/permissions.

**Comment by C3C0** [comment]
Not true for devices with file based encryption. /data/app may not be accessible even to zygote because it is decrypted after user authenticates for the first time after boot.

**Comment by C3C0** [comment]
Maybe check this https://github.com/GravityBox/GravityBox/commit/d825b7be445c18de9a90eb8f77c1c5eb2b74deb8

**Comment by Mikanoshi** [comment]
But when you are authenticated and then open file manager and go to /data/user_de/<pkg_name>/ you have to see shared_pref and xml there? or they move to /data/data/? :)

**Comment by C3C0** [comment]
Those storages are independent. You decide which one app uses by telling the context.

**Comment by Mikanoshi** [comment]
I didn't specify it in my module of course, should it use regular by default? I asked user with the problem to check the contents in /data/user_de/. He is on Andoird 7.1.2 Xposed 89 btw.

**Comment by C3C0** [comment]
All devices since sdk24 come with /data/user_de

**Comment by Mikanoshi** [comment]
He doesn't have anything in user_de except code_cache folder.

**Comment by C3C0** [comment]
If you need to access preferences of your modules before user authenticates you should use device protected storage (on devices running sdk24 or higher).

**Comment by C3C0** [comment]
There should be 0 subfolder (for default user). So /data/user_de/0

**Comment by Mikanoshi** [comment]
Yep, only code_cache folder there, no shared_prefs.

**Comment by C3C0** [comment]
Of course it won't be there if you are not using it :)

**Comment by Mikanoshi** [comment]
So I have to use it and then retrieve it from protected storage in initZygote? Why it cannot just work with regular one?))

**Comment by C3C0** [comment]
Because zygote doesn't know the key to decrypt standard /data/data storage. This storage is decrypted only after user unlocks with pin/pass/whatever because it is used as a decrypion key

**Comment by Mikanoshi** [comment]
So much useless security)) Easier to just hook everything in initZygote unconditionally and check prefs using module's ContentProvider inside hooks...

**Comment by Mikanoshi** [comment]
I just did this in initZygote():
```
File[] files = new File("/data/data/").listFiles();
XposedBridge.log(Arrays.toString(files));
```
It prints all the package names unencrypted...

**Comment by C3C0** [comment]
Not sure how it's done internally, e.g. what this folder is linked to when encrypted and unencrypted. Maybe there are package names but you can't go further down the structure . But I'm sure your original issue is related to this as I had the same issue in the past. Also try checking if you can list /data/user/0 (this one is linked to /data/data after user gets authenticated)

**Comment by Mikanoshi** [comment]
/data/data/<pkg_name> has canRead() == false and returns an empty list of files, /data/user/0 is a symlink to /data/data, so it returns the same data. Must be encryption then...

**Comment by Mikanoshi** [comment]
It worked, had to move SharedPrefrences to protected storage and set all the folder and file permissions to world readable.

**Comment by C3C0** [comment]
Great. Glad it was the issue we were discussing.

**Comment by Mikanoshi** [comment]
@C3C0 
Resource hooks are back, so... not possible to get SharedPrefs there? =]
There is no context, so content observer won't work. Would be nice to be able to apply settings by just force closing the package that has its resources replaced.

**Comment by C3C0** [comment]
Not sure what you mean.

**Comment by Mikanoshi** [comment]
```
if (pkg.equals("com.miui.home")) {
	resparam.res.setReplacement(pkg, "integer", "config_folder_columns_count", mPrefs.getInt("launcher_folder_cols", 3));
	resparam.res.setReplacement(pkg, "integer", "folder_content_visible_count", mPrefs.getInt("launcher_folder_perpage", 12));
}
```

It replaces resources on package load, but value it replaces to can only be updated in initZygote, so still requires fast reboot.

**Comment by C3C0** [comment]
Yes, resource replacements always require reboot. I don't remember I have ever tried handling those during runtime.

**Comment by Mikanoshi** [comment]
It was possible when XSharedPreferences,reload() were working inside hooks. Everything was easier on Android 5 :)

**Comment by Mikanoshi** [comment]
> It's like that even in official Xposed since Oreo. In Android package it is not possible to read nor reload preferences. You have to choose a different strategy if you need to update prefs during runtime in Android package. Avoid using reload there.

@C3C0 How is it still working in GravityBox?)
https://github.com/GravityBox/GravityBox/blob/pie/GravityBox/src/main/java/com/ceco/pie/gravitybox/ModDialer26.java#L145

**Comment by Mikanoshi** [comment]
> It's like that even in official Xposed since Oreo. In Android package it is not possible to read nor reload preferences. You have to choose a different strategy if you need to update prefs during runtime in Android package. Avoid using reload there.

@C3C0 It actually works in any package, just tried both Android and Settings. But only if xml is world readable.

**Comment by Android1500** [comment]
hey Actually I am facing same issue i am developing a xposed module which will change imei from telephony class  but when i put key and value directly in XsharePreference then its changed my device imei but when i try to get imei from sharepreferences xml its not changing i tried to access direct data/user/0/packageName/shared_prefs/prefile.xml but still it can't change please can you help me i am new in xposed developing

**Comment by yujincheng08** [comment]
@Android1500  https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences

**Comment by Android1500** [comment]
> @Android1500 https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences

Thanks a lot i am checking
