### ISSUE TITLE
[BUG] Bootloop after installing EdXposed

### ISSUE THREAD

**Issue by perfiction** [ElderDrivers/EdXposed#150]
**什么情况/What happened?**

After flashing latest ResurrectionRemix (7.0.1 for Mido https://get.resurrectionremix.com/?dir=mido) phone is stuck in bootloop. It's caused by EdXposed - when I leave only Riru in my magisk modules, the phone boots normally.

**Xposed模块列表/Xposed Module List**

Doesn't matter - problem happens even without modules installed/enabled.

**Magisk模块列表/Magisk Module List**

Riru and EdXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.0.0_beta2

Riru: v16

**相关Logcat/Logcat**

[log.txt](https://github.com/ElderDrivers/EdXposed/files/2949712/log.txt)

**Comment by solohsu** [comment]
This has been fixed. Check https://github.com/ElderDrivers/EdXposed/issues/125#issuecomment-471152156

**Comment by j-massive** [comment]
Really??? had exactly the same problem, and before I realized what I can disable the module in recovery, I had already installed a backup three times, which I luckily did before
But if you say it's running now, I'll have to try it right away, hopefully it works this time, that would make me really happy... 
Hi five and Peace out 🤜🤛✌️😉
