### ISSUE TITLE
Cannot read log/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log (Permission denied)

### ISSUE THREAD

**Issue by KaMyKaSii** [ElderDrivers/EdXposed#151]
Although the log file exists, EdXposed Manager is denied to read it. But when running the command "setenforce 0" on a rooted shell the app can read the log correctly, then it is definitely a selinux issue. Let me know if a logcat is really needed and I'll provide it

[xposed_error_20190310_145511.log](https://github.com/ElderDrivers/EdXposed/files/2949860/xposed_error_20190310_145511.log)

**Comment by solohsu** [comment]
It's a EdXposed Manager bug, please raise a bug report there.
