### ISSUE TITLE
[BUG] Essential phone boot loop

### ISSUE THREAD

**Issue by seasonyuu** [ElderDrivers/EdXposed#153]
[**什么情况/What] happened?**

Essential phone  boot loop

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

无

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

![2019-3-11_15-2-55](https://user-images.githubusercontent.com/8638535/54105721-e42e9600-440e-11e9-8296-d3682c2c9a27.PNG)

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.0.0_beta3_snapshot from here 3https://github.com/ElderDrivers/EdXposed/issues/125#issuecomment-471152156

Riru: 16

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[magisk_log_20190311_150549.log](https://github.com/ElderDrivers/EdXposed/files/2950998/magisk_log_20190311_150549.log)

**Comment by seasonyuu** [comment]
补充：v0.3.0.0_beta2 也无法工作

**Comment by solohsu** [comment]
麻烦尝试312版本，如果还有bootloop请附上开机日志。
