### ISSUE TITLE
[BUG] 京东历史价格插件无效

### ISSUE THREAD

**Issue by rxzcums** [ElderDrivers/EdXposed#155]
**什么情况/What happened?**
京东历史价格插件无效。之前有edxp版本曾经有效过。

**Xposed模块列表/Xposed Module List**
![Screenshot_2019-03-13-16-58-59-767_com solohsu android edxp manager](https://user-images.githubusercontent.com/11990604/54266153-cc434780-45b1-11e9-9671-b29b719aa03e.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_2019-03-13-16-58-55-215_com topjohnwu magisk](https://user-images.githubusercontent.com/11990604/54266182-d8c7a000-45b1-11e9-83bd-89cf49b36585.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.1.2 b1

Riru: v17

**相关Logcat/Logcat**
[error - 复制.log](https://github.com/ElderDrivers/EdXposed/files/2960585/error.-.log)
错误在日志结尾

**Comment by rxzcums** [comment]
该插件无界面，使用方法是：在京东app商品页面点击分享到“其他”，选择 JD历史价格。

**Comment by solohsu** [comment]
模块本身未适配京东新版本的问题。7.4.2以下版本正常。
下次先自己测试好。：）

**Comment by rxzcums** [comment]
@solohsu 实在抱歉，下次注意了😱
