### ISSUE TITLE
[BUG] 启用验证码提取器（xposed）后，疑似黑名单不工作

### ISSUE THREAD

**Issue by rxzcums** [ElderDrivers/EdXposed#157]
**什么情况/What happened?**
验证码提取器（xposed）启用后，温州银行打不开。
之前是音量放大器启用后，温州银行打不开，该问题已解决，现在又遇到类似问题，请大佬帮忙，谢谢！

**Xposed模块列表/Xposed Module List**
![Screenshot_2019-03-14-14-34-58-439_com solohsu android edxp manager](https://user-images.githubusercontent.com/11990604/54336387-e3903c80-4666-11e9-992e-632c91179d72.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_2019-03-14-14-35-07-638_com topjohnwu magisk](https://user-images.githubusercontent.com/11990604/54336400-edb23b00-4666-11e9-9dc2-15c86b79dccb.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.1.2

Riru: 17.1

**相关Logcat/Logcat**
[error - 复制.log](https://github.com/ElderDrivers/EdXposed/files/2965005/error.-.log)

**Comment by solohsu** [comment]
用xposed仓库里最新的验证码提取器无法复现。
另外日志需要温州银行打开时的完整系统日志，可以用MatLog之类的工具获取。

**Comment by rxzcums** [comment]
@solohsu 谢谢。我用matlog抓了2份温州银行启动时的log。二者的区别是，启用模块时，wzbank在push一段包名后deny了，而禁用模块时，push包名后，是mcode…
我不懂其他了，麻烦大佬帮忙。
谢谢。
[2019-03-16-03-21-14（启用模块时）.txt](https://github.com/ElderDrivers/EdXposed/files/2972636/2019-03-16-03-21-14.txt)
[2019-03-16-03-33-02（禁用模块时）.txt](https://github.com/ElderDrivers/EdXposed/files/2972638/2019-03-16-03-33-02.txt)

**Comment by solohsu** [comment]
看不出什么东西来，不知道温州银行干了啥。

**Comment by rxzcums** [comment]
@solohsu 经测试，最新内测版验证码提取器（xposed）与ed 0.3.1.7下，温州银行已经能运行了！目前，一切都显得如此完美，谢谢！
