### ISSUE TITLE
[BUG] 坚果Pro bootloop

### ISSUE THREAD

**Issue by TonyHutt** [ElderDrivers/EdXposed#160]
**什么情况/What happened?**

坚果Pro，刷入magisk-EdXposed后重启bootloop

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

- Ruri - Core
- Ruri - Ed Xposed
- Tai Chi
- Systemless Hosts

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.1.2_beta
Riru: v17.1
Magisk: v18.2-0204d053(18114)

**相关Logcat/Logcat**
[bootloop.log](https://github.com/ElderDrivers/EdXposed/files/2970329/bootloop.log)

**Comment by TonyHutt** [comment]
不知道这两个case有没有参考价值：
[坚果 Pro2s开机卡logo](https://github.com/taichi-framework/TaiChi/issues/34)
[酷安 - 柴可夫手扶拖拉机司机的动态](https://www.coolapk.com/feed/10427539?shareKey=Y2JlOGExMTZlZTkwNWM2ZmI0NjM~&shareUid=2013801&shareFrom=com.coolapk.market_9.0.2)

**Comment by solohsu** [comment]
8.0 以下的建议还是用原版的 Xposed 或者 太极 吧。
由于个人时间精力有限决定不再支持 7.x 及以下版本了。
感谢支持～
