### ISSUE TITLE
［bug］magisk勾选模块导致数据流量不能使用

### ISSUE THREAD

**Issue by zjszzw** [ElderDrivers/EdXposed#161]
什么情况/What happened?

无法使用流量

Xposed模块列表/Xposed Module List

无

Magisk模块列表/Magisk Module List

riru-Ed Xposed v0.3.1.2_beta
riru-core v17.1

EdXposed及Riru版本/Versions of EdXposed and Riru

EdXposed: v0.3.1.2_beta

Riru:v17.1

相关Logcat/Logcat
未获取到

**Comment by rxzcums** [comment]
请按模板要求反馈，并附上log
