### ISSUE TITLE
Crash shown in logs and no further logging occurs

### ISSUE THREAD

**Issue by bggold** [ElderDrivers/EdXposed#167]
Installed magisk-EdXposed-v0.3.1.5_beta-SNAPSHOT-release to see if it would fix an issue with a module and no matter how many modules are loaded after the last module is loaded a crash begins and not further logging occurs.  

The two modules it is loading are working even though there is the crash.

You can see  in the logs I just saved the last entry in the log occurred at 13:12 and it is currently 18:45.

This build did not resolve the issue with a module.  I don't expect it to work as it is too old.

EdXposedInstaller v2.2.3
Riru v17.1

Thanks

[xposed_error_20190317_183713.log](https://github.com/ElderDrivers/EdXposed/files/2976066/xposed_error_20190317_183713.log)

**Comment by solohsu** [comment]
Please check if the log file content is ok.

**Comment by bggold** [comment]
Module logs still shows crash and not thing after but verbose does have more info.  There are a lot of errors and permission denied.
[xposed_error_20190322_080357.log](https://github.com/ElderDrivers/EdXposed/files/2997060/xposed_error_20190322_080357.log)
[xposed_all_20190322_080354.log](https://github.com/ElderDrivers/EdXposed/files/2997061/xposed_all_20190322_080354.log)

**Comment by solohsu** [comment]
Errors recorded in logs seem to be not related.
I wonder what further loggings you are expecting.
Maybe it's normal if modules just print logs at the beginning. I am not sure.
If you think it's a crash which stops logging, maybe you can try to catch and provide it via logcat.

**Comment by bggold** [comment]
Everything seems to be working.  Logs just done make sense.
