### ISSUE TITLE
[BUG] Snapchat detects EdXposed when logging in FIX!

### ISSUE THREAD

**Issue by Juxstin** [ElderDrivers/EdXposed#168]
**什么情况/What happened?**
Says  Connecting to Server ERROR
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
SnapTools
允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
Adguard DNS
BUSYBOX
IOS 12.1
Riru - Core LATEST
EdXposed LATEST
YTB VANCED
SWIFT INSTALLER 
允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
0.3.1.2 BETA 
Riru:
17.1
**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
Are you sure it was caused by Xposed stuff having been detected?

**Comment by Juxstin** [comment]
@solohsu yes magisk isn't detect but as soon i install ed xposed it doesn't let u sign in XD

**Comment by hockeymikey** [comment]
> @solohsu yes magisk isn't detect but as soon i install ed xposed it doesn't let u sign in XD
You can never sign into Snap with any xposed enabled because of safetynet, it gets tripped.

**Comment by IsaiasLeos** [comment]
@hockeymikey how does it get tripped? Have any proof? I've tried multiple different apps with edxposed installed and they've all said the same thing. That you've passed safetynet. It's either detecting snapfreedom or the exposed installer app. But it's not because of safetynet "tripping" or failing.

**Comment by arshess** [comment]
Same here. Just got banneda and Impossible to reconnect on snap with edxposed on. Must to deactivate it.

I can't be sûre if edxposed is the reason of ban, but i prefer add it for information

**Comment by nicegamer7** [comment]
Maybe the package name (com.solohsu.android.edxp.manager) has been added to a black list.

**Comment by Juxstin** [comment]
@solohsu possible repackage name support? if what @nicegamer7 is saying.
Plus its a good idea to avoid other apps to do that method IMO

**Comment by nicegamer7** [comment]
I've done no research into it, just pure speculation. But I too thought it would helpful to have package renaming, like Magisk Manager has.

**Comment by Juxstin** [comment]
@nicegamer7 snapchat has been known to blacklist package names. It's blacklisted snaptools before.

**Comment by dna1982** [comment]
Install XPrivacyLua then disable "Get Applications" permission of Snapchat, see how it goes.
Without this permission, app can't get your installed applications list.

**Comment by Juxstin** [comment]
@dna1982 that method hasn't worked for years.... Snapchat bypassed that.

**Comment by solohsu** [comment]
#209
