### ISSUE TITLE
[BUG] Bootloop on LineageOS 15.1, Android 8.1

### ISSUE THREAD

**Issue by Menci** [ElderDrivers/EdXposed#17]
**什么情况/What happened?**
开机时停在 LineageOS 引导动画中，无法进入系统。
Stuck in LineageOS boot animation. Unable to boot into system.

**Xposed模块列表/Xposed Module List**
N/A

**Magisk模块列表/Magisk Module List**
Busybox for Android NDK ***1.29.3***
Ice Box System Plugin Module ***v1.6***
LogCat Bootloop ***v10***
Riru - Core ***v11*** (or ***v10***)

And EdXposed.

**系统型号、版本及xp版本/Versions**
尽量完整/Please write down fully
Sony Xperia XZ1 Compact - [LineageOS 15.1](https://forum.xda-developers.com/xperia-xz1-compact/development/lineageoslilac-t3745215) - Android 8.1 - EdXposed 0.2.6 ~ 0.2.9.1

**相关Logcat/Logcat**
我进行了两次引导尝试，其中第二次引导尝试前，我在 TWRP 中清除了 Dalvik / Cache。以下是 LogCat Bootloop 模块为我获取的日志。似乎第一次引导时，EdXposed 并没有被加载。
I attempted to boot twice. Before the second time, I wiped Dalvik / Cache in TWRP. Here is the log got by LogCat Bootloop. It seems that in the first boot EdXposed is not loaded.

First: https://gist.github.com/Menci/88c59cb31d479ce2bb373582ce02503a
Second: https://gist.github.com/Menci/3c009c3649b9bc2b7bde34f379be6303

**Comment by Leungsiuyin** [comment]
lineageOS可以用原版xposed或者systemless版的xposed。

**Comment by Menci** [comment]
@Leungsiuyin 我用官方 Xposed 也不太稳，经常闪退之类的

**Comment by solohsu** [comment]
日志里没有找到什么有用的信息。如果你清理了dalvik-cache的话，下一次启动应该会比较慢，会重新优化部分应用

**Comment by Menci** [comment]
@solohsu 通过哪些方式可以获取更多信息？

**Comment by solohsu** [comment]
Try https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2

**Comment by Menci** [comment]
Thanks but I no longer have a device running Oreo. I've upgraded to Pie and
running EdXp.

**Comment by solohsu** [comment]
Good choice. :)
