### ISSUE TITLE
[BUG] 系统优化导致森林庄园模块无效

### ISSUE THREAD

**Issue by binera** [ElderDrivers/EdXposed#170]
**什么情况/What happened?**

系统优化导致森林庄园模块无效

**Xposed模块列表/Xposed Module List**

森林&庄园
音量增强器
云村清洁工
运动加速器

**Magisk模块列表/Magisk Module List**

Riru-Core

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.1.6_beta-SNAPSHOT (3160)

Riru: 17.1

**相关Logcat/Logcat**

[error-1970-02-24-10-43-04.log](https://github.com/ElderDrivers/EdXposed/files/2982280/error-1970-02-24-10-43-04.log)

**Comment by solohsu** [comment]
日志里只看到有加载音量增强器。
没看到其他模块的相关信息。
