### ISSUE TITLE
[BUG] UI Crashing (Android 9)

### ISSUE THREAD

**Issue by ishuya** [ElderDrivers/EdXposed#172]
**什么情况/What happened?**

UI crashing & reloading every 30sec from boot while using device.

**Xposed模块列表/Xposed Module List**

1. GravityBox v9.0.0-beta-4

**Magisk模块列表/Magisk Module List**

1. Riru - Core
2. Riru - Ed Xposed
3. YouTube Vanced - Magisk Repo

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.1.2_beta

Riru: v17.1

**相关Logcat/Logcat**

Xposed Logcat-
[xposed_error_20190319_183643.log](https://github.com/ElderDrivers/EdXposed/files/2985992/xposed_error_20190319_183643.log)

Android Logcat Suggesting EdXposed related issue-
[Log.txt](https://github.com/ElderDrivers/EdXposed/files/2986003/Log.txt)

Android Full Logcat-
[logcat.log](https://github.com/ElderDrivers/EdXposed/files/2986004/logcat.log)

**Comment by MlgmXyysd** [comment]
@C3C0

**Comment by C3C0** [comment]
Althou module does not support MIUI, errors in module are handled which means reported system ui crash is not directly related to module. Those crashes happen in ART. Check Log.txt.

**Comment by C3C0** [comment]
OK. Still, that cannot be fixed at module level.

**Comment by ishuya** [comment]
There were no issue of crash in 1 month old ROM with same versions. Maybe recent Security Patch has some role?

**Comment by ishuya** [comment]
**No issues after recent update with EdXposed v0.3.1.7_beta & EdXposedManager v4.3.1**

**Comment by ishuya** [comment]
Closed

**Comment by ishuya** [comment]
Same crashes again came after updating ROM. Tried uninstalling & reinstalling EdXposed with newer versions, no luck.

**Comment by Juxstin** [comment]
See nothing related to edxposed.

**Comment by ishuya** [comment]
Issue Solved with GravityBox v9.0.0-beta-7 Update for now.
