### ISSUE TITLE
[BUG] Cannot run Module after upgrade module version.

### ISSUE THREAD

**Issue by tuyennn** [ElderDrivers/EdXposed#173]
**什么情况/What happened?**
While
Upgrading GravityBox v9.0.0-beta-3 to GravityBox v9.0.0-beta-4
Or sometimes upgrading other modules
- The new upgraded version hangs at first after reboot
- Sometimes upgraded version caused bootloop.
- Clear the Riru - Core and Riru - Ed Xposed from Recovery then reflash them on Magisk once more time
- New upgraded module works

***As my investigation***
In the log, there was some kind of compare module name and xpose called the old module version but not the new one to load -> this could caused the module doesn't work after upgrading.
```
03-19 18:29:36.404   699   699 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-V4ltiLxioVB727G9H-QgzQ==/base.apk
```

**Xposed模块列表/Xposed Module List**
   - GravityBox v9.0.0
   -  CorePatch
   - Maxlock
   - Minminguard
   -  SMS code extractor
   - Statusbardownload

**Magisk模块列表/Magisk Module List**
   - Riru - Core
   -  Riru - Ed Xposed
   - YouTube Vanced - Magisk Repo

**EdXposed及Riru版本/Versions of EdXposed and Riru**

- EdXposed: v0.3.1.5_beta
- Riru: v17.1

**相关Logcat/Logcat**
[xposed_error_20190319_183643.log](https://github.com/ElderDrivers/EdXposed/files/2986453/xposed_error_20190319_183643.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by tuyennn** [comment]
Related #102

**Comment by solohsu** [comment]
If it was loading old module apk, there should be logs like "File not found".
In logs you provided I can't find anything suspicious.
Did you do a hard reboot or soft reboot?

**Comment by tuyennn** [comment]
@solohsu this is the log which I was success bootup after reflash Ed Xposed and Riru. Should the implementation be more inefficiency to detect old and new version (apk) while checking modules enabled from module list?

**Comment by tuyennn** [comment]
Here the log which I cached after upgrading GravityBox v9.0.0-beta-4 to GravityBox v9.0.0-beta-5
Once again the new apk installed then reboot but module cannot load instantly. Have to disable from module list, normal reboot then reenable once again.  
[xposed_error_20190324_074223.log](https://github.com/ElderDrivers/EdXposed/files/2999953/xposed_error_20190324_074223.log)

**Comment by solohsu** [comment]
@tuyennn Maybe it's a common issue. You have to keep the installer app alive when updating module apk, otherwise the installer app cannot receive the broadcast of module upgrade to update enabled module list.

**Comment by tuyennn** [comment]
@solohsu You're correct
