### ISSUE TITLE
[BUG]  MIUI系统的安全中心 hook异常

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#176]
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: error when hooking LoadedApk.<init>: pkg=com.miui.securitycenter, prc=com.miui.securitycenter
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: java.lang.NullPointerException
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at java.io.File.<init>(File.java:283)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at dalvik.system.DexPathList.addNativePath(DexPathList.java:617)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at dalvik.system.BaseDexClassLoader.addNativePath(BaseDexClassLoader.java:201)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.app.ApplicationLoaders.addNative(ApplicationLoaders.java:134)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:744)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.elderdrivers.riru.xposed.entry.hooker.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:80)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.app.ContextCompat.createLoadedApk(Unknown Source:101)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.app.ContextCompat.createApplicationContext(Unknown Source:0)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.miui.securitycenter.dynamic.ApkLoader.getDynamicContext(Unknown Source:36)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.createOrUpdateManagerWT(Unknown Source:2)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.connectWT(Unknown Source:19)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.access$400(Unknown Source:0)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at com.miui.securitycenter.dynamic.DynamicServiceManager$DynamicWorkHandler.handleMessage(Unknown Source:35)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.os.Looper.loop(Looper.java:201)
03-22 11:36:01.209  3872  4265 E EdXposed-Fwk: 	at android.os.HandlerThread.run(HandlerThread.java:65)

小米9 android p miui10 
我不太清楚这个异常会导致什么问题 而且貌似是riru的报错？

**Comment by solohsu** [comment]
这是在hook LoadedApk的构造方法时尝试获取它的classloader时发生的错误。
貌似是libPath数组里有一个字符串为null，不清楚是小米的bug还是什么。
已经做了try catch finally处理，所以不会导致应用本身有什么问题。
除非有人想要hook com.miui.securitycenter？
不过就算要hook它也不一定有问题，看他的调用堆栈不像是正常启动应用时的调用。
