### ISSUE TITLE
[BUG] 网易云音乐插件2.8.2无效

### ISSUE THREAD

**Issue by Howard20181** [ElderDrivers/EdXposed#177]
**什么情况/What happened?**

模块无效
> 网易云音乐插件2.8.2

[网易云音乐插件_2.8.2.zip](https://github.com/ElderDrivers/EdXposed/files/2994936/_2.8.2.zip)
模块自己报告已激活，但实际无效果

**Xposed模块列表/Xposed Module List**

> 网易云音乐插件2.8.2
微信学英语
微信增强
微X
音量增强器0.0.30
云村清洁工2.7.0
指纹支付
MusicNotification
QQ净化
QX

**Magisk模块列表/Magisk Module List**

> ADB & Fastboot for Android NDK
Busybox for Android NDK
Log Catcher15
Magisk管理器Recovrey版
MIUI通知栏去白边+分块
Riru-Core17.1
Riru_Edxposed
Systemless Hosts
通用GMS打盹

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.3.1.7

Riru:17.1

设备：小米5
系统：MIUI 10.2 Android8.0

Magisk：18.1(18100)
Magisk Manager：7.0.0(185)

**相关Logcat/Logcat**
[log.log](https://github.com/ElderDrivers/EdXposed/files/2994916/log.log)
[all.log](https://github.com/ElderDrivers/EdXposed/files/2995158/all.log)

**Comment by solohsu** [comment]
建议联系插件作者吧，没发现什么相关错误日志。不清楚是什么问题导致。
如果确定是框架bug，再来反馈。
