### ISSUE TITLE
[BUG]  三星S9+只能用2.9.8版本 以后的版本都会卡第二屏

### ISSUE THREAD

**Issue by zhang-001** [ElderDrivers/EdXposed#178]
**什么情况/What happened?**

卡开机第二屏

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:最新

Riru:最新

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
Please provide your boot logs :)

**Comment by zhang-001** [comment]
> 请提供你的启动日志:)

**Comment by zhang-001** [comment]
> 请提供你的启动日志:)

**Comment by zhang-001** [comment]
> 请提供你的启动日志:)

如何提取日志

**Comment by zhang-001** [comment]
> 请提供你的启动日志:)

[libart.zip](https://github.com/ElderDrivers/EdXposed/files/3000032/libart.zip)
