### ISSUE TITLE
要你命三千模块无效

### ISSUE THREAD

**Issue by soulpursuit** [ElderDrivers/EdXposed#182]
MIUI10 安卓8.1 模块：要你命三千无效

**Comment by solohsu** [comment]
请提供xposed日志。

**Comment by soulpursuit** [comment]
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 8.1.0
Android sdk: 27
Android build: OPM1.171019.019
Fingerprint: Xiaomi/jason/jason:8.1.0/OPM1.171019.019/9.3.14:user/release-keys
ROM build description: jason-user 8.1.0 OPM1.171019.019 9.3.14 release-keys
EdXposed Version: 0.3.1.7_beta (3170)
Architecture: arm64-v8a
Device: jason
Manufacture: Xiaomi
Brand: Xiaomi
Product: jason
--------- beginning of main
--------- beginning of system
09-09 14:37:36.742  1051  1051 I EdXposed-Core-Native: onModuleLoaded: welcome to EdXposed!
09-09 14:37:36.742  1051  1051 I EdXposed-Core-Native: start to install inline hooks
09-09 14:37:36.742  1051  1051 I EdXposed-Core-Native: install riru hook
09-09 14:37:36.749  1051  1051 I EdXposed-Core-Native: riru hooks installed
09-09 14:37:36.749  1051  1051 I EdXposed-Core-Native: using api level 27
09-09 14:37:36.765  1052  1052 I EdXposed-Core-Native: onModuleLoaded: welcome to EdXposed!
09-09 14:37:36.765  1052  1052 I EdXposed-Core-Native: start to install inline hooks
09-09 14:37:36.765  1052  1052 I EdXposed-Core-Native: install riru hook
09-09 14:37:36.773  1052  1052 I EdXposed-Core-Native: riru hooks installed
09-09 14:37:36.773  1052  1052 I EdXposed-Core-Native: using api level 27
09-09 14:37:36.774  1051  1051 I EdXposed-Core-Native: using installer com.solohsu.android.edxp.manager
09-09 14:37:36.774  1051  1051 I EdXposed-Core-Native: black/white list mode: 0, using whitelist: 0
09-09 14:37:36.774  1051  1051 I EdXposed-Core-Native: dynamic modules mode: 0
09-09 14:37:36.776  1051  1051 I EdXposed-Core-Native: classLinkerCst hooked
09-09 14:37:36.778  1051  1051 I EdXposed-Core-Native: heapPreFork hooked.
09-09 14:37:36.779  1051  1051 I EdXposed-Core-Native: disableHiddenAPIPolicyImpl done.
09-09 14:37:36.779  1051  1051 I EdXposed-Core-Native: install inline hooks done
09-09 14:37:36.791  1052  1052 I EdXposed-Core-Native: using installer com.solohsu.android.edxp.manager
09-09 14:37:36.791  1052  1052 I EdXposed-Core-Native: black/white list mode: 0, using whitelist: 0
09-09 14:37:36.791  1052  1052 I EdXposed-Core-Native: dynamic modules mode: 0
09-09 14:37:36.793  1052  1052 I EdXposed-Core-Native: classLinkerCst hooked
09-09 14:37:36.794  1052  1052 I EdXposed-Core-Native: heapPreFork hooked.
09-09 14:37:36.795  1052  1052 I EdXposed-Core-Native: disableHiddenAPIPolicyImpl done.
09-09 14:37:36.795  1052  1052 I EdXposed-Core-Native: install inline hooks done
09-09 14:37:36.836  1051  1051 I EdXposed-Core-Native: system_property_get: dalvik.vm.dex2oat-filter -> quicken
09-09 14:37:36.836  1051  1051 I EdXposed-Core-Native: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
09-09 14:37:36.843  1052  1052 I EdXposed-Core-Native: system_property_get: dalvik.vm.dex2oat-filter -> quicken
09-09 14:37:36.843  1052  1052 I EdXposed-Core-Native: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
09-09 14:37:36.948  1051  1051 I EdXposed-Core-Native: classLinkerCst starts
09-09 14:37:36.949  1051  1051 I EdXposed-Core-Native: class_linker_ changed from 0x0 to 0x73b1cfd140
09-09 14:37:36.949  1051  1051 I EdXposed-Core-Native: classLinkerCst finishes
09-09 14:37:36.949  1052  1052 I EdXposed-Core-Native: classLinkerCst starts
09-09 14:37:36.949  1052  1052 I EdXposed-Core-Native: class_linker_ changed from 0x0 to 0xe9dd3240
09-09 14:37:36.949  1052  1052 I EdXposed-Core-Native: classLinkerCst finishes
03-23 00:48:41.275  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.yaerin.xposed.hide-GfCWXLlr9HVR939_ER1zFg==/base.apk
03-23 00:48:41.294  1051  1051 I EdXposed-Bridge:   Loading class com.yaerin.xposed.hider.InitInjector
03-23 00:48:41.296  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/ru.sxbuIDfx.pFSOyagrF-uG57k1xKla_aQfCeMiFVeg==/base.apk
03-23 00:48:41.349  1051  1051 I EdXposed-Bridge:   Loading class com.xposed.XSupport
03-23 00:48:41.544  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.fkzhang.wechatxposed-MrEAAo57d-Wtal01LC52-Q==/base.apk
03-23 00:48:41.558  1051  1051 I EdXposed-Bridge:   Loading class com.fkzhang.wechatxposed.XposedInit
03-23 00:48:41.565  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedgepro-rPxGelsgM42DqEkYQzJxVQ==/base.apk
03-23 00:48:41.586  1051  1051 I EdXposed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
03-23 00:48:41.590  1051  1051 I EdXposed-Bridge: [XEdgePro] App version: 5.3, activated by ed xposed.
03-23 00:48:41.600  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/cn.kwaiching.hook-K0ftums2YVaZngW3o3mVHA==/base.apk
03-23 00:48:41.619  1051  1051 I EdXposed-Bridge:   Loading class cn.kwaiching.hook.hook.ChingHook
03-23 00:48:41.625  1051  1051 I EdXposed-Bridge:   Loading class cn.kwaiching.hook.hook.Ching
03-23 00:48:41.625  1051  1051 E EdXposed-Bridge:     This class requires resource-related hooks (which are disabled), skipping it.
03-23 00:48:41.625  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.yuanwofei.cardemulator-yLvFKmqOsrZnViC0MyAnyA==/base.apk
03-23 00:48:41.647  1051  1051 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
03-23 00:48:41.651  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/eu.faircode.xlua-6OWE4T-bhIr721rDRJ-NNg==/base.apk
03-23 00:48:41.672  1051  1051 I EdXposed-Bridge:   Loading class eu.faircode.xlua.XLua
03-23 00:48:41.684  1051  1051 I EdXposed-Bridge: Loading modules from /system/priv-app/Greenify/Greenify.apk
03-23 00:48:41.696  1051  1051 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
03-23 00:48:41.711  1051  1051 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
03-23 00:48:41.711  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.coderstory.toolkit-T_X__cke9a0YXnvSmfiSSw==/base.apk
03-23 00:48:41.732  1051  1051 I EdXposed-Bridge:   Loading class toolkit.coderstory.com.toolkit.CorePatch
03-23 00:48:41.888  1051  1051 I EdXposed-Bridge: Loading modules from /data/app/com.sky.xposed.aweme-RWg0OZSvkqO6eS5EQ0YTuw==/base.apk
03-23 00:48:41.900  1051  1051 I EdXposed-Bridge:   Loading class com.sky.xposed.aweme.Main
03-23 00:48:43.192  1903  1903 I EdXposed-Bridge: [XEdgePro] System hooked
03-23 00:48:50.624  1903  1903 I EdXposed-Bridge: [XEdgePro] Screen size: 1080, 1920
03-23 00:48:50.631  1903  1903 I EdXposed-Bridge: [XEdgePro] Display info{ initial size(1080, 1920), forced size(1080, 1920), initial density=480, scaled density=480 }
03-23 00:48:51.483  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.yaerin.xposed.hide-GfCWXLlr9HVR939_ER1zFg==/base.apk
03-23 00:48:51.490  1052  1052 I EdXposed-Bridge:   Loading class com.yaerin.xposed.hider.InitInjector
03-23 00:48:51.492  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/ru.sxbuIDfx.pFSOyagrF-uG57k1xKla_aQfCeMiFVeg==/base.apk
03-23 00:48:51.501  1052  1052 I EdXposed-Bridge:   Loading class com.xposed.XSupport
03-23 00:48:51.686  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.fkzhang.wechatxposed-MrEAAo57d-Wtal01LC52-Q==/base.apk
03-23 00:48:51.696  1052  1052 I EdXposed-Bridge:   Loading class com.fkzhang.wechatxposed.XposedInit
03-23 00:48:51.699  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.jozein.xedgepro-rPxGelsgM42DqEkYQzJxVQ==/base.apk
03-23 00:48:51.707  1052  1052 I EdXposed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
03-23 00:48:51.712  1052  1052 I EdXposed-Bridge: [XEdgePro] App version: 5.3, activated by ed xposed.
03-23 00:48:51.716  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/cn.kwaiching.hook-K0ftums2YVaZngW3o3mVHA==/base.apk
03-23 00:48:52.148  1052  1052 I EdXposed-Bridge:   Loading class cn.kwaiching.hook.hook.ChingHook
03-23 00:48:52.149  1052  1052 I EdXposed-Bridge:   Loading class cn.kwaiching.hook.hook.Ching
03-23 00:48:52.149  1052  1052 E EdXposed-Bridge:     This class requires resource-related hooks (which are disabled), skipping it.
03-23 00:48:52.149  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.yuanwofei.cardemulator-yLvFKmqOsrZnViC0MyAnyA==/base.apk
03-23 00:48:52.156  1052  1052 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
03-23 00:48:52.162  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/eu.faircode.xlua-6OWE4T-bhIr721rDRJ-NNg==/base.apk
03-23 00:48:52.170  1052  1052 I EdXposed-Bridge:   Loading class eu.faircode.xlua.XLua
03-23 00:48:52.184  1052  1052 I EdXposed-Bridge: Loading modules from /system/priv-app/Greenify/Greenify.apk
03-23 00:48:52.193  1052  1052 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
03-23 00:48:52.204  1052  1052 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
03-23 00:48:52.205  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.coderstory.toolkit-T_X__cke9a0YXnvSmfiSSw==/base.apk
03-23 00:48:52.213  1052  1052 I EdXposed-Bridge:   Loading class toolkit.coderstory.com.toolkit.CorePatch
03-23 00:48:52.369  1052  1052 I EdXposed-Bridge: Loading modules from /data/app/com.sky.xposed.aweme-RWg0OZSvkqO6eS5EQ0YTuw==/base.apk
03-23 00:48:52.381  1052  1052 I EdXposed-Bridge:   Loading class com.sky.xposed.aweme.Main
03-23 00:48:54.706  1903  2846 I EdXposed-Bridge: [XEdgePro] Boot completed
03-23 00:49:12.936  4480  4480 I EdXposed-Bridge: com.tencent.mm loading com.fkzhang.wechatxposed
03-23 00:49:18.173  4480  4480 I EdXposed-Bridge: feature loaded: themes 1
03-23 00:49:18.193  4480  4480 I EdXposed-Bridge: 微X模块 2.0_1.1 ()(1,1) p
03-23 00:49:18.194  4480  4480 I EdXposed-Bridge: com.fkzhang.wechatxposed (2.0): wechat version 7.0.3(1400)
03-23 00:49:18.200  4480  4741 I EdXposed-Bridge: feature loaded: base 1
--------- beginning of crash
03-23 00:50:51.733  9419  9419 I EdXposed-Bridge: com.tencent.mm loading com.fkzhang.wechatxposed
03-23 00:50:55.240  9419  9513 I EdXposed-Bridge: feature loaded: base 1
03-23 00:50:55.272  9419  9419 I EdXposed-Bridge: feature loaded: themes 1
03-23 00:50:55.288  9419  9419 I EdXposed-Bridge: 微X模块 2.0_1.1 (b1)(1,1) p
03-23 00:50:55.288  9419  9419 I EdXposed-Bridge: com.fkzhang.wechatxposed (2.0): wechat version 7.0.3(1400)
03-23 00:52:45.586  4480  5009 I EdXposed-Bridge: [1553297400000]
03-23 00:52:45.729  4480  4741 I EdXposed-Bridge: load transcoder 2

**Comment by soulpursuit** [comment]
这样提交对吗？

**Comment by soulpursuit** [comment]
主要是针对小草客户端也就是里面的那个填头草的选项不行，其他的选项没测试

**Comment by solohsu** [comment]
```
03-23 00:48:52.148 1052 1052 I EdXposed-Bridge: Loading class cn.kwaiching.hook.hook.ChingHook
03-23 00:48:52.149 1052 1052 I EdXposed-Bridge: Loading class cn.kwaiching.hook.hook.Ching
03-23 00:48:52.149 1052 1052 E EdXposed-Bridge: This class requires resource-related hooks (which are disabled), skipping it.
```
看起来这个模块是用到了资源hook功能，现在EdXposed尚未支持。不知道不生效是不是这个原因导致。
由于这个模块不是开源的，所以我也没法帮忙确定。
建议联系模块作者，如果确定是框架的bug再来反馈。
