### ISSUE TITLE
add auto update 

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposed#184]
hope we add auto update so we don't have to keep coming here for new versions

**Comment by solohsu** [comment]
You may want to check out the [EdXposed Manager](https://github.com/ElderDrivers/EdXposedManager/releases) developed by MlgmXyysd  :)
And if you want it to be included in EdXposed Installer, you are welcome to submit a feature request to [its issues page](https://github.com/solohsu/XposedInstaller/issues).
