### ISSUE TITLE
[BUG] 三星S9+刷最新会卡第二屏  只能用2.9.8版本  

### ISSUE THREAD

**Issue by zhang-001** [ElderDrivers/EdXposed#186]
**什么情况/What happened?**

开机卡第二屏

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**Logcat不知道怎么提取    只有libart

/system/lib/libart.so 
[libart.zip](https://github.com/ElderDrivers/EdXposed/files/2999205/libart.zip)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
@zhang-001 用这个抓日志：https://github.com/ElderDrivers/EdXposed/issues/131#issuecomment-473502478
参考：https://github.com/MlgmXyysd/Log-Catcher

**Comment by zhang-001** [comment]
> @ zhang-001用这个抓日志：[＃131（评论）](https://github.com/ElderDrivers/EdXposed/issues/131#issuecomment-473502478)
> 参考：[https](https://github.com/MlgmXyysd/Log-Catcher)：[//github.com/MlgmXyysd/Log-Catcher](https://github.com/MlgmXyysd/Log-Catcher)

[boot-2018-10-21-19-31-53.log](https://github.com/ElderDrivers/EdXposed/files/3018889/boot-2018-10-21-19-31-53.log)
[boot-2018-10-21-19-34-00.log](https://github.com/ElderDrivers/EdXposed/files/3018890/boot-2018-10-21-19-34-00.log)
[boot-2018-10-21-19-12-46.log](https://github.com/ElderDrivers/EdXposed/files/3018891/boot-2018-10-21-19-12-46.log)
[boot-2018-10-21-19-15-18.log](https://github.com/ElderDrivers/EdXposed/files/3018892/boot-2018-10-21-19-15-18.log)
[boot-2018-10-21-19-19-28.log](https://github.com/ElderDrivers/EdXposed/files/3018893/boot-2018-10-21-19-19-28.log)
[boot-2018-10-21-19-22-06.log](https://github.com/ElderDrivers/EdXposed/files/3018894/boot-2018-10-21-19-22-06.log)
[boot-2018-10-21-19-29-12.log](https://github.com/ElderDrivers/EdXposed/files/3018895/boot-2018-10-21-19-29-12.log)
[error-2018-10-21-19-12-46.log](https://github.com/ElderDrivers/EdXposed/files/3018898/error-2018-10-21-19-12-46.log)
[error-2018-10-21-19-15-18.log](https://github.com/ElderDrivers/EdXposed/files/3018899/error-2018-10-21-19-15-18.log)
[error-2018-10-21-19-19-28.log](https://github.com/ElderDrivers/EdXposed/files/3018900/error-2018-10-21-19-19-28.log)
[error-2018-10-21-19-22-06.log](https://github.com/ElderDrivers/EdXposed/files/3018901/error-2018-10-21-19-22-06.log)
[error-2018-10-21-19-29-12.log](https://github.com/ElderDrivers/EdXposed/files/3018902/error-2018-10-21-19-29-12.log)
[error-2018-10-21-19-31-53.log](https://github.com/ElderDrivers/EdXposed/files/3018903/error-2018-10-21-19-31-53.log)
[error-2018-10-21-19-34-00.log](https://github.com/ElderDrivers/EdXposed/files/3018904/error-2018-10-21-19-34-00.log)


所有的都发给你了、希望不会太多

**Comment by zhang-001** [comment]
@solohsu
