### ISSUE TITLE
[Question] Android Version Q

### ISSUE THREAD

**Issue by GODLIKE5** [ElderDrivers/EdXposed#187]
Will there be support or already is support for Android Q if so can you send it... I have a developer preview with my pixel and was wanting to try it.

**Comment by solohsu** [comment]
I don't have devices running Android Q. I haven't tried it myself.
But I saw that [Riru might have some issues on Android Q](https://github.com/RikkaApps/Riru-LocationReportEnabler/issues/16).

**Comment by MlgmXyysd** [comment]
Riru now support Q, try youself.

**Comment by GODLIKE5** [comment]
I'll try thanks.

**Comment by CuCuCheung** [comment]
Happy

**Comment by hacker1024** [comment]
I'm getting a bootloop, MIUI based on AOSP 10. I have a Redmi K20 Pro.
https://hastebin.com/uguzagehed.txt
