### ISSUE TITLE
Google Text to Speech error

### ISSUE THREAD

**Issue by samahmed** [ElderDrivers/EdXposed#189]
When trying to navigate in Google Maps, Google Text to Speech engine throws the following error when EdXposed is enabled. Can you please check?

03-24 10:18:19.430 12969 12969 E AndroidRuntime: Process: com.google.android.tts, PID: 12969
03-24 10:18:19.430 12969 12969 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.google.android.tts.service.GoogleTTSService: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3762)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:237)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7045)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at EdHooker12.hook(Unknown Source:165)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at atm.a(PG:266)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at atm.a(PG:185)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at asq.a(PG:261)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at ars.a(PG:255)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at ars.a(PG:168)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at com.google.android.tts.service.GoogleTTSService.onLoadLanguage(PG:65)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.speech.tts.TextToSpeechService.onCreate(TextToSpeechService.java:144)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at com.google.android.tts.service.GoogleTTSService.onCreate(PG:27)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3750)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: 	... 8 more

**Comment by solohsu** [comment]
```
03-24 10:18:19.430 12969 12969 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at EdHooker12.hook(Unknown Source:165)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at atm.a(PG:266)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at atm.a(PG:185)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at asq.a(PG:261)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at ars.a(PG:255)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at ars.a(PG:168)
03-24 10:18:19.430 12969 12969 E AndroidRuntime: at com.google.android.tts.service.GoogleTTSService.onLoadLanguage(PG:65)
```
It seems like this module messed it up.
Can you provide the enabled xposed module list?

**Comment by samahmed** [comment]
Sure, the module list has been attached.
![Screenshot_20190328-174106_EdXposed Installer](https://user-images.githubusercontent.com/5702276/55162388-2da61180-5181-11e9-944e-b244fd30c2c2.jpg)

**Comment by solohsu** [comment]
I could not figure out which module caused this. Can you try to disable these modules one by one and find it?

**Comment by samahmed** [comment]
Sure! After switching each module off one by one, it turned out to be the AFWall+ module causing the issue. The strange thing is that when I enabled AFWall+ again, just to be double check it was indeed causing the issue, the force close disappeared. Seems like simply switching the AFWall+ module off and back on fixed it. Anyhow, many thanks for your time!
