### ISSUE TITLE
[BUG] pixel3 激活xposed edge 无法开机

### ISSUE THREAD

**Issue by anyin233** [ElderDrivers/EdXposed#19]
**什么情况/What happened?**
激活xposed edge后无法开机

**Xposed模块列表/Xposed Module List**
仅激活xposed edge和Google app助手

**Magisk模块列表/Magisk Module List**

![screenshot_20190124095812](https://user-images.githubusercontent.com/35858233/51650109-f0c37000-1fc1-11e9-9daa-592e8fc5dc6f.jpg)

![screenshot_20190124095832](https://user-images.githubusercontent.com/35858233/51650122-ffaa2280-1fc1-11e9-9005-1a028be342a6.jpg)

**系统型号、版本及xp版本/Versions**
pixel 3 -系统具体版本：PQ1A.190105.004-安全补丁19年1月5日-出现问题的edxposed版本：2.8.5及以后
**相关Logcat/Logcat**
有助于定位问题/It can help us to locate issue
[bootloop-2019-01-24-10-42-33.log](https://github.com/solohsu/EdXposed/files/2790020/bootloop-2019-01-24-10-42-33.log)
[bootloop-2019-01-24-10-47-02.log](https://github.com/solohsu/EdXposed/files/2790021/bootloop-2019-01-24-10-47-02.log)
[bootloop-2019-01-24-10-52-16.log](https://github.com/solohsu/EdXposed/files/2790022/bootloop-2019-01-24-10-52-16.log)

**Comment by MlgmXyysd** [comment]
请更新edxposed。

**Comment by anyin233** [comment]
抱歉，是从2.8.5开始以后的版本都会出现问题

**Comment by MlgmXyysd** [comment]
你的截图里显示是0.2.8版本

**Comment by anyin233** [comment]
那个是可以正常开机的版本，之后的版本尝试后都已经回退了

**Comment by MlgmXyysd** [comment]
@solohsu 看一下。

**Comment by solohsu** [comment]
Fixed in [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)
