### ISSUE TITLE
Please SandHook save Nougat

### ISSUE THREAD

**Issue by Stillhard** [ElderDrivers/EdXposed#192]
@SandHook please save Nougat and Earlier devices, make EdXposed working in our devices.

**Comment by rxzcums** [comment]
check this
https://github.com/ElderDrivers/EdXposed/commit/8c4a7e90f34eb6eeb63aefd968a87038e48981b3

**Comment by Stillhard** [comment]
I'm aware of that, I just need to said it out loud to @sandhook for help(s)

**Comment by R3habDroid** [comment]
Dudes Is there any version support android 7.1？

**Comment by DanGLES3** [comment]
No, currently edxposed doesn't support nougat, currently only official Xposed is available

**Comment by ganyao114** [comment]
Android N, please use origin xposed
