### ISSUE TITLE
我想知道怎么修改edxposed的默认仓库？

### ISSUE THREAD

**Issue by WangSiwang** [ElderDrivers/EdXposed#196]
现在的仓库是xda的仓库，需要墙，
我找到了一个http://edxp.meowcat.org/但是我不知道怎么修改

**Comment by solohsu** [comment]
没太明白。http://edxp.meowcat.org 这个是个空页面。

**Comment by MlgmXyysd** [comment]
http://edxp.meowcat.org 仅供更新检测用，目前没有建立仓库的打算。
