### ISSUE TITLE
[BUG] Safetynet does not pass after a few hours after installing EdXposed. 

### ISSUE THREAD

**Issue by Daviteusz** [ElderDrivers/EdXposed#198]
**什么情况/What happened?**

Safetynet does not pass after a few hours after installing EdXposed. 
After restarting the device, safetynet passes again. It does not matter what module I use.

**Xposed模块列表/Xposed Module List**

![Screenshot_20190330-121754](https://user-images.githubusercontent.com/11527277/55275413-f309b980-52e5-11e9-8e8b-c3c132a2256d.jpg)

**Magisk模块列表/Magisk Module List**

![Screenshot_20190330-121904](https://user-images.githubusercontent.com/11527277/55275420-17659600-52e6-11e9-8ec7-1556183d2c03.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.1.7-beta

Riru: v17.1

**相关Logcat/Logcat**

[xposed_error_20190330_122334.log](https://github.com/ElderDrivers/EdXposed/files/3025396/xposed_error_20190330_122334.log)
[magisk_log_20190330_122540.log](https://github.com/ElderDrivers/EdXposed/files/3025402/magisk_log_20190330_122540.log)

**Comment by bggold** [comment]
Did you blacklist google play services and google pay in edxposed installer?  That will prevent them from getting touched.

**Comment by Daviteusz** [comment]
> Did you blacklist google play services and google pay in edxposed installer? That will prevent them from getting touched.

No, but I will try.

**Comment by bggold** [comment]
Yeah that got me the first time until someone mentioned it.  It would be nice if the dev would do those on install like Magisk does.

**Comment by switchtegrax1** [comment]
Can confirm that blacklisting play services doesn't work, atleast for me, safetynet will randomly fail

**Comment by Daviteusz** [comment]
@bggold Safetynet still passes only for a few hours

**Comment by nicegamer7** [comment]
same for me, I suggested in #168 that it could be the package name (com.solohsu.android.edxp.manager) has been added to a blacklist. I haven't looked into it though, this is just pure speculation. I've seen people suggest the SudoHide module to hide the package.

**Comment by switchtegrax1** [comment]
If it was blacklisted then safetynet wouldn't randomly pass,also disabling edxposed fixes the issue,so it's unlikely it's blacklisted

**Comment by Raidek** [comment]
Then EDXposed passes safetyNet sometimes. Do not? Or do we have to follow a procedure or activate something to make it happen?

**Comment by switchtegrax1** [comment]
Yes,it passes for awhile then it randomly fails,it can take minutes to hour for safetynet to fail for me

**Comment by Raidek** [comment]
So the problem is "riru" or Elder

**Comment by Raidek** [comment]
I have see that there are any betas like this, but i dont know how install it

EdXposed-sandhook-v0.3.1.8_beat7--SHOT-release

https://www.lanzous.com/b642738

**Comment by switchtegrax1** [comment]
Just download them and flash the zip through magisk,before downloading there will be a captcha you need to answer before you download

**Comment by Raidek** [comment]
But, Do They need Riru core?

**Comment by switchtegrax1** [comment]
Yes,I'm using it just fine with riru17.1

**Comment by XspeedPL** [comment]
In EdXposed enable blacklist and add 3 things to it: Google Play Services, Google Play Store and the app you want to pass.
Then in Magisk enable MagiskHide and add the same apps (select all subitems for Google Play Services).
If you don't see the subitems in Magisk upgrade to Magisk v19.

**Comment by switchtegrax1** [comment]
The 3.1.8 betas solved the issue for me,more than 24 hours and safetynet still passes

**Comment by Raidek** [comment]
> In EdXposed enable blacklist and add 3 things to it: Google Play Services, Google Play Store and the app you want to pass.
> Then in Magisk enable MagiskHide and add the same apps (select all subitems for Google Play Services).
> If you don't see the subitems in Magisk upgrade to Magisk v19.

It does not work, I have followed your steps, I have the latest versions of both magisk and EDXposed that are uploaded to the Github

**Comment by Raidek** [comment]
> The 3.1.8 betas solved the issue for me,more than 24 hours and safetynet still passes

You uninstalled EDXposed with "EdXposedUninstaller_rec.zip" from Magisk Manager and then rebooted. After that flash "EdXposed-sandhook-v0.3.1.8_beta8_-SHOT-release (修复 部分 失效 问题) .zip" from magisk manager and finally rebooted. Did you leave version 2.2.4 of EDXposed installer, right?

**Comment by DanGLES3** [comment]
Yes,yes and yes

**Comment by Raidek** [comment]
> Yes,yes and yes

nothing.... :(

**Comment by DanGLES3** [comment]
Try using edxposed in whitelist mode instead of blacklist

**Comment by Raidek** [comment]
> Try using edxposed in whitelist mode instead of blacklist

Selected something?

**Comment by cahyohape** [comment]
For troubleshooting, Try to remove all your module on magisk except riru core and riru edxposed, also remove all module on edxposed, safety net can fail because some module do bad hook to system. After that try restart phone from magisk.

**Comment by Raidek** [comment]
Nothing...

**Comment by Cobertos** [comment]
@Raidek I've had Riru only for a couple weeks now and have had no issues with safetynet. (I've been waiting to install EdXposed once the safetynet stuff is figured out).

**Comment by Raidek** [comment]
I have disabled EdXposed (the module) and I have left the one of riru 17.1 active, and now SafetyNet pass

**Comment by bggold** [comment]
Still no issues.  Did you also blacklist google framework?

**Comment by Raidek** [comment]
I use White list

**Comment by josehdx** [comment]
Hello. I would like to share my experience. I am using a xiaomi a1 with pie. Magisk 19, EdXposed-sandhook-v0.3.1.8 and riru 17.1. my safety net started to fail when updating magisc from 18 to 19( i had the edxposed 3.1.7) then after updating all the xposed related tools, safety net is still failing. I removed xposed and riru from magisk (EdXposedUninstaller_rec.zip did not work for me) and i noticed some things. First, safety net fails the first and second try but after it passes, it never fails again(every reboot is the same). Play services (im in beta) is marked with all sub modules but there is one that can never be inactive(it ends with unstable). I did mark to hide play store but I did not mark play framwork. This is only the things i found on my observation, so i can not say i do the right setup. Thanks for your help
