### ISSUE TITLE
Uninstaller gives error

### ISSUE THREAD

**Issue by barney2229** [ElderDrivers/EdXposed#199]
Uninstaller gives error magisk needs to be installed when magisk is installed

**Comment by instazedd** [comment]
+1

**Comment by ivaf** [comment]
+1

**Comment by MlgmXyysd** [comment]
Uninstaller zip not support in Magisk v19, because it's unused.
Magisk v19 remove magisk.img file, all modules are in /data/adb/modules.
Remove /data/adb/modules/riru_edxposed manually if you want to uninstall.

**Comment by solohsu** [comment]
https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.1.2
Fixed with EdXposedUninstaller_rec-v2.zip

**Comment by garoxas** [comment]
excuse me for asking on closed issue, but I just need to confirm
since the last 2 comments are 2 different options, so which one is recommended to uninstall edxposed?
remove the module in magisk manager as suggested or by flashing the uninstaller by adding it in magisk manager module?
