### ISSUE TITLE
[BUG] Random reboots.

### ISSUE THREAD

**Issue by Danielsahm** [ElderDrivers/EdXposed#201]
**什么情况/What happened?**

Random reboots, not related to any specific task/ situation. Samsung Galaxy Note 8 Exynos version. Android 9.0

**Xposed模块列表/Xposed Module List**

Only XPrivacyLua 

**Magisk模块列表/Magisk Module List**

Riru-core
Riru-ed xposed
Systemless hosts
Ubuntu font
Youtube Vanced

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.1.7_beta

Riru: 17.1

**相关Logcat/Logcat**
[xposed_error_20190402_204556.log](https://github.com/ElderDrivers/EdXposed/files/3035516/xposed_error_20190402_204556.log)
[pmsg-ramoops-0.log](https://github.com/ElderDrivers/EdXposed/files/3035517/pmsg-ramoops-0.log)

**Comment by Danielsahm** [comment]
Still having the same on 0.4.1.2 Yahfa

**Comment by russianspy1234** [comment]
Same issue. My only xposed module is exi for SwiftKey. My magisk modules are
App systemizer
Riru core
Riru edxposed
Substratum

I have an s9+ exynos
edxposed 2.2.4

**Comment by akivura** [comment]
Same issue with Samsung Note 8 Exynos on Android 9.

Magisk Modules:
Systemless Hosts
Riru - Core v19.5
Riru - EdXposed v0.4.5.1_beta(4463) (SandHook)

I don't have any Xposed modules installed.
I just changed from the SandHook version of EdXposed to YAHFA to see if that's relevant.
EdXposed Installer v2.2.4

**Comment by dr-kaisar** [comment]
Riru core magisk module is causing random soft reboots in my Samsung Galaxy Note 10 Lite (running Android 10). Can anyone help regarding this issue?

I have tried both EDxposed and LSposed. Whenever I only tick the Riru core within magisk app then soft reboots occur randomly.
