### ISSUE TITLE
[BUG] Framework not answering

### ISSUE THREAD

**Issue by ivaf** [ElderDrivers/EdXposed#206]
**什么情况/What happened?**

When I try to start any modules - nothing happened. For example, MinMinGuard says, that Exposed not found, or just not starting. GravityBox says that framework not answers.
Also in EdXposed installer message "Xposed Framework version 90.0-0.3.1.7-beta active" is always green (regardless of whether the switch "Status Xposed" is on or off).
Can you help me understand what wrong with my device, please? How can I use EdXposed on my Sharp Aquos (Android 8.0)?

**Xposed模块列表/Xposed Module List**

EdXposedInstaller_v2.2.4-release
MinMinGuard
GravityBox [O]

允许截图/Screenshot allowed
![Screenshot_2019-04-06-13-53-55](https://user-images.githubusercontent.com/17968134/55669360-fa4d3c00-587e-11e9-9d74-8e5e47808908.png)
![Screenshot_2019-04-06-13-54-08](https://user-images.githubusercontent.com/17968134/55669367-046f3a80-587f-11e9-8474-353082f6d3c2.png)
![Screenshot_2019-04-06-16-01-34](https://user-images.githubusercontent.com/17968134/55669887-79de0980-5885-11e9-94ba-9ec5265e03b8.png)
![Screenshot_2019-04-06-15-59-00](https://user-images.githubusercontent.com/17968134/55669896-84000800-5885-11e9-9700-44bb826e0998.png)

**Magisk模块列表/Magisk Module List**

Magisk v19.0
Magisk Manager v7.1.1
magisk-riru-core-v17.1
magisk-EdXposed-v0.3.1.7_beta-release (also trying EdXposed-sandhook-v0.3.1.8_beat7--SHOT-release)

允许截图/Screenshot allowed

![Screenshot_2019-04-06-15-57-38](https://user-images.githubusercontent.com/17968134/55669910-a8f47b00-5885-11e9-9075-258834a47e20.png)
![Screenshot_2019-04-06-15-57-45](https://user-images.githubusercontent.com/17968134/55669894-84000800-5885-11e9-966c-1a7294a292f2.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.3.1.7_beta, v0.3.1.8_beta

Riru: Riru Core v17.1

**相关Logcat/Logcat**

[xposed_all_20190406_155958.log](https://github.com/ElderDrivers/EdXposed/files/3050472/xposed_all_20190406_155958.log)
[xposed_error_20190406_155931.log](https://github.com/ElderDrivers/EdXposed/files/3050473/xposed_error_20190406_155931.log)

**Comment by ivaf** [comment]
The problem with GravityBox decided. Install the module from here: https://github.com/GravityBox/GravityBox/releases/tag/v8.5.3.1-edxposed_o

**Comment by ivaf** [comment]
With the MinMinGuard module the problem was temporarily solved as follows. After rebooting the smartphone, I install the module again (I launch the installation of the apk (https://github.com/chiehmin/MinMinGuard/releases), and it works.

**Comment by solohsu** [comment]
04-06 15:56:23.593   722   722 I EdXposed-Bridge:   Loading class com.ceco.oreo.gravitybox.GravityBox
04-06 15:56:23.597   722   722 E EdXposed-Bridge:     This class requires resource-related hooks (which are disabled), skipping it.
@ivaf It was because of v0.3.x.x didn't support resources hooking. Try release v0.4.1.2.
