### ISSUE TITLE
[BUG] After restart EdXposed does not always find the installed modules

### ISSUE THREAD

**Issue by yennor** [ElderDrivers/EdXposed#207]
**什么情况/What happened?**

When restarting the device. Most of the time EdXposed doesn't find the installed modules, and doesn't load them. The same when doing a shutdown and then switching the device on again. But I have the feeling that it happens less often when shuting down the device. My best guess is that there must be some kind of timing issue??? So just switching the phone on and off 1-2 times usually helps.
The phone is a mi a2 lite, with android pie.
Removing/Reinstalling the modules etc. Doesn't help. I just need to do several restarts, until edxposed finds the modules. 

As it seems it can't find the modules (I've verified the paths, they are correct):

04-06 12:03:31.630  1938  1938 I EdXposed-Bridge: Loading modules from /data/app/xyz.nulldev.statusbarsleep-tSo_q2fGNoZQ3PllEKkd7Q==/base.apk
04-06 12:03:31.630  1938  1938 E EdXposed-Bridge:   File does not exist
04-06 12:03:31.630  1938  1938 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-IGef4jhx8WMDShPaXvkQMQ==/base.apk
04-06 12:03:31.630  1938  1938 E EdXposed-Bridge:   File does not exist
04-06 12:03:35.532  1939  1939 I EdXposed-Bridge: Loading modules from /data/app/xyz.nulldev.statusbarsleep-tSo_q2fGNoZQ3PllEKkd7Q==/base.apk
04-06 12:03:35.532  1939  1939 E EdXposed-Bridge:   File does not exist
04-06 12:03:35.532  1939  1939 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-IGef4jhx8WMDShPaXvkQMQ==/base.apk
04-06 12:03:35.533  1939  1939 E EdXposed-Bridge:   File does not exist

**Xposed模块列表/Xposed Module List**

-Gravitybox
-Statusbarsleep

**Magisk模块列表/Magisk Module List**

TTL Tethering Fix (asus zenfone max pro)
Systemless host
Greenify4Magisk
f-droid privileged extension
debloater
daily job scheduler

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
v0.3.1.7_beta

Riru:
v17.1

**相关Logcat/Logcat**

I've already restarted the phone again, and it found the modules again. But I can attach a logcat the next time it happens....

**Comment by weigeloveu** [comment]
are you using oxygen os？I have the same bug on my oneplus 3 with h2os 9.0

**Comment by yennor** [comment]
No. I'm using the stock os, which is Android One

**Comment by 2220209876** [comment]
This is also the case in Syberia OS, magisk 19.1

**Comment by papuruth** [comment]
Same issue here it was fine on lineage os but the problem arised when i started to use resurrection remix
