### ISSUE TITLE
[BUG] 要你命三千模块fc，有时会跟jasi patcher冲突

### ISSUE THREAD

**Issue by weigeloveu** [ElderDrivers/EdXposed#208]
**什么情况/What happened?**

要你命三千模块fc，有时会跟jasi patcher冲突
3000模块现在已经适配edxposed，在某些机型上可以运行，不依赖于资源钩子了
**Xposed模块列表/Xposed Module List**

![Screenshot_20190407-161016_EdXposed_Manager](https://user-images.githubusercontent.com/19830500/55680708-c0983600-594f-11e9-9d86-5ca23dc61e78.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_20190407-161009_Magisk_Manager](https://user-images.githubusercontent.com/19830500/55680709-cee65200-594f-11e9-8636-b5d9f1744be8.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.3.1.7

Riru:17.1

**相关Logcat/Logcat**

[log.zip](https://github.com/ElderDrivers/EdXposed/files/3051339/log.zip)

**Comment by solohsu** [comment]
应该是模块问题。找作者反馈吧。
