### ISSUE TITLE
[BUG] Snapchat COMPLETELY Detects EdXposed

### ISSUE THREAD

**Issue by JReverse** [ElderDrivers/EdXposed#209]
**What happened?**
After the recent updates snapchat now fully detects EdXposed on any version you will be banned if you hook and sometimes they ban for having it installed

How is this possible you ask well its known for a while snapchat has a backdoor to check shit. They started doing that in 10.25

How do i know this for sure?: I hooked one function as a test and got a 12 hour ban Proof:
https://cdn.discordapp.com/attachments/559850493283926036/565078572364988416/Screenshot_20190409-023539.jpg

**EdXposed Module List**
My Module (Enabled)
Lucky Patcher (Disabled)

**Magisk Module List**
AdGuardDNS AdBlocker (Unoffical)
Busybox for Android NDK
IOS 12.1 Emoji
Riru - Core
Riru - EdXposed
Snapchat Host Blocker
Swift Installer Module
Youtube Vanced

**Versions of EdXposed and Riru**

EdXposed:
0.3.1.7_Beta

Riru:
17.1

**Logcat/Logcat**
None i'm not risking another ban

As i stated in #168 this is a big issue that has gotten worse!

**Comment by perfiction** [comment]
Try installing XprivacyLua xposed module, then block "Determine activity" and "Get applications" for Snapchat. It helped some time ago, when SC was detecting modules like Snapprefs or Snaptools.

**Comment by dizzydoo** [comment]
Want to believe it's bypassing any blocks done by xprivacylua, I have both checked, Snapchat v10.53.0 installed and was running Riru 17.1 + EdXp 0.3.1.7-beta as well. Got a 24hr lockout, after it was up I received another but I had EdXposed itself uninstalled, only Riru v15 and EdXposed Installer app v2.2.4 (now removed).

**Comment by Juxstin** [comment]
@dizzydoo @perfiction XprivacyLua will not help they execute remote javascript code to detect 
![image](https://user-images.githubusercontent.com/40630518/56559718-f9e3bf00-6567-11e9-8fef-d0a1e69c0204.png)
Thats the response it gives

**Comment by jizzy002** [comment]
So the issue is still present and there is no fix for it currently?

**Comment by Juxstin** [comment]
@jizzy002 i know the issue Hint a .so file is detected

**Comment by ChanceGPM** [comment]
Is this fixed yet?

**Comment by AeonLucid** [comment]
@ChanceGPM No, https://github.com/ElderDrivers/EdXposed/pull/281.
