### ISSUE TITLE
[BUG] 日志错误

### ISSUE THREAD

**Issue by zxf969175364** [ElderDrivers/EdXposed#210]
**什么情况/What happened?**

日志显示不了

edxposed中的模块日志与详细日志都有这个问题

Cannot read log /data/user_de/0/com.solohsu.android.edxp.manager/log/all.log (Permission denied)

magisk v19.0
magisk manager v7.1.1
EdXposed v0.3.1.7_beta 
EdXposedInstaller_v2.2.4-release.apk

![image](https://user-images.githubusercontent.com/12622610/55860851-b5d7de00-5ba7-11e9-80d9-03c6974dba2c.png)

![image](https://user-images.githubusercontent.com/12622610/55860863-bf614600-5ba7-11e9-9717-2c63a9d3c834.png)

**Comment by zxf969175364** [comment]
给了root权限了

**Comment by zxf969175364** [comment]
![image](https://user-images.githubusercontent.com/12622610/55861352-cc326980-5ba8-11e9-8ab9-063797172ca2.png)

补一张图 两个日志文件中都打印出日志了 貌似只是edxpoesd没权限读取

**Comment by zxf969175364** [comment]
![image](https://user-images.githubusercontent.com/12622610/55861679-71e5d880-5ba9-11e9-851f-bfed32a36d5b.png)

补一张图 两个日志文件都有内容 实际是打印出来了只是不知道为什么没正常读取

**Comment by pine1212** [comment]
Selinux status
 Enforcing

**Comment by zxf969175364** [comment]
> Selinux status
> Enforcing

????

**Comment by pine1212** [comment]
我这里也是跟你一样的情况，只有把selinux关闭才能读出来。但是文件内容还是一直都有在写的。可以su cat 查看

**Comment by zxf969175364** [comment]
@pine1212 是的 还是可以cat看的 可是有点麻烦...我想着把它每次cp出来 也还是不行 他可能是日志位置写错了 8.0之后貌似 app只能对/data下自己app所对应的文件夹有读写权限 即使你怎么给他赋权都不能读写别的

**Comment by MlgmXyysd** [comment]
可能是文件的用户组问题。

**Comment by mr-cn** [comment]
同样的问题
Mi6 MIUI9 稳定版9.6.3.0
