### ISSUE TITLE
[BUG] 什么时候支持资源挂钩，想修改通知栏

### ISSUE THREAD

**Issue by 1229375100** [ElderDrivers/EdXposed#211]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
在最新的Open-beta版(0.4.0.1)已支持资源hook。

**Comment by 1229375100** [comment]
> 在最新的开放-β版（0.4.0.1）已支持资源钩。

最新版在哪呢？官网没有啊？

**Comment by 1229375100** [comment]
最新版在哪呢？github上没有更新啊






------------------ 原始邮件 ------------------
发件人: "Jim Wu"<notifications@github.com>;
发送时间: 2019年4月25日(星期四) 中午11:32
收件人: "ElderDrivers/EdXposed"<EdXposed@noreply.github.com>;
抄送: "陈帅"<1229375100@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ElderDrivers/EdXposed] [BUG] 什么时候支持资源挂钩，想修改通知栏 (#211)




在最新的Open-beta版(0.4.0.1)已支持资源hook。
