### ISSUE TITLE
[BUG] Snapchat App

### ISSUE THREAD

**Issue by samet53** [ElderDrivers/EdXposed#213]
**What happened?**
Continuous accounts are banned.I'm forbidden after the riru module.
I was banned for 2 days.
then 1 week.
XPrivacyLua I've tried.the result is still the same. 😔

**Xposed Module List**
Jasi patcher
Lucky patcher
NSFW keyboard
SudoHide
XPrivacyLua

**Magisk Module List**
Busybox
GLtools
NFS-INJECTOR
Riru-Core
Riru-Ed Xposed

**Versions of EdXposed and Riru**
EdXposedInstaller_v2.2.4-release
magisk-EdXposed-v0.3.1.7_beta-release
magisk-riru-core-v17.1

**Comment by samet53** [comment]
I hid it with SudoHide Module. How does he detect? I do not understand.

**Comment by samet53** [comment]
https://play.google.com/store/apps/details?id=com.oasisfeng.island

I've tried

**Comment by Juxstin** [comment]
#209 same issue bro

**Comment by solohsu** [comment]
#209
