### ISSUE TITLE
凤凰os 刷入EdXposed后无法开机黑屏 UI无法启动

### ISSUE THREAD

**Issue by yanygm** [ElderDrivers/EdXposed#216]
希望大佬适配！

**Comment by Howard20181** [comment]
目前只是支持8.0+ 
凤凰OS似乎是Android 7

**Comment by MlgmXyysd** [comment]
Android 7也可以用，目前支持版本是5+。

**Comment by solohsu** [comment]
@yanygm Details about the device and ROM?

**Comment by yanygm** [comment]
@solohsu 
CPU:intel i7-6500U
ROM:Phoenix OS v3.0.8 x86_64 Android 7.1.1
kernel:4.13.5-android-x86_64

**Comment by solohsu** [comment]
> @solohsu
> CPU:intel i7-6500U
> ROM:Phoenix OS v3.0.8 x86_64 Android 7.1.1
> kernel:4.13.5-android-x86_64

EdXposed 之前就已经不再支持 8.0 以下的系统了。8.0 以下的建议安装官方 Xposed吧。
