### ISSUE TITLE
Conflicting with other magisk modules on Android pie

### ISSUE THREAD

**Issue by manuw2009** [ElderDrivers/EdXposed#217]
Hi,
Xposed no longer works (using chromepie) when viper4android magisk module is enabled.
Redmi note 4x, pixel expérience pie rom

**Comment by xDaKillerx** [comment]
i see. in my case . using james DSP + Audio compatibility patch with Sandhook results in a bootloop. but the yahfa works fine.

**Comment by h4rdc4stle** [comment]
bump on this issue reporting same conflict with any Viper module happens with xHIFI and FX. xPrivacy not functional with Viper module active.

**Comment by solohsu** [comment]
#265
