### ISSUE TITLE
请问能兼容3c toolbox吗？

### ISSUE THREAD

**Issue by Gokou-Ruri** [ElderDrivers/EdXposed#220]
**什么情况/What happened?**

3c toolbox的权限管理功能需要xposed支持，但在edxposed中勾选3c toolbox，重启后3c toolbox依旧提示未启用模块。（其它模块例如文本自定义、PCB、Undo等都正常工作。）

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.3.1.7（edxposed manager 4.2.1 标准工作模式）

Riru:v18

**Comment by solohsu** [comment]
确定3c toolbox支持9.0并且兼容EdXposed吗？

**Comment by Gokou-Ruri** [comment]
给3ctb开发者发了email但是没收到回复，该软件用到xposed的功能主要是权限管理功能，理论上应该是能兼容Android 9的（对于新权限应该不兼容，但3c本身也不支持那些新功能，旧权限应该能兼容）。

**Comment by solohsu** [comment]
暂时无法知道到底哪里需要兼容。
