### ISSUE TITLE
[Question] Is there a way to set the priority of a module?

### ISSUE THREAD

**Issue by Ninlives** [ElderDrivers/EdXposed#222]
There is a "priority" property for ``XCallback``, but I didn't find a way to set the priority for a class implements ``IXposedHookLoadPackage``, since it's not a subclass of ``XCallback``

**Comment by C3C0** [comment]
Questions if is legitimate to have such possibility. How do you assess your module needs other priority than others?

**Comment by Ninlives** [comment]
@C3C0 I think I actually want to be able change the loading priority manually in the installer apo. Currently the priority seems to be determined by the hash of the package name

**Comment by XspeedPL** [comment]
Modules should be designed to not interfere with others. Dependencies aren't supported out of the box.
What do you need the priority for?

**Comment by solohsu** [comment]
@Ninlives You can set priority on an instance of XCallback's subclasses, e. g. XC_MethodHook.

**Comment by XspeedPL** [comment]
@solohsu From what I understand OP wants to be able to set priority on module interfaces like zygote init and package load hooks

**Comment by solohsu** [comment]
@XspeedPL Sorry for the mistake. You are right. Those are not supported.
