### ISSUE TITLE
error 1 in twrp // samsung s9 PIE

### ISSUE THREAD

**Issue by hanswurst31** [ElderDrivers/EdXposed#225]
what am i doing wrong?

**Comment by hanswurst31** [comment]
seems to work via magisk but not in twrp. of course this gets a problem when you install a xposed module and end up in a bootloop, because you cant flash the edxposed uninstaller via twrp....

**Comment by hanswurst31** [comment]
s ere a module.list like with orig xposed  i can fix my bootloop manually lke discribed here:

https://forum.xda-developers.com/xposed/howto-disable-xposed-modules-via-t3227175

**Comment by hanswurst31** [comment]
i worked around thios problem via uninstalling magisk via zip file:

https://forum.xda-developers.com/showpost.php?p=72542167&postcount=242

**Comment by MlgmXyysd** [comment]
See in https://github.com/ElderDrivers/EdXposed/issues/199.

**Comment by solohsu** [comment]
https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.1.2
Fixed with EdXposedUninstaller_rec-v2.zip
