### ISSUE TITLE
[Question] Android Version 6.0

### ISSUE THREAD

**Issue by SunatP** [ElderDrivers/EdXposed#230]
Can EdXposed run in Android 6.0? i found something i before i flashed Magisk 19.1, i already flash Xposed v87.3 for magisk and Magisk 18.1 after flash Magisk 19.1 and restart Xposed Framework is change it to Riru-EdXposed and it stuck in splash screen

**Comment by DanGLES3** [comment]
No, edxposed currently only supports Android Oreo and above

**Comment by SunatP** [comment]
@DanGLES3 Thanks for an information a lot!!!😎😎

**Comment by MlgmXyysd** [comment]
EdXposed can run in 5.0-9.0(10.0 not tested).
Riru can run in 6.0-10.0.
so you can use on 6.0-9.0.

**Comment by SunatP** [comment]
@MlgmXyysd But Edxposed can't Run on my device Galaxy Note 4 that's use Android 6.0 and Lenovo K4 note based on RR 7.1 can't runt too and i can't grab a logcat to report, what do i wrong or EdXposed not fully work on 6.0 and 7.1???

**Comment by solohsu** [comment]
> @MlgmXyysd But Edxposed can't Run on my device Galaxy Note 4 that's use Android 6.0 and Lenovo K4 note based on RR 7.1 can't runt too and i can't grab a logcat to report, what do i wrong or EdXposed not fully work on 6.0 and 7.1???

No, Android 7 and lower are not supported by EdXposed. You can install official Xposed.
