### ISSUE TITLE
[BUG] [XPOSED API] afterHook callback called when it shouldn't

### ISSUE THREAD

**Issue by C3C0** [ElderDrivers/EdXposed#233]
When param.setResult is called in beforeHookedMethod callback, afterHookedMethod callback should not be called afterwards but it actually is. Looks like there is something wrong about handling returnEarly flag. The same behavior in YAHFA as well as Sandhook.

**Comment by solohsu** [comment]
https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XposedBridge.java#L350
@C3C0 I see that `param.returnEarly` is used to determine whether to skip remaining "before" callbacks and corresponding "after" callbacks.

**Comment by C3C0** [comment]
Yes, it's in original Xposed API implementation and it worked OK in official Xposed. But isn't it done differently in EdXposed? What about this? https://github.com/ElderDrivers/EdXposed/blob/master/edxp-yahfa/src/main/java/com/elderdrivers/riru/edxp/yahfa/dexmaker/HookerDexMaker.java#L451

**Comment by ganyao114** [comment]
https://github.com/ganyao114/SandHook/blob/master/xposedcompat/src/main/java/com/swift/sandhook/xposedcompat/hookstub/HookStubManager.java

I think SandHook is same as OG Xposed

**Comment by C3C0** [comment]
Looks to be the same at first sight but there is a different handling of snapshot length. OG Xposed has snapshot length value stored in a variable before loops start while EdXp uses length directly during loops. I did not inspect the underlying code but what about if length changes during enumeration?

**Comment by ganyao114** [comment]
Object[] callbacksSnapshot = additionalInfo.callbacks.getSnapshot();
 
Will get a clone of copyOnWriteArrayList, length will not change in bridge

**Comment by C3C0** [comment]
OK. How can I help with debugging? I am 100% sure afterHook calls even if you do param.setResult in beforeHook.

**Comment by solohsu** [comment]
> OK. How can I help with debugging? I am 100% sure afterHook calls even if you do param.setResult in beforeHook.

Which afterHook call you mean? I think the corresponding afterHook of the beforeHook in which param.setResult is done won't be skipped as designed. If you mean other afterHooks, then it should be a bug.

**Comment by C3C0** [comment]
Maybe I just did not notice such behavior up until now although it has always been there.
