### ISSUE TITLE
[BUG] EdXposed not working on Huawei 9.0 (Mate 20 Pro for exemple)

### ISSUE THREAD

**Issue by izno69** [ElderDrivers/EdXposed#234]
Hi, i have a Mate 20 Pro
I install Magisk (v19.1) Riru (v18), Edxposed (v0.4.1.2_beta) and i follow the guide... but bootloop !
Edxposed is not working on Huawei with 9.0 Pie
I install on a official Huawei Rom (bootloop) and i test too on the RomAur (1.4) and bootloop too... [link](https://forum.xda-developers.com/mate-20-pro/development/08-01-romaur-v1-0-fast-stable-t3887498)
:(

**Comment by izno69** [comment]
So What ?

**Comment by solohsu** [comment]
https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.2.3_a
check out the release notes

**Comment by izno69** [comment]
The solution it work:
https://www.google.com/amp/s/forum.xda-developers.com/mate-20-pro/development/how-to-install-xposed-mate-20-pro-lya-t3937612/amp/
