### ISSUE TITLE
[BUG] 0.2.9.8后不支持Perfect Color Bar了?

### ISSUE THREAD

**Issue by VKinTang** [ElderDrivers/EdXposed#235]
**什么情况/What happened?**

安装PCB后只能用0.2.9.8版本，如果升级到后面的版本就会无法开机卡第二屏只能刷回0.298的版本。有没有办法重新让PCB模块工作？？

**Xposed模块列表/Xposed Module List**
Perfect Color Bar

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.1.2

Riru:18

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by Gokou-Ruri** [comment]
pcb1.5.2亲测可以正常工作，请自行测试。

**Comment by VKinTang** [comment]
原来1.5.2可以。我是用1.5.3，谢谢大佬了
