### ISSUE TITLE
[BUG] SandHook卡开机

### ISSUE THREAD

**Issue by vonf** [ElderDrivers/EdXposed#237]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by vonf** [comment]
索尼XZP用SandHook版本卡开机界面，无限重启

**Comment by ganyao114** [comment]
请提供有效开机日志
