### ISSUE TITLE
[BUG] 刷入edxposed后，导致所有magisk模块失效。

### ISSUE THREAD

**Issue by Gokou-Ruri** [ElderDrivers/EdXposed#238]
**什么情况/What happened?**

当未刷入edxposed模块时，其它所有magisk模块（包括riru模块）均正常工作。
当刷入edxposed模块后，所有magisk模块（包括edxp模块）均失效，例如emoji替换、sub主题模块、vanced等模块失效，且edxp manager或installer会提示框架未安装（不是“未激活”）。也就是说这些magisk模块挂载的文件实际未挂载到系统分区中。

**Xposed模块列表/Xposed Module List**

> com.surcumference.fingerprintpay
com.elderdrivers.googlesearchbox
ru.WBWYnech.MPOTOnuIO
top.fols.aapp.eternalprocessxposed
io.shortway.appcontext
com.github.tianma8023.xposed.smscode
liubaoyua.customtext
com.oasisfeng.greenify
pub.chara.cwui.pretendsharing_xposed

**Magisk模块列表/Magisk Module List**

> Advanced Charging Controller (acc)
Riru - Core
Riru - Ed Xposed
S9 Emoji for Magisk
Screen Recorder
Setting summary text fix
substratum
YouTube Vanced - Magisk Repo

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.3.1.7（也试过0.4.1.2 SandHook和YAHFA）

Riru: v18

Magisk: Stable 19.1

Android: Pie(AOSIP)

**相关Logcat/Logcat**
[liveboot_edxp.log （刷入edxp模块后的开机日志](https://github.com/ElderDrivers/EdXposed/files/3145333/liveboot_edxp.log)
[liveboot_noedxp.log （刷入edxp模块前的开机日志](https://github.com/ElderDrivers/EdXposed/files/3145334/liveboot_noedxp.log)
因为刷入edxp后magisk模块无法工作，所以用liveboot抓取了开机启动时的日志。
如果该日志对排查没有帮助，请告诉我其它方法，谢谢！

**Comment by Gokou-Ruri** [comment]
补充：测试了两个rom均如此，猜测应该是edxposed当前无法兼容magisk stable v19.1。

**Comment by solohsu** [comment]
Fixed.
