### ISSUE TITLE
[BUG] SandHook 模式下，网易云音乐相关插件全部失效

### ISSUE THREAD

**Issue by if1y** [ElderDrivers/EdXposed#239]
**什么情况/What happened?**

最新版，SandHook 模式确实很好，解决了之前很多问题，唯独这个模式下，网易云音乐相关插件全部失效
同时想说明的是，一同发布的 YAHFA 模式则直接尿崩，完全闪退到无法使用。

**Xposed模块列表/Xposed Module List**

核心破解，上帝模式，微信学英语，微x，音量增强器，应用变量，云村清洁工，运动加速器，MusicNotification，QNotified，QQ净化，QX

**Magisk模块列表/Magisk Module List**

iOS Emoji，Google DNS，MM，MIUI Download Vip，Project WIPE Systemless，Riru，Edxposed，状态栏分栏

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.1.2 beta (SandHook)

Riru: 17.1

**Comment by lie-ying** [comment]
riru   v18下也失效

**Comment by dna1982** [comment]
我用 SandHook 模式，网易云音乐相关插件正常。

**Comment by lie-ying** [comment]
请问版本是？

**Comment by yesmiley** [comment]
测试：通过关闭“即时模块列表”，网易云插件成功生效，但与此同时，卡顿延迟加剧，且插件不能实时生效。

**Comment by lie-ying** [comment]
重新刷机后已经解决。大音量有效清洁工有效

**Comment by ivancheng458** [comment]
我换到hahfa的xpsosed大音量正常哦

**Comment by NewBugger** [comment]
我的经历：无论 yahfa sandhook，只要关闭 instant module list 就能生效网易云模块。

以后每次更新模块都要重启。

**Comment by yesmiley** [comment]
> 我的经历：无论 yahfa sandhook，只要关闭 instant module list 就能生效网易云模块。
> 
> 以后每次更新模块都要重启。

是的，我也是这样，前面有说。
应该是这个有冲突。

**Comment by NewBugger** [comment]
应该不是冲突。经历表明，不仅是网易云模块，还有 amplify xprivacylua 等老牌模块，都不能用于 instant mode，可以猜测是这些模块只适配 xp 原项目那类需要重启的方式，并不适配 edxp instant 方式。

**Comment by yesmiley** [comment]
最新发现：

关闭 instant module list 确实能够解决网易云相关的模块，但又导致 云闪付APP 卡在 splash 页了（这个问题之前有，后来在 edxp 更新迭代过程中得到了解决）

所以意思是网易云和云闪付必须只宠一个嘛 😂

**Comment by yesmiley** [comment]
> 应该不是冲突。经历表明，不仅是网易云模块，还有 amplify xprivacylua 等老牌模块，都不能用于 instant mode，可以猜测是这些模块只适配 xp 原项目那类需要重启的方式，并不适配 edxp instant 方式。

就是冲突的，你看我最新发的，关闭之后又导致了其它问题。

**Comment by NewBugger** [comment]
@yesmiley  
依旧不能证明你的冲突猜测。支付类应用一般不需要用到框架。  
你需要白名单模式排除云闪付应用。

**Comment by yesmiley** [comment]
> @yesmiley
> 依旧不能证明你的冲突猜测。支付类应用一般不需要用到框架。
> 你需要白名单模式排除云闪付应用。

就是因为支付应用不应该搭上xp我才会说存在冲突
此前我已经使用过黑名单---无效，搭配兼容模式--无效，现在改成了白名单---依旧无效，magisk hide添加了---还是无效。
尝试过这么多的屏蔽方式，依然无法使得 云闪付和网易云同时正常工作，这不是猜测这是实证冲突。

**Comment by NewBugger** [comment]
这什么逻辑啊。。

首先这完全无法证明是两个应用的冲突

如果不能确定那个支付应用出问题的原因，什么都确定不了

**Comment by dna1982** [comment]
自己找问题吧 在我这里云闪付和网易云同时正常工作 根本没什么冲突
instant mode记得关了

**Comment by yesmiley** [comment]
> 自己找问题吧 在我这里云闪付和网易云同时正常工作 根本没什么冲突
> instant mode记得关了

如果不是反尝试多种方法之后还存在问题，我会来这问吗？
你没有问题不代表别人没有，不要说这种不负责任的话，谢谢！

**Comment by yesmiley** [comment]
> 自己找问题吧 在我这里云闪付和网易云同时正常工作 根本没什么冲突
> instant mode记得关了



> 这什么逻辑啊。。
> 
> 首先这完全无法证明是两个应用的冲突
> 
> 如果不能确定那个支付应用出问题的原因，什么都确定不了

因为 instant module list 打开就能进去了，所以这是冲突，这个逻辑有问题吗？
你是不是没看完全我说的话？

**Comment by yesmiley** [comment]
**继续状态更新：**
最新使用 SandHook-v0.4.4.4_alpha 可以在开启 instant module list 状态下，使得网易云相关模块正常，并保证云闪付亦可正常运行（在未开启 instant module list 状态下依旧卡 splash），看起来是冲突 bug 暂时得到了解决。
后续保持关注。

不过有个问题，白名单模式下会导致部分模块提示未启用（但具体功能有成功了一些，只是一些，也就是半生效）。
