### ISSUE TITLE
[BUG] EdXposed not loading module

### ISSUE THREAD

**Issue by jizzy002** [ElderDrivers/EdXposed#241]
EdXposed not recognising one module, log attached.

EdXposed: 0.4.1.2_beta
Riru: v18

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 9
Android sdk: 28
Android build: PQ2A.190405.003
Fingerprint: htc/himaulatt_na_gen_unlock/htc_himaulatt:7.0/NRD90M/894012.12:user/release-keys
ROM build description: 4.30.617.12 CL894012 release-keys
EdXposed Version: 0.4.1.2_beta (4120)
Architecture: arm64-v8a
Device: himaul
Manufacture: HTC
Brand: htc
Product: himaul
--------- beginning of main
--------- beginning of system
05-07 22:19:56.038   841   841 I EdXposed-Bridge: using HookProvider: com.elderdrivers.riru.edxp.sandhook.config.SandHookProvider
05-07 22:19:56.191   841   841 I EdXposed-Bridge: Loading modules from /data/app/com.ihelp101.instagram-j0EhTFFr36KBXqxBZWGdTg==/base.apk
05-07 22:19:56.191   841   841 E EdXposed-Bridge:   File does not exist
05-07 22:20:08.709   842   842 I EdXposed-Bridge: using HookProvider: com.elderdrivers.riru.edxp.sandhook.config.SandHookProvider
05-07 22:20:08.977   842   842 I EdXposed-Bridge: Loading modules from /data/app/com.ihelp101.instagram-j0EhTFFr36KBXqxBZWGdTg==/base.apk
05-07 22:20:08.978   842   842 E EdXposed-Bridge:   File does not exist

**Comment by jizzy002** [comment]
Issue unknown, closing due to lack of replies

**Comment by papuruth** [comment]
You say you can't fix it what is issue unknown.
It's already been specified that edxposed is unable to load modules.
