### ISSUE TITLE
[BUG]  libriru_edxp.so IS DETECTED BY SNAPCHAT

### ISSUE THREAD

**Issue by Juxstin** [ElderDrivers/EdXposed#242]
#209 #168 #213 
libriru_edxp.so is 100% detected
I have solved the problem after extensive testing. I cannot fork due to my method isn't a permit fix.

**Comment by DarshanDeshpande** [comment]
Could you please share the solution if possible. Im scared to downloading edxposed  because I already faced a  12hour account lock before even though I had no modules related to snapchat installed. I don't want another lock please

**Comment by jizzy002** [comment]
Updooting this, any way to share the solution with us? (locked for 8 more hours tho)

**Comment by tobias231h** [comment]
Is Snapchat already banning if EdXposed is installed or only when you hook SC-methods?
Does XPrivacyLua help?
Would you like to give us some hints to solve the problem with the libriru_edxp.sp detection?
(I'd like to install EdXposed again, but as long as SC is banning you, I don't want to risk anything)

**Comment by AeonLucid** [comment]
Snapchat checks for the existence of atleast these classes
- de/robv/android/xposed/XposedBridge
- xposed/dummy/XResourcesSuperClass

**Comment by solohsu** [comment]
#209
