### ISSUE TITLE
[BUG] EdXposed Detected or Blacklist function not working

### ISSUE THREAD

**Issue by lahceneamine** [ElderDrivers/EdXposed#245]
Since updating to v0.4.1.2, my banking app is detecting EdXposed (or the blacklist function isn't working I can't tell).
Whever my banking app detects any "root" related thing, it instantly crashes and return an html page which tells you that there's a security error.

Banking App :
dz.natixis.prod

**Xposed Module List**
- App Locale 2
- Exi for Swiftkey
- Firefds Kit
- Firefox Tablet Mode
- MinMinGuard
then I added RootCloak & Sudohide to try hiding EdXposed from the banking app but no clue.

**Magisk Module List**
- Call Recorder - SKVALEX
- Riru - Core v19
- Riru - Ed Xposed v0.4.1.2 SandHook
- substratum
- Sysconfig patcher
- Systemless Hosts
- YouTuve Vanced

EdXposed:
v0.4.1.2 sandhook (I also tried YAHFA, same thing)
Riru:
v19 (also tried 18)

**Logcat**
I attached a logcat for the specific app in the zip
[logs-2019-05-09-17-51-32.zip](https://github.com/ElderDrivers/EdXposed/files/3163240/logs-2019-05-09-17-51-32.zip)

**If you need anything else, like the banking apk, just tell me**
Thank You

**Comment by rxzcums** [comment]
have you tested edxposed installer?

**Comment by lahceneamine** [comment]
> 
> 
> have you tested edxposed installer?

you mean [this ](https://github.com/solohsu/XposedInstaller/releases) ?
I'm using it since it has been launched.

**Comment by Evengard** [comment]
I'm actually having the same problem with Samsung Pay (Watch Plug-in) "com.samsung.android.samsungpay.gear". If I disable the Magisk module and reboot - it works fine (even with enabled Riru Core and WITH installed EdXposed Manager - only EdXposed module disabled), if I reenable it back - it complains about root and stuff.

**Comment by xinxin8816** [comment]
> > have you tested edxposed installer?
> 
> you mean [this ](https://github.com/solohsu/XposedInstaller/releases) ?
> I'm using it since it has been launched.

Please test [this](https://github.com/ElderDrivers/EdXposedManager)

**Comment by xinxin8816** [comment]
On my device, edxposed installer works well , but not edxposed manager, It may relatively.

**Comment by lahceneamine** [comment]
> 
> 
> > > have you tested edxposed installer?
> > 
> > 
> > you mean [this ](https://github.com/solohsu/XposedInstaller/releases) ?
> > I'm using it since it has been launched.
> 
> Please test [this](https://github.com/ElderDrivers/EdXposedManager)



> 
> 
> On my device, edxposed installer works well , but not edxposed manager, It may relative.

Thank you for your answer, but it didn't work for me as well :(
It works for some apps, but not all :/

**Comment by lahceneamine** [comment]
I don't know how/why, but with : 
- v0.4.2.3 alpha YAHFA
- Riru core v19.1
- EdXposed Installer v2.2.4
The blacklist fuction is working again even with broken safetnet (because of the alpha)

**Comment by solohsu** [comment]
Please try the latest alpha version.

**Comment by lahceneamine** [comment]
> 
> 
> Please try the latest alpha version.

It seems to be working well on the beta 0.4.5.1.
Thank you a lot :)

**Comment by yayaflirt** [comment]
Please i am in thé same case of you , with the same app, the last update edxposed IS detected

**Comment by Evengard** [comment]
I'm using [this experimental build (0.5.0.0 (4558))](https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/34428655/artifacts) - seems to work fine.

**Comment by kotori2** [comment]
#634 should fixed this
