### ISSUE TITLE
[BUG] ：华为Nexus6  EdXposed安装一直显示尚未激活

### ISSUE THREAD

**Issue by xiguabugaoxing** [ElderDrivers/EdXposed#246]
**什么情况/What happened?**
EDXposed 安装后 显示没有激活

**Magisk模块列表/Magisk Module List**
Riru-core
Riru EDXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
Riru-core: v10
Riru EDXposed: v0.0.9.8_beat1

**相关Logcat/Logcat**

[all.log](https://github.com/ElderDrivers/EdXposed/files/3168769/all.log)
[error.log](https://github.com/ElderDrivers/EdXposed/files/3168770/error.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
> /system/framework/XposedBridge.jar

Uninstall official Xposed framework.
