### ISSUE TITLE
Bug (Don't install framework)

### ISSUE THREAD

**Issue by SerikKr** [ElderDrivers/EdXposed#25]
Do not install framework(0.2.9.5) on my Xiaomi Mi max 3 ( Pixel Experience, 9.0 Android, 28 sdc, arch64). I try install riru core 11, after edxposed to magisk/recovery, but no install in Xposed installer by dvd Android..

**Comment by MlgmXyysd** [comment]
Bootloop on 0.2.9.5 in Mi max 3?

**Comment by solohsu** [comment]
Did it show "not installed" or "not activated" ?

**Comment by solohsu** [comment]
Please try latest release
