### ISSUE TITLE
[SUGGESTION] Put Edxposed to Magisk Module Library (HALF DONE)

### ISSUE THREAD

**Issue by JohnGLFour** [ElderDrivers/EdXposed#251]
(Title is self-explainitory)
I want this because of ease of upgrade modules. So we won't need to download a new version from github and install from recovery.
Riru has uploaded the module too.

**Comment by JohnGLFour** [comment]
@solohsu

**Comment by JohnGLFour** [comment]
Half done because of sandhook. I only see YAHFA one.

**Comment by JohnGLFour** [comment]
Update: You can either choose any options you like, those are just suggestions. @solohsu

**Comment by JohnGLFour** [comment]
All done, closing...

**Comment by MlgmXyysd** [comment]
Yahfa and SandHook are approved.
BTW, Magisk repo may be updated not timely.
You also can use [EdXposed Manager](https://github.com/ElderDrivers/EdXposedManager/releases) to check the latest version.(use Github api)
