### ISSUE TITLE
[BUG] 开机卡在动画界面，无法进入系统

### ISSUE THREAD

**Issue by wrlssqi** [ElderDrivers/EdXposed#252]
**什么情况/What happened?**

pixel2,原生Pie，may 2019 update. 开机卡在G标loading界面。一开始安装edxposed 0.4.1.2-sandhook，重启并未发生卡死，但是似乎使用一段时间后，重启手机就会卡住。这时用mm禁掉edxposed模块，重启就能正常进入系统。然后再重新激活edxpoxed模块，重启又可以正常进入系统，然后使用一段时间后重启又会卡住。 YAHFA版本还在实验中，有问题会继续更新。

**Xposed模块列表/Xposed Module List**

App locale2
fingerprint pay
greenify
xprivacylua
微信增强

**Magisk模块列表/Magisk Module List**

app systemizer
mm
riru
riru-edxposed
riru-location report enabler
riru-storage redirect
voenabler
pixel2 volte enabler for china

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
 0.4.1.2-sandhook
Riru:
v19
**相关Logcat/Logcat**

[bootloop1.txt](https://github.com/ElderDrivers/EdXposed/files/3173607/bootloop1.txt)

**Comment by solohsu** [comment]
Boot into recovery mode and wipe dalvik-cache.
