### ISSUE TITLE
[BUG] Lots of Errors after Enable Resources Hooking

### ISSUE THREAD

**Issue by a0193143** [ElderDrivers/EdXposed#255]
**什么情况/What happened?**
Noticed LOTS of errors in log after enable resource hooking, although modules works fine

**Xposed模块列表/Xposed Module List**
I disabled every modules, still get those errors

**Magisk模块列表/Magisk Module List**
App Systemizer, Busybox for Android NDK, Disable screenshot and camera sounds, Magisk Manager for Recovery Mode (mm), Riru - Core, Riru - Ed Xposed, Systemless Hosts, ViPER4Android FX, Youtube Vanced black themed- Magisk Repo

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 90.0-v0.4.1.0_beta (YAHFA)
Riru: v19

**相关Logcat/Logcat**
[xposed_all_20190514_081234.zip](https://github.com/ElderDrivers/EdXposed/files/3178991/xposed_all_20190514_081234.zip)

**Comment by XspeedPL** [comment]
If you don't necessarily need the resource hooking, you can disable it in Xposed settings (bottom, Experimental category).

**Comment by a0193143** [comment]
> 
> 
> If you don't necessarily need the resource hooking, you can disable it in Xposed settings (bottom, Experimental category).

I need Resources Hooking for modifing navbar, but the unusual errors make me nervous.
