### ISSUE TITLE
[BUG] Latest alpha breaks SafetyNet

### ISSUE THREAD

**Issue by ghost** [ElderDrivers/EdXposed#258]
**什么情况/What happened?**

On my Pixel 3 XL, the latest alpha causes SafetyNet to fail both ctsProfile and basicIntegrity. The previous beta passes SafetyNet. This occurs even with all Xposed modules disabled and only the framework active. 

**Xposed模块列表/Xposed Module List**

* [Screenshot_20190518-093928](https://user-images.githubusercontent.com/25443872/57970585-f538dd80-7950-11e9-90e8-6cadc62effe2.png)

**Magisk模块列表/Magisk Module List**

* [Screenshot_20190518-094046](https://user-images.githubusercontent.com/25443872/57970589-0e418e80-7951-11e9-9213-3b79950d5faf.png)

* [Screenshot_20190518-094055](https://user-images.githubusercontent.com/25443872/57970591-15689c80-7951-11e9-83b6-b5d09ee7cbe0.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: magisk-EdXposed-SandHook-v0.4.2.3_alpha-release

Riru: v19

**相关Logcat/Logcat**

Did not see anything suspect in logcat, and there are no crashes, etc.

**Comment by Senliast** [comment]
Yes, I can confirm it. I updated EdXposed on my two devices and SafetyNet started failing on both, it passed before update.

**Comment by DanGLES3** [comment]
So far safety net is passing just fine on my device

**Comment by rushiranpise** [comment]
I fixes it by changing selinux to enforcing

**Comment by Senliast** [comment]
@rushiranpice, how do you Change selinux to enforcing?

**Comment by yuukieve** [comment]
SafetyNet is broken with the alpha on my device without any changes to SELinux @rushiranpise, `getenforce` reports SELinux as Enforcing both before and after installing the alpha, so I do not think this problem is related.

**Comment by HpNoTiQ56** [comment]
Problem is here since 0.4.2.0 (I've built it and triggers SafetyNet on N5X and SM Galaxy A5 2017 running Pixel experience).

**Comment by dbolivar** [comment]
Same thing here, alpha 0.4.2.0 breaks SafetyNet (both ctsProfile and basicIntegrity). LG G7, stock Oreo, March 2019 security patch. I'm not reverting to the beta, though, because the alpha is much faster for my device (SandHook). Just would like to know if there's an update on this; I've seen several commits since the release, are any of them related to this?

**Comment by HpNoTiQ56** [comment]
Build last alpha with no sucess bypassing Safetynet.

**Comment by yuukieve** [comment]
@solohsu 任何新闻？

**Comment by harbing3r1** [comment]
Did the latest alpha fix it? v4.3.7

**Comment by solohsu** [comment]
> Did the latest alpha fix it? v4.3.7

I think so, you can try it out.

**Comment by HpNoTiQ56** [comment]
> > Did the latest alpha fix it? v4.3.7
> 
> I think so, you can try it out.

Tried it on my Pixel 3a : Safetynet is ok!

**Comment by Senliast** [comment]
I also tried it on my Pixel 2, SafetyNet Passes. Thank you a lot!
