### ISSUE TITLE
riru xposed magisk module bootloop[BUG] 

### ISSUE THREAD

**Issue by h7x00r** [ElderDrivers/EdXposed#259]
**什么情况/What happened?**
i install magisk module of riru xposed and after restart my phone does not boot 
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
riru-core-v19-mod
magisk-EdXposed-SandHook-v0.4.2.3_alpha-release.zip
magisk-EdXposed-YAHFA-v0.4.2.3_alpha-release.zip
1.95

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
device :- Coolpad note 3
rom :- aim nougat

**Comment by XspeedPL** [comment]
You apparently have two EdXposed modules installed. Only one should be activated or it may cause serious issues.

**Comment by rushiranpise** [comment]
Nougat! Use official xposed instead

**Comment by Maxxtrof** [comment]
Same here, using 7.0 android but i can't use original xposed because it'll fail safetynet check.

**Comment by solohsu** [comment]
Sorry. Nougat is not supported anymore.
