### ISSUE TITLE
[BUG] Snaptools + EdXposed crashes Snapchat

### ISSUE THREAD

**Issue by perfiction** [ElderDrivers/EdXposed#26]
**什么情况/What happened?**

Snapchat is crashing when enabling SnapTools module. Problem is related to EdXposed - on previous Android versions (7.0 and 8.1) with original Xposed it was working properly, crashes started occuring after changing ROM to Resurrection Remix 7.0.0 (Android 9.0).

**Xposed模块列表/Xposed Module List**

XPrivacyLua, XInsta, SnapTools

**Magisk模块列表/Magisk Module List**

Riru - Core, Riru - Ed Xposed, Systemless Hosts, Youtube Vanced

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.5_beta

Riru: v11

**相关Logcat/Logcat**

    com.snapchat.androi  I  The ClassLoaderContext is a special shared library.
               MultiDex  I  VM with version 2.1.0 has multidex support
                         I  Installing application
                         I  VM has multidex support, MultiDex support library is disabled.
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.snapchat.android, PID: 17023
                         E  java.lang.IllegalAccessError: Illegal class access: 'EdHooker58' attempting to access 'aqkl' (declaration of 'EdHooker58' appears in /data/user_de/0/com.snapchat.android/cache/edhookers/com.snapchat.android/Generated_1379810334.jar)
                         E      at EdHooker58.hook(Unknown Source:118)
                         E      at aqkk.a(SourceFile:142)
                         E      at aptj.a(SourceFile:1111)
                         E      at apsx.<init>(SourceFile:22)
                         E      at apsx.<init>(SourceFile:17)
                         E      at abiy.<init>(SourceFile:39)
                         E      at abiy.<init>(SourceFile:16)
                         E      at abiy$a.<clinit>(SourceFile:35)
                         E      at abiy$a.a(SourceFile:34)
                         E      at amus.<init>(SourceFile:1031)
                         E      at amcn.get(SourceFile:1348)
                         E      at azcj.get(SourceFile:47)
                         E      at ziq.a(SourceFile:50187)
                         E      at com.snapchat.android.SnapchatApplication.performDependencyInjection(SourceFile:587)
                         E      at com.snapchat.android.SnapchatApplication.onCreate(SourceFile:222)
                         E      at xdu.onCreate(SourceFile:39)
                         E      at com.facebook.buck.android.support.exopackage.ExopackageApplication.onCreate(SourceFile:136)
                         E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
                         E      at com.elderdrivers.riru.xposed.c.b.a.hook(Unknown Source:229)
                         E      at android.app.ActivityThread.access$1100(ActivityThread.java:201)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loop(Looper.java:193)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6723)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
        ActivityManager  W    Force finishing activity com.snapchat.android/.LandingPageActivity

**Comment by solohsu** [comment]
Can you provide links where I can get the SnapTools? :)

**Comment by perfiction** [comment]
Here is the link to apk file and .jar packs with functionality (I was using release apk and module pack for snapchat 10.41.6.0 when the bug occured):
https://github.com/jaqxues/SnapTools_DataProvider

And here you can find source code:
https://github.com/jaqxues/SnapTools

**Comment by solohsu** [comment]
`16352-16352/? E/linker: library "/storage/emulated/0/SnapTools/ModulePacks/oat/arm/STModulePack_1.0.1.2_Premium_10.41.6.0.odex" ("/storage/emulated/0/SnapTools/ModulePacks/oat/arm/STModulePack_1.0.1.2_Premium_10.41.6.0.odex") needed or dlopened by "/system/lib/libart.so" is not accessible for the namespace: [name="(default)", ld_library_paths="", default_library_paths="/system/lib", permitted_paths="/system/lib/drm:/system/lib/extractors:/system/lib/hw:/system/product/lib:/system/framework:/system/app:/system/priv-app:/vendor/framework:/vendor/app:/vendor/priv-app:/odm/framework:/odm/app:/odm/priv-app:/oem/app:/system/product/framework:/system/product/app:/system/product/priv-app:/data:/mnt/expand"]`

It seems like on Android Pie odex file on sdcard is not accessible to ART runtime, I don't know why but I managed to solve the crash by moving `/storage/emulated/0/SnapTools` to `/data/data/com.ljmu.andre.snaptools/SnapTools`. You may want to check my commit [here](https://github.com/solohsu/SnapTools/commit/c638518a740afdc684c9bffd9b19a144e0b5d551).

**Comment by perfiction** [comment]
Thanks for this workaround, it's not crashing anymore with your changes in the app.

Should I leave issue open since the main problem (not being able to access internal/external storage odex files) is not fixed, or close it because it's not something you are able or willing to fix in EdXposed?

**Comment by cristisilaghi** [comment]
@perfiction can you share the apk, please?
