### ISSUE TITLE
[BUG] black and white list isn't working 

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposed#261]
problem with Samsung Pay (Watch Plug-in) "com.samsung.android.samsungpay.gear". If I disable the edxposed Magisk module and reboot 
It will work since I added my cards but black and white list doesn't work. 
![Screenshot_20190523-095622_Samsung Pay (Watch plug-in)](https://user-images.githubusercontent.com/30217010/58259270-3448a380-7d42-11e9-864d-b5b47b358938.jpg)

**Comment by solohsu** [comment]
Try the latest alpha version.
