### ISSUE TITLE
[BUG] 无法对island中的应用使用黑名单

### ISSUE THREAD

**Issue by Halry** [ElderDrivers/EdXposed#262]
**什么情况/What happened?**

Edxposed manager中无法对island中的应用使用黑名单

**Xposed模块列表/Xposed Module List**

微X模块

**Magisk模块列表/Magisk Module List**

riru-core
 riru-edxposed yahfa
**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.1.2（yahfa）

Riru:19

**相关Logcat/Logcat**

无需log，edxposed manager问题

**Comment by Halry** [comment]
转移到edxposed manager发布

**Comment by MlgmXyysd** [comment]
非manager问题。
