### ISSUE TITLE
Log is not being written

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposed#263]
Magisk module installation does not copy common/util_functions.sh, so logcat does not start and no logs are being written.
https://github.com/ElderDrivers/EdXposed/blob/master/edxp-core/template_override/META-INF/com/google/android/update-binary

**Comment by alexa-v2** [comment]
I experienced the same issue:
Neither module nor verbose logs are ever written

**Comment by muhviehstah** [comment]
same here

**Comment by rushiranpise** [comment]
i face the same, btw here is a temporary fix for it by 

@Mikanoshi  You can get common\util_functions.sh file from EdXposed magisk module zip and copy it to /data/adb/modules/riru_edxposed_sandhook/ (if you use SandHook), logs should work then after reboot.
--

**Comment by MlgmXyysd** [comment]
Fixed in ElderDrivers/EdXposed@6d1690f.
