### ISSUE TITLE
[BUG] hook失效后 直接退出方法

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#268]
XposedHelpers.findClass()这个接口本身用来读取class的

但是我发现一个问题，如果这个接口报了ClassNotFond错误，会直接退出整个hook接口
也就是之后的hook无法执行。

比如handleLoadPackage我写了三个hook，结果中间的那个hook的类找不到了
那么第三个hook就不会执行

我改成了原生的 Class.forName(className,false,classLoader) 然后try catch 异常 就ok了

**Comment by solohsu** [comment]
Use XposedHelpers#findClassIfExists
