### ISSUE TITLE
[Features] 自动匹配apk路径

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#269]
在很久以前，一个apk安装之后，apk会复制到/data/app/packname中
但某个版本之后，这个路径最后的包名上会附加一串随机字符串，
比如/data/app/SomeSoftWare-sfdsafsf23
 这样就导致，插件更新后 xposed会无法根据modulelist读取到相应的apk，导致插件失效

所以这个路径能不能改成匹配模式，忽略掉后面的随机字符串。
每次都要点一下 好麻烦呀 TAT

**Comment by MlgmXyysd** [comment]
所以暂时解决办法是重新勾选模块，这个我看看能不能在Manager方面解决。

**Comment by neoblackxt** [comment]
没错，这个随机字符串很烦，manager不在后台运行时，插件更新再重启，就失效了，还是勾选状态，这会让用户困惑，应该加个正则规则

**Comment by neoblackxt** [comment]
^(packageName)(?:-[0-9a-zA-Z=_-]{24})?$

**Comment by NewBugger** [comment]
说起来，云村清洁工要关掉 instant nodule list 才能生效也是这个原因吗

**Comment by solohsu** [comment]
属于Manager的需求。
