### ISSUE TITLE
Problems Some Apps with SD card

### ISSUE THREAD

**Issue by rushiranpise** [ElderDrivers/EdXposed#271]
Xposed Version: 90.0-0.4.1.2-beta sandhook/yahfa
Device OS version: 9
Device Manufacturer: Motorola
Device Name: G2
EdXposed Installer/ Manager

Reproduction Steps
Have a phone with an  SD card
Install the app like spotify/youtube

Expected Result
The app should be working

Actual Result
The app notices that there is something wrong with the mount points and refuses to work (throws exceptions due to inaccessible files)
And have to set up the app again, even when it files still exist at the sdcard

Like Spotify/YouTube log out automatically. And have to re setup again.. but their files exist in the internal/external storage. (downloaded files, account related)

Without installing edxposed it is fine
@solohsu @MlgmXyysd

**Comment by rushiranpise** [comment]
@MlgmXyysd @solohsu

**Comment by solohsu** [comment]
Any logs?
