### ISSUE TITLE
[BUG] 卡开机动画

### ISSUE THREAD

**Issue by Rothes** [ElderDrivers/EdXposed#274]
**什么情况/What happened?**

卡开机动画，不进系统

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

mm
riru-core
riru-edxposed
Systemless Hosts
Log Catcher

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:magisk-EdXposed-SandHook-v0.4.2.3_alpha-release

Riru:v19

**相关Logcat/Logcat**

[error-1970-01-02-08-49-57.log](https://github.com/ElderDrivers/EdXposed/files/3246039/error-1970-01-02-08-49-57.log)
[boot-1970-01-02-08-49-57.log](https://github.com/ElderDrivers/EdXposed/files/3246040/boot-1970-01-02-08-49-57.log)

**Comment by solohsu** [comment]
日志太短，时间搞长点，具体参考 log catcher的说明：
https://github.com/Magisk-Modules-Repo/logcat
