### ISSUE TITLE
[非 bug]有没有办法能在白名单模式下使用 system-wide 模块

### ISSUE THREAD

**Issue by NewBugger** [ElderDrivers/EdXposed#275]
为了流畅度，以及基于我的主要需求在于单个应用，我选择白名单模式并工作顺利。

但是我很想用 xprivacylua greenify 这样 system-wide 的模块。

虽说我觉得可能没法在白名单下使用，我的猜测是白名单模式下，各个应用的框架环境是 isolated 的，这样就无法实现 system-wide。只是我的猜测，所以抱着侥幸心理来问下。

**Comment by NewBugger** [comment]
已找出方案，告辞。

**Comment by tofuliang** [comment]
> 已找出方案，告辞。

能分享一下？
