### ISSUE TITLE
[BUG] XModuleResources.createInstance causes Resources$NotFoundException

### ISSUE THREAD

**Issue by MSkjel** [ElderDrivers/EdXposed#276]
**什么情况/What happened?**
MinMinGuard crashes and app icon changes to the default app icon when drawable/abc_vector_test isnt found. This only happens when XModuleResources.createInstance() is called with startupParam.modulePath,null inside initZygote. It only seems to happen on certain devices, especially on chinese phones like xiaomi.
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
Happens on all EdXposed versions > 0.2.9.8. Older versions doesnt seem to have this problem, though this is only reported to me. I dont have a phone to test it with

**相关Logcat/Logcat**
https://dl.xda-developers.com/4/7/6/6/7/4/8/alogcat.2019-05-27-16-50-04-0300.txt?key=IFvkcfnplg1oQOw-MAx2QQ&ts=1559590649

**Comment by solohsu** [comment]
The link is broken. Please just upload it here in the comment.
