### ISSUE TITLE
Are there any differences bewteen the Sandhook or YAHFA versions?

### ISSUE THREAD

**Issue by BeeeWall** [ElderDrivers/EdXposed#282]
Is one of the two faster, more stable, has more features, etc, or is there no visible difference from a user perspective? I'm not really sure which to choose.

**Comment by DanGLES3** [comment]
Sandhook should be faster while YAHFA is usually more stable since it's been developed for much longer than sandhook

**Comment by BeeeWall** [comment]
Ah ok, thanks.
