### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Annunak2012** [ElderDrivers/EdXposed#283]
**splash when launching applications/What happened?**

如无法开机/模块无效等

**Xposed 4.4.8/Xposed Module List**

允许截图/Screenshot allowed

**Magisk19.3/Magisk Module List**

允许截图/Screenshot allowed

![Screenshot_2019-06-07-06-55-53-345_org meowcat edxposed manager](https://user-images.githubusercontent.com/51468484/59078757-86b4c300-88f1-11e9-95b1-b8d28d77fada.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:4.4.8

Riru:19.1

**相关Logcat/Logcat**
[2019-06-06-22-41-15.txt](https://github.com/ElderDrivers/EdXposed/files/3264220/2019-06-06-22-41-15.txt)

/It can help us to locate issue, must use our logcat module
Hello. I installed the last edXposed after that when launching any system application for two seconds, a white screen slips. After deleting it, everything is fine. The log attached

**Comment by solohsu** [comment]
Please provide EdXposed logs in companion Apps.

**Comment by Annunak2012** [comment]
> Пожалуйста, предоставьте журналы EdXposed в сопутствующих приложениях.

Do you need a log in those applications where the white screen?

**Comment by Annunak2012** [comment]
Or in which applications

**Comment by Mikanoshi** [comment]
Logs from EdXposed Manager/Installer

**Comment by Annunak2012** [comment]
ок

**Comment by Mikanoshi** [comment]
EdXposed Framework should be 0.4.3.7+ for logs to work.

**Comment by Annunak2012** [comment]
0450

**Comment by Mikanoshi** [comment]
Framework, not the Manager.

**Comment by Mikanoshi** [comment]
Unless you downloaded from here
https://ci.appveyor.com/project/ElderDrivers/edxposed/build/artifacts
