### ISSUE TITLE
[BUG] EdXposed-Bridge (provider: Crypto) cannot be found

### ISSUE THREAD

**Issue by realali** [ElderDrivers/EdXposed#286]
EdXposed-Bridge: java.security.NoSuchAlgorithmException: class configured for SecureRandom (provider: Crypto) cannot be found.

**Comment by realali** [comment]
private static class CryptoProvider extends Provider {
        public CryptoProvider() {
            super("Crypto", 1.0, "HARMONY (SHA1 digest; SecureRandom; SHA1withDSA signature)");
            put("SecureRandom.SHA1PRNG", "org.apache.harmony.security.provider.crypto.SHA1PRNG_SecureRandomImpl");
            put("SecureRandom.SHA1PRNG ImplementedIn", "Software");
        }
    }

SecureRandom sr = SecureRandom.getInstance("SHA1PRNG", new CryptoProvider());
 sr.setSeed(seed);

**Comment by solohsu** [comment]
Not EdXposed related
