### ISSUE TITLE
[BUG] EdXposed doesn't start at all, and prevents riru core from starting

### ISSUE THREAD

**Issue by yennor** [ElderDrivers/EdXposed#287]
**什么情况/What happened?**
I've tried the versions v0.4.1.2_beta, v0.4.2.3_alpha and v0.4.3.7_alpha, sandhook and yahfa h ooks. The same problem. EdXposed doesn't start properly up at boot. When rebooting several times, the behaviour randomly changes:
- Edxposed Installer (and when trying out edxposed manager) tell that EdXposed is installed but not started up. 
- EdXposed Installer tells that EdXposed is not installed at all.

In both cases, when checking with the riru app. it Tells me, that Riru wasn't started up.
When deinstalling EdXposed, Riru is started up properly.

The device used is a Xiaomi Mi A2 Lite

**Xposed模块列表/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**
F-Drod Privileged extension
Riru - Core
Systemless hosts
TTL Tethering Fix
Youtube Vanced

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
v0.4.1.2_beta, v0.4.2.3_alpha and v0.4.3.7_alpha, sandhook and yahfa

Riru:
19 and 19.1

**相关Logcat/Logcat**

at the moment github tells me that it can't process the uploaded file? I'll try again to attach it later, when I get a better internet connection.

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by yennor** [comment]
For whatever reason I've could only upload the files by using a VPN??? anyway. here they are.
Logcat when edxposed manager says that edxposed is not installed:
[logcat_edxposed_not_installed.txt](https://github.com/ElderDrivers/EdXposed/files/3282107/logcat_edxposed_not_installed.txt)
Logcat when edxposed manager says that edxposed is installed but not active:
[logcat_edxposed_installed.txt](https://github.com/ElderDrivers/EdXposed/files/3282109/logcat_edxposed_installed.txt)

**Comment by XspeedPL** [comment]
Try replacing your post-fs-data script with this one: https://pastebin.com/iibhTUaJ
It may or may not solve the problem.

**Comment by yennor** [comment]
I've replaced the script with yours and now it is working!

**Comment by XspeedPL** [comment]
That confirms I'm not the only one with supolicy issues
Good to know

**Comment by damadikaz** [comment]
> Try replacing your post-fs-data script with this one: https://pastebin.com/iibhTUaJ
> It may or may not solve the problem.

The only difference from original post-fs-data is that "setenforce 0" right (no need #? i.e. #setenforce 0)?
I got bootloops from that pastebin file.

**Comment by XspeedPL** [comment]
@damadikaz it has all supolicy calls removed and sets selinux to permissive mode.
If you bootloop with it there may be two reasons:
1. Your kernel denies selinux permissive mode
2. You have an issue unrelated to policies and should seek help in another thread

**Comment by damadikaz** [comment]
I got bootloop on the stock kernel. I just updated with modified kernel and
now it boot up with SELinux being permissive but the problem still there.

It means my problem isn't SELinux related?

**Comment by avalx** [comment]
I have a similar problem with Oneplus 3, OOs 9.0.3, Magisk 19.3, FrancoKernel 48. The stange thing is that the first time I installed EdXposed (and rebooted twice!) it was working, for exampke I could use Gravitybox without problems.

Now after every reboot I get "Riru not found in memory." message and "EdExposed Framework is not installed." status in EdExposed Manager.

I will try the changes proposed for the script and report back later.

**Comment by yennor** [comment]
With previous versions of magisk, edxposed, etc. I had a similar problem, see: #207 .
With the new versions I didn't have that problem anymore. With the new versions, it is as above explained. It didn't work at all, never, until I've changed the script.

**Comment by avalx** [comment]
Just to update: the latest beta v0.4.5.1_beta(4463) works fine, both versions YAHFA and SandHook).

**Comment by yennor** [comment]
I've tried it out with the latest version edxposed gets loaded with the normal post-fs-data.sh BUT the mobile internet connection doesn't work :-(. When I exchange post-fs-data.sh with the one from Xspeedpl, then also the mobile internet connection works.
