### ISSUE TITLE
[BUG] MIUI10安卓8.0使用0.4.3.7无法开机

### ISSUE THREAD

**Issue by mymine** [ElderDrivers/EdXposed#288]
**什么情况/What happened?**

MIUI10安卓8.0使用0.4.3.7两个版本无法开机

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.3.7两个版本都无法开机

Riru:19.1

**相关Logcat/Logcat**

无法开机不知道怎么抓取log

**Comment by kkwpsv** [comment]
小米5 MIUI10同样情况

**Comment by liwenjie119** [comment]
同米5不能开机

**Comment by solohsu** [comment]
试试最新版。

**Comment by mymine** [comment]
> 试试最新版。

OK没问题了。完美使用。感谢修复。
