### ISSUE TITLE
[BUG] MIUI10 安卓9，所有应用调用webview时都闪退，比如哔哩哔哩的开屏广告，使用内置浏览器的应用没有内核也会闪退

### ISSUE THREAD

**Issue by Rlmigly** [ElderDrivers/EdXposed#289]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
#291
