### ISSUE TITLE
[BUG] 开启xapm卡第二屏

### ISSUE THREAD

**Issue by weigeloveu** [ElderDrivers/EdXposed#29]
**什么情况/What happened?**
xapm卡第二屏

**Xposed模块列表/Xposed Module List**

微x
qx
音量增强
xapm

**Magisk模块列表/Magisk Module List**

riru core 11
edxposed 0.2.9.5

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.2.9.5

Riru:11

**相关Logcat/Logcat**

[xapm.zip](https://github.com/solohsu/EdXposed/files/2798746/xapm.zip)

**Comment by solohsu** [comment]
Fixed in [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)
