### ISSUE TITLE
[BUG] 0437版本无法激活！

### ISSUE THREAD

**Issue by VKinTang** [ElderDrivers/EdXposed#290]
**什么情况/What happened?**
刷了最新0.4.3.7版的edxp，显示无法激活。重启了多次都如此。刷回0423版则正常了。用的三星one ui 9.0安卓变种
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0437

Riru:19.1

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
Try the latest build.
