### ISSUE TITLE
problems with webview after EdXposed-Installation (LineageOS 16)?

### ISSUE THREAD

**Issue by tusch001** [ElderDrivers/EdXposed#291]
right up front: I have no idea how the framework works so I just tell you what happens. I don't know if this is a problem with webview or the EdXposed module:

Tablet: Samsung SM-P605 with LineageOS 16.0 from davidmueller13
Rooted with Magisk 19.1
Installed riru core module
So far everything works.
-> Installation of EdXposed Module (either SandHook or YAHFA, both versions 0.4.2.3 alpha and versions 0.4.3.7 alpha):
after installation all apps that use the integrated lineageOS-webview don't work, even after wiping cache / davlik, after installing Google more or less latest Android Webview some apps could be used (octodroid, fdroid, yalpstore), others still show a blank page (FOSS browser / Via browser). 
When I deinstall the EdXposed Module and reboot everything is fine again.

Thought I let you know, not sure where the problem is.
Thx

**Comment by Dusan80** [comment]
Just get chrome dev from play store and in developer options webview implementation select Google dev. Let us know did that work...

**Comment by solohsu** [comment]
Does the latest build fix this?

**Comment by Dusan80** [comment]
Just do what I said. I had the same problem, for 3 days searching for solution. In fact my problem could not fix removing (Ed) xposed, it stayed after removing it. But chrome dev in webview implementation helped

**Comment by Dusan80** [comment]
The latest build didn't fix it

**Comment by tusch001** [comment]
@Dusan80
Thx for help

report (not good):

clean install lineageOS 16 (there is only an unofficial build available that worked very well so far, the build is from June 4th, 2019)
-> contains webview 72.0.3636.121
-> using fdroid to update: no update available

magisk 19.3
chrome dev apk version 76.0.3809.21, variant for arm architecture
(although it contains android webview implementation version 72.0.3626.121 according to lineageOs settings)
riru core module
-> internal browser / foss browser / via browser working
EdXposed 0.4.4.4_alpha (the latest):
android webview neither works with SandHook nor YAHFA variant :-(
deinstalled chrome dev, 
installation of the latest android webview I could find (version 75.0.3770.67)
reboot: wiped cache / davlik
no browser can display any webpage

With the 0.4.4.4_alpha SandHook module I tried to record error messeges while starting the internal browser (it is set to google startpage and tries immediately to load that page):
A lot of red lines show up. I append the file. Maybe someone knows what they mean.


I just want to mention that this tablet is an older model with 32 bit arm. Don't know if this is important. 

So thanks again for helping


Patricia

**Comment by Dusan80** [comment]
Do not install latest edxposed just the version from a few weeks ago. But
why don't you do a full wipe and install all from beginning but for first
few hours (days) without edxposed? And then with riru edxposed 0.4.1.2.
(but only YAHFA version, sandhook didn't work for me)?

**Comment by Dusan80** [comment]
I am not a developer, I had similar problem. I think that you can try with
taichi xposed or original xposed framework. And I think that this problem
will not solve new version because there is no way to find what is causing
the problem. It is the problem with webview and that Is that. It can be on
same devices but with different apps. A lot of them had the problem with
messenger but I didn't. I think that your sister is a little bit
overprotective parent. I have 2 kids (7 and 9 years old) and there is no
way to control all of what they are doing. But am also very scared of the
time when they start using technology full time. Maybe you could try dirty
flash with the rom that is similar with the one you are using?

**Comment by tusch001** [comment]
@Dusan80
TaiChi magisk module (without any further xposed module) fixed my fifa app problem (Most important :-). But the xposed module XInternalSD didn't work for other apps. Even made things worse. Don't ask why. I don't need those apps. Thanks for the tipp. 

I abandon EdXposed module at the moment and come back when webview works. Wherever the error is.

**Comment by tusch001** [comment]
I assume the problm is with webview. Therefore I'm closing it. If the developers think otherwise and need someon for testing just reopen it.
