### ISSUE TITLE
Crash when updating module

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposed#297]
EdXposed 0.4.4.4
Riru 19.1
EdXposed Installer 2.2.4

I use Android Studio to install new module version via adb, when active module is updated like that zygote starts to crash, cannot launch any app until (soft) reboot.
```
A/zygote64: jni_internal.cc:616] JNI FatalError called: (com.solohsu.android.edxp.manager) Failed open(/data/app/name.mikanoshi.customiuizer-yXfPiNH_zsURTLS8tw4Zrg==/base.apk, 0): No such file or directory
```
Also this line started to appear during EdXposed initialization:
```
E/EdXposed: CallStaticVoidMethod class_linker_class_ post_fixup_static_mid_, clazz.get()
```

Full logcat:
[log_0.4.4.4.txt](https://github.com/ElderDrivers/EdXposed/files/3292830/log_0.4.4.4.txt)

**Comment by solohsu** [comment]
Was instant-run turned on?

**Comment by Mikanoshi** [comment]
No, none of EdXp settings were checked.

**Comment by solohsu** [comment]
I mean instant-run in Android Studio.
Have you checked whether `/data/app/name.mikanoshi.customiuizer-yXfPiNH_zsURTLS8tw4Zrg==/base.apk` exists or not and have you tried installing the release version of your module apk?

**Comment by Mikanoshi** [comment]
That is also disabled. And I usually install release version because Xposed mods need debugging, not the module settings.

**Comment by Mikanoshi** [comment]
APK file it tries to load doesn't exist, it was already replaced by the new version in a new folder.
0.4.5.0 version has this problem too.

**Comment by solohsu** [comment]
> APK file it tries to load doesn't exist, it was already replaced by the new version in a new folder.
> 0.4.5.0 version has this problem too.

This is a known legacy issue. You have to keep the installer app alive to receive package-update broadcast to update the module list config file.

**Comment by Mikanoshi** [comment]
It was working in every single version before 0.4.4.4. What do you mean by "alive"? :)

**Comment by solohsu** [comment]
You can revert to before v0.4.4.4 and build it from source to find which commit breaks your module since I can't reproduce your problem myself.

**Comment by Mikanoshi** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dalvikdx:dexInJar'.
> A problem occurred starting process 'command 'dx.bat''

* Exception is:
...
Caused by: java.io.IOException: Cannot run program "dx.bat" (in directory "D:\Progs\Mobile\Xiaomi Mi Mix 2S\Projects\EdXposed\dalvikdx\build\libs"): CreateProcess error=2, The system cannot find the file specified
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	... 9 more
```

**Comment by Mikanoshi** [comment]
Happens on 0.4.5.1 beta too, I can't compile due to error above.

**Comment by AeonLucid** [comment]
@Mikanoshi If you read the [build instructions](https://github.com/ElderDrivers/EdXposed#build-requirements), you would [find out](https://github.com/RikkaApps/Riru/blob/master/README.md#build-requirements) that you need to add NDK to your PATH variable.
- C:\Users\USERNAME\AppData\Local\Android\Sdk\ndk-bundle
- C:\Users\USERNAME\AppData\Local\Android\Sdk\build-tools\28.0.3 (Contains dx.bat)

**Comment by Mikanoshi** [comment]
I added ndk-bundle, nowhere it says to add build-tools too.

**Comment by Mikanoshi** [comment]
Found it. It's this one:
https://github.com/ElderDrivers/EdXposed/commit/7eaae6d898f8fc43c0ab3cbd9c37d36a6e2a6616

**Comment by Mikanoshi** [comment]
Latest versions don't have this bug it seems
