### ISSUE TITLE
Android q beta4 essential phone bootloop

### ISSUE THREAD

**Issue by meecoffee** [ElderDrivers/EdXposed#298]
magisk 都是最新版本
然后edxposed sandbox跟另一个方式都是bootloop

**Comment by Yun1ng** [comment]
我用4.12没事 4.4 4.5 都开不了机 米8

**Comment by solohsu** [comment]
Try installing the latest Magisk canary build:
https://github.com/topjohnwu/magisk_files/tree/master/canary_builds

**Comment by hlwhl** [comment]
Have met same situation . Pixel 2 XL android Q beta5. According to logcat, something is keep crashing.
