### ISSUE TITLE
[BUG] Android Q DP4 Mi 8 Bootloop

### ISSUE THREAD

**Issue by hytzongxuan** [ElderDrivers/EdXposed#300]
**什么情况/What happened?**

Bootloop

**Xposed模块列表/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**

Riru-Core 19.1
Riru-LocationReportEnabler 9.1

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:magisk-EdXposed-YAHFA-v0.4.4.4_alpha-release

Riru:19.1

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
#298
