### ISSUE TITLE
[BUG]sandhook v0.4.4.4_alpha京东无法打开

### ISSUE THREAD

**Issue by Livxx** [ElderDrivers/EdXposed#303]
**什么情况/What happened?**
使用sandhook版导致京东卡在第一屏，加黑名单可以解决且YAHFA版本无此问题。机型为MI9

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:4.5.0

Riru:v19.1

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
未提供crash日志。
