### ISSUE TITLE
[BUG] Xposed causes black screen and battery drain after boot

### ISSUE THREAD

**Issue by hjr06** [ElderDrivers/EdXposed#307]
I have problem on my Wileyfox Storm (arm64-v8a) with Pie (OS only - no other apps installed jet).
I have testet every up to now available lineage version in combination of Magsik, Magisk Manager, Riru core, EDXposed and EdXposedInstaller.
Always same Problem: immediatly after the boot is finished and sim unlock screen has been shown for a second the ui becomes black. About every 5 seconds the screen shows very shortly the status bar. After that the screen becomes black again - seems to be a loop in starting the apps (may be loop with try starting Xposed. The device becomes hot and battery drains strongly.
In all cases - after removing EDXposed via TWRP Pie works fine.
Please help - Thanks

**Comment by runo280** [comment]
I have the same problem on Honor 5x LOS16.

**Comment by XRevan86** [comment]
It is notable that both Wileyfox Storm and Huawei Honor 5X have very similiar SoCs: Qualcomm MSM8939[v1] and MSM8939v2 respectively.

**Comment by XRevan86** [comment]
It is notable that both Wileyfox Storm and Huawei Honor 5X have very similiar SoCs: Qualcomm MSM8939[v1] and MSM8939v2 respectively.

The same thing happens with the EdXposed's [own custom Magisk](http://edxp.meowcat.org/repo/version.json) "for Huawei devices".

**Comment by hjr06** [comment]
On my Wileyfox Storm now I have installed the components under Lineage 15.1 (Magisk 19.3, Riru Core 19.1, EDXposed 4.5.1 sandhook and EDXposed Installer 2.2.4). Everything works fine (especialy XPrivacyLUA).
With Lineage OS 16.0 - every version - I have still the same Problem

**Comment by NicolasChamllet** [comment]
same here. on redmi k20 pro. When booting system, it causes black screen AFTER enter system password. Disable riru edxposed module fixes this problem

**Comment by XRevan86** [comment]
> downgrade to ver 0.4.1.2 (riru api 3)

I do not confirm that on Honor 5X. And on it the black screen occures instantly and appears to be SystemUI crashing.
@NicolasChamllet, your issue seems to be unrelated.

**Comment by XRevan86** [comment]
Tried with latest updates, including Riru, and the issue is gone.
@hjr06, @runo280, it's most likely fixed for you, too.

**Comment by runo280** [comment]
> 
> 
> Tried with latest updates, including Riru, and the issue is gone.
> @hjr06, @runo280, it's most likely fixed for you, too.

Yeah fixed, thanks for good news 😀

**Comment by hjr06** [comment]
Sorry, for me has nothing changed.
Today I downloaded latrst versions of Lineage 16, Magisk, Riru, Edxposed, and Edxposed installer,
installed Lineage and Magisk, boot, installed Riru and Edxposed via TWRP. After boot finished - black screen - ui crash - same as after all my other tries.
For me it`s not fixed

**Comment by XRevan86** [comment]
To be more verbose, the versions are: ```LineageOS 16.0-20190910-nightly```, ```Magisk 19.3```, ```Riru 19.5```, ```EdXposed 0.4.5.1```, ```EdXposed Manager 4.5.0```.
@hjr06, it is possible that it got fixed only for Huawei Honor 5X, but considering how close the devices are I would've guessed not.
Or maybe the fix is in LineageOS after all, and only in the ```kiwi``` device tree…

**Comment by hjr06** [comment]
These are exactly the versions I used
Result: Black screen

**Comment by qinidema** [comment]
Same here on Android x86 32bit 14.1 r4 (based on Lineage OS with Android 7.1.2), Magisk manager v7.5.1 and Magisk ZIP 20.4 (20400), Riru v21.2, EdXposed v0.4.6.1 (4510) (YAHFA). That should be a lot easier to debug as you can reproduce it on any VM on Linux/Windows/Mac/etc. I could attach logcat output just after booting if that would help. The "black screen" appears just after boot.

**Comment by kotori2** [comment]
closed as stale
