### ISSUE TITLE
即时模块列表建议2

### ISSUE THREAD

**Issue by 253551464** [ElderDrivers/EdXposed#308]
![Screenshot_2019-06-25-23-50-59-183_com solohsu android edxp manager](https://user-images.githubusercontent.com/36783515/60113680-e4c42000-97a4-11e9-8455-95e6dcd76e91.jpg)
我试了新的即时模块列表，发现还有一些瑕疵，从图中可以看到，发生改变的模块，每有一个APP启动就要加载一次，我觉得完美的即时是：模块改变后第1个启动的APP重新加载这个模块，之后启动的APP不用再重新加载（感觉容错率有点低，我只是把自己的想法说出来，不喜勿喷）

如果作者大佬有空的话就改一下吧。

**Comment by 253551464** [comment]
忘了说，没有使用黑/白名单模式

**Comment by solohsu** [comment]
Fixed with 1df3d88c13b67dae40b75d4b28f19ffd5d002ed5.
