### ISSUE TITLE
File does not exist (modules won't load)

### ISSUE THREAD

**Issue by akano12** [ElderDrivers/EdXposed#309]
i don't know why ,but edxposed stopped loading modules,here's the modules log:
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 9
Android sdk: 28
Android build: PPR1.180610.011
Fingerprint: samsung/j6primeltedd/j6primelte:9/PPR1.180610.011/J610FXXU2BSE3:user/release-keys
ROM build description: j6primeltedd-user 9 PPR1.180610.011 J610FXXU2BSE3 release-keys
EdXposed Version: v0.4.5.1_beta(4463) (Yahfa)
Architecture: armeabi-v7a
Device: j6primelte
Manufacture: samsung
Brand: samsung
Product: j6primelte
--------- beginning of main
--------- beginning of system
--------- beginning of crash
06-25 19:26:17.450  1302  1302 I EdXposed-Bridge: Loading modules from /data/app/eu.faircode.xlua-G5ihWc-z4t9zUMnAZyz7Xg==/base.apk
06-25 19:26:17.450  1302  1302 E EdXposed-Bridge:   File does not exist
06-25 19:26:17.450  1302  1302 I EdXposed-Bridge: Loading modules from /system/priv-app/Greenify/Greenify.apk
06-25 19:26:17.774  1302  1302 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
06-25 19:26:17.788  1302  1302 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
06-25 19:26:17.789  1302  1302 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-JOvOO9OtntINgHEenWzNYw==/base.apk
06-25 19:26:17.789  1302  1302 E EdXposed-Bridge:   File does not exist
06-25 19:26:17.790  1302  1302 I EdXposed-Bridge: Loading modules from /data/app/dev.ukanth.ufirewall-ifpE_D8iUpC_Pil4xuNr3g==/base.apk
06-25 19:26:17.790  1302  1302 E EdXposed-Bridge:   File does not exist

the only module working is greenify (it's a priviliged app bcz i have greenify4magisk module installed)
so obviously the only working module is a priviliged app.

tried disbaling/enabling edxposed from magisk,tried disbaling/enabling modules and rebooting from edxposed manager,tried flashing sandhook/yahfa (beta/alpha) and still no success
any ideas????????????????

**Comment by pcktm** [comment]
I have the same issue. Modules won't load on boot (and they did before, it happened without any reason), however when I disable and enable any of them in EdXposed Manager most of them load dynamically just fine, except GravityBox which says that it's system framework is not responding.

[all.log](https://github.com/ElderDrivers/EdXposed/files/3438966/all.log)
