### ISSUE TITLE
能不能修复一下状态栏问题[BUG] 

### ISSUE THREAD

**Issue by dragon518877** [ElderDrivers/EdXposed#311]
![Screenshot_2019-06-26-13-13-45-875_tv danmaku bili](https://user-images.githubusercontent.com/52231206/60153891-4671a200-9818-11e9-8ec9-b8bccab3e929.jpg)
0317后的版本，系统修改过state_bar_height，就会出现这条白色的一杠！望看看能不能修改一下，谢谢！

**Comment by solohsu** [comment]
请给出详细的复现步骤。
