### ISSUE TITLE
[BUG] MinMinGuard & XPrivacyLua Xposed modules not working since v0.4.5.1_beta

### ISSUE THREAD

**Issue by Enkidu70** [ElderDrivers/EdXposed#316]
**What happened?**

MinMinGuard & XPrivacyLua Xposed modules stopped working with v0.4.5.1_beta.
Both say "Module not activated".

![Screenshot_20190625-225110_XPrivacyLua](https://user-images.githubusercontent.com/1456895/60455071-c3948100-9c35-11e9-9f30-628b80668362.png)

Until v0.4.1.2_beta all was working fine.
(I did not try alphas!)

For me those are essential modules. Please help.

**Xposed Module List**
tw.fatminmin.xposed.minminguard
eu.faircode.xlua

**Magisk Module List**
![Screenshot_20190701-193305_Magisk_Manager~01](https://user-images.githubusercontent.com/1456895/60456498-b1b4dd00-9c39-11e9-9fd3-0cde6a60505f.png)
![Screenshot_20190701-193319_Magisk_Manager~01](https://user-images.githubusercontent.com/1456895/60456504-b5e0fa80-9c39-11e9-8f32-2b0a2bc15377.png)
![Screenshot_20190701-193329_Magisk_Manager~01](https://user-images.githubusercontent.com/1456895/60456513-bbd6db80-9c39-11e9-88eb-4af1e294bb21.png)

**Versions of EdXposed and Riru**

EdXposed:
not working: v0.4.5.1_beta
working: v0.4.1.2_beta

Riru:
v19

**相关Logcat/Logcat**
-/-

**Device**

Oneplus 3T
Resurrection 7.0.2 (Android 9/Pie)

**Comment by Y-T-G** [comment]
Even Greenify says Xposed not installed although I have activated the module and rebooted several times.

**Comment by NewBugger** [comment]
no, it shouldn't be there, at least Xlua works fine. both 0.4.3.7_alpha or 0.4.4.4_alpha even 0.4.5.1_alpha/beta releases.

**Comment by Enkidu70** [comment]
> no, it shouldn't be there, at least Xlua works fine. both 0.4.3.7_alpha or 0.4.4.4_alpha even 0.4.5.1_alpha/beta releases.

On my device, using 4.5.1 beta, many modules say they are not activated. XPrivacy Lua, Greenify, MinMinGuard, ...

**Comment by NewBugger** [comment]
try disable Instant Module

**Comment by Y-T-G** [comment]
Ok, so I enabled Blacklist mode and all the modules are detecting Xposed fine now.

**Comment by Enkidu70** [comment]
I never used instant mode.
But enabling blacklist mode also here was the solution!

**Comment by Enkidu70** [comment]
Well... I am not quite sure it it really works as it should...
Today I noticed, modules say they are not activated... So I saw there is a new version around and updated it. But it was still not working.
So I uninstalled it, reboot, installed YAFHA version instead of Sandhook, reboot.
So now it is working again...

**Comment by Dark-Yox** [comment]
I have the same problem 
EdXposed version : 90-v4.6.0_beta(4471) (YAHFA) (Sandhook version bootloop my device)
Android version : 10
Kernel version : 4.9.196-Illusion-v4.2-PixelExp+ 
Modules that can't detect the Xposed Framework : MinMinGuard, Lucky Patcher and Unclutter IG
The only module working is GravityBox [Q]
The weird thing is that everything was working fine at first but it stopped working alone for some reason without installing anything new and without touching anything.
I already tried the blacklist thing but still not working.

**Comment by sakamai** [comment]
> Well... I am not quite sure it it really works as it should...
> Today I noticed, modules say they are not activated... So I saw there is a new version around and updated it. But it was still not working.
> So I uninstalled it, reboot, installed YAFHA version instead of Sandhook, reboot.
> So now it is working again...

Can you assist me pls? I have same isseu

**Comment by Dark-Yox** [comment]
Uninstall FDE.AI if you are using it, and reinstall all your modules + try the canary version of EdXposed https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/30454607/artifacts

**Comment by sakamai** [comment]
> Uninstall FDE.AI if you are using it, and reinstall all your modules + try the canary version of EdXposed https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/30454607/artifacts

Solved, thx bud
