### ISSUE TITLE
[BUG] EdXposed 0.4.5.1 Both 2 version YAHFA (or SandHook) boot loop on Oneplus 6T Pie

### ISSUE THREAD

**Issue by tuyennn** [ElderDrivers/EdXposed#318]
**什么情况/What happened?**

EdXposed 0.4.5.1 Both 2 version YAHFA (or SandHook) boot loop on Oneplus 6T Pie. I could successfully boot on, but after enter the PIN, I got boot loop. Then need to use Magisk Manager TWRP to disable EdXposed  module then I could boot again.

**Xposed模块列表/Xposed Module List**

CorePatch
Minminguard
GravityBox

**Magisk模块列表/Magisk Module List**

YoutubeVanced

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.5.1

Riru: v19

**相关Logcat/Logcat**

None.

**Comment by tuyennn** [comment]
Update: Now reverted and using 0.4.1.2

**Comment by tmjvonboss** [comment]
I have a boot loop on my OnePlus 3 with all versions up to 0.4.5.5_beta

I noticed that if I boot into recovery and then reboot to system through TWRP somehow it boots perfectly

very weird
