### ISSUE TITLE
Bootloop on Honor View 10 with Canary 19305

### ISSUE THREAD

**Issue by Mohsyn** [ElderDrivers/EdXposed#321]
Causes a bootloop with no root access on Honor View 10 with EMUI 9
EDX core installs fine
Yahfa and sandhook cause bootloop
cannot access logcat as phone keeps rebooting

**Comment by Mohsyn** [comment]
Just a query... Are there any reports of anyone else with honor view 10 and emui 9 reported a successful installation of Riru?

**Comment by Mohsyn** [comment]
Please help

**Comment by SpectreMz** [comment]
@Mohsyn you are stucked on "Your device booting now"?

**Comment by eebssk1** [comment]
try get logs using magisk

**Comment by Kev1nKe** [comment]
I Have The Same Problem And I Have Catch The Log SomeOne Who Can Help Me Solve it Thanks ~

[ 08-09 15:16:11.416   578:  578 W/EdXposed ]
_ZNK23FileDescriptorWhitelist9IsAllowedERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE not found

**Comment by SpectreMz** [comment]
I've fixed this problem, you need to install the custom magisk files provided by riru and install last canary version

**Comment by Mohsyn** [comment]
I had to disable magisk modules from loading. While booting it gives root access for just a few seconds before restating.
use adb to either create a .disable_magisk in /data/cache
Or
Use
rm -rf /data/adb/modules

And boot to a clean start

Haven't figured out to make Riru modules work yet
