### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Hyqs007** [ElderDrivers/EdXposed#322]
**什么情况/What happened?**
我的手机在开数据流量的情况下重启手机，会掉4g，用不了volte和4g网络，2g网络也用不了，
我想要再次关闭数据开关，然后重启才能解决
而magisk里关闭edxposed模块就不会出现这个问题
不论是ya版本还是sanhook版本都一样，
我不知道是我的手机问题还是edxposed模块问题，
希望能有解决方案
机型：红米Note4x（高通骁龙625）
rom：rr Pie
**Xposed模块列表/Xposed Module List**
  
![Screenshot_20190709-160221_EdXposed_Manager](https://user-images.githubusercontent.com/52695109/60870239-08866c00-a263-11e9-8710-fc7354a79f4e.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_20190709-160332_Manager](https://user-images.githubusercontent.com/52695109/60870282-1d62ff80-a263-11e9-81f7-f9e8ea9cabd5.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.5.1

Riru:19.1

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat modul

**Comment by MlgmXyysd** [comment]
empty title.
