### ISSUE TITLE
Edxposed missing

### ISSUE THREAD

**Issue by ivankazzzz** [ElderDrivers/EdXposed#323]
Hello sir , today  flash edxposed through magisk and reboot , and edxposed installer said "Edxposed installed with green check"

and then

 iam downloading the module edxposed and enable it , reboot

edxposed installer said my edxposed is not installed with red color 

how to fix it sir ?

thx u before

![photo_2019-07-10_11-37-36](https://user-images.githubusercontent.com/52730890/60940846-27d6d500-a307-11e9-808a-44157afe370c.jpg)
![photo_2019-07-10_11-37-32](https://user-images.githubusercontent.com/52730890/60940847-27d6d500-a307-11e9-8ca5-2b0303443f06.jpg)
![photo_2019-07-10_11-37-38](https://user-images.githubusercontent.com/52730890/60940848-286f6b80-a307-11e9-814e-5914c04ae636.jpg)
![photo_2019-07-10_11-37-37](https://user-images.githubusercontent.com/52730890/60940849-286f6b80-a307-11e9-9cbf-245861ad6d99.jpg)

**Comment by tmjvonboss** [comment]
Try using Riru 19.1 and Edxposed 0.4.5.5_beta

That is what I'm running on Magisk 19.3, if that doesn't work let me know

Could you pose a screenshot of your edxposed manager
