### ISSUE TITLE
[Question] 可有针对 EdXposed 的重启调试方案

### ISSUE THREAD

**Issue by zhangwilling** [ElderDrivers/EdXposed#324]
i feel so sorry, there is not an issue template for question. As we know that github issue not works for question, but i still did it .
不好意思，这里似乎没有提问模板,尽管我也知道issue并不是用来咨询的，但苦于无处询问还是提了这个issue。

i want know if there is a way to debug my xp module without restart my phone. in original xposed, i know some tricks to do some experiment without restart.
我想咨询一下，在edxposed方案下，如何做到免重启调试我的xp模块。在原始xp下，我知道几种方式可以做到免重启调试，但似乎在edxposed下不起作用。

anyway thanks for your reading.

**Comment by zhangwilling** [comment]
还是关掉吧。我在另一个issue里进行提问了。

**Comment by MlgmXyysd** [comment]
edxp提供了即时模块列表(暂时还有selinux的bug，据说用edxposed installer没有bug)

**Comment by zhangwilling** [comment]
好的，谢谢。我试试
