### ISSUE TITLE
[BUG] EdXposed Framework can't be loaded (orange)

### ISSUE THREAD

**Issue by Tortue95** [ElderDrivers/EdXposed#325]
Hi,
**What happened?**
I'm trying to install EdXposed on fresh resinstalled Samsung A8 SM-A530F
but the EdXposed Framework is installed but it can't be activated (orange alert in EdXposed manager )

**Version used:**
android: 9 (arm64)
Magisk: 19.3
Magisk manager: 7.3.2
RIRU core: 19.1-magisk
EdXposed: tried on 0.4.5.1 (sandhook or yahfa) and 0.4.5.5 (sandhook or yahfa)

**other Magisk Module List**:
youtube vanced 14.21.54

**Logcat/Logcat**
i can't read log, the directory: /data/user_de_0_org.meowcat.edxposed.manager/log/ is empty...

Thanks for your help !

**Comment by Tortue95** [comment]
i just tested with the new version of RIRU core 19-4 with magisk.
but it does not works too :(

i have no idea how to debug it, Thanks for your help !

**Comment by Tortue95** [comment]
i get the boot log with Log-Catcher :)
[boot-issue-edxposed-tortue.log](https://github.com/ElderDrivers/EdXposed/files/3386004/boot-issue-edxposed-tortue.log)

but i see no issue:
![edxposed-issue-1](https://user-images.githubusercontent.com/11313869/61120922-4cb18080-a49e-11e9-995e-f2ae6502bf5a.jpg)

do you have an idea?

**Comment by NewBugger** [comment]
or you can try Edxp 0.4.5.3_beta and test.

**Comment by seasonyuu** [comment]
@Tortue95 Hey, have you solve the problem?
