### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by reiryuki** [ElderDrivers/EdXposed#328]
My Torch Flash Light cannot be activated after installing Riru_-_EdXposed-v0.4.5.1_beta(4463)_(SandHook/YAHFA).zip Module.

EdXposed Installer 2.2.4

Android 9 AOSP
![Screenshot_20190719-143841](https://user-images.githubusercontent.com/46316533/61576464-8e78a180-ab04-11e9-8a76-2e7bfd4f6aa8.png)

Xiaomi Redmi 4A
Pixel Experience Official ROM

**Comment by NewBugger** [comment]
logcat needed, of all edxp magisk adb(system).

**Comment by reiryuki** [comment]
Pada tanggal Min, 21 Jul 2019 7.00 PM, 凉风青木 <notifications@github.com>
menulis:

**Comment by reiryuki** [comment]
Pada tanggal Sel, 23 Jul 2019 9.58 AM, Rei Ryuki <
lightningthunder9999@gmail.com> menulis:
