### ISSUE TITLE
Android Pie: XSharedPreferences are not working correctly

### ISSUE THREAD

**Issue by dark1993rm** [ElderDrivers/EdXposed#330]
Hello,
I have a problem with the module I'm developing... even if the preferences have the WORLD_READABLE (777) permissions, in handleLoadPackage I cannot recover them and it only works if SELinux is set to **permissive**. What could be the problem?
There are no relevant logs.

Thanks.

**Comment by kslakhani** [comment]
It works.
Do this in your activity/service
SharedPreferences prefs = (SharedPreferences) getSharedPreferences("my_pref", MODE_WORLD_READABLE);

then in your hook class
XSharedPreferences pref = new XSharedPreferences(MainActivity.class.getPackage().getName(), "my_pref");
			pref.makeWorldReadable();
			pref.reload();

Hope this helps and let us know if it works

**Comment by dark1993rm** [comment]
Hi, thank you for your reply.
As I wrote in the first message, the preferences file already have the correct permissions (777) 😞
I can get them in the hooked app only if SELinux is set to Permissive.

**Comment by kslakhani** [comment]
yes it is mandatory on both sides:0

**Comment by dark1993rm** [comment]
[makeWorldReadable()](https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L87) just set the file as world readable, so it is useless if the preferences file has already the correct permissions. Also according to the [documentation](https://github.com/rovo89/XposedBridge/blob/a535c02ed9dfd53683cc0274d9f95bcb6ffb9f79/app/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L75) it works only if SELinux is disabled.
Anyway I added it and the preferences file is still not accessible in **handleLoadPackage()**.

**Comment by kslakhani** [comment]
That shouldnt be a case.
Mine is enforcing and works I am on pie with Magisk.
Are you fully rooted? Did you grant to your Xposed/EdXposed su permission?

**Comment by kslakhani** [comment]
makeWorldReadaable() needed both sides coz Xposed hooking runs in different thread. if file exists it just ovverrides

**Comment by dark1993rm** [comment]
The makeWorldReadable() method returns **false** so it is not executed and I don't use it since API 24 and everything works fine on API 27 and older BUT as I said, I have added it but nothing has changed, the preferences file is not accessible in handleLoadPackage().
Yes I'm fully rooted, other modules works fine.

**Comment by kslakhani** [comment]
As you said other module works so SELinux is not an issue.
Are you able to load the package? You can do that with reflection like
in onHandleLoadPackage
if (!lpparam.packageName.equals(packageName)) return;
XposedBridge.log("we are in");

If you manage to enter in the package then you could have wrong codes which simply not allowing to run further
and if you dont have it other code then I suggest you Invalidate cache in your Android Studio and create fresh project with all latest gradle and libraries and build tools.
You could grab a working module code from github but you will never know what went wrong in your code

**Comment by dark1993rm** [comment]
Yes, If I set SELinux in **Permissive mode** the module works correctly. It also works on Android 8 with SELinux in **Enforcing mode**.
I have already invalidated the cache, I will start over again the project hoping not to continue to have this strange problem 🤷🏻‍♂️
Thank you for your replies 😄

**Comment by kslakhani** [comment]
They must be busy with other stuffs ;)

**Comment by Android1500** [comment]
Facing same issue you got solution for this?

**Comment by yujincheng08** [comment]
@Android1500 https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences
