### ISSUE TITLE
[BUG] Sony Xperia X Compact (with rom 34.4.A.2.118) Boot loop

### ISSUE THREAD

**Issue by AxisRay** [ElderDrivers/EdXposed#335]
**什么情况/What happened?**

Sony Xperia X Compact (with rom 34.4.A.2.118)

EdXposed 0.4.5.1 Both 2 version YAHFA (or SandHook) boot loop on Sony Xperia X Compact(with 34.4.A.2.118).  Then need to use Magisk Manager TWRP to disable EdXposed module then I could boot again.

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**

Magisk Manager for Recovery Mode(mm) 2019.4.4
Riru - Core v19.4

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.5.1_beta(4463)

Riru: v19.4

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by XspeedPL** [comment]
Try commenting out the "supolicy **" calls in post-fs-data.sh and replace them with a "setenforce 0".
Search other issues here for my posts for more details, this is a known problem.
