### ISSUE TITLE
[BUG] Extreme lags

### ISSUE THREAD

**Issue by zeromentu** [ElderDrivers/EdXposed#337]
**什么情况/What happened?**

I still didn't find any pattern, however with the module activated sometimes the phone freezes and its a considerable freeze. I already ytied with just riru core and tried sandhook and yafa module, the problem is with exposed. (Many people reported here https://github.com/RikkaApps/Riru/issues/37)
I'm using a mi8 with miui 10 on pie version

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: Did tried the last 4 versions and keeps lagging

Riru: 19.4 and 19.1 did the tests with both

**Comment by kotori2** [comment]
It should be solved by using white list mode and optimize laggy apps manually in EdXposed Manager.
