### ISSUE TITLE
[BUG] #238（已修复）的问题在Magisk Stable19.3上似乎再次复现了。

### ISSUE THREAD

**Issue by Gokou-Ruri** [ElderDrivers/EdXposed#338]
**什么情况/What happened?**

原本#238 中我反映过edxposed会导致所有magisk模块（包括edxp自身）全部失效的问题，后来edxp更新后修复了此问题。
但现在我将magisk更新到stable 19.3后再次出现了此问题。
edxp版本目前为“magisk-EdXposed-YAHFA-v0.4.5.1_beta.4463.-release”。
系统：Android 9.0（AOSiP Official）

**Comment by NewBugger** [comment]
have you ever tried 0.4.5.5 latest, especially YAHFA.
