### ISSUE TITLE
[BUG]  Don't have any mobile data

### ISSUE THREAD

**Issue by Necrog** [ElderDrivers/EdXposed#340]
**什么情况/What happened?**

I have one chance out of 10 to make it work, but the other times, when I reboot the phone with EdXposed the mobile data is just unavailable.
I can call, send text but can't use internet.
I have One Plus 3t under Pie

**Xposed模块列表/Xposed Module List**

BubbleUpnp
XprivacyLua
Snaptools

**Magisk模块列表/Magisk Module List**

Busybox
iOs Emoji 12.1
Ritu Core and EdXposed
Systemless host

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: version 90 Sandhook v 0.4.5.1 beta 4463

Riru: 19.4

**Comment by DanGLES3** [comment]
I had this issue before, it seems to be caused by one sepolicy patch in Edxposed, if you want you can try my custom zip with the broken sepolicy removed 
[magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip](https://github.com/ElderDrivers/EdXposed/files/3479356/magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip)

**Comment by wl223600** [comment]
The same question. I have tried several versions of EdXposed, but all of them have the probability of causing this problem. Even when I just enabled Greenify module and have EdXposed running in whitelist mode.
When the problem occurred, I cannot see baseband version in system settings.
Tested on OnePlus 3T, Pixel Experience official build 201905/06/07.

**Comment by Necrog** [comment]
> I had this issue before, it seems to be caused by one sepolicy patch in Edxposed, if you want you can try my custom zip with the broken sepolicy removed
> [magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip](https://github.com/ElderDrivers/EdXposed/files/3479356/magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip)

Not to offense u, but I'm not 100% sure to download and install something like that, it was kinda hard to do it for Xposed, and I already have a modified xposed to make Snapchat works and don't get banned so..

**Comment by DanGLES3** [comment]
@Necrog if you don't trust me that's fine, you can make the modification yourself, all you need to do is modify the post-fs-data.sh file in the zip and remove this line of code 
supolicy --live "attradd {system_app platform_app} mlstrustedsubject"

**Comment by DanGLES3** [comment]
I mean no harm I just wish to help as I also suffer this issue with the regular Edxposed

**Comment by Necrog** [comment]
> @Necrog if you don't trust me that's fine, you can make the modification yourself, all you need to do is modify the post-fs-data.sh file in the zip and remove this line of code
> 
> supolicy --live "attradd {system_app platform_app} mlstrustedsubject"
> 
> you can also do that by using a file manager (without needing to reinstall Edxposed), go into data/adb/modules Edxposed and edit the post-fs-data file there and simply reboot

Oh well, now I feel bad for rejecting you 
But since I deactivated the module bc I go outside kinda often, I'm gonna modify it and install it, thx !

**Comment by Necrog** [comment]
Just quick question, it's my really first time someone actually answered me and I wanted to see if I can mark my issues as solved, is it possible or not at all ?

**Comment by l3golas83** [comment]
I have the same problem. When I activate Edxposed (yahfa or sandhook), I don't have mobile Internet connection and data icon doesn't appear in the status bar.
I tried by removing all the other magisk modules (apart from Riru) but nothing changes. If I disable EdXposed mobile data work again.
I'm using a Xiaomi Mi A1 with stock Android Pie.

**Comment by l3golas83** [comment]
Any news about this? Apparently there is more than one person having issues with mobile data

**Comment by Necrog** [comment]
> Any news about this? Apparently there is more than one person having issues with mobile data

Well, I can't help u, cause what DanGLES3 told me worked.
U should create ur own thread and ask, I think there will be more people

**Comment by l3golas83** [comment]
Mmm, understood. Since for you it worked, I will try modifying manually the module by commenting that line and see what happens. I suspect having selinux in permissive mode can also solve the problem, even if I wouldn't like doing that.

**Comment by Jappe62** [comment]
> I had this issue before, it seems to be caused by one sepolicy patch in Edxposed, if you want you can try my custom zip with the broken sepolicy removed
> [magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip](https://github.com/ElderDrivers/EdXposed/files/3479356/magisk-EdXposed-SandHook-v0.4.5.1_beta.4463.-release.zip)

This solves the loss of mobile connection for me, but...

Sadly GravityBox Xposed module is not fully working. Some of it's functions are working, some not. I have to stick with the YAFKA version and boot the phone 5 times to get the connection. =(

Could this be fixed officially? DanGLES3 seems to know what the problem is.

**Comment by Jappe62** [comment]
> > This solves the loss of mobile connection for me, but...
> > Sadly GravityBox Xposed module is not fully working. Some of it's functions are working, some not. I have to stick with the YAFKA version and boot the phone 5 times to get the connection. =(
> > Could this be fixed officially? DanGLES3 seems to know what the problem is.
> 
> Here's a patched YAHFA version
> 
> [magisk-EdXposed-YAHFA-v0.4.5.1_beta.4463.-release.zip](https://github.com/ElderDrivers/EdXposed/files/3542012/magisk-EdXposed-YAHFA-v0.4.5.1_beta.4463.-release.zip)

Thank you for trying to help, but sadly this version behaves just like the SandyHook version above. Mobile data connection works every time(!), but most of the functions of the GravityBox module do not work.

**Comment by l3golas83** [comment]
Hi there. Unfortunately the patched version doesn't change anything on my Xiaomi Mi A1. I get mobile data once every 4 or 5 reboots. My Xposed modules instead work, I use just 2 modules: gravitybox (huge module) and XToast (adds title and icon to toast notifications)

**Comment by Marty6** [comment]
Thank you so much, @DanGLES3! I removed the line from the _post-fs-data.sh_ file of my SandHook EdXposed installation on my Xiaomi Mi A2 Lite with Pie and - even after several reboots - I haven't lost mobile data connection so far! (keep fingers crossed)

But as @Jappe62 said, now the **GravityBox** settings don't survive reboot... :(
For example, I switched to the circle battery indicator - but after reboot it goes back to the default design... Any idea how to fix this?

**Comment by sorryusernameisalreadytaken** [comment]
I have the same issue on HavocOS Pie.

Tred all mentioned packages here and I did the patch here too on the current beta:
`supolicy --live "attradd {system_app platform_app} mlstrustedsubject"`

I s there anything else I can do do fix that mobile-data issue?
