### ISSUE TITLE
[BUG] BOOTLOOP ONEPLUS 7 PRO ANDROID Q YAHFA & SANDHOOK

### ISSUE THREAD

**Issue by Juxstin** [ElderDrivers/EdXposed#349]
**What happened?**
BOOTLOOP ONEPLUS 7 PRO ANDROID Q

**Xposed Module List**
None

**Magisk Module List**
Just Ed Xposed

**Versions of EdXposed and Riru**
EdXposed:
LATEST

Riru:
LATEST

**Comment by kotori2** [comment]
duplicate #346

**Comment by ecompton59** [comment]
running good on my 7pro on 10.0.1 with 7 other magisk mods
