### ISSUE TITLE
[BUG] 2.9以后小米8 2分钟内自动重启

### ISSUE THREAD

**Issue by codehz** [ElderDrivers/EdXposed#35]
**什么情况/What happened?**

自动重启

**Xposed模块列表/Xposed Module List**

黑屏，没截图

**Magisk模块列表/Magisk Module List**

riru core
riru edxposed
riru displaycutoutmode
riru locationreportenabler
riru storage redirect
noto cjk

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v2.9.6_beta

Riru: v10

**相关Logcat/Logcat**

稍后上传

**Comment by solohsu** [comment]
Try with riru v15 and edxposed v0.2.9.9_beta2
