### ISSUE TITLE
[Question] Apps uninstalling? 

### ISSUE THREAD

**Issue by Gunner82** [ElderDrivers/EdXposed#353]
Is anyone else experiencing apps uninstalling randomly on their own? I thought it was an app called "Icebox" causing the issue, but after running it a few weeks without issues I don't think it's that. after installing Edxposed the issue begins again.

**Comment by devanteweary** [comment]
Hey man, I came here to post this.
It seems like everytime I reboot, a random app will be uninstalled.

Sometimes it's something easy to replace like the McDonald's app, sometimes it's extremely annoying like the Tiles app. Which means I have to set all that up again.

Once or twice it seemed like even the Play store uninstalled and I had to reupdate it. Another time Google Play services (or whatever it is that keeps you logged into all your google services) was gone and I had to relog into everything (Music and Play store for instance) and they acted like I was logging in for the first time.

It only started happening recently and I had a suspicion that it was EdXposed. I have GravityBox and XposedSmsCode installed.

Pixel 2 XL, Android Pie, EdXposed v0.4.5.1_beta (SandHook), Manager 4.5.3

It's at the point where I am scared to reboot each time ha

**Comment by refi64** [comment]
@Gunner82 were you also using sandhook? What EdXposed version? Given the fact that this doesn't seem to be particularly common but I think it's happened to me as well, I'm wondering if it's a SandHook-specific thing.

**Comment by devanteweary** [comment]
After a lot of testing and a LOT of rebooting, I can say that I haven't lost an app using the YAHFA version.

I uninstalled SandHook and installed YAHFA and so far after like 50 reboots, I haven't lost an app.

**Comment by drewcu** [comment]
For at least the 2nd time I lost an app after a reboot -- just now Gravitybox disappeared and I had to reinstall it...

Am using Sandhook 4497, and unfortunately YAHFA has lag that I don't experience with Sandhook that makes it a no-go for me.
