### ISSUE TITLE
[BUG] 模組運作時，不會顯示在列表

### ISSUE THREAD

**Issue by luxontw** [ElderDrivers/EdXposed#356]
當我使用 Edxposed Manager 時，如果 LuckуPаtcher 的 Xposed 模組正常運作，就不會顯示在 Edxposed 的列表，而當模塊沒有在運作時，就會顯示在 Edxposed 的列表中，並且顯示未啟用。

![Screenshot_20190917-212831](https://user-images.githubusercontent.com/38381008/65046384-19560b00-d993-11e9-90fb-16ad2f7ddfe2.jpg)

![Screenshot_20190917-212826](https://user-images.githubusercontent.com/38381008/65046423-2c68db00-d993-11e9-95bc-af2d5ecf6738.jpg)

**Xposed模块列表/Xposed Module List**
![Screenshot_20190917-213638](https://user-images.githubusercontent.com/38381008/65046502-57532f00-d993-11e9-8c53-bc5321135506.jpg)

**Magisk模块列表/Magisk Module List**
![Screenshot_20190917-213657](https://user-images.githubusercontent.com/38381008/65047072-58d12700-d994-11e9-8fb4-b5c1383f588c.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 90.0-v0.4.5.1 _beta(4463) (SandHook)

Riru: v19.5

**相关Logcat/Logcat**
[Verbose Log](https://drive.google.com/file/d/16SjUNe38n9W8qMbqqiGpdse4HZTM8lfK/view?usp=drivesdk) 
[Module Log](https://drive.google.com/file/d/16IqobSAMtR-Ox7adLm-j2gmtTLNFDqrd/view?usp=drivesdk)

**Comment by eebssk1** [comment]
建议完整卸载LP然后开着EdXp manager重新安装LP。
LP混淆自身后检查以后的包名和manager里的一不一样，不一样的话重新安装混淆后的包

**Comment by SekiBetu** [comment]
same with https://github.com/ElderDrivers/EdXposed/issues/207 and https://github.com/ElderDrivers/EdXposed/issues/570

**Comment by sospartan** [comment]
https://medium.com/@quaful/the-changes-of-apk-install-location-since-android-oreo-e646d1b53c4d   
The install path changed after 're-run'  from android studio, and EdXposed still look for the install path at system boot.
