### ISSUE TITLE
[BUG] 32Errors per minutes with GravityBox

### ISSUE THREAD

**Issue by a0193143** [ElderDrivers/EdXposed#358]
**什么情况/What happened?**
Lots of errors, don't know it's a module bug or framework bug

**Xposed模块列表/Xposed Module List**
GravityBox [O]

**Magisk模块列表/Magisk Module List**
AOSP Volume Steps Increase 30
ViPER4Android FX
Busybox for Android NDK
Systemless Hosts
YouTube Vanced black themed - Magisk Repo
Riru - Core
Riru - Edxposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: v0.4.5.1_beta (YAHFA)
Riru: v19.5

**相关Logcat/Logcat**
The zip file
[xposed_error_20190920_181146.zip](https://github.com/ElderDrivers/EdXposed/files/3635392/xposed_error_20190920_181146.zip)

**Comment by C3C0** [comment]
It's GravityBox related. Clock features are not compatible with your system. You can turned them off using clock features master switch

**Comment by a0193143** [comment]
> 
> 
> It's GravityBox related. Clock features are not compatible with your system. You can turned them off using clock features master switch

Turned off and the problem solved, thanks
