### ISSUE TITLE
[BUG] android 10 GSI bootloop

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposed#359]
**什么情况/What happened?**

latest version from magisk 
**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: latest version

Riru: 19.5

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by gudenau** [comment]
I can confirm, I have a bootloop on Android 10 and a Pixel XL.

**Comment by GammatonCleric** [comment]
Same here on K20 Pro with Android 10.

**Comment by nasim7500** [comment]
Same problem also have redmi note 3 pro

**Comment by zacchi4k** [comment]
Same here on Mi Mix 2S with Android 10

**Comment by Howard20181** [comment]
https://github.com/ElderDrivers/EdXposed/pull/354#issue-317628252

**Comment by dawidkossa** [comment]
Same here Pixel experience redmi note 5 android 10

**Comment by 0987363** [comment]
same here with oneplus 6t android 10

**Comment by Howard20181** [comment]
> same here with oneplus 6t android 10

Try canary builds from [here](https://ci.appveyor.com/project/ElderDrivers/edxposed/branch/master/artifacts).

**Comment by 0987363** [comment]
> > same here with oneplus 6t android 10
> 
> Try canary builds from [here](https://ci.appveyor.com/project/ElderDrivers/edxposed/branch/master/artifacts).

It still bootloop when enter desktop.

oneplus 6t
android 10
magisk v20.4
riru core v19.8
edxposed sandhook v0.4.6.3

**Comment by Howard20181** [comment]
It might be helpful to provide some logs.
Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.

**Comment by 0987363** [comment]
> It might be helpful to provide some logs.
> Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.

OK

I try boot twice, here are two logs.

one.
https://github.com/0987363/edlogs/blob/master/edxposed.log

second.
https://github.com/0987363/edlogs/blob/master/edxposed2.log

**Comment by Palatis** [comment]
> 
> 
> > It might be helpful to provide some logs.
> > Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.
> 
> OK
> 
> I try boot twice, here are two logs.
> 
> one.
> https://github.com/0987363/edlogs/blob/master/edxposed.log
> 
> second.
> https://github.com/0987363/edlogs/blob/master/edxposed2.log

actually you can just use gist...

**Comment by MlgmXyysd** [comment]
> > 
> > 
> > > It might be helpful to provide some logs.
> > > Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.
> > 
> > OK
> > 
> > I try boot twice, here are two logs.
> > 
> > one.
> > https://github.com/0987363/edlogs/blob/master/edxposed.log
> > 
> > second.
> > https://github.com/0987363/edlogs/blob/master/edxposed2.log
> 
> actually you can just use gist...

maybe drag to upload(

**Comment by 0987363** [comment]
> > > > It might be helpful to provide some logs.
> > > > Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.
> > > 
> > > 
> > > OK
> > > I try boot twice, here are two logs.
> > > one.
> > > https://github.com/0987363/edlogs/blob/master/edxposed.log
> > > second.
> > > https://github.com/0987363/edlogs/blob/master/edxposed2.log
> > 
> > 
> > actually you can just use gist...
> 
> maybe use drag to upload better(



> > > It might be helpful to provide some logs.
> > > Enable USB debugging and run "ADB logcat > log" on the computer when the phone starts.
> > 
> > 
> > OK
> > I try boot twice, here are two logs.
> > one.
> > https://github.com/0987363/edlogs/blob/master/edxposed.log
> > second.
> > https://github.com/0987363/edlogs/blob/master/edxposed2.log
> 
> actually you can just use gist...

sure

[edxposed.log](https://github.com/ElderDrivers/EdXposed/files/4484758/edxposed.log)
[edxposed2.log](https://github.com/ElderDrivers/EdXposed/files/4484759/edxposed2.log)

**Comment by 0987363** [comment]
I upgraded to v21.1 and v0.5.0.0.
It's fine now.
