### ISSUE TITLE
[BUG] Error when hooking LoadedApk

### ISSUE THREAD

**Issue by FuLygon** [ElderDrivers/EdXposed#360]
**什么情况/What happened?**

Error when hooking LoadedApk, Verbose Logs, MIUI 10.3.10, android P

**Xposed模块列表/Xposed Module List**

MinMinGuard
Xposed Edge

**Magisk模块列表/Magisk Module List**

Blobmoji
Busybox for Android NDK
Systemless hosts
Youtube Vanced
Riru - Core
Riru - Edxposed
Unicode Google Sans Font

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.5.1_beta(4463)(YAHFA)

Riru: v19.5

**相关Logcat/Logcat**

09-23 17:58:06.219  5127  5346 E EdXposed: error when hooking LoadedApk.<init>: pkg=com.miui.securitycenter, prc=com.miui.securitycenter
09-23 17:58:06.219  5127  5346 E EdXposed: java.lang.NullPointerException
09-23 17:58:06.219  5127  5346 E EdXposed: 	at java.io.File.<init>(File.java:283)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at dalvik.system.DexPathList.addNativePath(DexPathList.java:589)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at dalvik.system.BaseDexClassLoader.addNativePath(BaseDexClassLoader.java:164)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.app.ApplicationLoaders.addNative(ApplicationLoaders.java:134)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:744)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.app.ContextCompat.createLoadedApk(Unknown Source:99)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.app.ContextCompat.createApplicationContext(Unknown Source:0)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.miui.securitycenter.dynamic.ApkLoader.getDynamicContext(Unknown Source:36)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.createOrUpdateManagerWT(Unknown Source:2)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.connectWT(Unknown Source:19)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.miui.securitycenter.dynamic.DynamicServiceManager.access$400(Unknown Source:0)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at com.miui.securitycenter.dynamic.DynamicServiceManager$DynamicWorkHandler.handleMessage(Unknown Source:35)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.os.Looper.loop(Looper.java:201)
09-23 17:58:06.219  5127  5346 E EdXposed: 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by kotori2** [comment]
closed as stale
