### ISSUE TITLE
EXI Module Fails to hook

### ISSUE THREAD

**Issue by AlwyNjOshy** [ElderDrivers/EdXposed#363]
Hi,
Something prevent EXI SWIFTKEY module to hook, tried everything after 3 reboots issues starts, its works on dvandroids' xposed manager. Issues is with Edxposed manager. I have detailed bug reports please look

[Android logcat 2019-09-25-01-57-32 log.txt](https://github.com/ElderDrivers/EdXposed/files/3653075/Android.logcat.2019-09-25-01-57-32.log.txt)
[EdXposed_Module_error_20190925_015713.log](https://github.com/ElderDrivers/EdXposed/files/3653078/EdXposed_Module_error_20190925_015713.log)
[EdXposed_Verbose_all_20190925_015702.log](https://github.com/ElderDrivers/EdXposed/files/3653080/EdXposed_Verbose_all_20190925_015702.log)

**Comment by Einheit-101** [comment]
I can confirm. Exi stops working.
