### ISSUE TITLE
Bootloop on revenge os android Q redmi note 4 qualcomm version

### ISSUE THREAD

**Issue by nanachitang420** [ElderDrivers/EdXposed#364]
Redmi Note 4 qualcomm version, Revenge os android 10 beta build. Tried yahfa 0.4.5.5 & sandhook 0.4.6.0 canary version but phone is not booting. Going to fast boot
[boot-1972-01-25-21-04-47.log](https://github.com/ElderDrivers/EdXposed/files/3670671/boot-1972-01-25-21-04-47.log)

**Comment by Hacktivist13** [comment]
Facing same issue: Bootloop
ROM : Revenge OS android 10 beta
Device : Redmi note 4 SD 625 (Mido)
Fixed version for Android 10 are not working.

**Comment by mirsella** [comment]
same on MI8, with xiaomi eu rom android Q. tried both yahfa 0.4.5.5 & sandhook 0.4.6.0

**Comment by nanachitang420** [comment]
Latest canary build 0.4.6.0 beta is working ok with Q. Thanks
