### ISSUE TITLE
When to support Android q

### ISSUE THREAD

**Issue by skyliao1** [ElderDrivers/EdXposed#367]

**Comment by Howard20181** [comment]
https://github.com/ElderDrivers/EdXposed/pull/354#issue-317628252

**Comment by BobbyWibowo** [comment]
Latest canary appears to be working:
![Screenshot](https://i.fiery.me/C0BM.jpg)
It should've been built against this commit https://github.com/ElderDrivers/EdXposed/commit/b9b10b510e9e8ae314846bb0dce685da4baacefb.

The PR linked above appears to be pretty much ignored by the devs.

**Comment by MrHappy** [comment]
Both YAHFA & SandHook seem to be working ok, but both prevent screen from rotating and other sensors from working (on OP6T / OOS10)...

**Comment by MrHappy** [comment]
Is this fixed?
