### ISSUE TITLE
我很喜欢MyAndroidToolsXposed

### ISSUE THREAD

**Issue by heiyutian** [ElderDrivers/EdXposed#368]
以前一直是autostarts配合MyAndroidToolsXposed的0.8版本（非MyAndroidTools）来控制阻止自动激活某些自启动事件服务，现在买的新手机是8.1，只能使用edxposed来装模块，现在被autostarts禁用了然后用MyAndroidToolsXposed选择阻止的应用没有效果了，打开那些应用之后相关自启动事件服务还是会被激活。

我不知道是这个模版太老了，还是别的原因，如果不能解决，希望大家给推荐一个完全相关功能的模块或软件，能够完全阻止激活自启动事件服务，我知道市面上有很多别的阻止自启动的软件，但跟这个autostarts完全不一样。

**Comment by MlgmXyysd** [comment]
8.1可以使用原版xp
