### ISSUE TITLE
小米开发版 7,1系统 面具 刷入成功 安装Ed提示can,t rename system/lib/libart.so

### ISSUE THREAD

**Issue by w296488320** [ElderDrivers/EdXposed#371]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
不支持 7.1
