### ISSUE TITLE
[BUG] system_server crash using SandHook-v0.4.6.0_beta.4471

### ISSUE THREAD

**Issue by C3C0** [ElderDrivers/EdXposed#372]
**What happened?**
- Always soft reboots immediately after booting (log attached). Seems to be GC related (similar we had in the past).
- Also I can see some errors related to SElinux relabeling but not sure if they play any role or could have another negative side effects (log attached).

**Device**
OnePlus 7 Pro running Oxygen OS 10.0.1

**Xposed Module List**
GravityBox [Q]

**Magisk Module List**
- Riru v19.5
- EdXposed v0.4.6.0_beta.4471 (Sandhook)
(using custom Magisk v20 from https://github.com/solohsu/magisk_files)

**Logs**
[crash_sandhook.txt](https://github.com/ElderDrivers/EdXposed/files/3754065/crash_sandhook.txt)
[avc_denied_sandhook.txt](https://github.com/ElderDrivers/EdXposed/files/3754068/avc_denied_sandhook.txt)

**Comment by Mikanoshi** [comment]
So as I understand it SELinux policies moved from EdXposed to custom Magisk build, even for Android 9 where previous post-fs-data.sh was working absolutely fine?
For me the only version that doesn't crash apps with native errors, doesn't suddenly bootloop and doesn't spam logs with errors and debug on Android 9 is 0.4.5.5 YAHFA from here: https://github.com/ElderDrivers/EdXposed/pull/354

**Comment by C3C0** [comment]
+1 - experience seems to be better using YAHFA with whale patch in #354 on my OnePlus 7 Pro
@Mikanoshi 
As far as I understand, SELinux adjustments were moved because they don't work on some devices in post-fs-data stage of boot process. They need to be adjusted earlier in the boot process.

**Comment by Howard20181** [comment]
+1
many apps FC in  v0.4.6.0_beta.447 Sandhook & YAHFA
0.4.5.5 YAHFA from https://github.com/ElderDrivers/EdXposed/pull/354 work well in Mi9 Android Q

**Comment by solohsu** [comment]
@C3C0 @Mikanoshi @Howard20181 
How about this build?https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/27518070/artifacts
This build is with sepolicies embedded. I am not sure if it's their removal causing problems.

**Comment by Howard20181** [comment]
> @C3C0 @Mikanoshi @Howard20181
> How about this build?https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/27518070/artifacts
> This build is with sepolicies embedded. I am not sure if it's their removal causing problems.

it work! 
in MIUI 11 9.10.28 Android 10
with Magisk 20.0 (20000)

**Comment by Mikanoshi** [comment]
This one works fine for me too.
