### ISSUE TITLE
[BUG] crash in nativeForkAndSpecialize after normal boot (4471 YAHFA)

### ISSUE THREAD

**Issue by C3C0** [ElderDrivers/EdXposed#373]
**What happened?**
The first normal boot often ends up with soft reboot shortly after booting. After such soft reboot, often no further crashes are observed and system runs normally.

**Device**
OnePlus 7 Pro running Oxygen OS 10.0.1

**Xposed Module List**
GravityBox [Q]

**Magisk Module List**
- Riru v19.5
- EdXposed v0.4.6.0_beta.4471 (YAHFA)
(using custom Magisk v20 from https://github.com/solohsu/magisk_files)

**Logcat**
[crash_yahfa.txt](https://github.com/ElderDrivers/EdXposed/files/3754147/crash_yahfa.txt)

**Comment by bush911** [comment]
After installing this build, my pixel 3 with android pixel does not boot. Previously, 4463 build works very well.
I am unable to provide a logcat.

**Comment by C3C0** [comment]
> After installing this build, my pixel 3 with android Pie does not boot. Previously, 4463 build works very well.
> I am unable to provide a logcat.
Are you using custom Magisk for those new builds? It is required as per release notes.
https://github.com/solohsu/magisk_files

**Comment by bush911** [comment]
> > After installing this build, my pixel 3 with android Pie does not boot. Previously, 4463 build works very well.
> > I am unable to provide a logcat.
> 
> Are you using custom Magisk for those new builds? It is required as per release notes.
> https://github.com/solohsu/magisk_files

Nope, I saw that note  but did not get it

**Comment by bush911** [comment]
> > > After installing this build, my pixel 3 with android Pie does not boot. Previously, 4463 build works very well.
> > > I am unable to provide a logcat.
> > 
> > 
> > Are you using custom Magisk for those new builds? It is required as per release notes.
> > https://github.com/solohsu/magisk_files
> 
> Nope, I saw that note but did not get it

using modified magisk then install the latest build now seems fine

**Comment by whitedavidp** [comment]
Just chiming in that I am seeing something quite similar. On some boots, my Samsung S8+ will reboot 1-2 times until it settles down. Then seems fine. Does not always happen. Have seen it with both cold starts and reboots.  I have hadesROM (Pie), Magisk 20.1, Core 19.5, and EdXposed 4.5.1_beta (sandhook) with just GravityBox[P]. Just FYI and thanks for all the hard work!

**Comment by kotori2** [comment]
`FileDescriptorInfo::CreateFromFd`
It seems fixed in recent PRs because we don't need to transfer open fd to child process.
