### ISSUE TITLE
[BUG] 黑名单无效 Blacklist is invalid

### ISSUE THREAD

**Issue by chnp101** [ElderDrivers/EdXposed#378]
**什么情况/What happened?**
黑名单无效

**Xposed模块列表/Xposed Module List**
大圣净化
钉钉打卡
钉钉考勤
核心破解
监视剪切板
绿色守护
上帝模式
微X模块
音量增强器
运存清洁工
Hack Connectivity Service
Xposed edge pro
XPrivacyLua

**Magisk模块列表/Magisk Module List**
Riru-Core
Riru-EdXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed:
Riru-Core:19.5
Riru-EdXposed:0.4.5.1_beta(4463)(SandHook)
EdXposed Manager:4.5.1

**相关Logcat/Logcat**
【】

具体情况：
一加5，安卓8.1.0升级到9（氧9.0.8）后，ed的黑名单好像不生效了。
已加入Magisk Hide
已加入ed的应用名单（已开启设置中的“应用名单模式”）
也试过EdXposed Manager的白名单模式。
也试过EdXposed Installer 2.2.5的黑/白名单模式（卸载Manager）
请问是我哪里打开方式不对吗？

**Comment by 168308711q** [comment]
miui11 androidQ 黑名单无效
