### ISSUE TITLE
(SOLVED: See Below) [BUG] Custom Magisk Cannot Install

### ISSUE THREAD

**Issue by JohnGLFour** [ElderDrivers/EdXposed#379]
**什么情况/What happened?**
Using the Magisk custom build, Magisk Manager cannot see Magisk, saying "Magisk not installed"

**Xposed模块列表/Xposed Module List**
None

**Magisk模块列表/Magisk Module List**
None

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: 0.4.6.0
Riru: 19.5

**相关Logcat/Logcat**
Cannot get logcat.

@solohsu @MlgmXyysd (don't know how to assign people so yeah)

**Comment by JohnGLFour** [comment]
Installing 19.3 works, however the 20.0 doesn't work as described above. I don't know what happened though.

**Comment by JohnGLFour** [comment]
Any fixes yet?

**Comment by muhviehstah** [comment]
same here with v20 and v20.1 custom builds

redmi note 5 pro (whyred) at xiaomi.eu MIUI 11

**Comment by solohsu** [comment]
Try to disable Magisk hide before installing the custom build.

**Comment by muhviehstah** [comment]
it did not work even if i uninstall /cleaninstall

**Comment by ecompton59** [comment]
20 works i use 20.1 no issues on 10.0.1

On Saturday, November 9, 2019, Timo Sarawinski <notifications@github.com>
wrote:
> it did not work even if i uninstall /cleaninstall
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/wBhRbhqOFS1-d7NvjBRXv57C7n8-h90j1yenM-LVGptA2_4EAkL6E0tmgF-YcsQs0-S0L7dp9HU_rkdBu4B2Lyyb20GztyjCnfDrrilyqDAtwJIjqwmQzs6mfbm9LM0L_XAowUw6w2cRA58otMd6_0GSIR53aMMTAGGhgr4FIKzyYzAt0VxGj3q_LLVjc8irok4uiPF5xMaxgSOdtmBuYJbSwwsrD9xVFUUpbwJwVQ=s0-d-e1-ft#https://github.com/notifications/beacon/AHPO5JG2XVDD6NNNSQBYAC3QS3ILFA5CNFSM4JFXOSLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDUIMDA.gif>

**Comment by JohnGLFour** [comment]
I tried, but it still doesn't work. I am on 9 (Pie)

**Comment by ShafiqSadat** [comment]
Same here!
Samsung A8 2018 
Android 9

**Comment by muhviehstah** [comment]
custom 19.1 version is working for me

20,20.1 not

**Comment by Darkpurple** [comment]
> Try to disable Magisk hide before installing the custom build.

Installing 19.3 works, however the 20.0 doesn't work as described above. I don't know what happened though.

**Comment by muhviehstah** [comment]
building the latest master with the custom patch worked fine. 

some of the selinux changes from the latest commits seems to fix the issue.

latest master git build + custom Patch in Attachment

greetings

[Magisk-v20.2.git.zip](https://github.com/ElderDrivers/EdXposed/files/3963493/Magisk-v20.2.git.zip)

**Comment by drewcu** [comment]
LG V30 VS996 - Pie Stock 

Same problem with "Magisk not installed" after installing v20.1_edxposed.

Tried Magisk-v20.2.git.zip from @muhviehstah which installed Magisk and everything seemed fine with latest Canary of EdXposed until... 

None of my Root-necessary apps were able to be granted Root permission from Magisk. They just show the message of "Requesting root..." and then time out. I went into Magisk Manager Settings and even enabled automatic granting of root privileges. Had no Root problems when on regular v20.1. So I uninstalled the custom version and switched back to the regular Magisk and non-Canary EdXposed (0.4.5.1) -- everything works again.

No clue why everyone else seems to be on EdXposed 0.4.6 without so many problems. Thoughts???

**Comment by sunnykatiyar50** [comment]
same here... custom magisk not installing... says magisk not installed.

**Comment by MlgmXyysd** [comment]
@sunnykatiyar50 try Canary magisk 20.2

**Comment by sunnykatiyar50** [comment]
I cannot find any canary magisk 20.2... custom for edxposed... did you mean official?

**Comment by muhviehstah** [comment]
[Magisk-v20.2-4f4f54a.zip](https://github.com/ElderDrivers/EdXposed/files/4003404/Magisk-v20.2-4f4f54a.zip)
newer build

**Comment by muhviehstah** [comment]
[Magisk-v20.2-025b0605.zip](https://github.com/ElderDrivers/EdXposed/files/4006203/Magisk-v20.2-025b0605.zip)

latest build today (commit 025b0605)

**Comment by i1itione** [comment]
> [Magisk-v20.2-025b0605.zip](https://github.com/ElderDrivers/EdXposed/files/4006203/Magisk-v20.2-025b0605.zip)
> 
> latest build today (commit 025b0605)

Is there a sepolicy patch able to install with official magisk stable 20.2 directly? Thank you.

**Comment by thebenjibenji** [comment]
> [Magisk-v20.2-025b0605.zip](https://github.com/ElderDrivers/EdXposed/files/4006203/Magisk-v20.2-025b0605.zip)
> 
> latest build today (commit 025b0605)

legend! thanks

**Comment by muhviehstah** [comment]
[Magisk-v20.3.zip](https://github.com/ElderDrivers/EdXposed/files/4056037/Magisk-v20.3.zip)
[Magisk-uninstaller-20200113.zip](https://github.com/ElderDrivers/EdXposed/files/4056039/Magisk-uninstaller-20200113.zip)

Custom v20.3 build

**Comment by JohnGLFour** [comment]
Official Canary Magisk?

**Comment by JohnGLFour** [comment]
Official Canary Magisk?

Edit: Just found out that the version for Magisk Canary are Cherry Picked from topjohnwu/Magisk.

Let me explain:
So. The latest Canary is 20.4-b39f4075. Take a look at b39f4075. When you find the number in topjohnwu/Magisk in commits, you will see the the comment on that commit is "Load lipsqulite dynamically".

Look back at the upload log for Magisk Canary in topjohnwu/magisk_files, you will see...

notes.md:
## Magisk (b39f4075) (20302)
- Dynamic link 'libsqlite.so'

Hmmmm....

**Comment by JohnGLFour** [comment]
Pin and close this so people will know, thank you.

**Comment by JohnGLFour** [comment]
Proofs:
![Screenshot_20200122-114520_EdXposed_Manager](https://user-images.githubusercontent.com/17681926/72863998-885eba00-3d0d-11ea-9e5e-11051cb6271f.png)
![Screenshot_20200122-114455_Magisk_Manager](https://user-images.githubusercontent.com/17681926/72864001-8a287d80-3d0d-11ea-960f-fdd280be9a77.png)
