### ISSUE TITLE
[BUG] black list is not working, gear 3 spay  sees root  but magisk hide is fine. 

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposed#382]
**什么情况/What happened?**
Gear 3 spay is detecting root with xposed  but magisk hide is fine 
I blacklist it or white list it. 
Same issue 
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: latest 

Riru:latest 

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by tuyennn** [comment]
#374

**Comment by manofsteel2017** [comment]
Different issue though

**Comment by 168308711q** [comment]
miui11 AndroidQ 黑名单未生效

**Comment by MlgmXyysd** [comment]
> miui11 AndroidQ 黑名单未生效

please open an new issue, not spam
