### ISSUE TITLE
[BUG] Bootloop Xiaomi redmi note 5 PE ANDROID 10

### ISSUE THREAD

**Issue by dawidkossa** [ElderDrivers/EdXposed#383]
**什么情况/What happened?**
Bootloop

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Nothing
允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
WiFi bonding (Qcom)
Systemless host
SafetyPatch
Riru-Core
MagiskHide Props Config
LKT
Busybox for android NDK
Riru edxposed Yahfa

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**
19.4
EdXposed:
0.4.5.1 yahfa
Riru:
19.4
**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
log required
