### ISSUE TITLE
[BUG] Ed Xposed doesn't work with Samsung firmware

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposed#39]
**什么情况/What happened?**
Using Samsung Galaxy S8, G950F Exynos -
Xposed Firmware is not installed error message

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
None

**Magisk模块列表/Magisk Module List**
Riru Core - v11
Riru - Ed Xposed 0.2.9.6 beta

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
Riru - Ed Xposed 0.2.9.6 beta
Riru:
Riru Core - v11
**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[logcat.txt](https://github.com/solohsu/EdXposed/files/2803600/logcat.txt)
![2019-01-28 16 09 46](https://user-images.githubusercontent.com/18083277/51845218-c9e99e80-231f-11e9-92ed-20a6084ea7d4.jpg)
![2019-01-28 16 09 54](https://user-images.githubusercontent.com/18083277/51845220-c9e99e80-231f-11e9-9b86-69cff375be80.jpg)

**Comment by Firefds** [comment]
> Please install Xposed Installer-3.1.4 by dvdandroid
> link:https://drive.google.com/file/d/1Yyf6oaha539O3UKZuVNEbFGvcWDxgyPc/view?usp=drivesdk

I am using that version

**Comment by 1161467173** [comment]
So that is a bug

**Comment by solohsu** [comment]
Sorry I have no Samsung Android Pie device on my hand now, so have no schedule when it would be supported.

**Comment by Firefds** [comment]
@solohsu if you need any help from me, even by remote adb, my device and I are available.

**Comment by amakuramio** [comment]
Works on aosp roms (phh treble pie)
But not on stock Samsung roms, S9+ here

**Comment by davidt123456** [comment]
I have Samsung S9 with SoLdieR9312s rom and doesn't work either (although it says AOSP-based ROM).

Anyone can confirm working on S9 with non-stock ROM? Which one?

**Comment by amakuramio** [comment]
@davidt phh treble 9.0. But I switched back to stock because google cam stabilization is horrible

**Comment by amakuramio** [comment]
@davidt123456 phh treble 9.0. But I switched back to stock oreo because google cam stabilization is horrible

**Comment by RYU81** [comment]
same here not working with note 9

**Comment by widget-** [comment]
I have a logcat from boot. I filtered it to just the Riru messages. Looks like there's a hook that mismatches what EdXposed is expecting.

Notably:
```
jniRegisterNativeMethods com/android/internal/os/Zygote
found nativeForkAndSpecialize but signature (II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I mismatch
{"nativeForkAndSpecialize", "(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I", 0x0}
{"nativeForkSystemServer", "(II[II[[IJJ)I", 0x709355ef50}
```
[widget-_logcat_riru_edxposed.txt](https://github.com/ElderDrivers/EdXposed/files/2873872/widget-_logcat_riru_edxposed.txt)

**Comment by widget-** [comment]
I now believe this is an issue with Riru. https://github.com/RikkaApps/Riru/blob/6f7a2e17f51ce8d24512a5f7c7bbfc373a6fc7fa/riru-core/jni/main/jni_native_method.h#L52 requires a new string for Samsung Android P zygote. I'll see if I can test the one reported in the logcat.

**Comment by solohsu** [comment]
@widget- Yes, I checked it too. Samsung always has its own `nativeForkAndSpecialize` sig pattern. Apparently here Android P version is missing.

**Comment by widget-** [comment]
I've created a PR at https://github.com/RikkaApps/Riru/pull/18

Attached is a build of Riru-Core I tested on my phone with.
[magisk-riru-core-v13.zip](https://github.com/ElderDrivers/EdXposed/files/2874107/magisk-riru-core-v13.zip)

**Comment by Firefds** [comment]
@widget- This works great on my S8 Exynos! thanks

**Comment by amakuramio** [comment]
doesnt work on s9+

**Comment by Kevin2296** [comment]
Can confirm that the linked one from Widget works on my S9 (G960F) 
Only wierd is that Xinsta doesnt work for me?

**Comment by solohsu** [comment]
@Kevin2296 plz check https://github.com/ElderDrivers/EdXposed/issues/75 for XInsta issue

**Comment by sayaksark** [comment]
@widget how to thank u man, its working now

**Comment by jakob1379** [comment]
So I can't can't flash til zip from widget from within magisk. Should it be flasher from twrp?
