### ISSUE TITLE
Flashlight icon disabled/greyed out

### ISSUE THREAD

**Issue by shubhamgawri** [ElderDrivers/EdXposed#391]
![Screenshot_20191112-195806(1)](https://user-images.githubusercontent.com/25635808/68680666-138e3780-0588-11ea-8e7b-132812820b80.jpg)
After installing edxposed torch tile greys out
Tried disabling all modules
And when edxposed is disabled everything works fine??...

-----Log----
[Log:--------- beginning of head EdXposed Log Powered by Log Catcher QQ chat group 855219808 --------- beginning of system info Android version: 9 Android sdk: 28 Android build: PQ3B.190801.002 Fingerprint: Xiaomi/rolex/rolex:7.1.2/N2G47H/V9.2.6.0.NCCMIEK:user/release-keys ROM build description: rolex-user 7.1.2 N2G47H V9.2.6.0.NCCMIEK release-keys EdXposed Version: v0.4.5.1_beta(4463) (Yahfa) Architecture: arm64-v8a Device: rolex Manufacture: Xiaomi Brand: Xiaomi Product: rolex --------- beginning of main --------- beginning of system 11-12 11:41:31.142  1512  1512 I EdXposed: onModuleLoaded: welcome to EdXposed! 11-12 11:41:31.142  1512  1512 I EdXposed: Start to install inline hooks 11-12 11:41:31.142  1512  1512 I EdXposed: Using api level 28 11-12 11:41:31.142  1512  1512 I EdXposed: Start to install Riru hook 11-12 11:41:31.162  1511  1511 I EdXposed: onModuleLoaded: welcome to EdXposed! 11-12 11:41:31.162  1511  1511 I EdXposed: Start to install inline hooks 11-12 11:41:31.162  1511  1511 I EdXposed: Using api level 28 11-12 11:41:31.162  1511  1511 I EdXposed: Start to install Riru hook 11-12 11:41:31.167  1512  1512 I EdXposed: Riru hooks installed 11-12 11:41:31.188  1511  1511 I EdXposed: Riru hooks installed 11-12 11:41:31.189  1512  1512 I EdXposed: ART hooks installed 11-12 11:41:31.189  1512  1512 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken 11-12 11:41:31.189  1512  1512 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0 11-12 11:41:31.228  1511  1511 I EdXposed: ART hooks installed 11-12 11:41:31.228  1511  1511 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken 11-12 11:41:31.228  1511  1511 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0 11-12 11:41:31.487  1512  1512 I EdXposed: using installer com.solohsu.android.edxp.manager 11-12 11:41:31.487  1512  1512 I EdXposed: black/white list mode: true, using whitelist: true 11-12 11:41:31.487  1512  1512 I EdXposed: dynamic modules mode: false 11-12 11:41:31.487  1512  1512 I EdXposed: resources hook: true 11-12 11:41:31.487  1512  1512 I EdXposed: deopt boot image: false 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: com.solohsu.android.edxp.manager 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: org.meowcat.edxposed.manager 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: de.robv.android.xposed.installer 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: com.android.systemui 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: android 11-12 11:41:31.490  1512  1512 I EdXposed: whitelist: org.lineageos.snap 11-12 11:41:31.491  1512  1512 I EdXposed: blacklist: com.android.systemui 11-12 11:41:31.491  1512  1512 I EdXposed: blacklist: android 11-12 11:41:31.547  1511  1511 I EdXposed: using installer com.solohsu.android.edxp.manager 11-12 11:41:31.547  1511  1511 I EdXposed: black/white list mode: true, using whitelist: true 11-12 11:41:31.547  1511  1511 I EdXposed: dynamic modules mode: false 11-12 11:41:31.547  1511  1511 I EdXposed: resources hook: true 11-12 11:41:31.547  1511  1511 I EdXposed: deopt boot image: false 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: com.solohsu.android.edxp.manager 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: org.meowcat.edxposed.manager 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: de.robv.android.xposed.installer 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: com.android.systemui 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: android 11-12 11:41:31.547  1511  1511 I EdXposed: whitelist: org.lineageos.snap 11-12 11:41:31.548  1511  1511 I EdXposed: blacklist: com.android.systemui 11-12 11:41:31.548  1511  1511 I EdXposed: blacklist: android 11-12 11:41:35.911  1511  1511 I EdXposed: EdxpVariant: 1 11-12 11:41:54.742  1512  1512 I EdXposed: EdxpVariant: 1 11-12 19:56:51.218  3248  3248 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.qualcomm.qti.poweroffalarm 11-12 19:56:51.218  3248  3248 E EdXposed: can't access config path, using snapshot white list: /data/user/0/com.qualcomm.qti.poweroffalarm 11-12 20:02:18.001  8114  8114 E EdXposed: can't parse /data/system 11-12 20:03:59.627  8674  8674 E EdXposed: can't parse /data/system]()

**Comment by eebssk1** [comment]
Looks like EdXposed do not even work on your device,It cannot read configs stored in your data  partition.There's no log about your "Torch"

**Comment by florof** [comment]
Hi. For me a same bug in gallery app on 973F with Ambasadii Rom. The little round on left corner disappears when I select a picture but this come greyed.
Without Edexposed activated all is fine...
