### ISSUE TITLE
[BUG] Honor View 10 Android 9.1

### ISSUE THREAD

**Issue by BlueMan1986** [ElderDrivers/EdXposed#392]
**Magisk模块**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: latest

Riru: latest
It does not work on magisk module.. 
Riru works.. 
But after instaling edXposed system want boot... 
Tried both versions of edXposed... Same... 
Honor View 10 Android 9.1

**Comment by JohnGLFour** [comment]
ref #384

**Comment by ecompton59** [comment]
after it doesn't boot you can force restart and flash in twrp then you will boot same happed to me i use yahfa v4471 just flash that some reason that fixes it

**Comment by ecompton59** [comment]
it messed me up i booted to twrp flashed magisk reflashed kernel magisk messes with ramdisk flash kernel after always rebooted to twro flashed edxposed yahfa and it booted

**Comment by kotori2** [comment]
closed as stale
