### ISSUE TITLE
[BUG] 不兼容运动加速器，无效，请修复

### ISSUE THREAD

**Issue by shajia1992** [ElderDrivers/EdXposed#393]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by shajia1992** [comment]
[BUG] 不兼容运动加速器，无效，请修复

**Comment by rxzcums** [comment]
一般是模块适配框架。

**Comment by 2220209876** [comment]
正常使用的
