### ISSUE TITLE
[BUG] EdXposed fail hook WeChat 64-bit version

### ISSUE THREAD

**Issue by AthonAlex** [ElderDrivers/EdXposed#395]
wx模块在Google Play版64位微信7.0.7上完全失效。
WeXposed Module fails hook completely on WeChat 7.0.7 Google Play version 64-bit.
![IMG_20191123_005725](https://user-images.githubusercontent.com/48885928/69444998-6b991b00-0d8c-11ea-9a50-9972e7b6e17c.jpg)

wx模块在国内版64位微信7.0.8上部分失效（有14处适配出错）。
WeXposed Module partial failure hook on WeChat 7.0.8 domestic version 64-bit  (there are 14 adaption errors).
![IMG_20191123_005734](https://user-images.githubusercontent.com/48885928/69445009-6dfb7500-0d8c-11ea-8626-1612b2e2e608.jpg)
![IMG_20191123_005744](https://user-images.githubusercontent.com/48885928/69445015-70f66580-0d8c-11ea-8045-88f75255e747.jpg)

EdXposed:
90.0-v0.4.6.0 beta(4478)(YAHFA)
or 90.0-v0.4.6.0 beta(4478)(SandHook)
Riru:
v19.5

**Comment by JasonKhew96** [comment]
Note: module can find and hook method but the hook won't work, injected function won't be called.

**Comment by ganyao114** [comment]
> Note: module can find and hook method but the hook won't work, injected function won't be called.

what's method? can provide a demo module?

**Comment by AthonAlex** [comment]
I don't know exactly，because there is no log available for analysis.
But I will send you the WechatXposed&nbsp;module as an attachment of the email.

---Original---

**Comment by JasonKhew96** [comment]
> > Note: module can find and hook method but the hook won't work, injected function won't be called.
> 
> what's method? can provide a demo module?

This code won't work. The function is hooked, but it won't invoke the injected code.
![image](https://user-images.githubusercontent.com/29531167/71086873-dd228880-21d5-11ea-820f-a1a342d643cb.png)

Direct hooking Android Activity class works (_Code from Xposed Fingerprint pay GitHub_)
![image](https://user-images.githubusercontent.com/29531167/71087073-42767980-21d6-11ea-8cf0-e2930f1b9ef8.png)

**Comment by Ninlives** [comment]
How do you know the function is hooked? Looks like "onCreate" is inherited from Activity and not overriden in SettingsUI, so Xposed is not able to find and hook the method(Because the method body is not in this class)

**Comment by JasonKhew96** [comment]
> @JasonKhew96 How do you know the function is hooked? Looks like "onCreate" is inherited from Activity and not overriden in SettingsUI, so Xposed is not able to find and hook the method(Because the method body is not in this class)

@Ninlives For this case, it's still throws error (ClassNotFoundError / MethodNotFoundError) normally with wrong method/class name, but didn't throw error with the correct name, so I assumed it's "hooked".
"onCreate" does overridden in SettingsUI. I tried a class that don't have superclass, failed.

**Comment by NewBugger** [comment]
sorry for out-topic speaks.  
if Xprivacylua hooks fine for Wechat playstore v7.0.7+?

**Comment by Ninlives** [comment]
@JasonKhew96 I did some experiment today with this code snippet:
```java
public void handleLoadPackage(final XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {

        if(!("com.tencent.mm".equals(lpparam.packageName)))return;
        try {
            findAndHookMethod(Activity.class, "onCreate", Bundle.class, new XC_MethodHook() {
                @Override
                protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                    if(param.thisObject.getClass().getCanonicalName().equals("com.tencent.mm.plugin.appbrand.ui.AppBrandUI")){
                        log("Created.");
                        ClassLoader loader = param.thisObject.getClass().getClassLoader();
                        log("ClassLoaer: " + loader.toString());
                        log("Same with package: " + (loader == lpparam.classLoader));
                        loader = loader.getParent();
                        while(loader != null){
                            if(loader == lpparam.classLoader){
                                log("Package class loader is one of the parent.");
                                return;
                            }
                            loader = loader.getParent();
                        }
                        log("Package class loader is not one of the parent.");
                    }
                }
            });
        } catch (Throwable e){
            log(e);
        }
```
And here is the log:
```
01-04 14:21:18.037  6710  6710 I EdXposed-Bridge: Created.
01-04 14:21:18.037  6710  6710 I EdXposed-Bridge: ClassLoaer: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/app/com.tencent.mm-u8TzlV4AUyTnt_aDuwvOzw==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.mm-u8TzlV4AUyTnt_aDuwvOzw==/lib/arm64, /data/app/com.tencent.mm-u8TzlV4AUyTnt_aDuwvOzw==/base.apk!/lib/arm64-v8a, /data/user/0/com.tencent.mm/MicroMsg/expansions/com.tencent.mm.expansions/1545/native/lib/arm64-v8a, /system/lib64, /system/product/lib64]]]
01-04 14:21:18.037  6710  6710 I EdXposed-Bridge: Same with package: false
01-04 14:21:18.037  6710  6710 I EdXposed-Bridge: Package class loader is not one of the parent.
```

It turns out that WeChat is using custom classloaders for loading activities, you should inject into not only the package classloader but also the custom classloaders.

Good luck.

**Comment by MlgmXyysd** [comment]
@Ninlives oh shit, tinker hotfix.
Is this fit with Google play application policy?

**Comment by Ninlives** [comment]
@MlprohibitsgmXyysd I'm not familiar with those policy because I have never published product to Google play.
I spend a few minutes checking the official quality guidance, in chapter "Security" Google prohibits apps to dynamically load code from "outside the app's APK". Well, these code are of course inside apk...

**Comment by Ninlives** [comment]
Apparently they are aware of the policy https://github.com/Tencent/tinker/issues/1314
