### ISSUE TITLE
[BUG] 刷入EdXposed后开机停留在logo界面（含日志）

### ISSUE THREAD

**Issue by cs-usst** [ElderDrivers/EdXposed#396]
**什么情况/What happened?**

诺基亚8.1 (android 10)刷入EdXposed后开机停留在logo界面

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

EdXposed
Log-Catcher
Riru-Core

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.5.1_beta(4463) (YAHFA)

Riru:19.5

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[boot-1970-12-29-03-51-17.log](https://github.com/ElderDrivers/EdXposed/files/3890427/boot-1970-12-29-03-51-17.log)
[error-1970-12-29-03-51-17.log](https://github.com/ElderDrivers/EdXposed/files/3890428/error-1970-12-29-03-51-17.log)

**Comment by HxaioH** [comment]
Android 10 可尝试使用 v0.4.6.0 版本模块。

**Comment by cs-usst** [comment]
@HxaioH 
谢谢，实测Android 10下可以使用0.4.6.0版YAHFA EdXposed模块+定制magisk v20.1(20101)
暂时没发现使用上的问题。关闭issue
