### ISSUE TITLE
[BUG] 无法正常使用。

### ISSUE THREAD

**Issue by HxaioH** [ElderDrivers/EdXposed#398]
**什么情况/What happened?**
框架不起作用但显示已激活,SandHook下Manager会出现FC的情况。

**Xposed模块列表/Xposed Module List**
![2019-11-30_11-3-43](https://user-images.githubusercontent.com/40495719/69894886-2020d700-1361-11ea-90f0-76b59cdaf568.PNG)

**Magisk模块列表/Magisk Module List**
![2019-11-30_11-5-1](https://user-images.githubusercontent.com/40495719/69894897-5bbba100-1361-11ea-8aa5-d63743812f2c.PNG)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed:0.4.6.0_beta(4471)(SandHook/YAHFA)
Riru:20.2(20108)

**相关Logcat/Logcat**
[boot-2019-11-30-01-14-41(YAHFA).log](https://github.com/ElderDrivers/EdXposed/files/3906691/boot-2019-11-30-01-14-41.YAHFA.log)
[boot-2019-11-30-01-19-18(SandHook).log](https://github.com/ElderDrivers/EdXposed/files/3906692/boot-2019-11-30-01-19-18.SandHook.log)

**Comment by MlgmXyysd** [comment]
#384
