### ISSUE TITLE
[BUG] Not working on Android 10.0 x86_64 (Google Play) AVD

### ISSUE THREAD

**Issue by andronoob** [ElderDrivers/EdXposed#399]
**什么情况/What happened?**

Although Magisk didn't mount riru-core and riru_edxposed_sandhook properly (https://github.com/topjohnwu/Magisk/issues/2112), I still managed to get them loaded on my Android emulator.

However, the system didn't boot, it just stuck at boot animation. Without EdXposed, the system could boot normally(https://github.com/RikkaApps/Riru/issues/68).

The commands were:
```
su -mm
export LD_LIBRARY_PATH=/sbin/.magisk/mirror/system/lib64
for TARGETDIR in lib lib64;do
  mount -t tmpfs tmpfs /system/$TARGETDIR
  for FILE in /sbin/.magisk/mirror/system/$TARGETDIR/*;do
    BASENAME=$(/sbin/.magisk/busybox/basename $FILE)
    if [ -f $FILE ]; then touch /system/$TARGETDIR/$BASENAME;
    elif [ -d $FILE ];then mkdir /system/$TARGETDIR/$BASENAME; fi
    mount -o bind $FILE /system/$TARGETDIR/$BASENAME
  done
  umount /system/$TARGETDIR/libmemtrack.so
  cp /sbin/.magisk/modules/riru-core/system_x86/$TARGETDIR/libmemtrack.so /system/$TARGETDIR/libmemtrack.so
  cp /sbin/.magisk/mirror/system/$TARGETDIR/libmemtrack.so /system/$TARGETDIR/libmemtrack_real.so
  for BASENAME in libriru_edxp.so libwhale.edxp.so;do
    cp /sbin/.magisk/modules/riru_edxposed_sandhook/system_x86/$TARGETDIR/$BASENAME /system/$TARGETDIR/$BASENAME
  done
done
setprop ctl.restart zygote
```

**Xposed模块列表/Xposed Module List**

Nothing.

**Magisk模块列表/Magisk Module List**

Riru - Core: v19.5

Riru - EdXposed: v0.4.6.0_beta(4471) (SandHook)

Systemless Hosts: 1.0

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.0_beta(4471) (SandHook)

Riru: v19.5

**相关Logcat/Logcat**

[riru-edxp-sandhook.log](https://github.com/ElderDrivers/EdXposed/files/3906758/riru-edxp-sandhook.log)

**Comment by JohnGLFour** [comment]
ref #384

**Comment by andronoob** [comment]
@JohnGLFour I downloaded the edxp zip file directly from https://github.com/ElderDrivers/EdXposed/releases

**Comment by andronoob** [comment]
Tried magisk-EdXposed-SandHook-v0.4.6.0_beta(4478)-release.zip (downloaded from AppVeyor artifacts), still not working, with or without custom magisk.

[tombstones.zip](https://github.com/ElderDrivers/EdXposed/files/3906929/tombstones.zip)

**Comment by andronoob** [comment]
Got original Xposed on Android 7.0 AVD. I have decided to give up on this.

**Comment by youling257** [comment]
you need use v0.4.6.1 (4489)-rtiihway (YAHFA),
you need copy the jar to framework,
edconfig.jar  eddalvikdx.jar  eddexmaker.jar  edxp.jar

the sandhook version missed libsandhook.edxp.so for x86 and x86_64.
