### ISSUE TITLE
Can it support xposed edge？

### ISSUE THREAD

**Issue by Tangweirui2018** [ElderDrivers/EdXposed#40]
Sorry,it is my first time to use it.As a beginner,I hope you can help me with this simple question!I will appreciate it!

**Comment by MlgmXyysd** [comment]
sorry, i don't used edge.you can ask users who used egde.

**Comment by Tangweirui2018** [comment]
Okay, I think I will try it myself, though it may takes mach time...😓

**Comment by zzmdhr** [comment]
edge work on 0.28

**Comment by solohsu** [comment]
Should works with [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)
