### ISSUE TITLE
Screen timeout not working on LGE-V300K

### ISSUE THREAD

**Issue by it-automator** [ElderDrivers/EdXposed#400]
I've installed Riru core and Riru EdXposed. I noticed that my screen does not turn off and stays turned on.
I tried removing both Riru Core and Riru EdXposed then screen timeout worked again.

Setup:

Magisk: 20.1 (20100)
Activated Modules:
Riru - Core v19.5
Riru - EdXposed v0.4.5.1_beta(4463) (YAHFA)

**Comment by smartymcfly** [comment]
Do you have either of the modules, "DIWA" or "hidden code mudule" installed?

This all of sudden started happening to me and it works again now after I removed these modules.  

Another problem it was causing is that any chrome browser, Dev, beta, canary, etc.... Would open and force close.  It also fixed this.

Kiwi and brave were not force closing.

**Comment by it-automator** [comment]
Hi,

I only have the Hidden Core module. However prior to installing this module
I already have that problem.
Didn't have problem with chrome though.

Kind regards.

**Comment by marios4code** [comment]
This is still happening with LG-V30. Screen timeout doesn't take effect (screen stays on).
Riru-core is fine, but HiddenCoreModule is causing the issue in my case.

**Comment by it-automator** [comment]
Yes, I also figured that HiddenCoreModules makes the screen timeout
ineffective. I no longer use Xposed anyway.

**Comment by carstenk70** [comment]
the same problem i have with my lenovo zuk z2 pro.
i tried to reinstall and checked timeout because my batterie was empty all the time and checked allway the timeout...
after installing the hiddencoremodul in xposed i faced this problem and after disabling this modul the display timeout is working again
but both net savety checkboxes are red.

is the a timeoutfix available allready...

carsten with aosp 10 magisk xposed xpivacylua

**Comment by Npvietkhoa** [comment]
You guys are right! After disable HiddenCore module in Edxposed, my screen timeout works again like a charm but Safety Net trips again!!

**Comment by JasonKhew96** [comment]
> You guys are right! After disable HiddenCore module in Edxposed, my screen timeout works again like a charm but Safety Net trips again!!

@Npvietkhoa dont' use HiddenCore, it's totally BS, it just change the response from server, fake value by changing the reading of json parsing function.
![image](https://user-images.githubusercontent.com/29531167/82184694-a2568500-991a-11ea-815c-0dec792617d9.png)

and @it-automator please close this, it's no longer an issue, thanks.

**Comment by it-automator** [comment]
Closing the ticket.
