### ISSUE TITLE
Cannot hook WeChat 7.0.7+ with WeXposed provisional solution

### ISSUE THREAD

**Issue by MlgmXyysd** [ElderDrivers/EdXposed#401]
无法在微信707（play商店版）使用微X模块的暂行解决办法

install V++ module

安装V++模块

![image](https://user-images.githubusercontent.com/17919858/69960404-4f436e00-1544-11ea-82db-8d0da44c03d8.png)

**Comment by MlgmXyysd** [comment]
玄学操作不懂，709国内版和64位都可以解决
7.0.9 and 64-bit apply equally

**Comment by JasonKhew96** [comment]
#395 duplicate

**Comment by MlgmXyysd** [comment]
Fixed in WeXposed 2.7
