### ISSUE TITLE
[BUG] modules.list 不存在

### ISSUE THREAD

**Issue by IPlayForHer** [ElderDrivers/EdXposed#402]
**什么情况/What happened?**
xposed模块全部不生效

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
riru
edxp
storage redirect
允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:4.6.0(4478)

Riru:19.5

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
12-21 11:49:43.053   708   708 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
12-04 17:32:50.055   951   951 E EdXposed: mmap failed, errno = Permission denied
12-04 17:32:50.055   951   951 E EdXposed: cannot hook method
12-04 17:32:50.056   951   951 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
12-04 17:32:50.056   951   951 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
12-04 17:32:50.056   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3097)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
12-04 17:32:50.056   951   951 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:609)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:494)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:349)
12-04 17:32:50.056   951   951 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-04 17:32:50.056   951   951 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
12-04 17:32:52.130   951   951 E EdXposed: mmap failed, errno = Permission denied
12-04 17:32:52.130   951   951 E EdXposed: cannot hook method
12-04 17:32:52.130   951   951 E EdXposed: error occur when generating dex. dexDir=null
12-04 17:32:52.130   951   951 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
12-04 17:32:52.130   951   951 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
12-04 17:32:52.130   951   951 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
12-04 17:32:52.130   951   951 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
12-04 17:32:52.130   951   951 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2309)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2252)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2223)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2183)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2170)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6942)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
12-04 17:32:52.130   951   951 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7169)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:7553)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:982)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:512)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:349)
12-04 17:32:52.130   951   951 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-04 17:32:52.130   951   951 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
--------- beginning of crash
12-04 17:33:21.770   709   709 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
12-04 17:33:48.287  9009  9009 I EdXposedManager: ModuleUtil -> updating modules.list

**Comment by IPlayForHer** [comment]
手动去那个文件夹创建一个就行了。。。

**Comment by IPlayForHer** [comment]
`touch /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list`
不知道权限要多少直接给777的
`chmod 777 /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list`

**Comment by MlgmXyysd** [comment]
mmap failed, errno = Permission denied
#384

**Comment by MlgmXyysd** [comment]
mmap failed, errno = Permission denied
#384
