### ISSUE TITLE
[BUG] SandHook 工作异常。

### ISSUE THREAD

**Issue by HxaioH** [ElderDrivers/EdXposed#403]
**什么情况/What happened?**
导致 EdXposed 出现 FC 。
导致 Chrome 无法正常使用。
Xposed 模块功能正常。

**Xposed模块列表/Xposed Module List**
![Screenshot_20191208-045454](https://user-images.githubusercontent.com/40495719/70387768-34735e00-1977-11ea-8711-0ed6b3d671b5.png)

**Magisk模块列表/Magisk Module List**
![2019-12-8_4-54-5](https://user-images.githubusercontent.com/40495719/70387770-3fc68980-1977-11ea-966e-a070b281b2f5.PNG)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: v0.4.6.0_beta(4471)(SandHook)
Riru: v19.5

**相关Logcat/Logcat**
[boot-2019-12-08-09-51-34.log](https://github.com/ElderDrivers/EdXposed/files/3936075/boot-2019-12-08-09-51-34.log)

**Comment by MlgmXyysd** [comment]
chrome和webview建议添加黑名单

**Comment by HxaioH** [comment]
EdXposed Manager 出现 FC 是否有解决方案？

**Comment by MlgmXyysd** [comment]
> EdXposed Manager 出现 FC 是否有解决方案？

需要crash的trace上下文日志

**Comment by HxaioH** [comment]
卸载 YAHFA 再安装 SandHook 后无进行其他操作且未出现异常问题。（玄学
