### ISSUE TITLE
恢復使用 supolicy 指令會造成任何 service.sh 無法被 Magisk 運行

### ISSUE THREAD

**Issue by i1itione** [ElderDrivers/EdXposed#404]
**什么情况/What happened?**

將 post-fs-data.sh 裡現已註解掉的 supolicy 指令取消註解後，會造成任何 Magisk 模組的 service.sh 無法被運行。

之所以希望這麼做主要是因為 Magisk 20.1 的 custom build 無法在我的裝置上正常使用，因此為了在原始版本的 Magisk 20.1 使用目前最新的 EdXposed，還是需要搭配 supolicy 指令。

請問這是 EdXposed 所需的 supolicy 指令會造成 Magisk 出現異常，又或者是 Magisk 本身的異常呢？

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.0

Riru: v19.5

**相关Logcat/Logcat**

**Comment by MlgmXyysd** [comment]
magisk本身问题，等Magisk官方下一版本更新supolicy相关内容
