### ISSUE TITLE
[BUG] 一加7p新系统无法工作，貌似是权限有问题

### ISSUE THREAD

**Issue by qtiuto** [ElderDrivers/EdXposed#409]
**什么情况/What happened?**
模块无效

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:4.6

Riru:19.5

**相关Logcat/Logcat**
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QKQ1.190716.003
Fingerprint: OnePlus/OnePlus7Pro_CH/OnePlus7Pro:10/QKQ1.190716.003/1911250200:user/release-keys
ROM build description: OnePlus7Pro-user 10 QKQ1.190716.003 1911250200 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: OnePlus7Pro
Manufacture: OnePlus
Brand: OnePlus
Product: OnePlus7Pro
--------- beginning of main
--------- beginning of system
12-12 23:19:15.314   771   771 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-12 23:19:15.314   771   771 I EdXposed: Start to install inline hooks
12-12 23:19:15.314   771   771 I EdXposed: Using api level 29
12-12 23:19:15.314   771   771 I EdXposed: Start to install Riru hook
12-12 23:19:15.324   771   771 I EdXposed: Riru hooks installed
12-12 23:19:15.390   772   772 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-12 23:19:15.390   772   772 I EdXposed: Start to install inline hooks
12-12 23:19:15.390   772   772 I EdXposed: Using api level 29
12-12 23:19:15.390   772   772 I EdXposed: Start to install Riru hook
12-12 23:19:15.400   772   772 I EdXposed: Riru hooks installed
12-12 23:19:15.405   771   771 I EdXposed: ART hooks installed
12-12 23:19:15.405   771   771 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-12 23:19:15.405   771   771 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-12 23:19:15.531   772   772 I EdXposed: ART hooks installed
12-12 23:19:15.532   772   772 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-12 23:19:15.532   772   772 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-12 23:19:15.629   771   771 I EdXposed: using installer com.solohsu.android.edxp.manager
12-12 23:19:15.629   771   771 I EdXposed: black/white list mode: false, using whitelist: false
12-12 23:19:15.629   771   771 I EdXposed: dynamic modules mode: false
12-12 23:19:15.629   771   771 I EdXposed: resources hook: true
12-12 23:19:15.629   771   771 I EdXposed: deopt boot image: false
12-12 23:19:15.743   772   772 I EdXposed: using installer com.solohsu.android.edxp.manager
12-12 23:19:15.743   772   772 I EdXposed: black/white list mode: false, using whitelist: false
12-12 23:19:15.743   772   772 I EdXposed: dynamic modules mode: false
12-12 23:19:15.743   772   772 I EdXposed: resources hook: true
12-12 23:19:15.743   772   772 I EdXposed: deopt boot image: false
12-12 23:19:17.653   771   771 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found
12-12 23:19:17.930  1471  1471 E EdXposed: mmap failed, errno = Permission denied
12-12 23:19:17.930  1471  1471 E EdXposed: cannot hook method
12-12 23:19:17.932  1471  1471 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
12-12 23:19:17.932  1471  1471 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3088)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:637)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:522)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
12-12 23:19:17.932  1471  1471 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
12-12 23:19:20.245  1471  1471 E EdXposed: mmap failed, errno = Permission denied
12-12 23:19:20.245  1471  1471 E EdXposed: cannot hook method
12-12 23:19:20.245  1471  1471 E EdXposed: error occur when generating dex. dexDir=null
12-12 23:19:20.245  1471  1471 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2413)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2356)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2327)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2217)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7208)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7495)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8392)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1013)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:540)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
12-12 23:19:20.245  1471  1471 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
--------- beginning of crash
12-12 23:19:30.672   772   772 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
#384
