### ISSUE TITLE
[BUG] 应用控制器，进程锁等 无法开机

### ISSUE THREAD

**Issue by zerofo** [ElderDrivers/EdXposed#41]
应用控制器，进程锁等 无法开机。

V10 + 0.28 可以开机的，模块启动也是正常的。

之后的版本 无论多个模块启动还是独立都卡开机。

**Comment by zerofo** [comment]
Android 9.0.3 第三方rom

**Comment by singleNeuron** [comment]
同样无法开机

**Comment by zerofo** [comment]
有解吗???? @solohsu @MlgmXyysd

**Comment by solohsu** [comment]
Try [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)

**Comment by zerofo** [comment]
可以了

**Comment by singleNeuron** [comment]
工作正常，作者辛苦了2019年2月12日 02:18，solohsu <notifications@github.com>写道：Try v0.2.9.8_beta1
