### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ffuser1** [ElderDrivers/EdXposed#410]
I can't get edxposed to work on my newly upgraded pixel 3 xl. Now with Dec 2019 android Q

Here's my logcat. Logcat is also attached, which might be easier to read. What do I do about the file that is missing?

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QQ1A.191205.008
Fingerprint: google/crosshatch/crosshatch:10/QQ1A.191205.008/5974827:user/release-keys
ROM build description: crosshatch-user 10 QQ1A.191205.008 5974827 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: crosshatch
Manufacture: Google
Brand: google
Product: crosshatch
--------- beginning of main
--------- beginning of system
12-14 01:57:02.464   972   972 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-14 01:57:02.464   972   972 I EdXposed: Start to install inline hooks
12-14 01:57:02.464   972   972 I EdXposed: Using api level 29
12-14 01:57:02.464   972   972 I EdXposed: Start to install Riru hook
12-14 01:57:02.470   972   972 I EdXposed: Riru hooks installed
12-14 01:57:02.582   972   972 I EdXposed: ART hooks installed
12-14 01:57:02.582   972   972 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-14 01:57:02.582   972   972 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-14 01:57:02.865   973   973 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-14 01:57:02.865   973   973 I EdXposed: Start to install inline hooks
12-14 01:57:02.865   973   973 I EdXposed: Using api level 29
12-14 01:57:02.865   973   973 I EdXposed: Start to install Riru hook
12-14 01:57:02.874   973   973 I EdXposed: Riru hooks installed
12-14 01:57:02.964   973   973 I EdXposed: ART hooks installed
12-14 01:57:02.964   973   973 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-14 01:57:02.965   973   973 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-14 01:57:02.969   972   972 I EdXposed: using installer org.meowcat.edxposed.manager
12-14 01:57:02.969   972   972 I EdXposed: black/white list mode: false, using whitelist: false
12-14 01:57:02.969   972   972 I EdXposed: dynamic modules mode: false
12-14 01:57:02.969   972   972 I EdXposed: resources hook: true
12-14 01:57:02.969   972   972 I EdXposed: deopt boot image: false
12-14 01:57:03.127   973   973 I EdXposed: using installer org.meowcat.edxposed.manager
12-14 01:57:03.127   973   973 I EdXposed: black/white list mode: false, using whitelist: false
12-14 01:57:03.127   973   973 I EdXposed: dynamic modules mode: false
12-14 01:57:03.127   973   973 I EdXposed: resources hook: true
12-14 01:57:03.127   973   973 I EdXposed: deopt boot image: false
12-14 01:57:04.515   972   972 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
12-14 01:57:04.758  1489  1489 E EdXposed: mmap failed, errno = Permission denied
12-14 01:57:04.759  1489  1489 E EdXposed: cannot hook method
12-14 01:57:04.759  1489  1489 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
12-14 01:57:04.759  1489  1489 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3088)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:610)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:495)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:350)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-14 01:57:04.759  1489  1489 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
12-14 01:57:06.500  1489  1489 E EdXposed: mmap failed, errno = Permission denied
12-14 01:57:06.501  1489  1489 E EdXposed: cannot hook method
12-14 01:57:06.501  1489  1489 E EdXposed: error occur when generating dex. dexDir=null
12-14 01:57:06.501  1489  1489 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2309)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2252)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2223)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2183)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2170)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6942)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7169)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:7555)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:983)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:513)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:350)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-14 01:57:06.501  1489  1489 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
--------- beginning of crash
12-14 01:57:16.598   973   973 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by MlgmXyysd** [comment]
mmap failed, errno = Permission denied
#384
