### ISSUE TITLE
新问题，无法hook hide方法[BUG] 

### ISSUE THREAD

**Issue by huacangliang** [ElderDrivers/EdXposed#412]
我对application进行了hook，发现attch方法hook的时候无报错行为，就是执行的时候没有回调

**Comment by kotori2** [comment]
这东西不是edxp已经hook过一次了吗。。？

**Comment by huacangliang** [comment]
> 这东西不是edxp已经hook过一次了吗。。？

还是不行的，后面改成hook其它函数了

**Comment by yujincheng08** [comment]
调用模块时候就已经运行完attach了吧

**Comment by kotori2** [comment]
> 还是不行的，后面改成hook其它函数了

对的，就是这个意思，因为EdXposed已经hook过一次了所以不能hook第二次。
所以如果以后真的有需要，可以考虑由EdXposed提供API。
建议换别的入口hook，比如`createSystemContext`
