### ISSUE TITLE
[BUG] module doesn't load on Android 10 Samsung note 9 /note 10

### ISSUE THREAD

**Issue by DrKetan** [ElderDrivers/EdXposed#413]
**什么情况/What happened?**
Module doesn't load. No error but module not working and log shoeing module doesn't load 
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:4.6.0

Riru:

**相关Logcat/Logcat**
[CODE] 
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QP1A.190711.020
Fingerprint: samsung/d2sxx/d2s:10/QP1A.190711.020/N975FXXU1BSL7:user/release-keys
ROM build description: d2sxx-user 10 QP1A.190711.020 N975FXXU1BSL7 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: d2s
Manufacture: samsung
Brand: samsung
Product: d2s
--------- beginning of main
--------- beginning of system
12-19 01:18:06.508  5498  5498 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-19 01:18:06.508  5498  5498 I EdXposed: Start to install inline hooks
12-19 01:18:06.508  5498  5498 I EdXposed: Using api level 29
12-19 01:18:06.508  5498  5498 I EdXposed: Start to install Riru hook
12-19 01:18:06.528  5498  5498 I EdXposed: Riru hooks installed
12-19 01:18:06.540  5499  5499 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-19 01:18:06.540  5499  5499 I EdXposed: Start to install inline hooks
12-19 01:18:06.540  5499  5499 I EdXposed: Using api level 29
12-19 01:18:06.540  5499  5499 I EdXposed: Start to install Riru hook
12-19 01:18:06.559  5499  5499 I EdXposed: Riru hooks installed
12-19 01:18:06.561  5498  5498 I EdXposed: ART hooks installed
12-19 01:18:06.561  5498  5498 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-19 01:18:06.561  5498  5498 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-19 01:18:06.586  5499  5499 I EdXposed: ART hooks installed
12-19 01:18:06.587  5499  5499 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-19 01:18:06.587  5499  5499 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-19 01:18:06.702  5498  5498 I EdXposed: using installer com.solohsu.android.edxp.manager
12-19 01:18:06.703  5498  5498 I EdXposed: black/white list mode: false, using whitelist: false
12-19 01:18:06.703  5498  5498 I EdXposed: dynamic modules mode: false
12-19 01:18:06.703  5498  5498 I EdXposed: resources hook: true
12-19 01:18:06.703  5498  5498 I EdXposed: deopt boot image: false
12-19 01:18:06.704  5499  5499 I EdXposed: using installer com.solohsu.android.edxp.manager
12-19 01:18:06.704  5499  5499 I EdXposed: black/white list mode: false, using whitelist: false
12-19 01:18:06.704  5499  5499 I EdXposed: dynamic modules mode: false
12-19 01:18:06.704  5499  5499 I EdXposed: resources hook: true
12-19 01:18:06.704  5499  5499 I EdXposed: deopt boot image: false
12-19 01:18:13.643  5498  5498 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found
12-19 01:18:20.985  5499  5499 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/com.solohsu.android.edxp.manager/conf/modules.list was not found
--------- beginning of crash

[/Code] 
有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by DrKetan** [comment]
Sorry, just found it requires recommended version of magisk. Tried it and worked like a charm.

**Comment by DrKetan** [comment]
Hi
Re-opening again
Tested with newer magisk (recommended 20.1) worked on Note9 but It doesn't solve on Note10 (SAR)

**Comment by DrKetan** [comment]
I can confirm magisk-EdXposed-YAHFA-v0.4.6.0_beta(4477)-release.zip is working with recommended magisk file on Note10 too.

**Comment by amakuramio** [comment]
@DrKetan  how did u get it working? on s9+ if i flash howards one, i get a bootloop, to download mode
which magisk version did u use? the magisk from solohsu doesnt work, it says not rooted

**Comment by usamaiqbal1177** [comment]
There are two magisk (normal/canary and custom solohsu magisk) and two EdXposed versions (normal EdXposed found on this elder driver github and canary edxposed found on solohsu github.... Try out different combinations or these 4 and see which one works for u.... In my one phone, normal magisk with normal edxposed works fine, while in other, solohsu magisk with canary edxposed works fine. Try it out yourself.

**Comment by MlgmXyysd** [comment]
The two EdXposed custom Magisk you said are the same

**Comment by amakuramio** [comment]
s9+ android 10
patched solohsu magisk 20.1 = no root
patched solohsu magisk 19.3, no boot
custom sepolicy by rikkaapps, bootloop, system unable to rw, need reflash entire rom and reset, or disable magisk
custom sepolicy patched by howard, bootloop, system unable to rw, need reflash entire rom and reset, or disable magisk
normal canary magisk 20.2, root works, edxposed works, no modules
now what

**Comment by MlgmXyysd** [comment]
@amakuramio well, Magisk 20.2 will support custom sepolicy

**Comment by amakuramio** [comment]
@MlgmXyysd then how do i get it working i dont wanna downgrade to pie again

**Comment by MlgmXyysd** [comment]
@amakuramio wait Magisk 20.2 to stabilize or use official canary Magisk

**Comment by amakuramio** [comment]
@MlgmXyysd can you give me a link

**Comment by amakuramio** [comment]
Any other magisk than 20.2 causes magisk manager app to freeze, cant open it, and no root found

**Comment by usamaiqbal1177** [comment]
Don't use EdXposed installer. Use EdXposed manager. Install manager apk first.
Completely uninstall magisk from uninstaller zip
Download and flash this solohsu magisk (https://github.com/topjohnwu/Magisk/releases)
And open manager app and navigate to EdXposed canary tab. Download the canary EdXposed from there. It's name should be "magisk-EdXposed-YAHFA-v0.4.6.0_beta(4478)-release.zip" notice the bracket in the name! Use this canary EdXposed with that custom magisk 20.1 and manager apk. Try this and tell

**Comment by ianmacd** [comment]
> @amakuramio wait for Magisk 20.2 to stabilize or use official canary Magisk

I built Magisk myself with commit 12fda2928051601ebc7fac980fae29a80e7979cc, which is the one that adds support for pre-init custom sepolicy patches, and this *still* doesn't allow EdXposed 0.4.6.0_beta(4481) to load modules.

These latest EdXposed betas are clearly still targeting the mechanism they implemented and proposed in issue 1685 on the Magisk repo and need to be altered to be compliant with the way John has now actually implemented the feature.

**Comment by amakuramio** [comment]
@ianmacd nothing worked for me so I downgraded to pie again, having to reset all :(
On pie only custom magisk 19.3 works,

**Comment by describe19** [comment]
Try this:

Fully uninstall whatever magisk you are using with uninstall zip or full uninstall in magisk manager (or reflash rom to remove).


Flash custom solohsu 20.1 build in twrp. (Idk why root wouldn't work, it should work)

In magisk manager install riru core.

Download ElderDriver's edxposed manager. Go to canary tab and download latest canary build (4481 as of writing).

Add to modules in MM and reboot.

If it doesn't work try the ordinary beta edxposed.
Make sure to try all 4 zips:
Sandhook/yahfa of both canary and beta builds.

Hopefully something works for you.

**Comment by ianmacd** [comment]
> Try this:
> 
> Fully uninstall whatever magisk you are using with uninstall zip or full uninstall in magisk manager (or reflash rom to remove).
> 
> Flash custom solohsu 20.1 build in twrp. (Idk why root wouldn't work, it should work)
> 
> In magisk manager install riru core.
> 
> Download ElderDriver's edxposed manager. Go to canary tab and download latest canary build (4481 as of writing).
> 
> Add to modules in MM and reboot.
> 
> If it doesn't work try the ordinary beta edxposed.
> Make sure to try all 4 zips:
> Sandhook/yahfa of both canary and beta builds.
> 
> Hopefully something works for you.

I've tried the betas and canaries of both Yahfa and Sandhook, and all of them have the same SELinux context issue with reading the module list. The common factor is Magisk itself.

John Wu added support for pre-init custom sepolicy patches in commit 12fda2928051601ebc7fac980fae29a80e7979cc on 13th December, but that doesn't work for EdXposed, so John must have implemented it slightly differently to how the EdXposed author intended.

As a last resort, I tried the custom 20.1 build of Magisk provided by solohsu, but that version comes up unrooted on my Note10+ running Android 10.

So, I'm currently out of options for the time being.

**Comment by ianmacd** [comment]
> @ianmacd nothing worked for me so I downgraded to pie again, having to reset all :(
> On pie only custom magisk 19.3 works,

On Pie, all betas of 0.4.6.0 caused a bootloop for me with the HEAD of Magisk. On Android 10, they all boot, but none can load the module list.

**Comment by describe19** [comment]
Strange, I'm on Android Q and managed to get it working fine. To be fair though I'm on an aosp rom not Samsung, so maybe that's the issue.

**Comment by amakuramio** [comment]
@describe19 offtopic: how is the video stabilization of aosp camera? gcam port? haha

**Comment by ianmacd** [comment]
I'm wondering at this point 

> Strange, I'm on Android Q and managed to get it working fine. To be fair though I'm on an aosp rom not Samsung, so maybe that's the issue.

I found that build 4477 **does** work for me, but 4481 does not. So long as I use 4477, both Yahfa and Sandhook variants work.

This is using my own build of Magisk.

**Comment by yomyself** [comment]
> 
> 
> I'm wondering at this point
> 
> > Strange, I'm on Android Q and managed to get it working fine. To be fair though I'm on an aosp rom not Samsung, so maybe that's the issue.
> 
> I found that build 4477 **does** work for me, but 4481 does not. So long as I use 4477, both Yahfa and Sandhook variants work.
> 
> This is using my own bleeding edge build of Magisk, compiled from the head of the master branch.

I have the same issue, only 4477 works with Q but I use official Magisk release

**Comment by describe19** [comment]
I am using solohsu's latest 20.1 build + magisk-EdXposed-SandHook-v0.4.6.3_beta.Justins.Fork.-release.zip

from here (to avoid snapchat bans)

**Comment by amakuramio** [comment]
So I go back to pie and suddenly someone has a new solution.  Great.

**Comment by amakuramio** [comment]
Can the OP try no custom magisk version plus official 20.2 canary?

**Comment by amakuramio** [comment]
> I'm wondering at this point
> 
> > Strange, I'm on Android Q and managed to get it working fine. To be fair though I'm on an aosp rom not Samsung, so maybe that's the issue.
> 
> I found that build 4477 **does** work for me, but 4481 does not. So long as I use 4477, both Yahfa and Sandhook variants work.
> 
> This is using my own bleeding edge build of Magisk, compiled from the head of the master branch.

Can you share the magisk you compiled?

**Comment by amakuramio** [comment]
Seems like this solution works https://github.com/Juxstin/EdXposed-SnapChat-Bypass/issues/9
Use sand hook justin no custom magisk and standard canary I think

**Comment by amakuramio** [comment]
tried it again, none of those versions work on s9, just boots me to twrp with selinux patched edexposed, same for justins fork

**Comment by amakuramio** [comment]
on android q aosp: only magisk-EdXposed-SandHook-v0.4.6.3_beta.Justins.Fork.-release.zip + canary 20.2 work normally

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd can you give me a link
Update channel:
https://github.com/topjohnwu/magisk_files/raw/canary/debug.json

**Comment by deluxor** [comment]
@DrKetan working like a charm with your ROM on my Note10+
 
![Screenshot_20191225-124154](https://user-images.githubusercontent.com/5440296/71445734-30d02d00-2714-11ea-9944-72c1cc740a6e.jpg)

![Screenshot_20191225-124215_Settings](https://user-images.githubusercontent.com/5440296/71445739-3c235880-2714-11ea-996f-26100f72e2c3.jpg)

**Comment by alroy214** [comment]
Does it work with any modules that attach to system process? I.e. Xposed edge, Greenify and so?
I think there is a problem here...

**Comment by ianmacd** [comment]
> Does it work with any modules that attach to system process? I.e. Xposed edge, Greenify and so?
> I think there is a problem here...

I think you're right. Greenify isn't working here (in Boost mode).

**Comment by alroy214** [comment]
> > Does it work with any modules that attach to system process? I.e. Xposed edge, Greenify and so?
> > I think there is a problem here...
> 
> I think you're right. Greenify isn't working here (in Boost mode).

Should we open a new issue? I don't think it's a pair app error and it's an exposed issue that's going on with those apps (in Samsung Android 10)

**Comment by MlgmXyysd** [comment]
@ianmacd ask Greenify author?

**Comment by MlgmXyysd** [comment]
@ianmacd Greenify test passed i think you should provide log...

http://t.me/code_of_meowcat

**Comment by alroy214** [comment]
> @ianmacd ask Greenify author?

It's also in Xposed Edge and in the system process in GravityBox, I don't think it's a pair app issue.
I think something is wrong with system hooking in EdXposed itself.

**Comment by alroy214** [comment]
@MlgmXyysd what EdXposed version are you using?

**Comment by MlgmXyysd** [comment]
@alroy214 legacy, it can always be used

**Comment by alroy214** [comment]
> > Does it work with any modules that attach to system process? I.e. Xposed edge, Greenify and so?
> > I think there is a problem here...
> 
> I think you're right. Greenify isn't working here (in Boost mode).

Are you on Samsung Android 10?
I think this problem only effects One UI 2.0 users

**Comment by ianmacd** [comment]
> Are you on Samsung Android 10?
> I think this problem only effects One UI 2.0 users

Yes, Android 10 on a Note10+. Build 4477 of Sandhook. The latest build, 4481, doesn't work at all for me.

**Comment by alroy214** [comment]
> > Are you on Samsung Android 10?
> > I think this problem only effects One UI 2.0 users
> 
> Yes, Android 10 on a Note10+. Build 4477 of Sandhook. The latest build, 4481, doesn't work at all for me.

Think we should open a new issue on what's happening?

**Comment by amakuramio** [comment]
Probably a security thing strongly resisting permissive
On s9 series any patched selinux exposed makes  data read only then boot to twrp 
And only 20.2 will root the device

**Comment by alroy214** [comment]
> Probably a security thing strongly resisting permissive
> On s9 series any patched selinux exposed makes data read only then boot to twrp
> And only 20.2 will root the device

You can root the device but a lot of modules won't work, and it's also in the S10 and Notes

**Comment by MlgmXyysd** [comment]
@alroy214 sure

**Comment by amakuramio** [comment]
tried new 20.2 canary with selinux patch:
4481 sandhook: not working (modules.list)
justins build: not working
justins non magisk build: straight to twrp
howards custom build: straight to twrp
4477 beta sandhook: not working

**Comment by describe19** [comment]
[edxposed-4481-y-sp.zip](https://github.com/ElderDrivers/EdXposed/files/4008003/edxposed-4481-y-sp.zip)
Try this with latest canary. Works fine for me.

**Comment by amakuramio** [comment]
> [edxposed-4481-y-sp.zip](https://github.com/ElderDrivers/EdXposed/files/4008003/edxposed-4481-y-sp.zip)
> Try this with latest canary. Works fine for me.

Boots normally, but not working

**Comment by MlgmXyysd** [comment]
@amakuramio Magisk Canary 20.2?
Check channel for more infonation: http://t.me/edxposed

**Comment by amakuramio** [comment]
> @amakuramio Magisk Canary 20.2?
> Check channel for more infonation: http://t.me/edxposed

Yes the latest magisk, doesn't work
![IMG_20191229_190312_689](https://user-images.githubusercontent.com/6065170/71560763-37d9a100-2a6e-11ea-8cc3-4de2a5adb9fb.jpg)
![IMG_20191229_190339_947](https://user-images.githubusercontent.com/6065170/71560764-37d9a100-2a6e-11ea-8b6f-bd29f3e26ab9.jpg)

**Comment by MlgmXyysd** [comment]
@amakuramio Samsung OneUI 2.0 Android 10?

**Comment by amakuramio** [comment]
It works now with latest canary, need to compile yourself.https://github.com/ElderDrivers/EdXposed/issues/379 but many apps won't load, many crashes.

**Comment by MlgmXyysd** [comment]
@amakuramio samsung oem known issues, not this

**Comment by THEBOSS619** [comment]
So... any known method for having Edxposed for Note 9 Android 10? please let me know :) already on Magisk 20.2

**Comment by amakuramio** [comment]
> So... any known method for having Edxposed for Note 9 Android 10? please let me know :) already on Magisk 20.2

20.3 plus latest edxposed from the app, use canary
Just many modules won't work, so if you can find an AOSP rom go for it

**Comment by MlgmXyysd** [comment]
Known Riru issue: https://github.com/RikkaApps/Riru/issues/69 https://github.com/RikkaApps/Riru/issues/73 https://github.com/RikkaApps/Riru/issues/75
