### ISSUE TITLE
[BUG] MIUI11 安卓10 安装后无法开机

### ISSUE THREAD

**Issue by Disappear9** [ElderDrivers/EdXposed#414]
**什么情况/What happened?**

安装EdXposed模块后无法开机，已尝试使用custom Magisk，关闭SELinux
机型：红米K20 PRO
MIUI版本：11.0.3（MiRoom）

**Magisk模块列表/Magisk Module List**

mm
Riru Core
EdXposed Sandhook

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.4.6.0_beta

Riru:v19.5

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by 168308711q** [comment]
小米9安卓q一出来时就安装过ED了

**Comment by Howard20181** [comment]
使用custom magisk 就不用关闭selinux 了

**Comment by Disappear9** [comment]
> 使用custom magisk 就不用关闭selinux 了

custom magisk+sandhook
custom magisk+YAHFA
原版magisk+sandhook
原版magisk+YAHFA
原版magisk+sandhook+selinux off
原版magisk+YAHFA+selinux off

都试了一遍的我表示......

**Comment by kooritea** [comment]
K 20pp miui11.2(xiaomi.eu)同样的问题
EdXposed:v0.4.6.0_beta YAHFA
Riru:v19.5

删除模块后正常恢复

**Comment by Howard20181** [comment]
试试使用Magisk 20.2+sepolicyTest版本

**Comment by kooritea** [comment]
0.4.6_4482 YAHFA 可以成功开机！
安装了绿色守护模块，暂时没有发现其他问题

**Comment by Disappear9** [comment]
0.4.6_4482 sandhook 可以开机，目前暂未发现问题

**Comment by greenhat616** [comment]
OnePlus H2OS(Based on Android 10) has this issue too.
