### ISSUE TITLE
[BUG] Modules that use system process won't load on Galaxy Android 10

### ISSUE THREAD

**Issue by alroy214** [ElderDrivers/EdXposed#416]
**什么情况/What happened?**
If an app uses system process it won't load on Galaxy with Android 10 One UI 2.0

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Xposed Edge
Greenify

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: all of them

Riru: 19.5

**相关Logcat/Logcat**

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QP1A.190711.020
Fingerprint: samsung/beyond1ltexx/beyond1:10/QP1A.190711.020/G973FXXU3BSKO:user/release-keys
ROM build description: beyond1ltexx-user 10 QP1A.190711.020 G973FXXU3BSKO release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: beyond1
Manufacture: samsung
Brand: samsung
Product: beyond1lte
--------- beginning of main
--------- beginning of system
12-26 04:42:06.473  5364  5364 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-26 04:42:06.473  5364  5364 I EdXposed: Start to install inline hooks
12-26 04:42:06.473  5364  5364 I EdXposed: Using api level 29
12-26 04:42:06.473  5364  5364 I EdXposed: Start to install Riru hook
12-26 04:42:06.489  5364  5364 I EdXposed: Riru hooks installed
12-26 04:42:06.548  5364  5364 I EdXposed: ART hooks installed
12-26 04:42:06.549  5364  5364 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-26 04:42:06.549  5364  5364 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-26 04:42:06.593  5365  5365 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-26 04:42:06.593  5365  5365 I EdXposed: Start to install inline hooks
12-26 04:42:06.593  5365  5365 I EdXposed: Using api level 29
12-26 04:42:06.593  5365  5365 I EdXposed: Start to install Riru hook
12-26 04:42:06.611  5365  5365 I EdXposed: Riru hooks installed
12-26 04:42:06.643  5365  5365 I EdXposed: ART hooks installed
12-26 04:42:06.644  5365  5365 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
12-26 04:42:06.644  5365  5365 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
12-26 04:42:06.685  5364  5364 I EdXposed: using installer org.meowcat.edxposed.manager
12-26 04:42:06.686  5364  5364 I EdXposed: black/white list mode: false, using whitelist: false
12-26 04:42:06.686  5364  5364 I EdXposed: dynamic modules mode: false
12-26 04:42:06.686  5364  5364 I EdXposed: resources hook: true
12-26 04:42:06.686  5364  5364 I EdXposed: deopt boot image: false
12-26 04:42:06.747  5365  5365 I EdXposed: using installer org.meowcat.edxposed.manager
12-26 04:42:06.747  5365  5365 I EdXposed: black/white list mode: false, using whitelist: false
12-26 04:42:06.747  5365  5365 I EdXposed: dynamic modules mode: false
12-26 04:42:06.747  5365  5365 I EdXposed: resources hook: true
12-26 04:42:06.747  5365  5365 I EdXposed: deopt boot image: false
12-26 04:42:14.522  5364  5364 I EdXposed-Bridge: Loading modules from /data/app/com.alex193a.gmdtenabler-3cryFEpPykhfRv2PETlrkg==/base.apk
12-26 04:42:14.529  5364  5364 I EdXposed-Bridge:   Loading class com.alex193a.gmdtenabler.Module
12-26 04:42:14.531  5364  5364 I EdXposed-Bridge: Loading modules from /data/app/com.alex193a.psdtenabler-4bmcrKEK6D-QY3ICzhAU6g==/base.apk
12-26 04:42:14.536  5364  5364 I EdXposed-Bridge:   Loading class com.alex193a.psdtenabler.Module
12-26 04:42:14.536  5364  5364 I EdXposed-Bridge: Loading modules from /data/app/git.hub.font-zopCMH-JhSQQAhZsPwNPPg==/base.apk
12-26 04:42:14.652  5364  5364 I EdXposed-Bridge:   Loading class git.hub.font.x.hooks.XposedInit
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at git.hub.font.x.hooks.PackagePermissions.initHooks(PackagePermissions.java:53)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at git.hub.font.x.hooks.XposedInit.initZygote(XposedInit.java:49)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedInit.loadModule(XposedInit.java:488)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedInit.loadModules(XposedInit.java:346)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.loadModulesSafely(BaseRouter.java:78)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.proxy.NormalProxy.forkAndSpecializePre(NormalProxy.java:28)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.core.Main.forkAndSpecializePre(Main.java:63)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native Method)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:252)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:268)
12-26 04:42:14.661  5364  5364 E EdXposed-Bridge: 	at com.a

**Comment by amakuramio** [comment]
Same on s9

**Comment by alroy214** [comment]
@amakuramio You are on Android 10?

**Comment by amakuramio** [comment]
> @amakuramio You are on Android 10?

Yes, on lineageos q it works normally, but on Samsung q it doesn't 
Probably needs a signature in system / framework

**Comment by alroy214** [comment]
@amakuramio what does that mean? You know how to add it?

**Comment by MlgmXyysd** [comment]
Known Riru issue: https://github.com/RikkaApps/Riru/issues/69 https://github.com/RikkaApps/Riru/issues/73 https://github.com/RikkaApps/Riru/issues/75
