### ISSUE TITLE
所有模块都无效

### ISSUE THREAD

**Issue by Daziax** [ElderDrivers/EdXposed#417]
手机型号：pixel4xl
问题：所有模块都无效。报错说找不到这个路径文件，我用文件管理器跟着能找到，里面也有记录。
详细日志：
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QQ1B.191205.012.A1
Fingerprint: google/coral/coral:10/QQ1B.191205.012.A1/6015823:user/release-keys
ROM build description: coral-user 10 QQ1B.191205.012.A1 6015823 release-keys
EdXposed Version: v0.4.6.0_beta(4481) (Yahfa)
Architecture: arm64-v8a
Device: coral
Manufacture: Google
Brand: google
Product: coral
Magisk: 20.1:MAGISKSU(20100)
--------- beginning of main
--------- beginning of system
12-28 03:31:55.552   873   873 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
--------- beginning of crash
12-28 03:32:08.756   874   874 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by kotori2** [comment]
下载新版manager

**Comment by MlgmXyysd** [comment]
#384
