### ISSUE TITLE
4.6.0 not working with OxygenOS 10

### ISSUE THREAD

**Issue by terlynn4** [ElderDrivers/EdXposed#418]
I have a OnePlus 7 Pro running OOS 10.3.0. Version 4.6.0 does not work. (Hasn't worked on any OOS 10.0.0 or higher.) It installs, but modules don't load (I've tried 4471 and 4481, both SandHook and YAHFA).

OxygenOS 10.3.0
Magisk v20.1 (20100)
Riru Core v19.5
Riru EdXposed v0.4.6.0_beta (4481) (YAHFA)
All other magisk modules disabled

If I open EdXposed Manager, it shows framework installed and active.
Then I install app such as Greenify or GravityBox [Q], enable module, reboot. Modules don't work (they say I need to install Xposed framework).
I can switch to version 4.5.5 (4470) and everything works as expected.

Anything I can do?

**Comment by JasonKhew96** [comment]
@terlynn4 4471 and above need custom magisk 
custom magisk update channel:
http://edxp.meowcat.org/repo/version.json

OR

wait for the stable version of 20.2 magisk
should be available in days

**Comment by terlynn4** [comment]
I'm not sure how to open that .json link, sorry.

I can wait for 20.2, thank you for the info.

**Comment by MlgmXyysd** [comment]
@terlynn4

**Comment by MlgmXyysd** [comment]
@terlynn4

**Comment by MlgmXyysd** [comment]
@terlynn4 Magisk Manager - Settings - Update Channel - Custom

**Comment by terlynn4** [comment]
Oh, I understand now. I have installed custom magisk and version 4481 is now working. Thanks for the help!
