### ISSUE TITLE
[BUG]hook play商店64位应用存在bug  微信国内64位能正常hook play版64位就hook不了

### ISSUE THREAD

**Issue by wyUshio** [ElderDrivers/EdXposed#419]
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 8.1.0
Android sdk: 27
Android build: OPM7.181205.001
Fingerprint: Android/osborn/osborn:7.1.1/NGI77B/1540814905:user/dev-keys
ROM build description: osborn-user 7.1.1 NGI77B 1 dev-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: osborn
Manufacture: smartisan
Brand: Smartisan
Product: osborn
--------- beginning of main
--------- beginning of system
12-29 13:52:23.920   693   693 I EdXposed-Bridge:   Loading class com.fkzhang.wechatxposed.XposedInit
12-29 13:52:23.924   693   693 I EdXposed-Bridge: Loading modules from /data/app/me.dannyit.wechat.chum-9xM_uZi0vTBYI2tST5nl-w==/base.apk
12-29 13:52:24.048   693   693 I EdXposed-Bridge:   Loading class me.dannyit.wechat.chum.backend.WechatHook
12-29 13:52:40.117  3103  3103 I EdXposed-Bridge: com.tencent.mm loading com.fkzhang.wechatxposed
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: parameter type must not be null
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getParameterClasses(XposedHelpers.java:498)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:36)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:21)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:760)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:27)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.ʾי(Unknown Source:36)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.hook(Unknown Source:103)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.ʾי(Unknown Source:55)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.hook(Unknown Source:0)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ᐧˎ(Unknown Source:54)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ʾʻ(Unknown Source:1)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.WxCoreLoader.ﹳᵢ(Unknown Source:14)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposed.ᐧˎ.יʼ(Unknown Source:2)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ⁱˑ$יʼ.run(Unknown Source:175)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:790)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:164)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6499)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-29 13:52:41.331  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.tencent.mm.pluginsdk.ui.chat.ChatFooter$2#onClick(android.view.View)#exact
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:36)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:21)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:760)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:27)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.ʾי(Unknown Source:36)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.hook(Unknown Source:103)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.ʾי(Unknown Source:55)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.hook(Unknown Source:0)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ᐧˎ(Unknown Source:54)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ʾʻ(Unknown Source:1)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.WxCoreLoader.ﹳᵢ(Unknown Source:14)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposed.ᐧˎ.יʼ(Unknown Source:2)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ⁱˑ$יʼ.run(Unknown Source:175)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:790)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:164)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6499)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-29 13:52:41.931  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: java.lang.NoSuchMethodError: com.tencent.mm.ui.LauncherUI#a(java.lang.String,android.os.Bundle,boolean)#exact
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:36)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ʽˑ.ᴵˎ.ʾי(Unknown Source:21)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:760)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ᵔᐧ.ˉʽ.ʾי(Unknown Source:27)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.ʾי(Unknown Source:36)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ˉʽ.hook(Unknown Source:103)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.ʾי(Unknown Source:55)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposedhooks.ˉʽ.ᵔʼ.hook(Unknown Source:0)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ᐧˎ(Unknown Source:54)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˊי.ʾʻ(Unknown Source:1)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.WxCoreLoader.ﹳᵢ(Unknown Source:14)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.wechatxposed.ᐧˎ.יʼ(Unknown Source:2)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ⁱˑ$יʼ.run(Unknown Source:175)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:790)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:164)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:6499)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-29 13:52:42.082  3103  3103 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-29 13:52:42.310  3103  3103 I EdXposed-Bridge: com.fkzhang.wechatxposed [WechatXposed](2.5|46): wechat version 7.0.9(1545)
12-29 13:52:42.310  3103  3103 I EdXposed-Bridge: com.fkzhang.wechatxposed load time: 2467
12-29 13:52:42.872  3103  3371 I EdXposed-Bridge: 微X模块 2.5_2.5 (4,25) p
12-29 13:52:50.101   694   694 I EdXposed-Bridge: Loading modules from /data/app/com.fkzhang.wechatxposed-zWbZYJ378aChyuMxham5og==/base.apk
12-29 13:52:50.143   694   694 I EdXposed-Bridge:   Loading class com.fkzhang.wechatxposed.XposedInit
12-29 13:52:50.147   694   694 I EdXposed-Bridge: Loading modules from /data/app/me.dannyit.wechat.chum-9xM_uZi0vTBYI2tST5nl-w==/base.apk
12-29 13:52:51.027   694   694 I EdXposed-Bridge:   Loading class me.dannyit.wechat.chum.backend.WechatHook
--------- beginning of crash
12-29 13:53:33.430  3103  3370 I EdXposed-Bridge: wexposed params file update success!
12-29 13:53:33.796  3103  3370 I EdXposed-Bridge: wexposed metadata file update success!
12-29 13:53:33.798  3103  3370 I EdXposed-Bridge: wexposed strings file update success!
12-29 13:53:33.833  3103  3370 I EdXposed-Bridge: wexposed core file update success!
12-29 13:53:33.848  3103  3373 I EdXposed-Bridge: load transcoder 3
12-29 13:53:34.849  3103  3373 I EdXposed-Bridge: feature loaded: base 49
12-29 13:53:35.805  3103  3373 I EdXposed-Bridge: feature loaded: themes 16

两个模块 微x模块 还有个微信密友模块 play版hook 不到 国内版可以正常hook

**Comment by MlgmXyysd** [comment]
模块问题，微x更新到2.7
