### ISSUE TITLE
如何可以 by-pass safetynet? 

### ISSUE THREAD

**Issue by Charles-Chan-HK** [ElderDrivers/EdXposed#42]
用了0.29.6配搭exp manager 有部份app依然檢測到xposed installer 的存在。
只要比installer 移除了，就正常開啓，裝了xposed installer 即報錯。。。

發現到的是DBS OMNI和HSBC HK這兩個銀行APp

**Comment by BoBppy** [comment]
改包名

**Comment by Charles-Chan-HK** [comment]
怎樣改掉xposed installer 包名，而插件又可以辨識得到？

**Comment by zhenchao** [comment]
这个问题应该与SafetyNet没有太大关系，EdXposed应该不会导致不能通过SafetyNet。
你可以在Magisk Manager检查您的SafetyNet状态。
你可以尝试使用EdXposed v0.2.9.6及以上版本配合Edxp Manager尝试对指定的应用停止加载EdXposed。

**Comment by Charles-Chan-HK** [comment]
試過，就是這兩個app, 對xposed特別敏感。

檢測到installer 存在即拒絕運行。但exposed 沒有它就開啟不了插件。

反而別家太極自有管理器就不會被這個app檢測到

**Comment by zhenchao** [comment]
由于EdXposed仍和原版Xposed一样使用Xposed Installer管理模块，所以一些应用通过检测是否安装了Xposed Installer来识别是否安装了Xposed。

可能的解决方案是等待作者@solohsu 支持随机包名隐藏管理器的功能。（就像Magisk Manager做的那样）

另外一些深度定制ROM例如MIUI，EMUI的权限管理可以禁止应用读取设备中已安装应用列表。

**Comment by Typhonling** [comment]
有没有试过xprivacylua？不过296&295有可能导致拖慢被privacy的应用，291正常使用。

**Comment by solohsu** [comment]
以后会有自己的独立管理器，不过如果也被检测相应包名的话，还需要寻找类似 Magisk Manger 那种随机包名解决方案。

**Comment by SumanKhanra** [comment]
Yes

**Comment by Charles-Chan-HK** [comment]
方法？@SumanKhanra

**Comment by solohsu** [comment]
Fixed in [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)
