### ISSUE TITLE
[BUG] Cannot load any modules (SM-G975F)

### ISSUE THREAD

**Issue by Exeedy** [ElderDrivers/EdXposed#422]
Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

I tried multiple Sandhook, YAHFA and Magisk versions but can't get it to work.

Here is the logcat: [Logcat](https://www49.zippyshare.com/v/WH0LvfjA/file.html) 

And here the Xposed log:

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QP1A.190711.020
Fingerprint: samsung/beyond2lteeea/beyond2:10/QP1A.190711.020/G975FXXU3BSKO:user/release-keys
ROM build description: beyond2ltexx-user 10 QP1A.190711.020 G975FXXU3BSKO release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: beyond2
Manufacture: samsung
Brand: samsung
Product: beyond2lte
--------- beginning of main
--------- beginning of system
01-01 12:07:44.394  5388  5388 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-01 12:07:44.394  5388  5388 I EdXposed: Start to install inline hooks
01-01 12:07:44.394  5388  5388 I EdXposed: Using api level 29
01-01 12:07:44.394  5388  5388 I EdXposed: Start to install Riru hook
01-01 12:07:44.408  5388  5388 I EdXposed: Riru hooks installed
01-01 12:07:44.462  5388  5388 I EdXposed: ART hooks installed
01-01 12:07:44.462  5388  5388 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-01 12:07:44.462  5388  5388 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-01 12:07:44.464  5389  5389 I EdXposed: onModuleLoaded: welcome to EdXposed!
01-01 12:07:44.464  5389  5389 I EdXposed: Start to install inline hooks
01-01 12:07:44.464  5389  5389 I EdXposed: Using api level 29
01-01 12:07:44.464  5389  5389 I EdXposed: Start to install Riru hook
01-01 12:07:44.482  5389  5389 I EdXposed: Riru hooks installed
01-01 12:07:44.518  5389  5389 I EdXposed: ART hooks installed
01-01 12:07:44.518  5389  5389 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
01-01 12:07:44.518  5389  5389 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
01-01 12:07:44.565  5388  5388 I EdXposed: using installer org.meowcat.edxposed.manager
01-01 12:07:44.565  5388  5388 I EdXposed: black/white list mode: false, using whitelist: false
01-01 12:07:44.565  5388  5388 I EdXposed: dynamic modules mode: false
01-01 12:07:44.565  5388  5388 I EdXposed: resources hook: true
01-01 12:07:44.565  5388  5388 I EdXposed: deopt boot image: false
01-01 12:07:44.597  5389  5389 I EdXposed: using installer org.meowcat.edxposed.manager
01-01 12:07:44.597  5389  5389 I EdXposed: black/white list mode: false, using whitelist: false
01-01 12:07:44.597  5389  5389 I EdXposed: dynamic modules mode: false
01-01 12:07:44.597  5389  5389 I EdXposed: resources hook: true
01-01 12:07:44.597  5389  5389 I EdXposed: deopt boot image: false
01-01 12:07:50.069  5388  5388 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-01 12:07:57.437  5389  5389 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by amakuramio** [comment]
https://github.com/ElderDrivers/EdXposed/files/4008003/edxposed-4481-y-sp.zip
And

**Comment by Exeedy** [comment]
> https://github.com/ElderDrivers/EdXposed/files/4008003/edxposed-4481-y-sp.zip
> And
> https://github.com/ElderDrivers/EdXposed/files/4006203/Magisk-v20.2-025b0605.zip
> Now it will load, but many xposed apps not working

Thanks works! But you are right none of my modules are working.

**Comment by MlgmXyysd** [comment]
*Known issue detected: "Samsung One UI Android 10"

**Comment by krokofant** [comment]
I thought I had this issue as well but I had just forgot to enable the Xposed module under Modules. Maybe the modules.list should be empty and not missing when no modules are enabled.

**Comment by Exeedy** [comment]
> I thought I had this issue as well but I had just forgot to enable the Xposed module under Modules. Maybe the modules.list should be empty and not missing when no modules are enabled.

good idea thank you.
But the modules.list is there 🤔

**Comment by Exeedy** [comment]
With the  and "EdXposed-YAHFA-v0.4.6.1 (4489)-rtiihway-release it loads the modules.list now. But none of the modules are working.

**Comment by amakuramio** [comment]
> With the and "EdXposed-YAHFA-v0.4.6.1 (4489)-rtiihway-release it loads the modules.list now. But none of the modules are working.

It will probably never work on Samsung
The developer has no test device. 
Only option is to install custom AOSP rom like lineageos

**Comment by MlgmXyysd** [comment]
@Exeedy run Riru Manager to check riru work infomation
https://github.com/RikkaApps/Riru/releases/download/v19.4/app-release.apk

**Comment by Exeedy** [comment]
> @Exeedy run Riru Manager to check riru work infomation
> https://github.com/RikkaApps/Riru/releases/download/v19.4/app-release.apk

Ok thank you here is the issue..

Riru output is that:

Riru Unknown (version code 27) found.
However, native methods of Zygote class not replaced, please contact developer with the following information.

nativeForkAndSpecializeSignature:
(II[II[[IILjava/lang/String;IILjava/lang/String;[I[IZLjava/lang/String;Ljava/lang/String;)I

nativeSpecializeAppProcessSignature (from Q beta 3):
(II[II[[IILjava/lang/String;IILjava/lang/String;ZLjava/lang/String;Ljava/lang/String;)V

nativeForkSystemServerSignature:
(II[IIII[[IJJ)I


I used RiruCore from Magisk Repo.

**Comment by MlgmXyysd** [comment]
@Exeedy well, the riru is broken, report it to https://github.com/RikkaApps/Riru/issues

**Comment by MlgmXyysd** [comment]
Known Riru issue: https://github.com/RikkaApps/Riru/issues/69 https://github.com/RikkaApps/Riru/issues/73 https://github.com/RikkaApps/Riru/issues/75
