### ISSUE TITLE
[BUG] MIUI11无法激活框架中的模块

### ISSUE THREAD

**Issue by Dalka0064** [ElderDrivers/EdXposed#423]
**什么情况/What happened?**

edxposed框架显示已激活，但勾选模块重启后，模块提示未激活

redmi k20 pro
安卓q
miui11.0.5.0稳定版

**Xposed模块列表/Xposed Module List**

![Screenshot_2020-01-02-11-48-24-180_org meowcat ed](https://user-images.githubusercontent.com/31382901/71651220-d3149400-2d56-11ea-9469-019484ac9681.jpg)

**Magisk模块列表/Magisk Module List**

![Screenshot_2020-01-02-11-48-14-355_com h A Hq0Asy](https://user-images.githubusercontent.com/31382901/71651214-cd1eb300-2d56-11ea-95f6-33baa22f27a1.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
90.0-v0.4.6.0_beta(4481)(YAHFA)
Riru:
19.5
**相关Logcat/Logcat**
E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
E EdXposed: mmap failed, errno = Permission denied
E EdXposed: cannot hook method
E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
[all.log](https://github.com/ElderDrivers/EdXposed/files/4014883/all.log)

**Comment by MlgmXyysd** [comment]
#384
