### ISSUE TITLE
[BUG] 安卓10，edxp管理器启动闪退

### ISSUE THREAD

**Issue by nekomiya-hinata** [ElderDrivers/EdXposed#424]
**什么情况/What happened?**
edxp使用的是sandhook_v0.4.5.1，现在能正常开机了，但edxp管理器无法正常使用（installer和manager都试过）

**Xposed模块列表/Xposed Module List**
无

**Magisk模块列表/Magisk Module List**
magisk manager for recovery mode

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
1) 请提供log
2) 请到 https://github.com/ElderDrivers/EdXposedManager/issues 提交
