### ISSUE TITLE
Oneplus 6t Oxygen 10 exposed not working 

### ISSUE THREAD

**Issue by muschiu40jp** [ElderDrivers/EdXposed#425]
I have installed edXposed and the framework is active but no module works. Today also I updated Magisk Manager to 7.2 and app to 7.5.0 but after reboot still not working. I have installed GravityBox, instapref and ifont and nothing works. Is it any fix?

**Comment by muschiu40jp** [comment]
Why do you close my issue? Please can you explain?

**Comment by 18712886438** [comment]
I also want to know why?

**Comment by JasonKhew96** [comment]
@muschiu40jp 
```
WILL CLOSE WITHOUT THIS TEMPLATE
```
![image](https://user-images.githubusercontent.com/29531167/71662482-96fc2600-2d8c-11ea-8c71-8a9fad1b1866.png)

**Comment by 18712886438** [comment]
@JasonKhew96 ah, okay I see

**Comment by muschiu40jp** [comment]
I opened verbose log and i got this crash
EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by JasonKhew96** [comment]
> I opened verbose log and i got this crash
> EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

@muschiu40jp use 4470 or below, 4471 or up need custom magisk, read [here](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.6.0)

**Comment by muschiu40jp** [comment]
> > I opened verbose log and i got this crash
> > EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 
> @muschiu40jp use 4470 or below, 4471 or up need custom magisk, read [here](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.6.0)

Do you know from where to download 4470?
