### ISSUE TITLE
[BUG] Edxposed v0.4.6.0 YAHFA bootloop

### ISSUE THREAD

**Issue by KaMyKaSii** [ElderDrivers/EdXposed#433]
**什么情况/What happened?**

Bootloop after installing edxposed v0.4.6.0 YAHFA on my Zenfone 4 with Android 9. I am running the last official Magisk Canary v20.3 (20201), hopefully not the problem. Liveboot log attached

**Xposed模块列表/Xposed Module List**

com.alex193a.watweaker
tk.wasdennnoch.scoop

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.0 YAHFA

Riru: v19.5

**相关Logcat/Logcat**

[liveboot.txt](https://github.com/ElderDrivers/EdXposed/files/4022261/liveboot.txt)

**Comment by MlgmXyysd** [comment]
@KaMyKaSii try 0.4.6.1

**Comment by MlgmXyysd** [comment]
@KaMyKaSii https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/29892805/artifacts

**Comment by JasonKhew96** [comment]
@KaMyKaSii https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/29892805/artifacts
download 0.4.6.1 here

**Comment by KaMyKaSii** [comment]
Downloaded through Edxposed Manager itself, is working now. I should have tested the Canary build before reporting, my bad
