### ISSUE TITLE
[BUG] Modules partially loading (SM-G975F)

### ISSUE THREAD

**Issue by Exeedy** [ElderDrivers/EdXposed#434]
**什么情况/What happened?**
Modules are loading but thinking that xposed is not enabled.
And log is full with this errors:

`01-07 21:49:58.326 17871 17937 W XSharedPreferences: getSharedPreferences
01-07 21:49:58.326 17871 17937 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-07 21:49:58.326 17871 17937 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
01-07 21:49:58.326 17871 17937 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
01-07 21:49:58.326 17871 17937 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-07 21:49:58.326 17871 17937 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-07 21:49:58.326 17871 17937 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)`

Riru Core v19.6 now working without errors
All modules not working
YAHFA version not working

**EdXposed及Riru版本/Versions of EdXposed and Riru**

Magisk Riru Core v19.6 - EdXposed SandHook v0.4.6.1 (4491) oacavrdt
Android SDK 29
SM-G975F

**相关Logcat/Logcat**

[logreader_2020-01-07_20-33-03.log](https://github.com/ElderDrivers/EdXposed/files/4032263/logreader_2020-01-07_20-33-03.log)

[EdXposed_Module_error_20200107_202741.log](https://github.com/ElderDrivers/EdXposed/files/4032267/EdXposed_Module_error_20200107_202741.log)

[EdXposed_Verbose_all_20200107_202649.log](https://github.com/ElderDrivers/EdXposed/files/4032274/EdXposed_Verbose_all_20200107_202649.log)

**Comment by amakuramio** [comment]
Works fine on my S9 plus.  Uninstall Riru and edxposed, reboot.  Download riru from here, install from within exposed manager. Reboot. Install edexposed, reboot.

**Comment by Exeedy** [comment]
> Works fine on my S9 plus. Uninstall Riru and edxposed, reboot. Download riru from here, install from within exposed manager. Reboot. Install edexposed, reboot.

Thank you for fast reply. Ok i will test it 😁

**Comment by Jasi2169** [comment]
you are right the modules which give error in detecting xposed are minminguard/lucky patcher

my jasi patcher can detect,

for me yhfa dont work, but sandhook work on note 9 android 10

i get error: edxposed: can;t access config path,using snapshot use_white_list:/data/user/150/com.google.anfroid.gms
i get error: edxposed: can;t access config path,using snapshot black list:/data/user/150/com.google.anfroid.gms

and safety faild to bypass even app list mode is enabled and gsf and gps are enabled in application tab

let me tell you the reason, we have data partition unmounted till we reboot the device fully, i cant even access the data partition wven though i have flashed the dm-varity disabled as well as force encryption disable.

**Comment by MlgmXyysd** [comment]
reinstall xp modules / clear modules data

**Comment by Exeedy** [comment]
> Hi i also got this issue, you can fix this issue by uninstalling and reinstalling those modules for example minminguard.
> 
> Install these module after flashing edxposed,if you uninstalled these modules before even enablng module and rebooting they show no xposed found.
> 
> So uninstalling and reinstalling fixed those issues for me on note 9 android 10

YES A THOUSAND THANK YOU! 🥳
Reinstalling the modules works!

**Comment by MlgmXyysd** [comment]
if no more question, pls close issue :)

**Comment by Exeedy** [comment]
> reinstall xp modules / clear modules data

Thank you too. it works now with reinstalling the modules.
