### ISSUE TITLE
[BUG] EdXposed framework is installed, but not active

### ISSUE THREAD

**Issue by F3FFO** [ElderDrivers/EdXposed#436]
**什么情况/What happened?**

After installing Riru-Core and EdXposed to the last version I have a message into EdXposed Manager that says: "EdXposed framework is installed, but not active. Please check the logs for details". After this messagge I try to check logs but I have nothing

**Xposed模块列表/Xposed Module List**

![Screenshot_2020-01-08-13-11-00-20](https://user-images.githubusercontent.com/38475841/71977139-5aab4880-3218-11ea-98d3-dcb58357287d.jpg)

**Magisk模块列表/Magisk Module List**

![Screenshot_2020-01-08-13-11-44-39](https://user-images.githubusercontent.com/38475841/71977183-7282cc80-3218-11ea-96f4-319640f38576.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.0_beta(4471) SandHook

Riru: 19.6

**相关Logcat/Logcat**

> --------- beginning of head
> EdXposed Log
> Powered by Log Catcher
> QQ chat group 855219808
> --------- beginning of system info
> Android version: 9
> Android sdk: 28
> Android build: PKQ1.190626.001
> Fingerprint: 
> ROM build description: msmnile-user 9 PKQ1.190626.001 eng.root.20191225.111704 release-keys
> EdXposed Version: v0.4.6.0_beta(4471) (Sandhook)
> Architecture: arm64-v8a
> Device: 
> Manufacture: realme
> Brand: realme
> Product: RMX1931
> --------- beginning of main
> --------- beginning of system

**Comment by MlgmXyysd** [comment]
@F3FFO Check the working status of Riru with Riru Manager: https://t.me/EdXposed/48

**Comment by F3FFO** [comment]
Oh sorry, I hadn't read that I had to check that. Strangely he says to me: "Riru not found in memory", but I followed all the steps installing everything from recovery to avoid bootloop

**Comment by MlgmXyysd** [comment]
@F3FFO ok,just uninstall riru-core, reboot, install riru-core in Magisk Manager, reboot

**Comment by F3FFO** [comment]
Ok ok, I done it and now riru-core is installed, now I have to install EdXposed from recovery true?

**Comment by MlgmXyysd** [comment]
@F3FFO feel free to use rec or Magisk Manager

**Comment by F3FFO** [comment]
Thank you, I'm sorry for my mistake

**Comment by saikwamhlaing** [comment]
Uninstall Edxposed manager and reinstall it again , I hope you will work .

**Comment by kngharv** [comment]
> Uninstall Edxposed manager and reinstall it again , I hope you will work .

Hey, thanks.  This worked and it wasn't something I expected.  I would never thought about reinstall the manager app.
