### ISSUE TITLE
[Download] Edxposed 0.4.6.1 Canary (!)

### ISSUE THREAD

**Issue by JohnGLFour** [ElderDrivers/EdXposed#437]
Neither Github or CI have it so here it is:
YAHFA: [Edxposed-YAHFA-v0.4.6.1 (4492)-jowfjvqw-release.zip](https://github.com/ElderDrivers/EdXposed/files/4043604/EdXposed-YAHFA-v0.4.6.1.4492.-jowfjvqw-release.zip)
SandHook: [EdXposed-SandHook-v0.4.6.1 (4492)-jowfjvqw-release.zip](https://github.com/ElderDrivers/EdXposed/files/4043605/EdXposed-SandHook-v0.4.6.1.4492.-jowfjvqw-release.zip)

Changelog:
- Merge SEPolicy Test (4487)
- Add custom SEPolicy rule (4487)
- Add Riru version to log (4487)
- No hardcoded EdXposed version (4487)
- No beta version (4487)
- Fix can't create prop (4488)
- Fix SEPolicy not work (4489)
- Fix typo (4490)
- Support old Magisk (4491)
- Fix bootloop on OPPO/Realme Android P (Color OS) (4492)

**Comment by JohnGLFour** [comment]
Pin then Close

**Comment by JasonKhew96** [comment]
it's in ci
https://ci.appveyor.com/project/ElderDrivers/edxposed/history
and also in EdXposed Manager Canary tab

**Comment by aeroxy** [comment]
@JasonKhew96 how can I download the zip file from ci on a mac?

**Comment by aeroxy** [comment]
I see, you will need to click on "Artifacts" which is a bit unclear...

**Comment by ch3mn3y** [comment]
Where normally can I find EdXposed 4.6.1 or any other that will be latest in the future?
Found it here, but there is only 4.5.1 in MAGISK and 4.6.0 is latest on GitHub releases...
