### ISSUE TITLE
[BUG] Build fingerprint: 'Android-x86/android_x86_64/x86_64:10/QD1A.190821.014.C2/eng.electr.20191227.215630:userdebug/test-keys' Revision: '0'

### ISSUE THREAD

**Issue by youling257** [ElderDrivers/EdXposed#438]
Revision: '0'
ABI: 'x86_64'
Timestamp: 2020-01-11 07:53:17+0800
pid: 2383, tid: 2383, name: main  >>> zygote64 <<<
uid: 0
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    rax 4800000026bafff2  rbx 00007ffeca0452f8  rcx 000000000000000b  rdx 00007762e960160c
    r8  0000000000000007  r9  0000000000000000  r10 0000000000000010  r11 0000000000000246
    r12 00007762e90d7a4d  r13 00007ffeca0452f8  r14 00007762e963fca0  r15 00007762e9644000
    rdi 0000000000000000  rsi fffffffffffffff8
    rbp 0000000000000000  rsp 00007ffeca0450b0  rip 00007762e94a658f

backtrace:

**Comment by MlgmXyysd** [comment]
so what version?
0.4.6.1_4494?

**Comment by youling257** [comment]
YAHFA version.
SandHook not support x86.

**Comment by MlgmXyysd** [comment]
@youling257 what version?

**Comment by youling257** [comment]
0.4.6.1_4494

**Comment by MlgmXyysd** [comment]
> 0.4.6.1_4494

try 4492
