### ISSUE TITLE
[BUG] modules.list can't be read on latest security patch (r23, january)

### ISSUE THREAD

**Issue by kurtextrem** [ElderDrivers/EdXposed#440]
**什么情况/What happened?**

EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Xposed模块列表/Xposed Module List**

Greenify only.

**Magisk模块列表/Magisk Module List**

Magisk 20.1
Riru v19.5
EdXposed 4.6.0

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 4.6.0

Riru: 19.5

**相关Logcat/Logcat**

EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by MlgmXyysd** [comment]
0.4.6.1 fixed
