### ISSUE TITLE
[BUG] Unfortunately installed 0.4.6.0.

### ISSUE THREAD

**Issue by Kusoneko** [ElderDrivers/EdXposed#442]
**What happened?**

EdXposed Manager offered to update the Xposed Framework to 0.4.6.0 from 0.4.5.1 through Magisk Manager. No mention of needing a custom Magisk install there so I'm now stuck. My device (marlin - Pixel XL running LineageOS version 16.0-20191029-NIGHTLY-marlin) keeps crashing during the boot, and for some reason it isn't a critical crash so it gets stuck on the boot animation for LineageOS and never actually boots into the system, nor reboot at all unless I press and hold the power button. I did an "adb logcat > logcat.txt" for a little while and posted the results below to show. I can boot into the bootloader, but I've attempted several times to boot into the latest twrp.img or to run the flash-all file from the factory image, and in either case, fastboot freezes if it gets asked anything besides --help or devices, meaning I'm still stuck.

I have read through #384 and it doesn't appear that any of the solutions offered there work at all. I cannot install the custom Magisk if I cannot boot into anything to flash it using Magisk Manager. Further, the release for 0.4.6.0 mentions that the custom Magisk is only required because https://github.com/topjohnwu/Magisk/pull/1685 isn't merged yet, however, a quick look at it shows it closed, and "merged". Someone said the following solution:

> Next time, you can boot into the loading screen, connect via adb and then do:
>
>  *  adb shell
>  *  su
>  *  touch /cache/.disable_magisk

I have attempted to do this, but the su command doesn't actually work, it freezes for a little while and eventually returns `Permission denied` -- after all I cannot give adb root permissions for the first time if I cannot get into the system to get asked to do so. I don't know what to do to get out of this. Help me please.

**Xposed Module List**

Due to the above issue of not being able to boot into anything besides bootloader, I can't actually give this information because I don't know exactly which modules I had installed.

**Magisk Module List**

Due to the above issue of not being able to boot into anything besides bootloader, I can't actually give this information because I don't know exactly which modules I had installed.

**Versions of EdXposed and Riru**

EdXposed: 0.4.6.0

Riru: 19.6

**Logcat**

*It can help us to locate issue, must use our logcat module*

I do not know what logcat module this is talking about, and doubt I could somehow manage to install it currently. Still, the attachment is the result of `adb logcat` so perhaps it will help.

[logcat.txt](https://github.com/ElderDrivers/EdXposed/files/4051944/logcat.txt)

**Comment by MlgmXyysd** [comment]
use Magisk 20.2+0.4.6.1

**Comment by Kusoneko** [comment]
How do I do that if I can't boot into system?

**Comment by MlgmXyysd** [comment]
@Kusoneko can u mount data in twrp?

**Comment by Kusoneko** [comment]
I can't even boot into twrp. Also, I'm using Magisk 20.3.

**Comment by MlgmXyysd** [comment]
@Kusoneko did u opened usb debugging in settings?

**Comment by Kusoneko** [comment]
Yes

**Comment by MlgmXyysd** [comment]
@Kusoneko okay, just plug ur phone to PC(in bootloop), type "adb shell magisk —remove-modules" in cmd

**Comment by Kusoneko** [comment]
It rebooted into system.

**Comment by MlgmXyysd** [comment]
@Kusoneko removed all of magisk modules

**Comment by MlgmXyysd** [comment]
@Kusoneko so u can re-install by urself

**Comment by Kusoneko** [comment]
Yup, I'm reinstalling them and then I'll probably go back to EdXposed 0.4.5.1
