### ISSUE TITLE
[BUG] Exposed Framework is installed, but not active

### ISSUE THREAD

**Issue by IPlayForHer** [ElderDrivers/EdXposed#443]
**什么情况/What happened?**

Exposed Framework is installed, but not active

**Xposed模块列表/Xposed Module List**

No module active

**Magisk模块列表/Magisk Module List**

ADB SDK
Busybox
Riru-core
Riru-edxposed
Riru-storage redirect
Font

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.6.1(4497)

Riru:19.6

**相关Logcat/Logcat**

--------- beginning of crash
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.hooker.XposedInstallerHooker$1.beforeHookedMethod(XposedInstallerHooker.java:32)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:87)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:187)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at org.meowcat.bugcatcher.MeowCatApplication.onCreate(MeowCatApplication.java:20)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1600(ActivityThread.java:231)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-14 14:22:14.645  6013  6013 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by MlgmXyysd** [comment]
re-install edxposed manager

**Comment by IPlayForHer** [comment]
01-24 09:28:07.350   769   769 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-24 09:28:08.482  1130  1130 E EdXposed: mmap failed, errno = Permission denied
01-24 09:28:08.482  1130  1130 E EdXposed: cannot hook method
01-24 09:28:08.485  1130  1130 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
01-24 09:28:08.485  1130  1130 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3088)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:637)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:522)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-24 09:28:08.485  1130  1130 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
01-24 09:28:11.674  1130  1130 E EdXposed: mmap failed, errno = Permission denied
01-24 09:28:11.674  1130  1130 E EdXposed: cannot hook method
01-24 09:28:11.674  1130  1130 E EdXposed: error occur when generating dex. dexDir=null
01-24 09:28:11.674  1130  1130 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2413)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2356)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2327)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2217)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7208)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7495)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8379)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1013)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:540)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-24 09:28:11.674  1130  1130 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
--------- beginning of crash
01-24 09:28:18.639   770   770 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.hooker.XposedInstallerHooker$1.beforeHookedMethod(XposedInstallerHooker.java:32)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:87)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:187)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at org.meowcat.bugcatcher.MeowCatApplication.onCreate(MeowCatApplication.java:20)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1600(ActivityThread.java:231)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-24 09:29:00.515  6508  6508 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by IPlayForHer** [comment]
still not working
