### ISSUE TITLE
[BUG] 模块对双开的应用无法生效

### ISSUE THREAD

**Issue by Matrix6677** [ElderDrivers/EdXposed#444]
**什么情况/What happened?**
模块对MIUI 11双开应用无法生效

**Xposed模块列表/Xposed Module List**
![image](https://user-images.githubusercontent.com/2385900/72320059-d820fe00-36db-11ea-90f7-2515636e8713.png)

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed
![image](https://user-images.githubusercontent.com/2385900/72320067-dce5b200-36db-11ea-9190-94ca9cb7a886.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.4.5.1_beta(4463)

Riru:v19.6

**相关Logcat/Logcat**
以下是微x模块的日志
模块日志：
```
01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
```
详细日志：
```
01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.eg.android.AlipayGphone
01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.eg.android.AlipayGphone
01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:18.844 27811 27811 I EdXposed: EdxpVariant: 2
01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:19.174 27841 27841 I EdXposed: EdxpVariant: 2
01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.gsf
01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.gsf
01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:20.302 27923 27923 I EdXposed: EdxpVariant: 2
01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:21.268 28098 28098 I EdXposed: EdxpVariant: 2
01-14 14:44:21.276 28080 28080 I EdXposed: EdxpVariant: 2
01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.webview
01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.webview
01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:22.387 28299 28299 I EdXposed: EdxpVariant: 2
01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:22.418 28307 28307 I EdXposed: EdxpVariant: 2
01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
01-14 14:44:24.008 28573 28573 I EdXposed: EdxpVariant: 2
01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
```

**Comment by MlgmXyysd** [comment]
selinux开启的情况下，开启即时模块列表会导致双开无法正常生效
已知bug

**Comment by Matrix6677** [comment]
> selinux开启的情况下，开启即时模块列表会导致双开无法正常生效
> 已知bug

好的，蟹蟹。回复的真快👍

**Comment by kangnaclub9** [comment]
> **什么情况/What happened?**
> 模块对MIUI 11双开应用无法生效
> 
> **Xposed模块列表/Xposed Module List**
> ![image](https://user-images.githubusercontent.com/2385900/72320059-d820fe00-36db-11ea-90f7-2515636e8713.png)
> 
> **Magisk模块列表/Magisk Module List**
> 
> 允许截图/Screenshot allowed
> ![image](https://user-images.githubusercontent.com/2385900/72320067-dce5b200-36db-11ea-9190-94ca9cb7a886.png)
> 
> **EdXposed及Riru版本/Versions of EdXposed and Riru**
> 
> EdXposed:v0.4.5.1_beta(4463)
> 
> Riru:v19.6
> 
> **相关Logcat/Logcat**
> 以下是微x模块的日志
> 模块日志：
> 
> ```
> 01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> ```
> 
> 详细日志：
> 
> ```
> 01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.eg.android.AlipayGphone
> 01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.eg.android.AlipayGphone
> 01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:18.844 27811 27811 I EdXposed: EdxpVariant: 2
> 01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:19.174 27841 27841 I EdXposed: EdxpVariant: 2
> 01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.gsf
> 01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.gsf
> 01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:20.302 27923 27923 I EdXposed: EdxpVariant: 2
> 01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.268 28098 28098 I EdXposed: EdxpVariant: 2
> 01-14 14:44:21.276 28080 28080 I EdXposed: EdxpVariant: 2
> 01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.webview
> 01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.webview
> 01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.387 28299 28299 I EdXposed: EdxpVariant: 2
> 01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.418 28307 28307 I EdXposed: EdxpVariant: 2
> 01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:24.008 28573 28573 I EdXposed: EdxpVariant: 2
> 01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> ```

**Comment by Palatis** [comment]
@kangnaclub9 找一下有沒有 SELinux denied log？

_從我的 OnePlus 7 Pro，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by kangnaclub9** [comment]
> **什么情况/What happened?**
> 模块对MIUI 11双开应用无法生效
> 
> **Xposed模块列表/Xposed Module List**
> ![image](https://user-images.githubusercontent.com/2385900/72320059-d820fe00-36db-11ea-90f7-2515636e8713.png)
> 
> **Magisk模块列表/Magisk Module List**
> 
> 允许截图/Screenshot allowed
> ![image](https://user-images.githubusercontent.com/2385900/72320067-dce5b200-36db-11ea-9190-94ca9cb7a886.png)
> 
> **EdXposed及Riru版本/Versions of EdXposed and Riru**
> 
> EdXposed:v0.4.5.1_beta(4463)
> 
> Riru:v19.6
> 
> **相关Logcat/Logcat**
> 以下是微x模块的日志
> 模块日志：
> 
> ```
> 01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> ```
> 
> 详细日志：
> 
> ```
> 01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.eg.android.AlipayGphone
> 01-14 14:44:17.293 27739 27739 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.eg.android.AlipayGphone
> 01-14 14:44:17.417 27739 27739 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:18.844 27811 27811 I EdXposed: EdxpVariant: 2
> 01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:18.853 27811 27811 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:18.906 27811 27811 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:19.174 27841 27841 I EdXposed: EdxpVariant: 2
> 01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.gsf
> 01-14 14:44:19.183 27841 27841 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.gsf
> 01-14 14:44:19.245 27841 27841 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:20.302 27923 27923 I EdXposed: EdxpVariant: 2
> 01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:20.311 27923 27923 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:20.379 27923 27923 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.268 28098 28098 I EdXposed: EdxpVariant: 2
> 01-14 14:44:21.276 28080 28080 I EdXposed: EdxpVariant: 2
> 01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:21.286 28098 28098 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.google.android.webview
> 01-14 14:44:21.333 28080 28080 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.google.android.webview
> 01-14 14:44:21.416 28098 28098 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:21.451 28080 28080 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.387 28299 28299 I EdXposed: EdxpVariant: 2
> 01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.397 28299 28299 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.418 28307 28307 I EdXposed: EdxpVariant: 2
> 01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.428 28307 28307 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:22.456 28299 28299 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:22.490 28307 28307 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> 01-14 14:44:24.008 28573 28573 I EdXposed: EdxpVariant: 2
> 01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/999/com.tencent.mm
> 01-14 14:44:24.017 28573 28573 E EdXposed: can't access config path, using snapshot black list: /data/user/999/com.tencent.mm
> 01-14 14:44:24.079 28573 28573 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
> ```

**Comment by Palatis** [comment]
please do not post same stuff over and over again. find SELinux denied logs if appropriate.

when you see `/data/user/0` means this app is currently executing as the primary user.
when you see `/data/user/999` means the app is currently executing as secondary user (anything other than 0).
