### ISSUE TITLE
How make it work on android 7?

### ISSUE THREAD

**Issue by obengsakti** [ElderDrivers/EdXposed#445]
please make riru xposed work on android 7!  some xposed module arnt compatible wit android 8 above

**Comment by NewBugger** [comment]
why not use ro89 official xposed?

**Comment by obengsakti** [comment]
if using ro89 most applications detect the hook, then force close, it's not safe

**Comment by nift4** [comment]
Systemless Rovo Xposed?

**Comment by MlgmXyysd** [comment]
EdXposed not support Android 7
For more details: https://github.com/ElderDrivers/EdXposed/wiki/Available-Android-versions
