### ISSUE TITLE
libsandhook.exp.so missing from x86 Arch in SANDHOOK releases

### ISSUE THREAD

**Issue by jfmedellinc** [ElderDrivers/EdXposed#446]
Or maybe i'm missing something?

**Comment by MlgmXyysd** [comment]
@jfmedellinc only YAHFA supoort x86

**Comment by jfmedellinc** [comment]
Understood.. Didn't read that anywhere.. 

If that's the case, it may be a good idea to 
* not include system_x86 folder in SANDHOOK releases
* state this limitation in the README.MD

**Comment by MlgmXyysd** [comment]
now Sandhook installation will abort on x86 devices
