### ISSUE TITLE
[BUG] APP LAUNCHING ANIMATION LAGGING ON EDXPOSED WORKAROUND

### ISSUE THREAD

**Issue by kinesight** [ElderDrivers/EdXposed#448]
ISSUE : EdXposed now tripped Safetynet and Workaround Lags Apps when launched

EdXposed : Yahfa v0.4.6.1 (4497) Canary
Device : Samsung Galaxy A20(SM-A205F)
ROM : Android 9.0 OneUI Stock Rom

A couple of days back when 4497 was released It tripped Safetynet. I was told of a solution by which I had to enable the black list mode in EdXposed Manager and select Google Framework/Google Services and Google Play Store. After I had done this , I did a Safetynet check and all was perfect.

However the issue that I began having was that my apps ( from any launcher I that I used ) had started lagging before it opened for about 1-2 seconds after I tapped on them to launch it. I have reverted my settings and to see if that the backlisting caused the lag and that was what had caused it.

I've tried Sandhook and Yahfa and received the same output.
![Screenshot_20200116-082027_EdXposed Manager](https://user-images.githubusercontent.com/58188282/72498905-1b44b380-3839-11ea-9858-d184a7213995.jpg)
![Screenshot_20200116-082016](https://user-images.githubusercontent.com/58188282/72498906-1b44b380-3839-11ea-81c5-8b8115d430e7.jpg)

**Comment by EhsanYE** [comment]
i have This Problem too, On Custom ROM AOSP Exrended With Android Q... Please Fix
