### ISSUE TITLE
[BUG] Pixel 4 xl brushed 4.5.1 could not boot

### ISSUE THREAD

**Issue by Sleepbuild** [ElderDrivers/EdXposed#449]
My pixel 4 xl brushed magisk-EdXposed-SandHook-v0.4.6.0_beta.4471.-release.zip can be started normally. After deleting it, re-brushing magisk-EdXposed-SandHook-v0.4.5.1_beta will not work. How to solve this problem when loading a page on google?

**Comment by yogaskung** [comment]
My pixel 3 is the same.
My Magisk Manager Download page only shows v0.4.5.1 and lower version.
Both the YAHFA and SandHook didn't work for me,booting stuck in the G logo.

**Comment by Inotamira** [comment]
Anyone know how to get out of the boot loop, or do you have to reinstall everything?

**Comment by yogaskung** [comment]
> Anyone know how to get out of the boot loop, or do you have to reinstall everything?
@Inotamira 
If you have adb debug enabled,try "adb wait-for-device shell" while the "G" logo stuck,and remove all modules in the shell

**Comment by Sleepbuild** [comment]
I repaired it with a line brush.

Jim Wu <notifications@github.com> 於 2020年2月8日 週六 下午1:53寫道：

**Comment by MlgmXyysd** [comment]
#459
