### ISSUE TITLE
Xiaomi A2 with Android 10 boot issue

### ISSUE THREAD

**Issue by bitching** [ElderDrivers/EdXposed#451]
Build Number
QKQ1.190910.002
V11.0.5.0.QDIMIXM

latest version of custom magisk(20.1) will fall in bootloop.
official magisk 20.3 boots smoothly.

maybe update custom magisk to 20.3 works.
can not open an issue at https://github.com/solohsu/magisk_files.

**Comment by JohnGLFour** [comment]
ref #384 #379

**Comment by MlgmXyysd** [comment]
Deprecated custom Magisk
