### ISSUE TITLE
[BUG]  app和框架冲突，每次都卡死

### ISSUE THREAD

**Issue by herolsh** [ElderDrivers/EdXposed#453]
**什么情况/What happened?**
我们公司的一个app，每次打开app，进入二级界面都会卡死，卸载框架就正常（框架下没有装任何模块）

**Xposed模块列表/Xposed Module List**
允许截图/Screenshot allowed
没有模块

**Magisk模块列表/Magisk Module List**
允许截图/Screenshot allowed
1、Riru-Core v19.5
2、Riru-Edxposed v0.4.6.0_beta(4471)(YAHFA)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: Riru-Edxposed v0.4.6.0_beta(4471)(YAHFA)
Riru: Riru-Core v19.5

**相关Logcat/Logcat**
我不会弄格式，只能麻烦将就看一下了
01-28 14:49:13.049: W/NotificationService(1587): Toast already cancelled. pkg=com.pingan.aftercarmarket callback=android.app.ITransientNotification$Stub$Proxy@f3965bd
01-28 14:49:13.049: E/LocationManagerService(1587): request 5348303 gps Request[ACCURACY_FINE gps requested=+900ms fastest=+900ms] from com.pingan.aftercarmarket(10225)
01-28 14:49:15.028: W/AppOps(1587): Finishing op nesting under-run: uid 10225 pkg com.pingan.aftercarmarket code 45 time=1579317009983 duration=2352 nesting=0
01-28 14:50:38.493: E/ActivityTrigger(1587): activityResumeTrigger: not whiteListedcom.pingan.aftercarmarket/com.pingan.aftercarmarket.inner.activity.OneInnerActivity/1121
01-28 14:50:40.687: E/ActivityTrigger(1587): activityStartTrigger: not whiteListedcom.pingan.aftercarmarket/com.pingan.aftercarmarket.activity.WebViewActivity/1121
01-28 14:50:40.688: E/ActivityTrigger(1587): activityResumeTrigger: not whiteListedcom.pingan.aftercarmarket/com.pingan.aftercarmarket.activity.WebViewActivity/1121
01-28 14:50:40.703: E/ActivityTrigger(1587): activityResumeTrigger: not whiteListedcom.pingan.aftercarmarket/com.pingan.aftercarmarket.activity.WebViewActivity/1121
01-28 14:50:50.151: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.355: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.406: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.561: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.614: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.630: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.666: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:50.825: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:51.681: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:51.710: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:53.843: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:53.895: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:53.946: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:53.998: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:54.127: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:54.179: W/ActivityManager(1587): Missing app error report, app = com.pingan.aftercarmarket crashing = false notResponding = true
01-28 14:50:54.206: E/ActivityManager(1587): ANR in com.pingan.aftercarmarket (com.pingan.aftercarmarket/.activity.WebViewActivity)
01-28 14:50:54.206: E/ActivityManager(1587): Reason: Input dispatching timed out (com.pingan.aftercarmarket/com.pingan.aftercarmarket.inner.activity.OneInnerActivity, Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 8.  Wait queue head age: 8793.1ms.)
01-28 14:50:54.206: E/ActivityManager(1587): Parent: com.pingan.aftercarmarket/.inner.activity.OneInnerActivity
01-28 14:50:54.206: E/ActivityManager(1587):   10% 25802/com.pingan.aftercarmarket: 7.9% user + 2.4% kernel / faults: 35748 minor 5 major
01-28 14:50:54.206: E/ActivityManager(1587):   0.3% 7890/com.pingan.aftercarmarket:push: 0.1% user + 0.1% kernel / faults: 989 minor
01-28 14:50:54.257: W/InputTransport(1587): Slow Input: 9695ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13058, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239022134000, pointerCount=1
01-28 14:50:54.257: W/InputTransport(1587): Slow Input: 9681ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13060, deviceId=7, source=0x1002, action=0x2, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239036255000, pointerCount=1
01-28 14:50:54.257: W/InputTransport(1587): Slow Input: 9649ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13062, deviceId=7, source=0x1002, action=0x2, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239068996000, pointerCount=1
01-28 14:50:54.257: W/InputTransport(1587): Slow Input: 9640ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13064, deviceId=7, source=0x1002, action=0x2, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239078192000, pointerCount=1
01-28 14:50:54.257: W/InputTransport(1587): Slow Input: 9632ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13066, deviceId=7, source=0x1002, action=0x2, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239085599000, pointerCount=1
01-28 14:50:54.258: W/InputTransport(1587): Slow Input: 9624ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13068, deviceId=7, source=0x1002, action=0x1, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239022134000, eventTime=2239094193000, pointerCount=1
01-28 14:50:54.258: W/InputTransport(1587): Slow Input: 9253ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13071, deviceId=7, source=0x1002, action=0x0, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239464703000, eventTime=2239464703000, pointerCount=1
01-28 14:50:54.261: W/InputTransport(1587): Slow Input: 9192ms so far, channel 'e5800c4 Application Not Responding: com.pingan.aftercarmarket (server)' publisher ~ publishMotionEvent: seq=13073, deviceId=7, source=0x1002, action=0x1, actionButton=0x00000000, flags=0x0, edgeFlags=0x0, metaState=0x0, buttonState=0x0, xOffset=0.000000, yOffset=-1474.000000, xPrecision=1.000000, yPrecision=1.000000, downTime=2239464703000, eventTime=2239529881000, pointerCount=1

**Comment by kotori2** [comment]
the log you provided seems useless

**Comment by tianguoyan** [comment]
> the log you provided seems useless

这个bug在miui12上很普遍，问了几个用redmi k30Pro的朋友，MIUI12上都有这个bug，并且这个bug在edxposed和太极上都有。同样都是magisk禁用框架，bug就消失。

**Comment by SekiBetu** [comment]
用随机包名重装magisk和magisk hide尝试过了吗

**Comment by herolsh** [comment]
hide 测试过了，应该不是这个原因。
在安卓8.0的magisk+xposed下可以正常运行



---原始邮件---
发件人: "惜别"<notifications@github.com&gt;
发送时间: 2020年9月18日(周五) 晚上7:01
收件人: "ElderDrivers/EdXposed"<EdXposed@noreply.github.com&gt;;
抄送: "herolsh"<herolsh@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ElderDrivers/EdXposed] [BUG]  app和框架冲突，每次都卡死 (#453)




 
用随机包名重装magisk和magisk hide尝试过了吗

**Comment by SekiBetu** [comment]
> hide 测试过了，应该不是这个原因。 在安卓8.0的magisk+xposed下可以正常运行
> […](#)
> ---原始邮件--- 发件人: "惜别"<notifications@github.com&gt; 发送时间: 2020年9月18日(周五) 晚上7:01 收件人: "ElderDrivers/EdXposed"<EdXposed@noreply.github.com&gt;; 抄送: "herolsh"<herolsh@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [ElderDrivers/EdXposed] [BUG] app和框架冲突，每次都卡死 (#453) 用随机包名重装magisk和magisk hide尝试过了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

红米K30pro变焦版
MIUI 12.0.9 稳定版
安卓10

我用的交管12123的APP，每次使用一段时间就会自动退出，我刚开始也是只开启了magisk hide，后来我用随机包名重装magisk manager然后清除了交管12123APP的数据之后重启手机，一切使用正常，仅供参考

**Comment by kotori2** [comment]
should be fixed in #624 and #634
