### ISSUE TITLE
I can't use this app

### ISSUE THREAD

**Issue by Zireael61** [ElderDrivers/EdXposed#455]
Hi, I want to use hushsms but it seems doesn't working. I uploaded apk file.
[HushSms.zip](https://github.com/ElderDrivers/EdXposed/files/4136450/HushSms.zip)

I tried with last version.
Riru-Core: v19.6
EdXposed: v0.4.6.0_beta (I tried YAHFA and SandHook version)
EdXposedManager: v4.5.4
Also I used customized Magisk build.

I can use this app with systemless xposed but systemless xposed doesn't support android pie :/

Sorry for my english.

**Comment by MlgmXyysd** [comment]
@Zireael61 hushsms seems need orig xposed installer installed
and some rom(like oneplus h2/o2 os) cannot use this

**Comment by MlgmXyysd** [comment]
@Zireael61 i found a HushSMS tutorial for EdXposed(in Chinese)
https://www.coolapk.com/feed/15835225?shareKey=NjVkMTIwZTIzMTEyNWUzMzhjNjk~&shareFrom=com.coolapk.market_10.0.1

**Comment by Zireael61** [comment]
> @Zireael61 i found a HushSMS tutorial for EdXposed(in Chinese)
> https://www.coolapk.com/feed/15835225?shareKey=NjVkMTIwZTIzMTEyNWUzMzhjNjk~&shareFrom=com.coolapk.market_10.0.1

Thanks a lot :)
Worked for me
