### ISSUE TITLE
[BUG] 官方Magisk转定制版，系统被锁死

### ISSUE THREAD

**Issue by Pyrokine** [ElderDrivers/EdXposed#457]
**什么情况/What happened?**

小米MIX2S最新开发版，刷官方Magisk20.3无法使用，刷定制版20.1覆盖，Data被锁死，锁屏密码被更改，无法进入系统，刷官方Magisk20.1卸载包（没找到定制版的卸载包），手机变砖

**Xposed模块列表/Xposed Module List**

无关

**Magisk模块列表/Magisk Module List**

无关

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:YAHFA-0.4.6.0

Magisk:定制版20.1

Riru:19.6

**相关Logcat/Logcat**

砖了，啥都没了，官方没线刷包，刷降级包三清了，数据全没了
有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
@Pyrokine edxposed manager版本多少？

**Comment by Pyrokine** [comment]
> @Pyrokine edxposed manager版本多少？

4.5.4

**Comment by Pyrokine** [comment]
@MlgmXyysd 4.5.4

**Comment by MlgmXyysd** [comment]
@Pyrokine 应该是Magisk降级的问题，为什么要刷回老版本？

**Comment by Pyrokine** [comment]
@MlgmXyysd 官方版的magisk并不能用啊，刷了定制版的才能正常使用

**Comment by MlgmXyysd** [comment]
@Pyrokine 用最新的 Canary 版本

**Comment by MlgmXyysd** [comment]
@Pyrokine edxp manager 的 Canary tab

**Comment by Pyrokine** [comment]
@Pyrokine 我重装之后刷ed-alpha-0.4.6.0+magisk-custom20.1能正常使用，只是反馈一下降级导致系统锁死的问题

**Comment by MlgmXyysd** [comment]
@Pyrokine 面具降级锁死应该去 Magisk 反馈，这里只接 edxposed 相关反馈

**Comment by MlgmXyysd** [comment]
@Pyrokine 另外custom版magisk已经废弃，不再维护

**Comment by Pyrokine** [comment]
因为custom版没有issue所以才来这里反馈的
