### ISSUE TITLE
[BUG] Cannot load any modules because modules.list was not found

### ISSUE THREAD

**Issue by LastStarDust** [ElderDrivers/EdXposed#458]
**What happened?**

Installed EdExposed on a Pixel 3a with rooted android 10 (latest android version).
EdXposed modules are not working even if EdExposed Framework is shown as active.

[EdXposed screenshot](https://www.dropbox.com/s/7o4a1fqge8y1e52/edxoised.png?dl=0)
[Magisk screenshot](https://www.dropbox.com/s/h7glvu9j3iju9bg/magisk.png?dl=0)

**Xposed Module List**

[screenshot](https://www.dropbox.com/s/nenxtg9mch6ffm8/edxposed_modules.png?dl=0)

- AdBlocker Reborn 1.8.1
- MinMinGuard 2.0.9
- YouTube AdAway 4.3.3

**Magisk Module List**

[screenshot](https://www.dropbox.com/s/ktpr3oifosr2vvj/magisk_modules.png?dl=0)

- Riru - Code v19.7
- Riru - EdXposed v0.4.6.0_beta(4471) (YAHFA)
- Systemless Hosts 1.0

**Versions of EdXposed and Riru**

- EdXposed: EdXposed v0.4.6.0_beta(4471) (YAHFA)
- Riru: v19.7

**Logcat**

- [Verbose log](https://www.dropbox.com/s/4xovw2izrgl3uug/verbose.log?dl=0)
- [Modules log](https://www.dropbox.com/s/vzpbfm7uoji860o/modules.log?dl=0)

**Comment by LastStarDust** [comment]
@MlgmXyysd Why the bug report was closed? Was the report not complete enough? Have I made some mistakes? In that case, how can I solve my issue?

**Comment by MlgmXyysd** [comment]
#459

**Comment by LastStarDust** [comment]
Thank you for the clarification

**Comment by LastStarDust** [comment]
Problem solved in EdXposed v0.4.6.1
