### ISSUE TITLE
[BUG] Massive battery overheat

### ISSUE THREAD

**Issue by nift4** [ElderDrivers/EdXposed#460]
**什么情况/What happened**
Massive battery overheat

Normal: 37 °C
With EdXp: 52 °C (that's too much)

I think it's edxp's fault because when disabling it the issie was fixed.

**Xposed模块列表/Xposed Module List**
- XposedUnifiedNlp
- AnyWebView
- Burnt Toast Revived
- BubbleUPnP Audio Cast
- Secure Settings
- Greenify
- ForceDoze
**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: YAFHA 4504

Riru: v19.7

**Comment by MlgmXyysd** [comment]
@nift4 open whitelist and only add your module controlled app in

**Comment by nift4** [comment]
Audio Cast needs all apps using sound - 99% of all apps (Browser, Music, Games, Gallery (for Videos), Radio, etc). I disable it and try again with System-UI and - what is needed for AnyWebView?

**Comment by MlgmXyysd** [comment]
@nift4 i dont know, i think u should ask module author for a list

**Comment by nift4** [comment]
Last update: 999999 years ago - probably no answer. I disable it too.

**Comment by MlgmXyysd** [comment]
@nift4 ahhh, so long

**Comment by MlgmXyysd** [comment]
@nift4 u can decompile it or guess a list

**Comment by alroy214** [comment]
I think you can send a email if it's the bubbleguuum guy, he helped me on my Samsung thing, anyway if it's a different module from the cast idk

**Comment by nift4** [comment]
> I think you can send a email if it's the bubbleguuum guy, he helped me on my Samsung thing, anyway if it's a different module from the cast idk

It is but it's broken with Android 10 anyway at the moment - I have it to don't miss the update ;)

**Comment by nift4** [comment]
> @nift4 u can decompile it or guess a list

I'm not going to decompile an module that I don't use currently 😂

**Comment by nift4** [comment]
Just saw my module list again. Some more modules were enabled ^^ I updated the list above

**Comment by nift4** [comment]
Ah and I use the sepolicy PR build on my **Permissive** ROM

**Comment by nift4** [comment]
I have no modules enabled: 46 °C

**Comment by nift4** [comment]
Heating up constantly, now 47 °C

**Comment by nift4** [comment]
Whitelist enabled, only System-UI + modules allowed

**Comment by nift4** [comment]
Now 45 °C again

**Comment by nift4** [comment]
**Xposed Modules List**
Nothing enabled

**App List**
App List, White List and Pass SafetyNet enabled
Force hook modules enabled by default

**White List**
All **disabled** modules

Battery thermal sensor says 49 °C

Clearly EdXp bug

**Comment by nift4** [comment]
@MlgmXyysd

**Comment by alroy214** [comment]
Dude also chrome uses power just let it cool naturally down and see how it goes, posting every minute won't help

**Comment by nift4** [comment]
I don't use chrome lol

**Comment by nift4** [comment]
I disabled EdXp again

**Comment by nift4** [comment]
I only made examples

**Comment by nift4** [comment]
I'm not intrested in having my phone broken because of overheat 😒

**Comment by nift4** [comment]
Don't worry I stop commenting

**Comment by nift4** [comment]
On SandHook the problem does not exist.

**Comment by nift4** [comment]
@MlgmXyysd any news from your side? FYI: Someone else reported this issue with the same device.

**Comment by nift4** [comment]
It's the Moto G5 (cedric)
Without s or +

**Comment by MlgmXyysd** [comment]
unuseful infomation

**Comment by nift4** [comment]
What 🤨? Nah, it's not my problem.

**Comment by nift4** [comment]
I reopen it as new issue and when that is also invalid I don't have any intrest to continue this discussion(?).

**Comment by nift4** [comment]
#468
