### ISSUE TITLE
[BUG] Outdated version within Magisk

### ISSUE THREAD

**Issue by update-freak** [ElderDrivers/EdXposed#462]
In Magisk the old version of EdXposed (v0.4.5.1_beta) is offered for download instead of the new version (v0.4.6.0_beta)

**Comment by MlgmXyysd** [comment]
@update-freak need more stable to update to Magisk repo

**Comment by update-freak** [comment]
ok, thanks!

**Comment by update-freak** [comment]
yes, your right. With 0.4.6.0_beta I get a bootloop on my S7 Stock ROM.

**Comment by MlgmXyysd** [comment]
@update-freak u should use 0.4.6.1
