### ISSUE TITLE
[BUG] [OnePlus7TProNR] Cannot activate EdXposed: null java.lang.Class java.lang.Object.getClass()

### ISSUE THREAD

**Issue by madisonhope** [ElderDrivers/EdXposed#465]
**什么情况/What happened?**
EdXposed won't activate under YAFHA or SandHook on OnePlus 7T Pro McLaren T-Mo running canary/latest.  YAFHA reports this logcat error, SandHook reports #458 .
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Fingerface (not enabled)
Greenify (not enabled)

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
AOSP Pill v1.0
QuickSwitch v3.0.8
Riru v19.7
EdXposed v0.4.6.1 (4504)-tdgptedc YAFHA
Substratum One Thousand Twenty Two

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.1 4504 tdgptedc

Riru: v19.7

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: OnePlus
Brand: OnePlus
Device: OnePlus7TProNR
Product: OnePlus7TProNR
Model: HD1925
Fingerprint: OnePlus/OnePlus7TProNR/OnePlus7TProNR:10/QKQ1.190716.003/2001101147:user/release-keys
ROM description: OnePlus7TProNR-user 10 QKQ1.190716.003 2001101147 release-keys
Architecture: arm64-v8a
Android build: QKQ1.190716.003
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.1 (4504)-tdgptedc (YAHFA)
EdXposed api: 90.0
Riru version: v19.7 (29)
Riru api: 4
Magisk: 20.3:MAGISKSU (20300)
--------- beginning of main
--------- beginning of system
02-14 16:27:25.857   859   859 I EdXposed: onModuleLoaded: welcome to EdXposed!
02-14 16:27:25.857   859   859 I EdXposed: Start to install inline hooks
02-14 16:27:25.857   859   859 I EdXposed: Using api level 29
02-14 16:27:25.857   859   859 I EdXposed: Start to install Riru hook
02-14 16:27:25.867   859   859 I EdXposed: Riru hooks installed
02-14 16:27:26.008   859   859 I EdXposed: ART hooks installed
02-14 16:27:26.009   859   859 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
02-14 16:27:26.009   859   859 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
02-14 16:27:26.093   860   860 I EdXposed: onModuleLoaded: welcome to EdXposed!
02-14 16:27:26.093   860   860 I EdXposed: Start to install inline hooks
02-14 16:27:26.093   860   860 I EdXposed: Using api level 29
02-14 16:27:26.093   860   860 I EdXposed: Start to install Riru hook
02-14 16:27:26.132   860   860 I EdXposed: Riru hooks installed
02-14 16:27:26.307   860   860 I EdXposed: ART hooks installed
02-14 16:27:26.307   860   860 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
02-14 16:27:26.307   860   860 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
02-14 16:27:26.389   859   859 I EdXposed: using installer org.meowcat.edxposed.manager
02-14 16:27:26.390   859   859 I EdXposed: application list mode: false, using whitelist: false
02-14 16:27:26.390   859   859 I EdXposed: dynamic modules mode: false
02-14 16:27:26.390   859   859 I EdXposed: resources hook: true
02-14 16:27:26.390   859   859 I EdXposed: deopt boot image: false
02-14 16:27:26.390   859   859 I EdXposed: no module log: false
02-14 16:27:26.505   860   860 I EdXposed: using installer org.meowcat.edxposed.manager
02-14 16:27:26.505   860   860 I EdXposed: application list mode: false, using whitelist: false
02-14 16:27:26.505   860   860 I EdXposed: dynamic modules mode: false
02-14 16:27:26.505   860   860 I EdXposed: resources hook: true
02-14 16:27:26.505   860   860 I EdXposed: deopt boot image: false
02-14 16:27:26.505   860   860 I EdXposed: no module log: false
--------- beginning of crash
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.hooker.XposedInstallerHooker$1.beforeHookedMethod(XposedInstallerHooker.java:32)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:87)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:187)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at org.meowcat.bugcatcher.MeowCatApplication.onCreate(MeowCatApplication.java:20)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6647)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1600(ActivityThread.java:231)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-14 16:29:09.169 10524 10524 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-14 16:29:09.259 10524 10524 D EdXposedManager: EdXposed is not active
02-14 16:29:09.259 10524 10524 D EdXposedManager: EdXposed is not active
02-14 16:29:09.512 10524 10524 D EdXposedManager: EdXposed is not active

**Comment by Caydenz** [comment]
Exactly the same issue on my device. Sandhook doesn't work either.

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/blob/83ecd3ae97bfc3080c77b5a2b24e5f1404c5c4a7/edxp-common/src/main/java/com/elderdrivers/riru/edxp/hooker/XposedInstallerHooker.java#L32
are you still using EdXposed Installer?

**Comment by Caydenz** [comment]
I will answer your question since I probably encounter the same issue (same stacktrace...). I don't have it installed. Just EdXposed Manager 4.5.4

**Comment by Caydenz** [comment]
Looks like I got it to work after reading issue #443. I disabled riru and riru-edxposed in magisk, rebooted, uninstalled and reinstalled edxposed manager, re-enabled riru and riru-exposed and rebooted. YAHFA is active now.

**Comment by MlgmXyysd** [comment]
Known issue, will fix in 4.5.5, just downgrade to 4.5.3

**Comment by madisonhope** [comment]
@MlgmXyysd I did what @Caydenz did, now I get
```
17.884   857   857 I EdXposed-Bridge: Loading modules from /data/app/com.edison.fingerface-2uzZNcQWE8kltN_33hfPiQ==/base.apk
02-17 19:30:17.885   857  5085 W XSharedPreferences: getSharedPreferences
02-17 19:30:17.885   857  5085 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
02-17 19:30:17.886   857  5086 W XSharedPreferences: getSharedPreferences
02-17 19:30:17.886   857  5086 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
02-17 19:30:17.887   857  5087 W XSharedPreferences: getSharedPreferences
02-17 19:30:17.887   857  5087 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
02-17 19:30:17.892   857   857 I EdXposed-Bridge:   Loading class com.edison.fingerface.XposedHandler
```

**Comment by madisonhope** [comment]
Any ideas?

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd I did what @Caydenz did, now I get
> 
> ```
> 17.884   857   857 I EdXposed-Bridge: Loading modules from /data/app/com.edison.fingerface-2uzZNcQWE8kltN_33hfPiQ==/base.apk
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: getSharedPreferences
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
> 02-17 19:30:17.885   857  5085 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: getSharedPreferences
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
> 02-17 19:30:17.886   857  5086 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: getSharedPreferences
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1416)
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:748)
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
> 02-17 19:30:17.887   857  5087 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
> 02-17 19:30:17.892   857   857 I EdXposed-Bridge:   Loading class com.edison.fingerface.XposedHandler
> ```

It seems your module crash, ask module author.


btw, can you give me OnePlus7TProNR's IMEI first 8 digit?

Just for statistics (the first 8 digit of each same device are the same), user information will not be collected
