### ISSUE TITLE
[BUG] XSharedPreferences-load thread not suspended causing bootloop when hooking into ShutdownThread class

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposed#467]
**什么情况/What happened?**

Bootloops sometimes accure when hooking into `com.android.server.power.ShutdownThread` and rebooting.
It also seems that the shared preferences aren't saved correctly after coming back from the bootloop.
Happens on Samsung Pie and Q

`2020-02-17 00:39:10.970 5906-5906/? E/system_server: Timed out waiting for threads to suspend, waited for 10.000s
2020-02-17 00:39:10.970 5906-5906/? E/system_server: Thread not suspended: Thread[2,tid=5904,Runnable,Thread*=0x719d147800,peer=0x12df6090,"XSharedPreferences-load"]`

**Xposed模块列表/Xposed Module List**

Firefds Kit [Q]

**Magisk模块列表/Magisk Module List**

Ed Xposed v4.6.1
Riru 19.7

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:  v4.6.1

Riru: 19.7

**相关Logcat/Logcat**
[logs.txt](https://github.com/ElderDrivers/EdXposed/files/4212046/logs.txt)

**Comment by Firefds** [comment]
Closing, seems like a Magisk selinux issue.

**Comment by MlgmXyysd** [comment]
It's not recommended to use xsharedperf, which was lost by Google after Android pie

**Comment by NULLO0B** [comment]
> It's not recommended to use xsharedperf, which was lost by Google after Android pie

What use instead please?

**Comment by MlgmXyysd** [comment]
> > It's not recommended to use xsharedperf, which was lost by Google after Android pie
> 
> What use instead please?

1. Use files in sdcard
2. Use files in /Android/data/package/
3. Use Content Provider
4. Use files in /data/data/hooked_app_package/shared_prefs
