### ISSUE TITLE
[BUG] Xposed manager package name

### ISSUE THREAD

**Issue by duramato** [ElderDrivers/EdXposed#47]
### **什么情况/What happened?**

When using EdXposed with Xposed manager, Pókemon GO detects the xposed manager's package name  (`de.robv.android.xposed.installer`) and doesn't work, even tough it passes SafetyNet. The fix it seems to  me, is to release an xposed manager that allows to randomize the package name, just like magisk manager allows.

### **Xposed模块列表/Xposed Module List**

App Locale 2, Greenify

### **Magisk模块列表/Magisk Module List**

Busybox, energized protection, magisk manager for recovery, Riru core, Riru Ed Xposed, Systemless hosts, Viper4Android.

### **EdXposed及Riru版本/Versions of EdXposed and Riru**

**EdXposed:** 0.2.9.7_beta

**Riru:** 11

**Comment by MlgmXyysd** [comment]
The EdXposed Manager is developing, just wait.

**Comment by solohsu** [comment]
Fixed in [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)
