### ISSUE TITLE
[BUG] 加载模块失败卡启动页

### ISSUE THREAD

**Issue by captain-miao** [ElderDrivers/EdXposed#470]
**什么情况/What happened?**

1. 部分Android 10 MIUI 11 20.1.21 开发版 卡开机，需要多次重启
2. 可能跟读取存储空间有关
```java
    // sdcard 准备好了再读
    public static boolean isSdcardMount() {
        try {
            String state = android.os.Environment.getExternalStorageState();
            return android.os.Environment.MEDIA_MOUNTED.equals(state) || android.os.Environment.MEDIA_MOUNTED_READ_ONLY.equals(state);
        } catch (Throwable t) {
            if (XLogger.isEnabled()) XLogger.localError(t);
        }
        return false;
    }
```

**Xposed模块列表/Xposed Module List**

大圣净化 v2.7.20

**Magisk模块列表/Magisk Module List**

![magisk](https://user-images.githubusercontent.com/1283212/74812676-e394c400-532e-11ea-8ff1-2f8005666bff.jpg)

![ed_xp](https://user-images.githubusercontent.com/1283212/74813042-8fd6aa80-532f-11ea-8214-6e06cbb75de3.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v4.5.4

Riru:0.4.6.1

**相关Logcat/Logcat**

02-18 16:16:48.734  4266  4266 I EdXposed-Bridge: Loading modules from /data/app/com.ext.star.wars-23ZTeJmsAhGnvN-yzr0vzA==/base.apk
02-18 16:16:49.343  4266  4266 I EdXposed-Bridge:   Loading class com.ext.star.wars.x.AdHook
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp.hooker.XposedInstallerHooker$1.beforeHookedMethod(XposedInstallerHooker.java:32)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at EdHooker_.hook(Unknown Source:87)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at org.meowcat.edxposed.manager.XposedApp.onCreate(XposedApp.java:187)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at org.meowcat.bugcatcher.MeowCatApplication.onCreate(MeowCatApplication.java:20)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6550)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1400(ActivityThread.java:223)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1886)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7536)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
02-18 16:17:46.645 10812 10812 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[edxp_reboot.log](https://github.com/ElderDrivers/EdXposed/files/4223523/edxp_reboot.log)

[tombstone_02.log](https://github.com/ElderDrivers/EdXposed/files/4224764/tombstone_02.log)

**Comment by captain-miao** [comment]
一个一个排除了，也不知道哪个生效:
#### 有读取 SharedPreferences 文件出错信息
```
        if(Build.VERSION.SDK_INT < Build.VERSION_CODES.P) {
            sXSP = new XSharedPreferences(appPkg, AD.X_SP_FILE_NAME);
            sXSP.makeWorldReadable();
        }
```
#### 有读取存储空间出错信息
```
    // sdcard 准备好了再读
    public static boolean isSdcardMount() {
        try {
            String state = android.os.Environment.getExternalStorageState();
            return android.os.Environment.MEDIA_MOUNTED.equals(state) || android.os.Environment.MEDIA_MOUNTED_READ_ONLY.equals(state);
        } catch (Throwable t) {
            if (XLogger.isEnabled()) XLogger.localError(t);
        }
        return false;
    }
```
#### 方法所在的类有 static 块(来自[太极](https://taichi.cool/zh/doc/for-xposed-dev.html#%E6%96%B9%E6%B3%95%E6%8B%A6%E6%88%AA-hook))
太极在 Hook static 方法的时候，会提前初始化方法所在的类。如果这个类有 static 块，并且这个 static 块有副作用（如加载数据库，或者别的业务逻辑等）；那么可能导致 APP 内部运行逻辑不正常。因此在 Hook 带有 static 块的 static 方法的时候，需要特别小心。
请注意：如果 static 块中只做变量初始化，创建对象等，这是没有问题的。

**Comment by MlgmXyysd** [comment]
> 一个一个排除了，也不知道哪个生效:
> 
> #### 有读取 SharedPreferences 文件出错信息
> ```
>         if(Build.VERSION.SDK_INT < Build.VERSION_CODES.P) {
>             sXSP = new XSharedPreferences(appPkg, AD.X_SP_FILE_NAME);
>             sXSP.makeWorldReadable();
>         }
> ```
> 
> #### 有读取存储空间出错信息
> ```
>     // sdcard 准备好了再读
>     public static boolean isSdcardMount() {
>         try {
>             String state = android.os.Environment.getExternalStorageState();
>             return android.os.Environment.MEDIA_MOUNTED.equals(state) || android.os.Environment.MEDIA_MOUNTED_READ_ONLY.equals(state);
>         } catch (Throwable t) {
>             if (XLogger.isEnabled()) XLogger.localError(t);
>         }
>         return false;
>     }
> ```
> 
> #### 方法所在的类有 static 块(来自[太极](https://taichi.cool/zh/doc/for-xposed-dev.html#%E6%96%B9%E6%B3%95%E6%8B%A6%E6%88%AA-hook))
> 太极在 Hook static 方法的时候，会提前初始化方法所在的类。如果这个类有 static 块，并且这个 static 块有副作用（如加载数据库，或者别的业务逻辑等）；那么可能导致 APP 内部运行逻辑不正常。因此在 Hook 带有 static 块的 static 方法的时候，需要特别小心。
> 请注意：如果 static 块中只做变量初始化，创建对象等，这是没有问题的。

EdXposed 使用 YAHFA/SandHook 内核，无需特殊适配

> 方法所在的类有 static 块(来自太极)
> 太极在 Hook static 方法的时候，会提前初始化方法所在的类。如果这个类有 static 块，并且这个 static 块有副作用（如加载数据库，或者别的业务逻辑等）；那么可能导致 APP 内部运行逻辑不正常。因此在 Hook 带有 static 块的 static 方法的时候，需要特别小心。
> 请注意：如果 static 块中只做变量初始化，创建对象等，这是没有问题的。

这应该是 epic 内核兼容性差的一个 远古 bug

另 XSharedPreferences 由于 Android 上的新特性已废弃，不建议使用
