### ISSUE TITLE
[BUG] 使用模块后QQ黑屏

### ISSUE THREAD

**Issue by kaniwow** [ElderDrivers/EdXposed#471]
**什么情况/What happened?**

QQ复读机开启之后QQ黑屏无法正常运行

**Xposed模块列表/Xposed Module List**

只开了QQ复读机

**Magisk模块列表/Magisk Module List**

![Screenshot_20200221-104602](https://user-images.githubusercontent.com/16221246/74999721-0b188900-5422-11ea-93ca-42f05472b5fa.jpg)
![Screenshot_20200221-104557](https://user-images.githubusercontent.com/16221246/74999733-12d82d80-5422-11ea-84e3-732b6e5e9426.jpg)
![Screenshot_20200221-104550](https://user-images.githubusercontent.com/16221246/74999752-1a97d200-5422-11ea-9998-eb6ab8a8fb0f.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 4502

Riru: 19.7

**相关Logcat/Logcat**

![IMG_20200221_105204_440](https://user-images.githubusercontent.com/16221246/75000204-541d0d00-5423-11ea-879b-42847e3ede07.jpg)
（QQ复读机作者说是这里hook的方法栈溢出了
"com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(Unknown Source:0")
"_hooker.impl.LoadedApkCstr.afterHookedMethod"
他提供的）

**Comment by kotori2** [comment]
给一下栈溢出的调用的完整调用栈啊（
