### ISSUE TITLE
[BUG] MIUI By Xiaomi.eu cannot restart into system after installing via Magisk

### ISSUE THREAD

**Issue by gzare** [ElderDrivers/EdXposed#475]
**什么情况/What happened?**

After I finished installation via Magisk (Riru Core and Riru EdXposed by YAHFA),I did reboot.
And my phone rebooted into the fastboot mode.I tried many times,It cannot reboot into the system.

So I had to reboot into TWRP Recovery and disabled the modules.
After I disabled them,my phone works well and it reboot into the system again.

**Magisk模块列表/Magisk Module List**

Riru Core
Riru -Xposed(YAHFA)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.5.1_beta(4463) YAHFA

Riru:19.7

MIUI Version: 11.0.1 by Xiaomi.eu

**Comment by MlgmXyysd** [comment]
#459
