### ISSUE TITLE
[BUG] 小米10框架无法激活

### ISSUE THREAD

**Issue by klever1988** [ElderDrivers/EdXposed#476]
**什么情况/What happened?**

框架无法激活

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

![image](https://user-images.githubusercontent.com/56048681/75565510-09d20680-5a89-11ea-996e-81bba2debe81.png)
![image](https://user-images.githubusercontent.com/56048681/75565542-16eef580-5a89-11ea-93cd-5504f8f6ee2a.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0460

Riru: 19.7

**相关Logcat/Logcat**

[all.log](https://github.com/ElderDrivers/EdXposed/files/4267971/all.log)
[error.log](https://github.com/ElderDrivers/EdXposed/files/4267972/error.log)

试过所有通道，alpha, canary, snapchat的sandhook和yahfa都无法加载

**Comment by MlgmXyysd** [comment]
manager降级4.5.3，edxp使用canary

**Comment by klever1988** [comment]
> manager降级4.5.3，edxp使用canary

非常感谢，成功了
