### ISSUE TITLE
[BUG] 4510 and 4511 causing samsung android 10 stock roms to download mode

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposed#477]
[error-2020-03-01-06-40-26.log](https://github.com/ElderDrivers/EdXposed/files/4271467/error-2020-03-01-06-40-26.log)
[boot-2020-03-01-06-40-26.log](https://github.com/ElderDrivers/EdXposed/files/4271468/boot-2020-03-01-06-40-26.log)

**什么情况/What happened?**
With build 4510 and 4511 causing samsung stock android 10 roms to goto download mode when try to reboot device using magisk,edxposed and even system reboot option leads to download mode, i have to downgrade to byuld 4505 to make it boot.

It does show persist not detected , so not adding sepolicy patch when installing maybe that issue

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 4511 build sandhook

Riru: 19.7

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
provide Magisk module install log

**Comment by lahceneamine** [comment]
I can confirm the bug.
I've updated Sandhook and got into download mode whenever I try to boot up.
I've tried YAHFA too, same thing.
I have no TaiChi at all.

My Config :
- Samsung Galaxy S9+ G965FD (Samsung Android 10)
- Stock Kernel
- EdXposedManager v4.5.4
- Magisk v20.3

**Xposed模块列表/Xposed Module List**
- Exi for Swiftkey v2.5.3
- Firefds Kit [Q] v0.1.0.0-BETA-1
- Snaptools v2.0.0.1
- SudoHide v1.28

**Magisk模块列表/Magisk Module List**
- Bluetooth Library Patcher v1.8
- Call Recorder SKVALEX v2.1.0(3.3.3)
- Font Changer v3.0.0
- Smali Patcher v0.6.7
- substratum lite Overlay Helper v1.0.0
- Systemless Hosts v1.0

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: v0.4.6.1 (4510) (Sandhook)
Riru: v19.7

**相关Logcat/Logcat**
I'm trying to find them.

**Comment by MlgmXyysd** [comment]
@lahceneamine provide Magisk module install log

**Comment by lahceneamine** [comment]
@MlgmXyysd : I've edited my last comment with the log.

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd : I've edited my last comment with the log.

it seems u don't have valid persist partition, put sepolicy.rule in flashable zip to /data/adb/modules(_update)/riru_edxposed(_sandhook)

**Comment by lahceneamine** [comment]
It worked.
My devices booted up successfully and is working well.
The ROM came like this, I didn't touch any partition at all.

**Comment by Jasi2169** [comment]
> > @MlgmXyysd : I've edited my last comment with the log.
> 
> it seems ur device don't have valid persist partition, put sepolicy.rule in flashable zip to /data/adb/modules(_update)/riru_edxposed(_sandhook)

Issue fixed please push the 4512 build with fix for samsung android 10 stock roms

**Comment by slxxls** [comment]
i got the same problem with my note 9 can you help me fix it

**Comment by MlgmXyysd** [comment]
> i got the same problem with my note 9 can you help me fix it

https://ci.appveyor.com/api/buildjobs/97kp019ydbrcrp76/artifacts/edxp-core%2Frelease%2FEdXposed-SandHook-v0.4.6.2%20(4512)-release.zip

**Comment by slxxls** [comment]
when i flash it from recovery it will be good ^^?

**Comment by slxxls** [comment]
[magisk_log_20200302_190007.log](https://github.com/ElderDrivers/EdXposed/files/4276353/magisk_log_20200302_190007.log)
![Screenshot_20200302-190021](https://user-images.githubusercontent.com/47132028/75693723-6e26dd00-5cb8-11ea-9ffc-7ede6dcb60a2.jpg)
![Screenshot_20200302-190026](https://user-images.githubusercontent.com/47132028/75693731-7252fa80-5cb8-11ea-9635-4aae89f51dd3.jpg)
![Screenshot_20200302-190049_Settings](https://user-images.githubusercontent.com/47132028/75693734-74b55480-5cb8-11ea-9a29-d70df0f8ace7.jpg)
![Screenshot_20200302-190058_Settings](https://user-images.githubusercontent.com/47132028/75693739-75e68180-5cb8-11ea-947c-ee60b3815205.jpg)

**Comment by MlgmXyysd** [comment]
so what problem with new link?

**Comment by slxxls** [comment]
i will try now and flash it i get back with info ^^

**Comment by slxxls** [comment]
its working on my phone thanks bro your great <3

**Comment by Jasi2169** [comment]
Buikd 4512 should be pushed to magisk repo as well as moved to alpha as many dont flash canary and alpha is nightmare for samsung stock roms

**Comment by MlgmXyysd** [comment]
> Buikd 4512 should be pushed to magisk repo as well as moved to alpha as many dont flash canary and alpha is nightmare for samsung stock roms

I am testing availability on a device without a perstst partition. If it is not available for a device without a perstst partition, it will not be published on other channels
