### ISSUE TITLE
[BUG] 0.4.6.1版本导致系统设置的分割线变粗变重

### ISSUE THREAD

**Issue by yesmiley** [ElderDrivers/EdXposed#478]
**什么情况/What happened?**
如题，暂未发现功能实质性影响，仅造成不美观。
已返回0.4.5.0版本，恢复正常，同样问题的朋友可以尝试回退。
如果有相同问题的朋友，看到不妨附上截图/log供作者修复用。

**EdXposed及Riru版本/Versions of EdXposed and Riru**
Riru v19.5
EdXposed v0.4.6.1-YAHAFA

**Comment by NekoInverter** [comment]
？

**Comment by MlgmXyysd** [comment]
？

**Comment by yesmiley** [comment]
emmm就是字面意思，抱歉提供的信息不多，因为回退之后正常了，不想又刷上来复现bug了，下次更新如果还遇到再补充😅
