### ISSUE TITLE
[BUG] EdXposed Sandhook causes Bootloop

### ISSUE THREAD

**Issue by Arouraios** [ElderDrivers/EdXposed#482]
SM-G960F
Latest Magisk, Magisk Manager and TWRP.
EdXposed 4.1.6 and EdXposed manager 4.5.4
EdXposed caused boot to odin mode about a month ago. Now I reflashed Stock rom, flashed TWRP, reinstalled devbase. Tried EdXposed again today. First EdXposedManager did not recognize the framework but Magisk said Core and EdXposed were active. I tried reinstalling Magisk which lead to boot loop. I updated DevBase Custom rom which fixed boot loop. Then I reinstalled Riru Core and EdXposed and got back to download mode/odin on reboot. So I disabled EdXposed Magisk Module from Recovery and then I could boot back into Android.
Magisk/SU work fine.
Reenabling EdXposed Module leads to certain boot to download mode/odin. Are there any troubleshooting steps I should try to narrow down the issue?

**Comment by MlgmXyysd** [comment]
Canary channel #447
