### ISSUE TITLE
[BUG] 一个软件启动时不会调用handleLoadPackage

### ISSUE THREAD

**Issue by Mivik** [ElderDrivers/EdXposed#484]
**什么情况/What happened?**

[此软件](https://drive.google.com/open?id=1NA_7TW24GII7qpK8na9yLzBq6zotQ5C8) 在启动时不会调用已启用插件的handleLoadPackage方法

尽管如此，它启动时会调用到handleInitPackageResources方法，但这并不能为hook此软件带来帮助

**Xposed模块列表/Xposed Module List**

一个简单的在handleLoadesourcesPackage和handleInitPackageR时输出包名的xposed模块

**Magisk模块列表/Magisk Module List**

![Magisk模块列表](https://s2.ax1x.com/2020/03/09/8S86qx.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.1 (4510) (YAHFA)
Riru: v19.7

**相关Logcat/Logcat**

和上面描述的一样，我的插件分别注册了一个handleInitPackageResources和handleLoadPackage的hook类，并分别在被调用时输出包名到日志。但该软件启动时只有handleInitPackageResources被调用。其他软件启动时都会正常调用handleInitPackageResources和handleLoadPackage

**Comment by Mivik** [comment]
本问题由爱加密导致... 爱加密在底层hook了log函数使得log等级小于error的都不会输出，希望能帮到后来人

**Comment by xumouren1234** [comment]
我也遇到了这个问题，目前还未被解决
