### ISSUE TITLE
Android 7.1.1 support

### ISSUE THREAD

**Issue by locbox** [ElderDrivers/EdXposed#485]
Please add support to Android devices on 7.1.1 and below. There are certain situations, like currently with the Note 8 or Nexus 6p, that even though the phone can be rooted it cannot run original xposed for whatever reason. Likewise, with the Note 8 atleast, you cannot run Magisk or Xposed at all. In these situations, native apks would be great. The Note 4 has a similar issue, as edxposed won't support 6.0.1. even though the majority of the touchwiz roms for it are based off 6.0.1.

**Comment by MlgmXyysd** [comment]
EdXposed will not support 7.1.1, you can try Dramland framework(No any support here)

https://github.com/canyie/DreamlandManager/releases/download/v0.0.1-alpha/0.0.1-release.apk
https://ci.appveyor.com/project/MlgmXyysd/Dreamland/build/artifacts

**Comment by locbox** [comment]
Will this brick my device?..im seeing it's unstable messages before i even
install the framework..
