### ISSUE TITLE
[BUG] Module list not found on ASUS ROG Phone 2

### ISSUE THREAD

**Issue by SpawnIshan** [ElderDrivers/EdXposed#486]
**什么情况/What happened?**
When i updated to the latest android 10 update released for my phone yesterday from the official build, after a factory reset i tried installing magisk and edxposed. Magisk seems to work as edxposed framework is active but the xposed modules are not working. I tried searching previous threads and also installed the latest canary build 0.4.6.2 Sandhook but still the problem persists.
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Instaprefs 1.2.1
GravityBox 10.0.0 beta 6
允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
Youtube Vanced 14.12
Riru 19.7
Riru Edxposed 0.4.6.2
允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.2 Sandhook

Riru:19.7

**相关Logcat/Logcat**
[EdXposed_Verbose_20200312_220327.log](https://github.com/ElderDrivers/EdXposed/files/4325424/EdXposed_Verbose_20200312_220327.log)
[magisk_log_20200312_220933.log](https://github.com/ElderDrivers/EdXposed/files/4325426/magisk_log_20200312_220933.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[EdXposed_Module_20200312_220218.log](https://github.com/ElderDrivers/EdXposed/files/4325428/EdXposed_Module_20200312_220218.log)

**Comment by MlgmXyysd** [comment]
@SpawnIshan seems sepolicy rule not loaded

provide your persist partition info (adb shell "mount|grep persist")

**Comment by SpawnIshan** [comment]
![image](https://user-images.githubusercontent.com/50465356/76558078-aac9b400-64c2-11ea-9abb-6139ea4a319b.png)
/sbin/.magisk/block/persist on /sbin/.magisk/mirror/persist type ext4 (rw,seclabel,relatime,data=ordered)
/dev/block/sda2 on /mnt/vendor/persist type ext4 (rw,seclabel,nosuid,nodev,noatime,data=ordered)

This is what i got when i ran the code you mentioned above, is it correct?

**Comment by SpawnIshan** [comment]
I tried finding the folder in the system  and found the file with modules.list, tried uninstalling edxposed via the uninstaller and installed v0.4.6.1 by yahfa from magisk but still have the same issue with running the modules.
![Screenshot_20200321-124754700](https://user-images.githubusercontent.com/50465356/77221747-93e62a00-6b72-11ea-9ea2-3f321b8fe92e.jpg)

**Comment by MlgmXyysd** [comment]
try remove "/data/adb/modules/riru_edxposed/sepolicy.rule"

**Comment by SpawnIshan** [comment]
Thank you bro, it worked. Deleted the file and did a reboot and edxposed was back.
