### ISSUE TITLE
[BUG] 0.4.6.1 / LOS 17.1 Unable to Boot

### ISSUE THREAD

**Issue by HarnickA** [ElderDrivers/EdXposed#488]
### **What happened?**
Samsung S8 (herolte) does not boot past "[Powered by Android](https://www.androidcentral.com/sites/androidcentral.com/files/styles/w830_wm_brw/public/article_images/2017/05/galaxy-s8-boot-screen.jpg)" splash.
LineageOS 17.1 / Android Q.
Both Sandhook and YAHFA do not boot.
Maybe related to #464 as SELinux is stuck as permissive. Seems to work on LOS 17.1 GSIs.
Tested with both Magisk 20.3 and your custom-built Magisk, but no dice.

### **Xposed Module List**
None

### **Magisk Module List**
- Riru Core
- EdXposed Sandhook / YAHFA

### **Versions of EdXposed and Riru**
- Riru v19.7
- EdXposed v0.4.6.1

### **Logcat**
~~Not available. ADB logcat returns `waiting for device` indefinitely.~~
ADB logcat is very inconsistent. Will try to output.

### It can help us to locate issue, must use our logcat module
Unable to install EdXposed Modules.

**Comment by MlgmXyysd** [comment]
Try to use canary channel

**Comment by HarnickA** [comment]
Canary channel works fine, as far as I can see. It activated fine, and my modules are working.
