### ISSUE TITLE
[Info] Updating module require double reboot

### ISSUE THREAD

**Issue by etmatrix** [ElderDrivers/EdXposed#493]
**What happened?**
I'm developing a test app for Xposed/EdXposed, every test apk is signed and compiled for release.
Every time I upgrade the app, on first reboot the app/module is not working but is enabled on EdXposed Manager, so I need disable the module, reboot and enable the module and reboot. For each upgrade I need to do 3 reboot but I can reduce to 2. 
Is it normal?

**Xposed Module List**
Only my test module

**Magisk/Magisk Module List**
Riru Core
EdXposed YAHFA

**Versions of EdXposed and Riru**
Magisk: 20.3
Riru Core: 19.7
Riru EdXposed: 0.4.6.1 YAHFA

**Comment by MlgmXyysd** [comment]
@etmatrix Just close and open module's switch, then reboot 1

**Comment by etmatrix** [comment]
@MlgmXyysd thanks, so it works.
EdXposedManager has already a receiver for PACKAGE_ADDED, PACKAGE_CHANGED and PACKAGE_REMOVED and should disable and enable module automatically.

**Comment by Mikanoshi** [comment]
It should, but it's not allowed to by Android.
https://github.com/ElderDrivers/EdXposedManager/issues/28
