### ISSUE TITLE
[BUG] 0.4.6.2 with XinternalSD will cause bootloop

### ISSUE THREAD

**Issue by a0193143** [ElderDrivers/EdXposed#495]
**什么情况/What happened?**
When XinternalSD module is enabled, will take 5mins to boot then bootloop
But no problem in 0.4.5.1

**Xposed模块列表/Xposed Module List**
XinternalSD 4.8

**Magisk模块列表/Magisk Module List**
Riru - Core
Riru - Edxposed
Magisk Manager for Recovery Mode

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: 0.4.6.1 (4510)、0.4.6.2(4529)
Riru: 19.8

**相关Logcat/Logcat**
[log.zip](https://github.com/ElderDrivers/EdXposed/files/4463995/log.zip)

Updated: Figure out that was USB3.0 problem make me can't get the log

**Comment by Senliast** [comment]
@a0193143 remove the modules, so that the phone boots. enable developer options, allow adb. connect the phone to pc, download platform tools, open cmd in the directory of platform tools, type "adb logcat", on the phone, check the checkbox "always allow from this pc".  then, install module, reboot the phone, on pc type "adb logcat".

**Comment by a0193143** [comment]
> 
> 
> @a0193143 remove the modules, so that the phone boots. enable developer options, allow adb. connect the phone to pc, download platform tools, open cmd in the directory of platform tools, type "adb logcat". on the phone, check the checkbox "always allow from this pc" and grant permission. then, install module, reboot the phone, on pc type "adb logcat".

I got the log before reboot, but once I reboot my phone, logcat stopping, then I tried adb logcat again during booting, it just showing "waiting for device".

btw my phone is Asus Max Pro in stock Oreo ROM

**Comment by Senliast** [comment]
ohh man i also want a oreo or pie ROM, but i must use the shitty Android 10 because my phone is new. and EdXposed is running just terrible with Android 10.

**Comment by a0193143** [comment]
> 
> 
> ohh man i also want a oreo or pie ROM, but i must use the shitty Android 10 because my phone is new. and EdXposed is running just terrible with Android 10.

I found that was USB3.0 port problem, now I got the log.

**Comment by cscomic** [comment]
same problem here, with XZ1, Android 8.0
phone will boot loop at boot animation, and adb device not appear.
in twrp can not get last_kmsg, it doesn't there.
here is the kernel log and recovery log.
[kernel_log.zip](https://github.com/ElderDrivers/EdXposed/files/4542966/kernel_log.zip)

**Comment by cscomic** [comment]
> @a0193143 remove the modules, so that the phone boots. enable developer options, allow adb. connect the phone to pc, download platform tools, open cmd in the directory of platform tools, type "adb logcat". on the phone, check the checkbox "always allow from this pc" and grant permission. then, install module, reboot the phone, on pc type "adb logcat".

But actually, adb device not connect to PC while boot loop in boot animation stage, even cannot get kernel log through twrp.

**Comment by kotori2** [comment]
Looks like a module-specific issue. It doesn't specify a user before requesting storage location. 
```
04-11 11:46:24.016  1366  1366 E AndroidRuntime: Error reporting WTF
04-11 11:46:24.016  1366  1366 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.IActivityManager.handleApplicationWtf(android.os.IBinder, java.lang.String, boolean, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.wtf(RuntimeInit.java:332)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at android.util.Log$1.onTerribleFailure(Log.java:110)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:304)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at android.util.Log.wtf(Log.java:294)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at android.os.Environment.throwIfUserRequired(Environment.java:919)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at android.os.Environment.getExternalStorageDirectory(Environment.java:456)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.pyler.xinternalsd.XInternalSD.handleLoadPackage(XInternalSD.java:185)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.elderdrivers.riru.edxp._hooker.impl.StartBootstrapServices.beforeHookedMethod(StartBootstrapServices.java:36)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:281)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_0(MethodHookerStubs64.java:78)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:396)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:274)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-11 11:46:24.016  1366  1366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:787)
```
