### ISSUE TITLE
[BUG] SandHook版的，beforeHookedMethod方法报错时不会打印错误日志

### ISSUE THREAD

**Issue by 253551464** [ElderDrivers/EdXposed#496]
![Screenshot_2020-03-24-18-39-58-262_aide ui1](https://user-images.githubusercontent.com/36783515/77416573-f7848780-6dfe-11ea-8234-42f23691d911.jpg)
![Screenshot_2020-03-24-18-40-16-985_org meowcat edxposed manager](https://user-images.githubusercontent.com/36783515/77416580-fa7f7800-6dfe-11ea-9557-b44468f55b62.jpg)

**Comment by YoYoJassie** [comment]
Divide by zero is a issue in all programming language u shud not use it.

**Comment by 253551464** [comment]
> Divide by zero is a issue in all programming language u shud not use it.

I know, but that's not the point. The point is that it doesn't print error logs

**Comment by 253551464** [comment]
> Divide by zero is a issue in all programming language u shud not use it.

@YoYoJassie 
I know, but that's not the point. The point is that it doesn't print error logs

**Comment by Palatis** [comment]
in fact **NOTHING** actually print any logs for me...
either before or after hooks.

I just do my own try-catch-log, anyway.

**Comment by 253551464** [comment]
com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:357)

![IMG_20200405_200011](https://user-images.githubusercontent.com/36783515/78498583-c6e90a00-777d-11ea-86a7-0075db0d75e4.jpg)

少了行代码，望尽快修复

**Comment by MlgmXyysd** [comment]
Fixed https://github.com/ElderDrivers/EdXposed/commit/c7509151fb1b1a56d8ac4583fea7f56ff5eaa734
