### ISSUE TITLE
Google Chrome issues

### ISSUE THREAD

**Issue by Pohlster** [ElderDrivers/EdXposed#497]
Latest version of Google chrome will open then immediately close. Older versions work fine. It doesn't seem to crash just closes the window, every time I try to reopen chrome it shows what had been open. I have two modules installed hidden core module and hide usb debug. Using the latest version of android 10. On the google pixel 2xl.

**Comment by MlgmXyysd** [comment]
@Pohlster Add Chrome to App List(Black), It seems Chrome has a legacy bug with Xposed Bridge(not EdXposed)

**Comment by Palatis** [comment]
I dunno, works for me (both Stable and Canary...)

EdXposed - 0.4.6.2 (4525) [YAHFA]
Chrome Stable - com.android.chrome - 80.0.3987.149
Chrome Canary - com.chrome.canary - 83.0.4098.3

**Comment by Pohlster** [comment]
Ads ng chrome to blacklist solved the issue

**Comment by kotori2** [comment]
Can't reproduce even if Chrome if not in blacklist. Is that a Pixel 2 XL exclusive bug?

**Comment by zyf0330** [comment]
This method doesn't work.
I have tried disable application list feature, enable application list and black list excluding chrome and webview, but chrome still closes after open immediately.
My phone is OnePlus 8T and use yafha 4564.
