### ISSUE TITLE
[BUG] why edxposed manager report always selinux enforcing?

### ISSUE THREAD

**Issue by andigenn** [ElderDrivers/EdXposed#498]
What happened
why edxposed manager report always selinux enforcing? (See screenshots)

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.

4.6.2 sandhook

Riru: 19.7

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
Rough inspection, waiting for perfection
