### ISSUE TITLE
Can't Pass Safety Net Check

### ISSUE THREAD

**Issue by drandrew1983** [ElderDrivers/EdXposed#501]
**什么情况/What happened?**: CAN'T PASS SAFETY NET CHECK

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**: 
- 3C All-in-One Toolbox
- Card Emulator Pro
- Device ID Masker Lite
- EdXposed Manager
- GravityBox [Q]
- Lucky Patcher
- MinMinGuard
- Phone Number Fix

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
- Busybox for Android NDK
- L Speed @LSpeedDiscussion
- OxyMod
- Riru (Riru-Core)
- Riru - EdXosed (YAHFA)
- Samli Patcher
- Systemless Hosts
- YouTube Vanced

允许截图/Screenshot allowed
![Screenshot_20200404-192652](https://user-images.githubusercontent.com/33606175/78454858-bd8f6d00-76ab-11ea-96ca-d4db103e72bd.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.1 (4510) (YAHFA)

Riru: Riru-Core v19.7

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
Can't find any logcat module on the website. logs in EdXposed shows cannot read log: EACCES (Permission denied) although I granted storage & superuser permissions

**Comment by MlgmXyysd** [comment]
#500
