### ISSUE TITLE
[BUG] ONEPLUS 7 PRO SHOWING NOT INSTALLED

### ISSUE THREAD

**Issue by JReverse** [ElderDrivers/EdXposed#502]
**What happened?**
SHOWING NOT INSTALLED

**Xposed Module List**
None

*Versions of EdXposed and Riru**
EdXposed: Latests

Riru:19.8

**Comment by baj24** [comment]
Same issue here.

**Comment by tardeaux** [comment]
It's coming up active on my OP7pro - here's what might be different:

OxygenOS 10.3.2 w/ Kirisakura 1.9.1 + companion module
EdExposed Manager 4.5.7 (45700)
Built EdExposed via forking and merging your Snapchat edits
SandHook version (haven't tried Yahfa)
Started with Riru 19.7, didn't see 19.8 until after updating Xposed
Installed as Magisk module update, did not remove my previous 4.6.1 module.

**Comment by datsoy** [comment]
uninstall edxposed module and manager, reboot.
install edxposed module, reboot
their should be a stub for edxposed manager now, then update/install it to latest manager. this works for me.

**Comment by gruber013** [comment]
Same issue on OnePlus 5.

**Comment by Thargarius** [comment]
> uninstall edxposed module and manager, reboot.
> install edxposed module, reboot
> their should be a stub for edxposed manager now, then update/install it to latest manager. this works for me.

thank you, this was the perfect solution !!!
