### ISSUE TITLE
[BUG] MOTO G7 Plus - unofficial Lineage OS 16.1 - null pointer dereference during boot within zygote64

### ISSUE THREAD

**Issue by Tutul-** [ElderDrivers/EdXposed#504]
**What happened?**

Since 4.6.X I get stuck during the boot process. zygote64 crash again and again. Devices doesn't reboot but keep trying to start zygote64. Didn't have any problems with 4.5.x and the crash happen with or without any module enabled. Dalvik cache cleaned for the logcat test.

**Xposed Module List**

- Greenify
- Statusbar Download Progress
- NoQSInLockScreen

**Magisk Module List**

- Fdroid-Priv
- busybox-ndk
- Vanced
- mm (recovery script)
- riru
- riru edxposed (sandyhook but same problem with YAHFA)
- riru storage redirect
- Single User

**Versions of EdXposed and Riru**

EdXposed: 0.4.6.2 (0.4.6.1 as well)

Riru: 19.8 (19.7 as well)

**Logcat**

--------- beginning of crash
04-06 06:19:27.117   789   789 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 789 (main), pid 789 (main)
04-06 06:19:27.161  1603  1603 I chatty  : uid=0(root) crash_dump64 expire 3 lines
04-06 06:19:27.162  1011  1011 I /system/bin/tombstoned: received crash request for pid 789
04-06 06:19:27.175  1603  1603 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 06:19:27.175  1603  1603 F DEBUG   : LineageOS Version: '16.0-20200201-UNOFFICIAL-lake'
04-06 06:19:27.176  1603  1603 F DEBUG   : Build fingerprint: 'motorola/lake/lake:9/PPWS29.98-111-9/d601:user/release-keys'
04-06 06:19:27.176  1603  1603 F DEBUG   : Revision: 'pvt'
04-06 06:19:27.176  1603  1603 F DEBUG   : ABI: 'arm64'
04-06 06:19:27.176  1603  1603 F DEBUG   : pid: 789, tid: 789, name: main  >>> zygote64 <<<
04-06 06:19:27.176  1603  1603 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-06 06:19:27.176  1603  1603 F DEBUG   : Cause: null pointer dereference
04-06 06:19:27.176  1603  1603 F DEBUG   :     x0  00000000707242e0  x1  0000007fc0dfe7d8  x2  0000007fc0dfe7d8  x3  000000792e814c00
04-06 06:19:27.176  1603  1603 F DEBUG   :     x4  0000007fc0dfec10  x5  0000007927e901fa  x6  0000000000008000  x7  23ff3a71646a6d68
04-06 06:19:27.176  1603  1603 F DEBUG   :     x8  0000000000000000  x9  0000000000000000  x10 0000000000430000  x11 0000000000000000
04-06 06:19:27.176  1603  1603 F DEBUG   :     x12 000000792e3ba530  x13 000000792e3ba584  x14 000000792e3ba5e4  x15 0000000000000000
04-06 06:19:27.176  1603  1603 F DEBUG   :     x16 0000007fc0dfe7d8  x17 0000000000000000  x18 0000000000000000  x19 00000000707242e0
04-06 06:19:27.176  1603  1603 F DEBUG   :     x20 00000079b429e5e0  x21 000000792e7fb000  x22 0000007fc0dfea70  x23 0000007927e901fa
04-06 06:19:27.176  1603  1603 F DEBUG   :     x24 0000000000000004  x25 00000079b429e5e0  x26 000000792e814ca0  x27 0000000000000001
04-06 06:19:27.176  1603  1603 F DEBUG   :     x28 0000000000000000  x29 0000007fc0dfe7b0
04-06 06:19:27.176  1603  1603 F DEBUG   :     sp  0000007fc0dfe780  lr  000000792e766cec  pc  000000792e766d50
04-06 06:19:27.177  1603  1603 F DEBUG   : 
04-06 06:19:27.177  1603  1603 F DEBUG   : backtrace:
04-06 06:19:27.177  1603  1603 F DEBUG   :     #00 pc 0000000000045d50  /system/lib64/libriru_edxp.so
04-06 06:19:27.177  1603  1603 F DEBUG   :     #01 pc 0000000000003cec  /data/dalvik-cache/arm64/system@framework@edxp.jar@classes.dex (offset 0x3000)
[...]
04-06 06:19:29.103  1852  1852 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 06:19:29.103  1852  1852 F DEBUG   : LineageOS Version: '16.0-20200201-UNOFFICIAL-lake'
04-06 06:19:29.103  1852  1852 F DEBUG   : Build fingerprint: 'motorola/lake/lake:9/PPWS29.98-111-9/d601:user/release-keys'
04-06 06:19:29.103  1852  1852 F DEBUG   : Revision: 'pvt'
04-06 06:19:29.103  1852  1852 F DEBUG   : ABI: 'arm64'
04-06 06:19:29.103  1852  1852 F DEBUG   : pid: 1644, tid: 1644, name: main  >>> zygote64 <<<
04-06 06:19:29.103  1852  1852 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
04-06 06:19:29.103  1852  1852 F DEBUG   : Cause: null pointer dereference
04-06 06:19:29.103  1852  1852 F DEBUG   :     x0  00000000707242e0  x1  0000007fe3098578  x2  0000007fe3098578  x3  0000007b9e414c00
04-06 06:19:29.103  1852  1852 F DEBUG   :     x4  0000007fe30989b0  x5  0000007b97b181fa  x6  0000000000008000  x7  23ff3a71646a6d68
04-06 06:19:29.103  1852  1852 F DEBUG   :     x8  0000000000000000  x9  0000000000000000  x10 0000000000430000  x11 0000000000000000
04-06 06:19:29.103  1852  1852 F DEBUG   :     x12 0000007b9e0bc530  x13 0000007b9e0bc584  x14 0000007b9e0bc5e4  x15 0000000000000000
04-06 06:19:29.103  1852  1852 F DEBUG   :     x16 0000007fe3098578  x17 0000000000000000  x18 0000000000000000  x19 00000000707242e0
04-06 06:19:29.103  1852  1852 F DEBUG   :     x20 0000007c23f4c5e0  x21 0000007b9e3e0000  x22 0000007fe3098810  x23 0000007b97b181fa
04-06 06:19:29.103  1852  1852 F DEBUG   :     x24 0000000000000004  x25 0000007c23f4c5e0  x26 0000007b9e414ca0  x27 0000000000000001
04-06 06:19:29.103  1852  1852 F DEBUG   :     x28 0000000000000000  x29 0000007fe3098550
04-06 06:19:29.103  1852  1852 F DEBUG   :     sp  0000007fe3098520  lr  0000007b9e34bcec  pc  0000007b9e34bd50
04-06 06:19:29.104  1852  1852 F DEBUG   : 
04-06 06:19:29.104  1852  1852 F DEBUG   : backtrace:
04-06 06:19:29.104  1852  1852 F DEBUG   :     #00 pc 0000000000045d50  /system/lib64/libriru_edxp.so
04-06 06:19:29.104  1852  1852 F DEBUG   :     #01 pc 0000000000003cec  /data/dalvik-cache/arm64/system@framework@edxp.jar@classes.dex (offset 0x3000)

**Comment by kotori2** [comment]
Please grab logs again with debug build.

**Comment by Tutul-** [comment]
I'll do that during the week-end

**Comment by Tutul-** [comment]
Ok I just realize that it was the old ticket still open.
The problem was resolved with a next release.
