### ISSUE TITLE
[BUG] 从2.8版本开始特定操作就会重启

### ISSUE THREAD

**Issue by seraph758** [ElderDrivers/EdXposed#51]
**什么情况/What happened?**

开机过会自动重启

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed
[bootloop-1970-02-16-08-22-54.log](https://github.com/ElderDrivers/EdXposed/files/2817444/bootloop-1970-02-16-08-22-54.log)
![_20190131214623](https://user-images.githubusercontent.com/10000026/52058277-13492080-25a2-11e9-83a0-35c9e8ab6666.jpg)
比如勾选绿色守护那个选项必定会重启

**Magisk模块列表/Magisk Module List**

![_20190131215144](https://user-images.githubusercontent.com/10000026/52058457-6de27c80-25a2-11e9-97fc-3c29dde7a922.jpg)

**Comment by zjhzsz** [comment]
me 2
