### ISSUE TITLE
[REQUEST] EdXposed module features settings

### ISSUE THREAD

**Issue by Tutul-** [ElderDrivers/EdXposed#514]
It's not a bug but the module make us look like having XposedManager and it trigger RootBeer "Root clocking detection". Maybe the manager should give us settings for that module so we can select what we want to enable (like keep the background restriction).

RootBeer system is used by some app to detect root system (sometimes next to safetyNet).

**Comment by MlgmXyysd** [comment]
These settings have been added to the latest source code and are being tested for stability. You can compile them if necessary
