### ISSUE TITLE
Permission denied when read file APK [BUG] 

### ISSUE THREAD

**Issue by erkie24** [ElderDrivers/EdXposed#516]
**什么情况/What happened?**

When accessing File and read it with FileInputStream on handleLoadPackage, I got Permission Denied, the File is an APK with permission 660 and file location is on External Directory. I tried use OS Nougat with Rovos Xposed and it works.

**Xposed模块列表/Xposed Module List**

Only my own module

**Magisk模块列表/Magisk Module List**

Edxposed and Riru

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.2

Riru: 19.8

**相关Logcat/Logcat**

Permission Denied

**Comment by Palatis** [comment]
handleLoadPackage() is executed with app uid, and O+ platforms has more restrict SELinux policy than N.
basically you can't access files directly outside some very limited places.

what were you trying to do?
