### ISSUE TITLE
[BUG] Edxposed is active but Xposed apps cannot detect Edxposed in Riru 20.1

### ISSUE THREAD

**Issue by JohnGLFour** [ElderDrivers/EdXposed#517]
**什么情况/What happened?**

While in Exposed Manager of latest version, it says Edxposed is active but opening Xposed apps says Edxposed isn't active.

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

GravityBox v10.0.0-Beta6
HiddenCore Module v1.7
Scoop v2.0.3
XPrivacyLua v1.27

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

![Screenshot_20200421-182017_Magisk_Manager](https://user-images.githubusercontent.com/17681926/79855034-ec9b2380-83b9-11ea-97e7-4cc1670a6603.png)
![Screenshot_20200421-182025_Magisk_Manager](https://user-images.githubusercontent.com/17681926/79854929-c5445680-83b9-11ea-859b-a41bd8bbf5ea.png)

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.2 (4529)

Riru: v20.1

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
Downgrade Magisk to stable
