### ISSUE TITLE
[BUG] @libcore.api.CorePlatformApi  此注解下都方法hook问题

### ISSUE THREAD

**Issue by huacangliang** [ElderDrivers/EdXposed#518]
**什么情况/What happened?**

@libcore.api.CorePlatformApi  使用这个注解的系统类的方法hook后未正确执行，表现为hook无报错、但是执行到方法时未调用invoke方法

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by Palatis** [comment]
give some examples of @CorePlatformApi annotated methods so we can test?

**Comment by huacangliang** [comment]
iobridge 这个类的10.0版本的open方法可以测试
