### ISSUE TITLE
EdXposed Framework is active but modules.list was not found (the file exists at this location)

### ISSUE THREAD

**Issue by MisiekDP** [ElderDrivers/EdXposed#519]
###### Include the following:
 - EdXposed Version: `0.4.6.3 (4545) (YAHFA)`
 - Android Version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 7 Pro`
 - EdXposed Manager Version: `4.5.7`
- Magisk: `e219867c (20403)`
- Magisk Manager: `765d5d97 (283)`
- Own update channel: `https://raw.githubusercontent.com/topjohnwu/magisk_files/canary/debug.json`
 
###### Reproduction Steps

1. Updated Magisk to the new version.
2. Bootloop.
3. Disabled all Magisk modules using _Magisk Modelu Disabler.zip_ (via TWRP).
4. Rebooted to OxygenOS and activated a few modules.
5. Activated all modules succesfull.
6. EdXposed can't load modules.list.

###### Additional information

In a previous version of Magiska I had to add my own update channel. In current version of Magisk (new, after today's update) added channel doesn't work (it doesn't cause finding modules.list file).
In addition, after uploading an earlier version of Magisk (stable) the modules.list file is still not found.

###### Actual Result

- EdXposed_Modules:
`--------- beginning of main
--------- beginning of system
04-20 11:24:13.948   827   827 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
--------- beginning of crash
04-20 11:24:34.314   828   828 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found`

- EdXposed_Verbose:
`--------- beginning of main
--------- beginning of system
04-20 11:24:11.702   827   827 I EdXposed: onModuleLoaded: welcome to EdXposed!
04-20 11:24:11.702   827   827 I EdXposed: Start to install inline hooks
04-20 11:24:11.702   827   827 I EdXposed: Using api level 29
04-20 11:24:11.702   827   827 I EdXposed: Start to install Riru hook
04-20 11:24:11.711   827   827 I EdXposed: Riru hooks installed
04-20 11:24:11.788   828   828 I EdXposed: onModuleLoaded: welcome to EdXposed!
04-20 11:24:11.788   828   828 I EdXposed: Start to install inline hooks
04-20 11:24:11.788   828   828 I EdXposed: Using api level 29
04-20 11:24:11.788   828   828 I EdXposed: Start to install Riru hook
04-20 11:24:11.798   828   828 I EdXposed: Riru hooks installed
04-20 11:24:11.802   827   827 I EdXposed: using installer org.meowcat.edxposed.manager
04-20 11:24:11.803   827   827 I EdXposed: data path prefix: /data/user_de/0/
04-20 11:24:11.803   827   827 I EdXposed:   application list mode: false
04-20 11:24:11.803   827   827 I EdXposed:     using whitelist: false
04-20 11:24:11.803   827   827 I EdXposed:   dynamic modules mode: false
04-20 11:24:11.803   827   827 I EdXposed:   resources hook: true
04-20 11:24:11.803   827   827 I EdXposed:   deopt boot image: false
04-20 11:24:11.803   827   827 I EdXposed:   no module log: false
04-20 11:24:11.803   827   827 I EdXposed:   hidden api bypass: true
04-20 11:24:11.807   827   827 I EdXposed: ART hooks installed
04-20 11:24:11.808   827   827 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
04-20 11:24:11.808   827   827 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
04-20 11:24:12.112   828   828 I EdXposed: using installer org.meowcat.edxposed.manager
04-20 11:24:12.113   828   828 I EdXposed: data path prefix: /data/user_de/0/
04-20 11:24:12.113   828   828 I EdXposed:   application list mode: false
04-20 11:24:12.113   828   828 I EdXposed:     using whitelist: false
04-20 11:24:12.113   828   828 I EdXposed:   dynamic modules mode: false
04-20 11:24:12.113   828   828 I EdXposed:   resources hook: true
04-20 11:24:12.113   828   828 I EdXposed:   deopt boot image: false
04-20 11:24:12.113   828   828 I EdXposed:   no module log: false
04-20 11:24:12.113   828   828 I EdXposed:   hidden api bypass: true
04-20 11:24:12.116   828   828 I EdXposed: ART hooks installed
04-20 11:24:12.117   828   828 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
04-20 11:24:12.117   828   828 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
04-20 11:24:13.948   827   827 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
04-20 11:24:14.118  1600  1600 E EdXposed: mmap failed, errno = Permission denied
04-20 11:24:14.118  1600  1600 E EdXposed: cannot hook method
04-20 11:24:14.119  1600  1600 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
04-20 11:24:14.119  1600  1600 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3097)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:637)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:522)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-20 11:24:14.119  1600  1600 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
04-20 11:24:16.430  1600  1600 E EdXposed: mmap failed, errno = Permission denied
04-20 11:24:16.430  1600  1600 E EdXposed: cannot hook method
04-20 11:24:16.430  1600  1600 E EdXposed: error occur when generating dex. dexDir=null
04-20 11:24:16.430  1600  1600 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:136)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:9225)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:461)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:238)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:55)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2413)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2356)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2327)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2217)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7208)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7495)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8425)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1013)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:540)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
04-20 11:24:16.430  1600  1600 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
--------- beginning of crash
04-20 11:24:34.314   828   828 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
04-20 11:24:37.129  5562  5562 D EdXposedManager: ApplicationList: Force add modules to list`

###### Logs files

[EdXposed_Verbose_20200420_114404.txt](https://github.com/ElderDrivers/EdXposedManager/files/4502771/EdXposed_Verbose_20200420_114404.txt)
[EdXposed_Modules_20200420_114418.txt](https://github.com/ElderDrivers/EdXposedManager/files/4502772/EdXposed_Modules_20200420_114418.txt)

**Comment by pointydev** [comment]
This issue appears to be fixed as of Magisk 2468f5a6 (20406). See topjohnwu/Magisk#2715.

**Comment by MisiekDP** [comment]
EdXposed now works 😊 Thanks!
