### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by davidt123456** [ElderDrivers/EdXposed#52]
Hi,

I have the same issue as many others - my xposed installer says that "Xposed is not compatible with Android SDK 28 or with architecture of the processor (arm64-v8a)".

Xposed SDK28 was not published yet, so do I need to flash some older version?

Or how does it work? The Xposed SDK 27 file had around 8 MB. Now, the installation packets are less than 1MB altogether, I guess something is missing in the installation manual.

Tx

Edit: Samsung S9, Android 9.0, rooted, SoLdieR9312s ROM

**Comment by cwkfr** [comment]
Try to reboot your phone

**Comment by zhenchao** [comment]
Read README.md

https://github.com/ElderDrivers/EdXposed/blob/master/README.md

**Comment by zhenchao** [comment]
For Samsung devices, there are some problems that prevent it from working.

**Comment by davidt123456** [comment]
TX for reply. I appreciate the work you are doing. Are the problems resolvable or is it dead end? Just to understand whether we should wait or not to have false hope. Thanks.

**Comment by MlgmXyysd** [comment]
1 Magisk
2 Riru
3 EdXposed
4 Installer
(It can not hook resources, so size is smaller than original ver.)

**Comment by davidt123456** [comment]
The problem is with Samsung S9

**Comment by solohsu** [comment]
Same with #39

**Comment by farissyf30** [comment]
This problem also on redmi 5 plus, i am using pixelexperience pie.

**Comment by GHOST696900** [comment]
How to flash xposed on sdk32.
My asus Zenfone 5z???
