### ISSUE TITLE
NOTICE: HOW YOU CAN USE SNAPCHAT WITH EDEXPOSED WITH NEW SAFETYNET 

### ISSUE THREAD

**Issue by EduardJipa** [ElderDrivers/EdXposed#520]
Basically just completely uninstall edxposed & magisk, which will delete TWRP too, then boot & reset the caches and delete app data for:

- Google Play Store
- Google Play Services
- Google Services Framework
- Google Pay
- Snapchat

Reboot, log in to snapchat (It may fail a few times, worked 3rd try in for me)

May work for other apps such as google pay or netflix

(Also sorry if this is the wrong section, just wanted to help others in the same situation as I was)

**Comment by thebenjibenji** [comment]
Or just have magisk hidden (toggle) and apk renamed and add the apps you mentioned to the list in magisk, disable riru/yahfa/sandhook in magisk, reboot and clear cache/data in snapchat, it should let you login. Then re-enable riru edxposed and don't logout! 
I have: Magisk 20407, Manager 283, EdXposed Manager 45700, riru core 21.1(34), EdXposed 4548 (SH), Android 10
Note: I did add snapchat to the application blacklist in edxposed, (dunno if this does anything), I have the safetynet pass for edxposed toggled and the module (hiddenCore Module) for it too.
![5672347 - Copy](https://user-images.githubusercontent.com/25398467/80851449-4c6cb680-8c65-11ea-8e4f-678ff5e10ef3.jpg)
![7645324 - Copy](https://user-images.githubusercontent.com/25398467/80851452-4d9de380-8c65-11ea-8b99-d9beca80267f.jpg)
![94235634 - Copy](https://user-images.githubusercontent.com/25398467/80851454-4e367a00-8c65-11ea-8bd5-6f14f6a7ba9f.png)
![230083234 - Copy](https://user-images.githubusercontent.com/25398467/80851455-4ecf1080-8c65-11ea-9b8c-2643a7d32787.png)
![1435654654 - Copy](https://user-images.githubusercontent.com/25398467/80851456-4f67a700-8c65-11ea-89f7-c9b12e16adfa.jpg)
![5437685345 - Copy](https://user-images.githubusercontent.com/25398467/80851459-5098d400-8c65-11ea-983b-f576ac749b51.png)
![9876234889 - Copy](https://user-images.githubusercontent.com/25398467/80851461-51316a80-8c65-11ea-8a66-288f3d4f8186.png)
![76956734532 - Copy](https://user-images.githubusercontent.com/25398467/80851462-52629780-8c65-11ea-8f4b-9b8f5a193855.png)
