### ISSUE TITLE
[BUG] UNINSTALLING DOESN'T FIX SAFETY NET

### ISSUE THREAD

**Issue by Soundpad** [ElderDrivers/EdXposed#522]
[BUG] UNINSTALLING DOESN'T FIX SAFETY NET

**Comment by QkiZMR** [comment]
Try clear data for Google Play store and Google Services apps.

**Comment by EhsanYE** [comment]
Yes i Confirm, Even Tried clear data for Google Play store and Google Services apps And Didnt Work...

**Comment by poweromania** [comment]
Same for me.. i had to reset my phone to factory settings to pass safetynet

**Comment by cscomic** [comment]
It's not caused by edXposed, but riru.
Disable riru module and all related module, or update riru to 21.1, will solute this problem.

**Comment by poweromania** [comment]
> It's not caused by edXposed, but riru.
> Disable riru module and all related module, or update riru to 21.1, will solute this problem.

I don't think riru is the problem here.. i have the latest version of riru installed and i pass safetynet. The moment i activate edxposed safetynet fails.

**Comment by cscomic** [comment]
> > It's not caused by edXposed, but riru.
> > Disable riru module and all related module, or update riru to 21.1, will solute this problem.
> 
> I don't think riru is the problem here.. i have the latest version of riru installed and i pass safetynet. The moment i activate edxposed safetynet fails.

Use snapshot version of edXposed, you will pass.

**Comment by PenguinDOOM** [comment]
I was able to pass Safetynet after deleting the data and cache of these apps.

- Google Play Store

- Google Play Services

- Google Services Framework

**Comment by PenguinDOOM** [comment]
riru leaves some folders, so delete that too.
