### ISSUE TITLE
[BUG] App Launching Animation Have Lags!!

### ISSUE THREAD

**Issue by iamehsangh** [ElderDrivers/EdXposed#523]
**Problem:** After Install edxposed App Launching Animation Have Lags...

**Xposed Module List:** instaprefs - HiddenCore (For Pass SafetyNet on Magisk, i tried with App Blacklist And Added Google play services And Framework And Store But Still That was False)
**Magisk Module List**: BusyBox - RiruCore V21 And Edxposed V4.6.2 (4526) YAHFA

**Device:** Xiaomi Mi Note 3
**ROM:** AOSP Extended Android Q

**ScreenShots:**

![photo_2020-04-27_22-24-32](https://user-images.githubusercontent.com/30960428/80404281-3746ff00-88d6-11ea-9d8f-5e4cf490d8ce.jpg)
![photo_2020-04-27_22-24-33](https://user-images.githubusercontent.com/30960428/80404290-3910c280-88d6-11ea-96a5-263c320d1f6a.jpg)

Please Fix This Issue, Thanks...

**Comment by EhsanYE** [comment]
Tried YAHFA And Sandhook Canary V5.0 And Still Lags And Sometimes Freez Are Here...

**Comment by EhsanYE** [comment]
@MlgmXyysd
