### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by GenjiPro** [ElderDrivers/EdXposed#525]
Motorola G5s Plus Oreo 8.1(armeabi-v7a).  gives error code 1 in twrp while flashing EdXposed-SandHook-v0.4.6.2.4529.-release.zip

**Comment by EhsanYE** [comment]
Okay You Should Flash it with Magisk Not TWRP, New Versions Not Working via TWRP

**Comment by GenjiPro** [comment]
After installing with Magisk mobile is still in boot process (it doesn't stuck in bootloader). Don't know when home screen appears?

**Comment by Firefds** [comment]
Start with a fresh rom install, or at least with no magisk modules.

1. Install Riru using Magisk
2. Reboot
3. Install EdXposed using Magisk
4. Reboot

This should work
