### ISSUE TITLE
[BUG] Invalid monitor state ForwardingAddress

### ISSUE THREAD

**Issue by Olit2000** [ElderDrivers/EdXposed#526]
**什么情况/What happened?**
These crashes occur quite often in _random_ packages/apps.
The stack trace seem pretty much useless but they do have one thing in common:
The app wanted to access one of its resources stored in its apk (like strings, layouts,...) and failed
```
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 2838 (Binder:2732_1), pid 2732
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: '16.0-20200427-NIGHTLY-klte'
Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys'
Revision: '14'
ABI: 'arm'
pid: 2732, tid: 2838, name: Binder:2732_1
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'monitor.cc:1120] Invalid monitor state ForwardingAddress'
    r0  00000000  r1  00000b16  r2  00000006  r3  00000008
    r4  00000aac  r5  00000b16  r6  8900a1b4  r7  0000010c
    r8  00000002  r9  00000000  r10 cfffffff  r11 a36f28a8
    ip  00000041  sp  8900a1a0  lr  a5273125  pc  a526ae4a
```

**Xposed模块列表/Xposed Module List**

```
com.alex193a.gmdtenabler
com.aviraxp.messagingnoquickreply
com.ceco.pie.gravitybox
com.crossbowffs.noautoshortcut
com.fifsource.android.noplaygames
com.hazemam.InstantScreenOff
com.marz.instaprefs
com.mayulive.swiftkeyexi
de.Maxr1998.xposed.maxlock
de.binarynoise.logfailedxsharedpreferences
de.defim.apk.howgivelolli
eu.faircode.xlua
me.rapperskull.burnttoastrevived
net.darkion.uniformedtransitions
org.meowcat.edxposed.manager
tk.wasdennnoch.scoop
tw.fatminmin.xposed.minminguard
tw.idv.palatis.xappdebug
```

**Magisk模块列表/Magisk Module List**
```
acp
aml
busybox-ndk
disable-screenshot-camera-sounds
hosts
magisk-whatsapp-emojis
mm
riru-core
riru_edxposed_sandhook
ssh
```

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.4.6.3 (4545), installed thru magager (had similar issues with v0.4.5.1, see #432)

Riru: v19.7

**相关Logcat/Logcat**
see above

**Comment by Olit2000** [comment]
Any clue how to fix this?

**Comment by kotori2** [comment]
close as fixed

**Comment by binarynoise** [comment]
Cool that you close it as fixed, but the crashes didn't go away.
What shall I do now? Open a new issue?

**Comment by Olit2000** [comment]
Cool that you close it as fixed, but the crashes didn't go away.
What shall I do now? Open a new issue?

**Comment by kotori2** [comment]
So this still persist on latest canary? #717 claims to fixed this and I never encountered that issue before.

**Comment by Olit2000** [comment]
I didn't try it out yet. Had some trouble with the Riru update and decided to wait for the next release.
And I use SandHook and not YAHFA. (sorry I posted with wrong account)

**Comment by kotori2** [comment]
> And I use SandHook and not YAHFA

There was a bug causing crash on Android O-Q which I just fixed tonight. 
Also SandHook looks pretty stable on my Android R device, but some ppl reported it doesn't work on lower Android versions.

**Comment by canyie** [comment]
I had the same problem with another hook framework, and I seem to have fixed it; I think that fix should apply to sandbook as well.

This is my commit: canyie/pine#7f2cf17
