### ISSUE TITLE
[BUG] 中国银行/中国银行信用卡app卡屏

### ISSUE THREAD

**Issue by Roiyaru** [ElderDrivers/EdXposed#529]
**什么情况/What happened?**

中国银行/中国银行信用卡卡屏

**Xposed模块列表/Xposed Module List**

与模块无关

**Magisk模块列表/Magisk Module List**

与模块无关

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:Cancry5.0.0-4548-Yahfa

Riru:21.1

小米6X，安卓10，2020年3月安全补丁，kernel4.4.221

**相关Logcat/Logcat**

https://send.firefox.com/download/23c820c5c1e807a5/#XKhC0Fc7A_48Xf9zJEgDuw

**Comment by Jkkoi** [comment]
应用检测 Xposed 或者 root 了吧

不属于 Edxposed 的 bug

**Comment by rxzcums** [comment]
仅启用面具的随机包名的情况下，测试了能运行中国银行app

**Comment by Roiyaru** [comment]
> 应用检测 Xposed 或者 root 了吧
> 
> 不属于 Edxposed 的 bug

目前最新版中国银行已经正常打开了，中国银行信用卡app未测试
