### ISSUE TITLE
[QUESTION] Resource hooking support

### ISSUE THREAD

**Issue by KaMyKaSii** [ElderDrivers/EdXposed#53]
Is there any extra difficulty to add resource hooking support for EDXposed? Is it something that is already being worked on or does not have a high priority yet? Most modules that do cool things are based on resource hooking so the sooner the support is added the better. Not wanting to rush development or something, your work on this project is excellent

**Comment by manofsteel2017** [comment]
hope this added soon 
we won't be able to disable verification signature without it

**Comment by solohsu** [comment]
@manofsteel2017 How it's used to disable signature verification?

**Comment by manofsteel2017** [comment]
Because on Android pie.
It's what needed to allow  us to modify system file.

**Comment by solohsu** [comment]
@manofsteel2017 Have you tried latest Lucky Patcher? 
If it doesn't work, maybe you want to try the CorePatch module for Android Pie.
https://drive.google.com/open?id=1F-ejKT8CyCVR9g6iApjn7yrS4AzAHJ9X

**Comment by manofsteel2017** [comment]
holy shit 
i never knew this existed. 
going to try it now
thank you @solohsu

**Comment by XspeedPL** [comment]
Not exactly sure if this is related, but some modules fail to see XResources class:
https://pastebin.com/qdhXfP3U

**Comment by C3C0** [comment]
There is no point in using XResources when there is no resource hooking/replacing framework in EdXposed.

**Comment by XspeedPL** [comment]
The repo has the Java file, so I assumed the class should at least be available. My bad

**Comment by tuyennn** [comment]
Resources hooking was used on many xposed modules, without it. There would be so many modules cannot be run on Edxposed, means Pie also

**Comment by solohsu** [comment]
I had tried to migrate original Xposed's resource hooking but found it was almost impossible to implement it in the same way as Xposed without a modified ART runtime.
So we have to find a different approach to implement it.
