### ISSUE TITLE
[BUG]  Phone not booting after installing edxposed

### ISSUE THREAD

**Issue by TontyTon** [ElderDrivers/EdXposed#535]
**What happened?**

I installed edxposed, system is not booting. I am sure the edxposed is causing the issue.
My device RealMe C2, Havoc OS gsi (Android 10)

**Xposed Module List**

non

**Magisk Module List**
riru
busybox
sytemize

**Versions of EdXposed and Riru**

EdXposed: 4.6.2 and canary 5.0.0 [Yahfa]

Riru:  v21.2

**Logcat**
I 'think' here is the problem, but I am adding the full logcat (with priority W and above).
_I am newbie._

> 05-13 17:54:08.688 +0000  1469  1493 W Watchdog: main annotated stack trace:
05-13 17:54:08.688 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteConnection.nativeBindString(Native Method)
05-13 17:54:08.688 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteConnection.bindArguments(SQLiteConnection.java:1113)
05-13 17:54:08.688 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:938)
05-13 17:54:08.688 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at com.android.server.locksettings.LockSettingsStorage.readKeyValue(LockSettingsStorage.java:233)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at com.android.server.locksettings.LockSettingsService.getStringUnchecked(LockSettingsService.java:1097)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at com.android.server.locksettings.LockSettingsService.getLong(LockSettingsService.java:1069)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at com.android.internal.widget.LockPatternUtils.getLong(LockPatternUtils.java:1605)
05-13 17:54:08.689 +0000  1469  1493 W Watchdog:     at com.android.internal.widget.LockPatternUtils.getKeyguardStoredPasswordQuality(LockPatternUtils.java:1113)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.internal.widget.LockPatternUtils.isSecure(LockPatternUtils.java:1437)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.trust.TrustManagerService.refreshAgentList(TrustManagerService.java:508)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.trust.TrustManagerService.onBootPhase(TrustManagerService.java:214)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:158)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.SystemServer.lambda$startOtherServices$4$SystemServer(SystemServer.java:2227)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.-$$Lambda$SystemServer$nIvCzeD-FjXbHKl6i5eyYrpwpwQ.run(Unknown Source:30)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:9053)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.SystemServer.startOtherServices(SystemServer.java:2108)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.SystemServer.run(SystemServer.java:540)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at com.android.server.SystemServer.main(SystemServer.java:381)
05-13 17:54:08.690 +0000  1469  1493 W Watchdog:     at java.lang.reflect.Method.invoke(Native Method)
05-13 17:54:08.691 +0000  1469  1493 W Watchdog:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-13 17:54:08.691 +0000  1469  1493 W Watchdog:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
05-13 17:54:09.375 +0000  1469  1493 W Watchdog: *** GOODBYE!
05-13 17:54:09.851 +0000   948   948 W AudioFlinger: power manager service died !!!
05-13 17:54:09.894 +0000   890   890 E Zygote  : Exit zygote because system server (pid 1469) has terminated
05-13 17:54:10.010 +0000  1012  1183 E         : flp_screen_monitor_thread: Screen off

For logcat I used command 
`adb logcat -v=UTC *:W > 2.txt`
This log is with canary version.
[Logcat](https://github.com/ElderDrivers/EdXposed/files/4623960/2.txt)

**Comment by Himalaya2020** [comment]
rm -rf /data ???

**Comment by JasonKhew96** [comment]
> rm -rf /data ???

@Himalaya2020 
5 days ago, not related
5 天前，无关
