### ISSUE TITLE
[WARNING] Edxposed dont install over build 4548

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposed#547]
Guys dont install version of edxposed above than v5.0.0.0 4548

Build 4548 last commited was solosu is final working build

Someone has messed up the commit putting rm -rf data partition in above these builds

I request @MlgmXyysd to push 4548 build to final but out of canary

Because v4529 build causes bootloop on samsung devices stock rom

I am attaching solosu commit here in case someone is in need

http://www.mediafire.com/file/crzlsmojn1vicoz/EdXposed-SandHook-v0.5.0.0_%284548%29.zip

**Comment by Jasi2169** [comment]
Always take backup of data partition in twrp just in case

Hopefully it be fixed

**Comment by blackbox87** [comment]
> I request @MlgmXyysd to push 4548 build to final but out of canary

SandHook v5.0.0.0 4548 works, but as a module developer it's problematic because [it enforces unnecessary error logging](https://github.com/ElderDrivers/EdXposed/issues/527). That should be fixed before they push out a new version to the master branch.

**Comment by blackbox87** [comment]
> I request @MlgmXyysd to push 4548 build to final but out of canary

SandHook v0.5.0.0 4548 works, but as a module developer it's problematic because [it enforces unnecessary error logging](https://github.com/ElderDrivers/EdXposed/issues/527). That should be fixed before they push out a new version to the master branch.
