### ISSUE TITLE
[SUGGEST] Only modifying the CI configuration file seems not to prevent pr be builded.

### ISSUE THREAD

**Issue by LokiSharp** [ElderDrivers/EdXposed#549]
https://github.com/ElderDrivers/EdXposed/pull/548

**Comment by kinosang** [comment]
It is not a problem at CI-side.

If u need a Canary feed, u should use a branch-specified query to CI’s API.

Also, many CIs, include appveyor, provide environment variables to tell your build script whether the build runs for pull requests.

**Comment by purerosefallen** [comment]
> It is not a problem at CI-side.
> 
> If u need a Canary feed, u should use a branch-specified query to CI’s API, or do not push artifacts to ur feed.
> 
> Many CIs, include appveyor, provide environment variables to tell your build script whether the build runs for pull requests.

I don't think detecting whether the build is from a PR by env is a correct way. They can simply delete those lines to make PR builds published.

A correct way of it should be, to publish the nightly versions from other ways, but deploy them from CI with encrypted env vars. In PR builds, the encrypted env vars are not passed in.

**Comment by kinosang** [comment]
@purerosefallen You are right. So the public Canary feed should be published manually, or use a server-side API fetching with a branch-specified query.
