### ISSUE TITLE
[BUG] 云闪付卡在第一屏，微信QQ频繁出现已停止，QQ净化模块不生效

### ISSUE THREAD

**Issue by kiwiape** [ElderDrivers/EdXposed#55]
**什么情况/What happened?**
云闪付卡在第一屏，微信QQ频繁出现已停止，QQ净化无效（由于无效所以去掉了模块勾选）

**Xposed模块列表/Xposed Module List**
![Screenshot_2019-02-01-14-30-40-060_de.robv.android.xposed.installer.png](https://i.loli.net/2019/02/01/5c53e7edd63e1.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_2019-02-01-14-32-54-032_com.topjohnwu.magisk.png](https://i.loli.net/2019/02/01/5c53e83dd2b34.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: 0.2.9.7
Riru: v11

**相关Logcat/Logcat**
[bootloop-1970-01-17-00-09-33.log](https://github.com/ElderDrivers/EdXposed/files/2820363/bootloop-1970-01-17-00-09-33.log)
启动云闪付APP时的matlog
![Screenshot_2019-02-01-14-28-19-627_com.pluscubed.matlog.png](https://i.loli.net/2019/02/01/5c53e840ce760.png)
微信的matlog
![Screenshot_2019-02-01-14-27-51-816_com.pluscubed.matlog.png](https://i.loli.net/2019/02/01/5c53e834ecb2a.png)

**Comment by solohsu** [comment]
Flash latest release and use black/ whitelist in EdXposed Installer.
For WeChat or QQ, try compat mode to avoid crashes.
