### ISSUE TITLE
[BUG] Canary tab is missing and Snapchat tab crashes edxposed manager

### ISSUE THREAD

**Issue by chaoticNRO** [ElderDrivers/EdXposed#554]
**What happened?**
Canary Tab is no longer present in app. 

**Xposed/Xposed Module List**
None

**Magisk/Magisk Module List**
Magiskhide Props Config
Riru Core
Riru Edxposed
Swift Installer
VIPER

**EdXposed-Riru/Versions of EdXposed and Riru**
EdXposed: 0.4.6.2 (4529) (YAHFA)
Riru: v21.2

**Comment by MlgmXyysd** [comment]
Temporary removal
