### ISSUE TITLE
[NOT A BUG] EdXposed v0.4.6.3(4552)

### ISSUE THREAD

**Issue by diassynthesis** [ElderDrivers/EdXposed#555]
What about: https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/32933762/artifacts

If some one can tell us something about this version.

**Comment by JasonKhew96** [comment]
https://github.com/ElderDrivers/EdXposed/commit/30f8b6390d211b2b7dd76b0dc3a1f8fd103a2205

**Comment by Firefds** [comment]
4552 basically is no different from 4546. They are just testing the build mechanism.
