### ISSUE TITLE
[BUG] Installing EdXposed on a Nintendo Switch causes bootloop

### ISSUE THREAD

**Issue by manuth** [ElderDrivers/EdXposed#557]
**What happened?**
After installing EdXposed from Magisk Repository the device runs into a bootloop.

**Xposed Module List**
No module has been installed

**Magisk Module List**
* Busybox for Android NDK v1.31.1
* MagiskHideProps Config v5.2.5-v91
* Riru (Riru - Core) v21.2
* Riru - EdXposed v0.4.6.1 (4510) (SandHook)

**Versions of EdXposed and Riru**
EdXposed: v0.4.6.1 (4510) (SandHook)
Riru: v21.2

**Logcat**
```log
- Copying zip to temp directory
- Installing Riru_-_EdXposed-v0.4.6.1_(4510)_(SandHook)(4510).zip
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*****************
 Riru - EdXposed 
*****************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
- EdXposed Version v0.4.6.1 (4510) (SandHook)
- Magisk version: 20400
cat: can't open '/data/misc/riru/api_version.new': No such file or directory
- Riru API version: 7
- EdXposed Variant: SandHook
- Device platform: arm64
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: EdXposed.apk
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: sepolicy.rule
  inflating: system.prop
   creating: system/
   creating: system/framework/
  inflating: system/framework/edconfig.jar
  inflating: system/framework/eddalvikdx.jar
  inflating: system/framework/eddexmaker.jar
  inflating: system/framework/edxp.jar
   creating: system/lib/
  inflating: system/lib/libriru_edxp.so
  inflating: system/lib/libsandhook.edxp.so
  inflating: system/lib/libwhale.edxp.so
   creating: system/lib64/
  inflating: system/lib64/libriru_edxp.so
  inflating: system/lib64/libsandhook.edxp.so
  inflating: system/lib64/libwhale.edxp.so
  inflating: uninstall.sh
- Mounted persist:
- Persist not detected, remove SEPolicy rule
- Copying extra files
- Welcome to EdXposed v0.4.6.1 (4510) (SandHook)!
- Done
```

**Comment by Firefds** [comment]
Did you reboot after installing Riru and before installing Edxposed?

**Comment by manuth** [comment]
Thanks for your rapid response
I installed `Riru - Core` from the Magisk Repository and rebooted the switch. This worked flawlessly.
After this I downloaded and installed the SandHook variant of [the most recent EdXposed release](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.4.6.2).

After this I rebooted my switch and waited for 25 minutes. Sadly my Nintendo Switch didn't reboot once more.

The Type-C Port of the switch can't be used for ADB which is why I cannot post a logcat. Is there another way to get the kernel log?

**Comment by MlgmXyysd** [comment]
@manuth You can use "Log Catcher" Magisk module(download in MagiskManager)
btw, linux pstore maybe useful too

**Comment by manuth** [comment]
@MlgmXyysd Thank you very much for the hint
The log-files remained after about 15 minutes of bootloop.

**Comment by kotori2** [comment]
@manuth Log Catcher should work now. Also EdXp changed a lot so you can try out latest canary build.

**Comment by MlgmXyysd** [comment]
Closing: Stale issue that have not been updated for a long time
