### ISSUE TITLE
problem the application is hooked after installing Edxposed 

### ISSUE THREAD

**Issue by Mohameds21** [ElderDrivers/EdXposed#561]
![Screenshot_2020-05-31-06-50-56-872_com fawry myfawry 1](https://user-images.githubusercontent.com/66061661/83344873-debbb500-a30c-11ea-8a2a-a7e3b98c4e91.jpg)
**什么情况/What happened?**
the issue is i had installed the edxposed already on my phone and it is active and working fine and the safetynet is good but there is an application that after i installed the edxposed does not work and i had tried to hide edxposed from it from the application (Black List) but it is still does not work and show me an massage (the application is hooked ) so please if have an salutation of this problem please tell me to fix it

 manufacturer : xiaomi  
model : redmi note 8 pro global
android version : 10

EdXposedmander : version 4.5.7
Riru: version 21.2
Riru Edxposed : yahfa v0.5.00(4548) (canary version)

The Issue : 
the issue is i had installed the edxposed already on my phone and it is active and working fine and the safetynet is good but there is an application that after i installed the edxposed does not work and i had tried to hide edxposed from it from the application (Black List) but it is still does not work and show me an massage (the application is hooked ) so please if have an salutation of this problem please tell me to fix it

**Comment by eebssk1** [comment]
The project is not actively developed currently(and does not care about small bugs), so you can go for some research first and provide what you found here.
That should make things easier when maintainer have free time to look into these.

**Comment by omarwasfi** [comment]
I had the same issue
After is disables Riru Edxposed from magisk it worked fine.

**Comment by kotori2** [comment]
#634
