### ISSUE TITLE
[BUG] EdXposed NOT installed error after enabling App List Mode

### ISSUE THREAD

**Issue by kvxrun** [ElderDrivers/EdXposed#562]
---
name: Bug report, EdXposed not installed error
about: EdXposed manager showing edxposed not installed error when App List Mode is on
title: "EdXposed manager showing edxposed not installed error when App List Mode is on"
labels: bug, edxposed manager, app list mode
assignees: ''

---

**什么情况/What happened?**

如无法开机/模块无效等
After turning on App List mode in EdXposed manager and reboot, EdXposed manager shows an edxposed not installed error and all the edxposed modules stop working.

**Xposed模块列表/Xposed Module List**

WA Tweaker
Instaprefs
EdXposed manager
Lucky Patcher

**Magisk模块列表/Magisk Module List**

ANXCamera
Audio Compatibility Patch
Audio Modification library
Busybox
Log Catcher
MagiskHide props config
Quickswitch
Riru core
Riru- EdXposed
Universal GMS Doze
ViPER4Android

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: EdXposed Canary v4.6.3 (4552)

Riru: v21.2

**相关Logcat/Logcat**
Here is the link for logcat : https://jpst.it/2bxFy

**Comment by shmykelsa** [comment]
Same here.

**Comment by 2220209876** [comment]
The same problem occurred in the update after EvolutionX_4.3 20200523,
If the list mode is turned off, it can be used normally.

**Comment by shmykelsa** [comment]
> The same problem occurred in the update after EvolutionX_4.3 20200523,
> If the list mode is turned off, it can be used normally.

Same ROM and same situation here.

**Comment by wasabisushi** [comment]
Looks like @Stallix has pushed this patch (Evolution-X/frameworks_base@9c5b6537ff2199c5db288b850e85b75c9af95efd) to address this issue for @Evolution-X

**Comment by randomdudesup** [comment]
Suffering from basically the same issue on PA on beryllium, except that when app list mode is on I get " EdXposed Framework is installed but not active".

**Comment by kvxrun** [comment]
It's fixed in EvolutionX as Joey reverted the commit that broke it
