### ISSUE TITLE
Log error : Have you downloaded the xposed patch?

### ISSUE THREAD

**Issue by ILDev** [ElderDrivers/EdXposed#565]
Hi,

I am trying to use kmod module , but some features don't work and the WhatsApp getting Fc.
It's not ROM , or theme related issue.
After fc the log output is 

EdXposed-Bridge: Remove Jid and Date from copied messages tweak doesn't work. Have you downloaded the xposed patch?

The " Remove Jid and Date from copied messages tweak doesn't work" its the module related option that cause the fc .
The dev of module says it working for me also other users , in my opinion its patched magisk issue.
I have s10 rooted , that using pathced magisk.
What does "Have you downloaded the xposed patch?" it mean?

Thanks in advance!

**Comment by Alex193a** [comment]
That's a WA Tweaker error.

**Comment by ILDev** [comment]
Thank you for the comment.
That's the problem , there no options that need to cause that issue , also tried to disable all options , and still have this issue.
Also module's dev said that none of the  #option should cause it.
Issue exist only on Samsung devices , so I thing that because the patched magisk ..
