### ISSUE TITLE
[BUG] 小米8 SkyMi - 9.1.25 无法开机

### ISSUE THREAD

**Issue by Jie2GG** [ElderDrivers/EdXposed#57]
**什么情况/What happened?**

无法开机

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

1. Magisk Manager for Recovery Mode (MM管理器)
2. Systemless Hosts
3. 卸载小米框架

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.6

Riru:v11

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
请尝试最新版。
