### ISSUE TITLE
[BUG] Android 11, make Google Chrome keeps crashing with used testing build

### ISSUE THREAD

**Issue by bluehomewu** [ElderDrivers/EdXposed#585]
**什么情况/What happened?**
After I install testing build for Android 11 beta 2,Google Chrome APP keeps crashing.
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
EdXposed-YAHFA-vDEVTESTONLY.4557-qusiusqf-release

Riru:21.3

**相关Logcat/Logcat**
[system logcat](https://t.me/CodeOfMeowCat/297695) 
[Edxposed log](https://t.me/CodeOfMeowCat/297696) 
[Video](https://t.me/CodeOfMeowCat/297694) 

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/497#issuecomment-605545214

**Comment by Asstiff** [comment]
> [#497 (comment)](https://github.com/ElderDrivers/EdXposed/issues/497#issuecomment-605545214)

no use

**Comment by phoenixxie7** [comment]
On oneplus8 Android11, the same problem, The chrome will FC unless in writelist or blacklist mode. But I fond that Chrome would run normally when I tun off the App List mode.

**Comment by kotori2** [comment]
#624
