### ISSUE TITLE
[BUG] 在一加8Pro中与storage redirect冲突

### ISSUE THREAD

**Issue by david4958606** [ElderDrivers/EdXposed#588]
**什么情况/What happened?**

一加8pro中Edxposed与storage redirect的Magisk模块共用会出现无限重启（bootloop）

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

![Screenshot_20200727-224352](https://user-images.githubusercontent.com/16517322/88555753-c6d98680-d05a-11ea-9b84-27de0be86f11.jpg)
![Uploading Screenshot_20200727-224352.jpg…]()

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.4.6.1和0.4.6.3均有此问题

Riru:v21.3

**相关Logcat/Logcat**

暂无

**Comment by kotori2** [comment]
一加8P+氧OS10.5.12国际版无法复现
自己排查下其他的magisk模块

**Comment by MlgmXyysd** [comment]
@david4958606 7TP氢OS内测版无法复现

**Comment by david4958606** [comment]
> 一加8P+氧OS10.5.12国际版无法复现
> 自己排查下其他的magisk模块

仅保留core、edxposed、storage redirect三个模块仍有该问题 ，系统为HOS10.5.12

**Comment by MlgmXyysd** [comment]
@david4958606 关闭所有xp模块，如仍然bootloop请提供开机日志

**Comment by david4958606** [comment]
> @david4958606 关闭所有xp模块，如仍然bootloop请提供开机日志

[EdXposed_Verbose_20200727_225437.txt](https://github.com/ElderDrivers/EdXposed/files/4982690/EdXposed_Verbose_20200727_225437.txt)

**Comment by MlgmXyysd** [comment]
@david4958606 开机日志，非edxp日志

**Comment by david4958606** [comment]
已解决问题，禁用“一个视界”XP模块即可
