### ISSUE TITLE
[BUG] Stuck at boot when Lucky Patcher module is enabled.

### ISSUE THREAD

**Issue by IsMaix** [ElderDrivers/EdXposed#591]
**什么情况/What happened?**
I am trying to get the google play proxy working, but I can't with the patch only being at 1/2, I've tried applying it multiple times, and without the patch being at 2/2 I cant enable the proxy, can be fixed by enabling edxposed module. My phone is stuck at the boot screen after enabling Lucky Patcher edxposed, only happens with lucky patcher module, tried reinstalling lucky patcher, and also reinstalling magisk and edxposed. 

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Exi for Swiftkey
Instaprefs
Statusbar download progress

**Magisk模块列表/Magisk Module List**
Busybox for android ndk
Global optimized gps file replacer
riru core
riru edxposed
systemless hosts
viper4android fx

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6 (4559) SandHook

Riru: v21.3

on android 10 crdroid for a7 2017 btw

**Comment by kotori2** [comment]
Please attach your log.

**Comment by IsMaix** [comment]
> Please attach your log.

Idk how to

**Comment by kotori2** [comment]
https://github.com/MlgmXyysd/Log-Catcher
Keyword: Log Catcher

**Comment by IsMaix** [comment]
ive installed it do i just need to enable the module to have the error occur and then send the file ?

**Comment by kotori2** [comment]
@IsMaix Exactly

**Comment by IsMaix** [comment]
"Catch boot log and save to /data/local/boot/boot-$time.log.

Error or Warning only log is saved to /data/local/boot_error/error-$time.log."

Both or just the first one?

**Comment by kotori2** [comment]
@IsMaix All of them under boot_error if you are unsure

**Comment by IsMaix** [comment]
kk

**Comment by IsMaix** [comment]
I might have to go for a bit btw, def won't be able to fix it today

**Comment by IsMaix** [comment]
> @IsMaix All of them under boot_error if you are unsure

I wasnt able to find the log folders in data/local
I flashed the zip through the magisk app, enabled the lucky patcher module, and rebooted (Same thing as always never completes boot) but there were no folders and it didn't show as a module in magisk

**Comment by kotori2** [comment]
closed as stale
