### ISSUE TITLE
[BUG] EdXposed and Riru Cause ANR error (App Not Responding) on Stbemu app

### ISSUE THREAD

**Issue by mondev2020** [ElderDrivers/EdXposed#593]
Riru and EdXposed Cause ANR error (App Not Responding) on Stbemu apps (in all STB apps like [STBemu](https://play.google.com/store/apps/details?id=com.mvas.stb.emu.free&hl=fr), [Ksport STB](https://play.google.com/store/apps/details?id=com.ksport.stb.pro&hl=fr), [MY TV STB](https://play.google.com/store/apps/details?id=com.mytv.stb.emu.tu&hl=fr) ...etc).

- I'am on Android Pi.e,
- I'am using Magisk.
- Riru and EdXposed are working properly.
- But cause ANR error on STB apps, and it is impossible to start these apps !

When I uninstall Riru and EdXposed from Magisk, all STBemu application rework again.

==> The issue is from Riru and EdXposed modules

**Comment by dethknite** [comment]
Sounds like this issue... Disabling app list mode fixes the issue at the moment.... https://github.com/ElderDrivers/EdXposed/issues/604
