### ISSUE TITLE
[BUG] nfc出现问题/nfc problem

### ISSUE THREAD

**Issue by cyjboost** [ElderDrivers/EdXposed#594]
**什么情况/What happened?**

安装edxp后nfc出现问题无法启用/When I installed edxpoesed,the nfc stop working

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

![Screenshot_20200807-192228061](https://user-images.githubusercontent.com/46393561/89641133-965bdd00-d8e3-11ea-9ead-5aa6d620d2a9.jpg)
![Screenshot_20200807-192258854](https://user-images.githubusercontent.com/46393561/89641148-9e1b8180-d8e3-11ea-9c3b-75735836f8b5.jpg)
![Screenshot_20200807-192320894](https://user-images.githubusercontent.com/46393561/89641151-9fe54500-d8e3-11ea-8bb0-969762a58f97.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.4.6.2(4529)(YAHFA)

Riru:21.3

**Comment by kotori2** [comment]
@cyjboost 请自行排查模块对NFC的影响而不是直接post一堆模块上来
