### ISSUE TITLE
[Question] Best way to load configurations on Zygote init

### ISSUE THREAD

**Issue by alan20210202** [ElderDrivers/EdXposed#595]
I'm sorry if this is something people keep asking about. I'm writing a module in which I hope to load my configuration in `initZygote` and I'm personally using Android Q. I have so far seen the following solutions:

1. `XSharedPreferences` in device protected storage with permission tricks: works on some ROM, but causes bootloop on others due to SELinux. (#467). 
2. Using context providers. Then since context providers haven't been initialized when `initZygote` is called I have to defer loading configuration to `handleLoadPackage`.  Another limitation that bothers me the most is that it requires the hooked app to have access permission to files, which is sometimes not the case.

My question is: Is there a location where we can read on Zygote initialization that is not affected by FBE and keeps SELinux happy? If this is impossible, is there a way to let a module read configurations in `handleLoadPackage` regardless of the permissions of the hooked app? Thanks!

**Comment by XspeedPL** [comment]
Wouldn't it be a good idea to follow Magisk or Riru and store information in places like `/data/adb/...` or `/data/misc/...`?

Then, instead of making the app write data and the module read it via a provider, reverse the roles and make the module host a public provider from system context that does storage I/O, while the app will communicate read/write requests to it.

**Comment by kotori2** [comment]
Files in `/data/misc/` can be detect so using them is a bad idea. `/data/adb/` is fine.

**Comment by astola-studio** [comment]
> Wouldn't it be a good idea to follow Magisk or Riru and store information in places like `/data/adb/...` or `/data/misc/...`?
> 
> Then, instead of making the app write data and the module read it via a provider, reverse the roles and make the module host a public provider from system context that does storage I/O, while the app will communicate read/write requests to it.

Thats really a great idea. But first of all “Is it safe?” because last time i disabled FLAG_SECURE and my phone’s touch screen stopped working. Can’t explain the pain to get over it.

If it is, and has anyone done it? Better reference us some codes or a file of a project where they used it. ;-)
