### ISSUE TITLE
[BUG] 刷入EdXp后无限重启

### ISSUE THREAD

**Issue by Henry-ZHR** [ElderDrivers/EdXposed#596]
**什么情况**

刷入EdXp后无限重启

**Xposed模块列表**

无

**Magisk模块列表**

- Riru - Core

**EdXposed及Riru版本**

EdXposed: 0.4.6.4 YAHFA

Riru: 21.3

**相关Logcat/Logcat**

[log.txt](https://github.com/ElderDrivers/EdXposed/files/5052457/log.txt)

---

设备：华为 荣耀8 FRD-AL10

ROM：OpenKirin LineageOS 16.0 Build 4 (底包：FRD-AL10 8.0.0.540(C00))

尝试过使用Manager里的版本以及目前最新的CI构建（均包括Y版和S版），都有相同问题。

**Comment by kotori2** [comment]
看起来是`_ZNK3art11ClassLinker27SetEntryPointsToInterpreterEPNS_9ArtMethodE`这函数的指针没拿到导致空指针的

**Comment by Henry-ZHR** [comment]
v0.4.6.1可以正常开机

疑似和 sepolicy 有关

**Comment by MlgmXyysd** [comment]
刷入最新删除/data/adb/modules/riru_edxposed/sepolicy.rule试试

**Comment by Henry-ZHR** [comment]
> 
> 
> 刷入最新删除/data/adb/modules/riru_edxposed/sepolicy.rule试试

可以正常开机了

**Comment by MlgmXyysd** [comment]
那就是sepolicy的问题了，原因是Magisk使用了只有高通处理器才有的persist分区，等Magisk做好fallback此问题应该会解决

**Comment by xiaofengjue** [comment]
> 刷入最新删除/data/adb/modules/riru_edxposed/sepolicy.rule试试

请问一下你这句话具体该怎么操作，我有点迷茫，我note10现在遇到了无限重启的问题

**Comment by Henry-ZHR** [comment]
> > 刷入最新删除/data/adb/modules/riru_edxposed/sepolicy.rule试试
> 
> 请问一下你这句话具体该怎么操作，我有点迷茫，我note10现在遇到了无限重启的问题

我是 bootloop 之后进 TWRP 删的

如果没 TWRP 的话，试一下装完模块先删 `/data/adb/modules_update/riru_edxposed(_sandhook)/sepolicy.rule` 再重启？

**Comment by xiaofengjue** [comment]
好的老哥了解了，谢谢你------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Henry&amp;nbsp;Zhang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月6日(星期天) 凌晨0:56
收件人:&nbsp;&quot;ElderDrivers/EdXposed&quot;<EdXposed@noreply.github.com&gt;;
抄送:&nbsp;&quot;xiaofengjue&quot;<2467452757@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ElderDrivers/EdXposed] [BUG] 刷入EdXp后无限重启 (#596)
