### ISSUE TITLE
Samsung Galaxy Tab S7+ 5G (T976B) and Z Fold2 5G (F916B) don't boot when EdXposed module is loaded.

### ISSUE THREAD

**Issue by ianmacd** [ElderDrivers/EdXposed#601]
EdXposed causes Android not to boot on the Galaxy Tab S7+ 5G (T976B).

Device configuration:

Magisk: Canary 11f254e5 (20424) (the latest at the time of writing).
riru: 21.3 from Magisk repo.
EdXposed versions tried: Sandhook 0.4.6.3 (4546), YAHFA 0.4.6.3 (4546) and YAHFA 0.5.0.6 (4561).
Samsung Android 10 ATH1 firmware.

`logcat` never even starts, so I can't supply a log. The screen turns black before the Samsung logo ever appears.

**Comment by ianmacd** [comment]
The Galaxy Z Fold2 5G also doesn't boot with the above configuration, so this issue appears to affect multiple recent Snapdragon-based devices from Samsung.

**Comment by ianmacd** [comment]
I have finally got around to building a permissive kernel for the Fold2 5G, and can confirm that this enables the device to boot with the EdXposed module installed.

I haven't managed to actually activate the module yet, but the device **is** booting, so this GitHub issue **is** related to SELinux.

Unfortunately, the issue occurs so early in the boot process that logging is not yet enabled, so I'm no closer to isolating what is being denied or why when SELinux is enforcing.

**Comment by ianmacd** [comment]
The permissiveness of the kernel turns out to be a red herring. The same custom kernel will allow the machine to boot with EdXposed enabled even when the kernel is in enforcing mode and the ability to switch to permissive mode has been disabled.

The real issue turns out to be `CONFIG_KDP_CRED`. With that enabled in the kernel, the device cannot boot with the EdXposed Magisk module enabled, **if** `CONFIG_SECURITY_SELINUX_DEVELOP` is also enabled. In the stock Samsung kernel, this is the case: Both are enabled. One or the other must be disabled for the device to boot.

I hope this information will provide the EdXposed developers with the information required to work around the issue in the EdXposed module files, thereby allowing the device to boot with EdXposed on a stock kernel.

**Comment by ianmacd** [comment]
I've opened a separate issue for this in Magisk. My hope is that the kernel can be patched using `magiskboot` to allow the stock kernel to boot with EdXposed.

See the issue below for the relevant decompiled kernel code:

https://github.com/topjohnwu/Magisk/issues/3485

**Comment by ianmacd** [comment]
Users who want to fix this issue on an existing system that has the EdXposed module installed but not enabled should run the following command from their PC:

`adb shell "su -c 'sed -i -re \"s/(manager|installer)\)/\\1 2>\&1)/g\" /data/adb/modules/riru_edxposed*/post-fs-data.sh'"`

This will patch the EdXposed boot script.

After patching the script, simply enable the EdXposed module and reboot the device.

**Comment by MlgmXyysd** [comment]
Fixed https://github.com/ElderDrivers/EdXposed/commit/4a9c30aa34073ef2941833ef63fb3b6f4cdafb8b
