### ISSUE TITLE
EdEx

### ISSUE THREAD

**Issue by KeefCWarLord** [ElderDrivers/EdXposed#607]

**Comment by kotori2** [comment]
@KeefCWarLord ？

**Comment by KeefCWarLord** [comment]
Trying to root my s10+ qualcomm snapdragon 855 on verizon.. damn bootloader is tricky. 

Any suggestions?? 

Thxx

**Comment by kotori2** [comment]
@KeefCWarLord This is EdXposed issue tracker, not a forum for any phone.
