### ISSUE TITLE
[BUG] 在edxp模块的构造函数或类代码块中启动线程，无法开机

### ISSUE THREAD

**Issue by Zingphoy** [ElderDrivers/EdXposed#608]
**什么情况/What happened?**
使用手机Pixel 3，版本Android 10，内核版本4.9.210-g28c696160049-ab6386370。
安装自己编写的edxp模块，软重启后无法开机，会在开机页面 【G】图标下一直等待

**Magisk模块列表/Magisk Module List**
- Riru(Riru-Core) v21.3
- Riru-EdXposed v0.4.6.2

**EdXposed及Riru版本/Versions of EdXposed and Riru**
- EdXposed:  EdXposed Manager v4.5.7

**相关Logcat/Logcat**
在开机【G】图标等待时logcat会一直输出error日志：system_server: Thread not suspended

**更多细节**
编写edxp模块，在implements IXposedHookLoadPackage的类的 **构造函数里** 或 **类代码块中** 添加 **启动一个新线程的逻辑** ，重启后会导致无法开机。导致无法开机原因是猜测出来的，因为在前面提及的两个地方添加启动线程的逻辑后就开始出现无法开机的现象，而将这个启动新线程的代码从这两个地方挪走后，一切恢复正常。

问题示例代码：
```java
public class HookDemo implements IXposedHookLoadPackage {

    private Thread workerThread = null;

    private Handler mainHandler = null;

    // 在构造函数或者类代码库中添加启动新线程的逻辑，软重启后无法开机了
    public HookDemo() {
        workerThread = new Thread(new Runnable() {

            @Override
            public void run() {
                Looper.prepare();
                mainHandler = new Handler(Looper.myLooper()) {

                    @Override
                    public void handleMessage(@NonNull final Message msg) {
                        // some codes
                    }
                };
                Looper.loop();
            }
        });
        workerThread.start();
    }

@Override
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam param) throws Throwable {
        // some codes
    }
}
```

**Comment by kotori2** [comment]
现在程序逻辑是在 `nativeForkAndSpecialize` 之前加载hook类，也就是说执行你的构造函数的时候还是在Zygote里，所以炸了，等 #634

**Comment by kotori2** [comment]
should be fixed in #608
