### ISSUE TITLE
[BUG] NekoSMS无效

### ISSUE THREAD

**Issue by gyj1109** [ElderDrivers/EdXposed#61]
**什么情况/What happened?**

NekoSMS无效

**Xposed模块列表/Xposed Module List**

![2019-2-7_19-48-42](https://user-images.githubusercontent.com/11223244/52409956-ebae0700-2b11-11e9-8b4a-0901ff5aa5d8.PNG)

**Magisk模块列表/Magisk Module List**

![2019-2-7_19-47-35](https://user-images.githubusercontent.com/11223244/52409968-f49ed880-2b11-11e9-9280-9be01daec31e.PNG)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.2.9.7

Riru:v11

**相关Logcat/Logcat**

无NekoSMS的相关Log输出

**Comment by zcyang668** [comment]
你的绿色magisk版支持9.0吗，最新的提示不支持28

**Comment by gyj1109** [comment]
> 你的绿色magisk版支持9.0吗，最新的提示不支持28

你既然知道上GitHub，为什么不去看看Magisk绿守的README

**Comment by solohsu** [comment]
I don't think this module supports Android Pie.
