### ISSUE TITLE
[BUG] EdXposed causing Force Close Chrome on Android 11 Pixel 4XL v0.5.0.6-YAHFA

### ISSUE THREAD

**Issue by bridges86406** [ElderDrivers/EdXposed#612]
So ever since installed EdXposed on my Pixel 4XL after updating to Android 11 I have had an issue with force closes. 
If I install EdXposed but start no (0) modules my phone works as normal.  If I activate any module I get errors with Chrome, or the System UI closing.  This is regardless of the module installed.  I have tried Fingerface, XPrivacyLUA, Greenify, system starts having issues regardless of which module I start.  

Logs attached.
[all.log](https://github.com/ElderDrivers/EdXposed/files/5301706/all.log)

**Comment by Howard20181** [comment]
#604

**Comment by bridges86406** [comment]
So does this mean that you believe it is the same issue?  Unfortunately I can't follow the track, but it looks like that issue has been open for 20+ days.  It also looks like someone identified the issue....

**Comment by peterandreasrothe** [comment]
This happens for me too on pixel 4xl with android r. It doesn't matter which module I enable. However if I disable app list mode and reboot, Chrome works fine but then I can't use Google pay.

**Comment by kodithegreat** [comment]
I'm on Android 11 Pixel 3XL, adding Chrome does nothing for me too. Enabling any module causes chrome to crash and usually every other app as well. 

Using Canary build on magisk, YAHFA, edXposed, Riru. I have tried every solution posted in the multiple issues threads, nothing works.

**Comment by phoenixxie7** [comment]
The chrome will FC unless in whitelist or blacklist mode. But I fond that Chrome would run normally when I tun off the App List mode.

**Comment by SkeleBones** [comment]
I have the same issue but any module being enabled also crashes lawnchair launcher and WebView along with chrome of course.

**Comment by kvxrun** [comment]
encountered same issue on android 11 in my redmi note 7. switched to firefox for the time being
