### ISSUE TITLE
[BUG] Bootloop after updating

### ISSUE THREAD

**Issue by scarf** [ElderDrivers/EdXposed#615]
**什么情况/What happened?**

I updated to latest version from Magisk Manager and now device is in bootloop.  Moto G4 (athene), Android 8.1

**Xposed模块列表/Xposed Module List**

EdXposed Manager 4.5.7
should be more listed like XPrivacyLua but it doesn't list anything else

**Magisk模块列表/Magisk Module List**

Font Changer 3.0.0.3

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.2

Riru: 21.3

**相关Logcat/Logcat**

Can't boot device to get logcat

**Comment by JasonKhew96** [comment]
https://topjohnwu.github.io/Magisk/faq.html#q-i-installed-a-module-and-it-bootlooped-my-device-help

**Comment by scarf** [comment]
Thanks!  I was able to go in through recovery and delete the EdX module.  Went back to v0.4.6.1 and phone is booting fine again.  Is there way I can help troubleshoot why v0.4.6.2 is bootlooping?

**Comment by agtpirrone** [comment]
I just got this issue in Pixel 2... fresh October 2020 (Android 11).
Magisk works fine.. Riru Core installs and boots fine.. but as soon as I reboot for enabling EdXposed its a direct bootloop... (i should probably open a new issue, but maybe someone has a quick answer (like a known working version or something)

**Comment by angrycrab** [comment]
Same issue here on Samsung S20 Ultra and Tab s7 plus bootloop with the new version old one works properly.

**Comment by thebackgroundeffect101** [comment]
updated to riru 23. rebooted the device twice. then flashed exposed yahya latest canary. device kept rebooting me into twrp recovery.

**Comment by LinnyR** [comment]
miui12 stability. As I update the riru-core module in the mask to version 23, my phone loop restarts and 21.3 has no such problem. I don't know what's wrong.

**Comment by kotori2** [comment]
v0.4.6.x is obsoleted. Please try with latest canary build. Closing as stale.
