### ISSUE TITLE
EdXposed no longer installed after Magisk update

### ISSUE THREAD

**Issue by sdw1988** [ElderDrivers/EdXposed#617]
After installing the most recent update of Magisk I no longer had EdXposed installed and working as I did prior to update. I've tried reinstalling and reflashing it as well as riru-core and the riru-edxposed modules in Magisk.. I've tried reflashing Magisk itself as well as trying both Sandhook and YAHFA. I had everything installed and working perfectly including passing Safety net. Device is Pixel 2 XL running Android R stock AOSP room. Including log from Magisk, EdXposed (module + verbose) as well as screenshots showing pertinent version information.. Any and all help would be greatly appreciated..

![Screenshot_20201012-110503](https://user-images.githubusercontent.com/17962065/95762426-b1e4ba80-0c7b-11eb-93fa-043ce83db61e.png)
![Screenshot_20201012-110514](https://user-images.githubusercontent.com/17962065/95762441-b6a96e80-0c7b-11eb-8a3e-dab87b4593ed.png)
![Screenshot_20201012-110536](https://user-images.githubusercontent.com/17962065/95762467-bf9a4000-0c7b-11eb-8a17-d0b8246bb397.png)
[EdXposed_Verbose_20201012_110551.txt](https://github.com/ElderDrivers/EdXposed/files/5365953/EdXposed_Verbose_20201012_110551.txt)
[EdXposed_Modules_20201012_110545.txt](https://github.com/ElderDrivers/EdXposed/files/5365959/EdXposed_Modules_20201012_110545.txt)
[LOG_2020.10.12.txt](https://github.com/ElderDrivers/EdXposed/files/5365962/LOG_2020.10.12.txt)

**Comment by MlgmXyysd** [comment]
re-install manager
