### ISSUE TITLE
[INFO] Resources hooking on Samsung One UI 2.5 (Android 10)

### ISSUE THREAD

**Issue by psychopathologist** [ElderDrivers/EdXposed#619]
**什么情况/What happened?**

Resources hooking not working

**Xposed模块列表/Xposed Module List**

My own only (under construction)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6 (4564) YAHFA

Riru: v21.3

Is resources hooking actually working on Samsung One UI 2.5 (Android 10)? Tia!

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/commit/b1bc7200a6d351d208d33336257a709877932bc2
