### ISSUE TITLE
[BUG] 虚拟定位软件“超级神行者”不支持

### ISSUE THREAD

**Issue by liypay** [ElderDrivers/EdXposed#62]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
描述过于简单，无助于解决问题。
