### ISSUE TITLE
Slow performance on Oneplus 7T Pro with the latest OOS 10 Beta 9

### ISSUE THREAD

**Issue by MSkjel** [ElderDrivers/EdXposed#621]
After updating to beta 9 of OOS my system is extremely slow and unresponsive with EdXposed active. I keep getting some errors in the logcat. Tried both 0.4.6.2 and 0.5.0.6 Sandhook and both of them do the same thing. This did not happen before the OOS update, so Im guessing it has something to do with it

10-31 02:07:05.025  7330  7330 I System.out: Update settings xposed
10-31 02:07:05.026  7330  7330 W System.err: java.io.FileNotFoundException: /data/ru.LjVfVXoU.HdHFfbQHl/xposed: open failed: EACCES (Permission denied)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:496)
10-31 02:07:05.026  7330  7330 W System.err:    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
10-31 02:07:05.026  7330  7330 W System.err:    at com.chelpus.ˆ.ˆ(Utils.java:7084)
10-31 02:07:05.026  7330  7330 W System.err:    at com.chelpus.ˆ.ᐧ(Utils.java:10077)
10-31 02:07:05.026  7330  7330 W System.err:    at com.xposed.XSupport.ʻ(XSupport.java:1249)
10-31 02:07:05.024  7330  7330 W gearhead:shared: type=1400 audit(0.0:3966): avc: denied { search } for name="ru.LjVfVXoU.HdHFfbQHl" dev="dm-8" ino=6915623 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c141,c257,c512,c768 tclass=dir permissive=0
10-31 02:07:05.026  7330  7330 W System.err:    at com.xposed.XSupport$30.afterHookedMethod(XSupport.java:1021)
10-31 02:07:05.026  7330  7330 W System.err:    at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
10-31 02:07:05.026  7330  7330 W System.err:    at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:393)
10-31 02:07:05.026  7330  7330 W System.err:    at SandHookerNew_266kqmbgf0rjocorsd0mb624aj.hook(Unknown Source:56)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ContextImpl.getPackageManager(ContextImpl.java:309)
10-31 02:07:05.024  7330  7330 W gearhead:shared: type=1400 audit(0.0:3967): avc: denied { search } for name="ru.LjVfVXoU.HdHFfbQHl" dev="dm-8" ino=6915623 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c141,c257,c512,c768 tclass=dir permissive=0
10-31 02:07:05.024  7330  7330 W gearhead:shared: type=1400 audit(0.0:3968): avc: denied { search } for name="ru.LjVfVXoU.HdHFfbQHl" dev="dm-8" ino=6915623 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c141,c257,c512,c768 tclass=dir permissive=0
10-31 02:07:05.026  7330  7330 W System.err:    at com.qualcomm.qti.Performance.checkAppPlatformSigned(Performance.java:264)
10-31 02:07:05.026  7330  7330 W System.err:    at com.qualcomm.qti.Performance.<init>(Performance.java:66)
10-31 02:07:05.026  7330  7330 W System.err:    at java.lang.reflect.Constructor.newInstance0(Native Method)
10-31 02:07:05.026  7330  7330 W System.err:    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
10-31 02:07:05.026  7330  7330 W System.err:    at android.util.BoostFramework.<init>(BoostFramework.java:155)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6517)
10-31 02:07:05.026  7330  7330 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-31 02:07:05.026  7330  7330 W System.err:    at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
10-31 02:07:05.026  7330  7330 W System.err:    at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
10-31 02:07:05.026  7330  7330 W System.err:    at SandHookerNew_5sm3dthec8858ee0to4kj3c1ge.hook(Unknown Source:51)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ActivityThread.access$1600(ActivityThread.java:236)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
10-31 02:07:05.026  7330  7330 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:107)
10-31 02:07:05.026  7330  7330 W System.err:    at android.os.Looper.loop(Looper.java:219)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7709)
10-31 02:07:05.026  7330  7330 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-31 02:07:05.026  7330  7330 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-31 02:07:05.026  7330  7330 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
10-31 02:07:05.026  7330  7330 W System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.Linux.open(Native Method)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
10-31 02:07:05.026  7330  7330 W System.err:    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7608)
10-31 02:07:05.026  7330  7330 W System.err:    at libcore.io.IoBridge.open(IoBridge.java:482)
10-31 02:07:05.026  7330  7330 W System.err:    ... 27 more
10-31 02:07:05.027  7330  7330 W System.err: org.json.JSONException: Value ���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������� of type java.lang.String cannot be converted to JSONObject
10-31 02:07:05.027  7330  7330 W System.err:    at org.json.JSON.typeMismatch(JSON.java:112)
10-31 02:07:05.027  7330  7330 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:168)
10-31 02:07:05.027  7330  7330 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:181)
10-31 02:07:05.027  7330  7330 W System.err:    at com.chelpus.ˆ.ᐧ(Utils.java:10077)
10-31 02:07:05.027  7330  7330 W System.err:    at com.xposed.XSupport.ʻ(XSupport.java:1249)
10-31 02:07:05.027  7330  7330 W System.err:    at com.xposed.XSupport$30.afterHookedMethod(XSupport.java:1021)
10-31 02:07:05.027  7330  7330 W System.err:    at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
10-31 02:07:05.027  7330  7330 W System.err:    at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:393)
10-31 02:07:05.027  7330  7330 W System.err:    at SandHookerNew_266kqmbgf0rjocorsd0mb624aj.hook(Unknown Source:56)
10-31 02:07:05.027  7330  7330 W System.err:    at android.app.ContextImpl.getPackageManager(ContextImpl.java:309)
10-31 02:07:05.027  7330  7330 W System.err:    at com.qualcomm.qti.Performance.checkAppPlatformSigned(Performance.java:264)
10-31 02:07:05.027  7330  7330 W System.err:    at com.qualcomm.qti.Performance.<init>(Performance.java:66)
10-31 02:07:05.027  7330  7330 W System.err:    at java.lang.reflect.Constructor.newInstance0(Native Method)
10-31 02:07:05.027  7330  7330 W System.err:    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
10-31 02:07:05.027  7330  7330 W System.err:    at android.util.BoostFramework.<init>(BoostFramework.java:155)
10-31 02:07:05.027  7330  7330 W System.err:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6517)
10-31 02:07:05.027  7330  7330 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-31 02:07:05.027  7330  7330 W System.err:    at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
10-31 02:07:05.027  7330  7330 W System.err:    at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:379)
10-31 02:07:05.027  7330  7330 W System.err:    at SandHookerNew_5sm3dthec8858ee0to4kj3c1ge.hook(Unknown Source:51)
10-31 02:07:05.027  7330  7330 W System.err:    at android.app.ActivityThread.access$1600(ActivityThread.java:236)
10-31 02:07:05.027  7330  7330 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
10-31 02:07:05.027  7330  7330 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:107)
10-31 02:07:05.027  7330  7330 W System.err:    at android.os.Looper.loop(Looper.java:219)
10-31 02:07:05.027  7330  7330 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:7709)
10-31 02:07:05.027  7330  7330 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
10-31 02:07:05.027  7330  7330 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-31 02:07:05.027  7330  7330 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by ystokar** [comment]
Same problem here. Had to disable module

**Comment by SekiBetu** [comment]
FileNotFoundException: /data/ru.LjVfVXoU.HdHFfbQHl/xposed: open failed: EACCES (Permission denied)
it seems that Oneplus's update deleted edxposed manager's directory?

**Comment by kotori2** [comment]
com.chelpus
Lucky Patcher caused the crash.

惜别 <notifications@github.com>于2020年11月1日 周日06:00写道：
