### ISSUE TITLE
[BUG] bootloop on one Ui 3.0 beta 

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposed#622]
**什么情况/What happened?**
Bootloop on android 11 one ui 3.0 beta 
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: latest canary 

Riru:latest 

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by manofsteel2017** [comment]
Why this was closed?
The xposed doesn't boot up on samsung Android 11 beta I.e 3.0.
It bootloop

**Comment by kotori2** [comment]
Option 1: Buy a phone and give it to any developer so they could test on their own.
Option 2: Attach detailed logs and version etc

**Comment by manofsteel2017** [comment]
Bad reply
Can't take logs if it's bootloop

**Comment by kotori2** [comment]
Then try option 1.

**Comment by manofsteel2017** [comment]
Please don't reply if you have nothing better to say.
This was for the main dev.
