### ISSUE TITLE
Yahfa/sandhook latest alpha build random reboots

### ISSUE THREAD

**Issue by Quannino** [ElderDrivers/EdXposed#626]
So after I update my edxposed to the latest alpha version which 0.4.6.4 yahfa, I keep experiencing random reboots and sometimes 3 times a day. So I decided to get sandhook version but doesnt seem like it fix it. I wanted to get this out cuz I havent seen anyone reporting this issue or having this issue. I got lucky patcher, greenify, gravity box for pie in my modules. The update passed safetynet perfectly btw..

I'm using samsung galaxy note 8 running android 9
Latest alpha edxposed build
Riru core latest version
Magisk latest version

**Comment by Quannino** [comment]
??? why is my issue closed??? with no reply what so ever and boom thats it? Great dev

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
