### ISSUE TITLE
[BUG] since v0.4.6.0_beta installation hangs at "- Removing 64-bit libraries"

### ISSUE THREAD

**Issue by ghuacc** [ElderDrivers/EdXposed#628]
Magisk: 21.0 and older

EdXposed: 0.4.6.x and newer (yahfa or sandhook)

Riru: 21.3 and older

OS: Android 10.0 / LineageOS latest nightly build and older

Hardware: HTC M8

![Screenshot_2020-11-11-19-30-07](https://user-images.githubusercontent.com/11440245/98851479-3cbcfe80-244e-11eb-91b4-16efe38bb013.png)

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/blob/f6cab13e22b1051664d294133c0adad6504e67bf/edxp-core/template_override/customize.sh#L244

pm won't exist on twrp. @MlgmXyysd any idea on detect twrp?

**Comment by MlgmXyysd** [comment]
> Any idea on detect twrp?

`BOOTMODE` (bool): `true` if the module is being installed in Magisk Manager

Ref: https://topjohnwu.github.io/Magisk/guides.html#variables
