### ISSUE TITLE
[BUG] MinMinGuard will cause bootloop with EdXposed

### ISSUE THREAD

**Issue by maple3142** [ElderDrivers/EdXposed#63]
**什么情况/What happened?**

Using [MinMinGuard](https://github.com/chiehmin/MinMinGuard) with EdXposed will cause bootloop, and I have to remove EdXposed manually to fix it.

**Xposed模块列表/Xposed Module List**

雲村清潔工
音量增強器
MinMinGuard
綠色守護 (disabled)

**Magisk模块列表/Magisk Module List**

Blobmoji
Magisk Manager for Recovery Mode (mm)
Move Certificates
Noto CJK (Lite)
Riru - Core
Riru - Ed Xposed
Riru - Storage Redirect
Swift Installer Module
Systemless Hosts
ViPER4Android FX Materialized
YouTube Vanced - Magisk Repo

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.7_beta

Riru: v11

**相关Logcat/Logcat**

I don't know how to capture logcat when I am unable to boot.

**Comment by cwkfr** [comment]
I don't know how to capture logcat when I am unable to boot.

As an addition to this, you could try this magisk module: https://github.com/MlgmXyysd/LogCat-Bootloop

**Comment by solohsu** [comment]
Fixed with https://www.github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2
