### ISSUE TITLE
[BUG] android 11:  modules.list was not found

### ISSUE THREAD

**Issue by achozex** [ElderDrivers/EdXposed#630]
**什么情况/What happened?**
Edxposed framework is installed, but not active , oneplust 8t
tried both sandhook and yahfa, same error
如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
nothing activated yet
允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**
![Screenshot (Nov 12, 2020 8 02 20 PM)](https://user-images.githubusercontent.com/10247595/98978324-79f2c080-2522-11eb-8658-26bef7744163.jpg)

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6-android_r (4564) (SandHook)

Riru: v21.3 (36)

**相关Logcat/Logcat**
[EdXposed_Modules_20201112_195844.txt](https://github.com/ElderDrivers/EdXposed/files/5532367/EdXposed_Modules_20201112_195844.txt)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by JasonKhew96** [comment]
try YAHFA variant

**Comment by achozex** [comment]
> 
> 
> try YAHFA variant

same issue,
[EdXposed_Modules_20201113_135120.txt](https://github.com/ElderDrivers/EdXposed/files/5536606/EdXposed_Modules_20201113_135120.txt)

**Comment by achozex** [comment]
the verbose logs:

[EdXposed_Verbose_20201113_192842.txt](https://github.com/ElderDrivers/EdXposed/files/5539146/EdXposed_Verbose_20201113_192842.txt)

**Comment by otonieru** [comment]
If i deduce it correctly, this is due to Magisk 21.1 (21100) update which seems to changed how sepolicy work as well. I facing same issue with 21.1 where module list wont loaded. I revert to stable 20.4 and everything work again. Try to downgrade your magisk.

**Comment by achozex** [comment]
just update my phone with full OTA and reflashed magisk from the manager  , and its working now 
@otonieru updated magisk to 21.1 and its working


will close the ticket
