### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by EternalTimes** [ElderDrivers/EdXposed#633]
无法识别riru 22
![Screenshot_20201114-192516](https://user-images.githubusercontent.com/49099376/99146096-d1726700-26af-11eb-9d45-92ff27034a1f.jpg)
![Screenshot_20201114-192507](https://user-images.githubusercontent.com/49099376/99146101-e0591980-26af-11eb-980e-aebf89f80986.jpg)
![Screenshot_20201114-192458](https://user-images.githubusercontent.com/49099376/99146105-e6e79100-26af-11eb-8eb4-04f06d50001d.jpg)

**Comment by JasonKhew96** [comment]
https://github.com/ElderDrivers/EdXposed/pull/623

**Comment by EternalTimes** [comment]
> 适配中
> #623

辛苦了
