### ISSUE TITLE
[BUG] 与《SD重定向》(me.dyq.android.SDLink)不兼容

### ISSUE THREAD

**Issue by lgq-lzw** [ElderDrivers/EdXposed#636]
**什么情况/What happened?**
当装上并激活《SD重定向》(me.dyq.android.SDLink[1.4.3(13)])这个模块后
重启无法开机，卡米。进REC删掉它则可以正常运行，其他已装模块正常。

**Xposed模块列表/Xposed Module List**
![Screenshot_2020-11-18-16-37-02-548_org meowcat edxposed manager](https://user-images.githubusercontent.com/59247842/99507038-da1fb180-29bd-11eb-981d-90d849b364e3.png)

**Magisk模块列表/Magisk Module List**
![Screenshot_2020-11-18-16-38-30-731_com topjohnwu magisk](https://user-images.githubusercontent.com/59247842/99506901-af355d80-29bd-11eb-8d40-3af42a347b9c.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed:
![Screenshot_2020-11-18-16-37-21-507_org meowcat edxposed manager](https://user-images.githubusercontent.com/59247842/99507069-e3108300-29bd-11eb-8119-8806b6bcb107.png)
Riru:
![Screenshot_2020-11-18-16-38-06-458_com topjohnwu magisk](https://user-images.githubusercontent.com/59247842/99507099-ec015480-29bd-11eb-8769-9bcf2514569e.png)

**相关Logcat/Logcat**
[EdXposed_Verbose_20201118_164004.txt](https://github.com/ElderDrivers/EdXposed/files/5558851/EdXposed_Verbose_20201118_164004.txt)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by JasonKhew96** [comment]
![image](https://user-images.githubusercontent.com/29531167/99507706-b610a000-29be-11eb-9efc-d476f74616b2.png)
啊这...

**Comment by MlgmXyysd** [comment]
测试：关闭其他所有Xposed模块，仅启用SD重定向模块

**Comment by lgq-lzw** [comment]
> 测试：关闭其他所有Xposed模块，仅启用SD重定向模块

不但关闭，甚至卸载掉其他模块，只剩SD重定向，也照样卡米进不了系统。

**Comment by coderstory** [comment]
这个古董插件。。。。

**Comment by kotori2** [comment]
> 只剩SD重定向，也照样卡米进不了系统。

这不是模块的问题吗...
