### ISSUE TITLE
[BUG] 开机卡死

### ISSUE THREAD

**Issue by su226** [ElderDrivers/EdXposed#638]
**什么情况/What happened?**

开机卡死在Logo处，并有严重发热，SandHook和YAHFA版本都有这个问题，设备：荣耀9 Magisk 20.4

**Xposed模块列表/Xposed Module List**

无

**Magisk模块列表/Magisk Module List**

只有Riru和EdXposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.4

Riru: 21.3

**相关Logcat/Logcat**

无

**Comment by qcnhy** [comment]
安卓版本啥也没。。谁知道你这啥 醉了

**Comment by su226** [comment]
> 安卓版本啥也没。。谁知道你这啥 醉了

忘了写……已经加上了
