### ISSUE TITLE
[BUG] Lucky Patcher stuck at boot

### ISSUE THREAD

**Issue by kusalux** [ElderDrivers/EdXposed#64]
**什么情况/What happened?**
Using LuckyPatcher with EdXposed the phone will be somewhat stuck on boot. Tried it on the following 2 roms for my lg g3:
RR-O-v6.2.1-20181215-d855-Final (fully installed/used) - inf. boot animation
liquid_remix-10.0.3-20181221-OFFICIAL-d855 (clean install with what's below + TitaniumBackup) - would finish boot animation, i can hear some sounds like from power menu, but always black screen
Problem only does exist, if LP is enabled in EdXposed. (it works okay on oreo with systemless xposed, but that has other flaws again is not available on pie)

**Xposed模块列表/Xposed Module List**
Luckypatcher 8.1.4
(also some others like Greenify, AfWall, FakeGapps but i've tried with Luckypatcher alone too)

**Magisk模块列表/Magisk Module List**
(Here I am not sure which I already had installed, possible):
DNSCrypt-Proxy 2.6.0
Magisk Manager for Recovery Mode (mm)
Nanodroid 20.6
Riru - Core
Riru - Ed Xposed
(i think I've installed Advanced Charging Controller and Busybox afterwards)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
EdXposed: v0.2.9.7_beta
Riru: v11

**相关Logcat/Logcat**
Prob. on boot but I'll look into

**Comment by manofsteel2017** [comment]
works on stock 9.1 phh and xl3 except we can't disable signature 
it kept saying failed 
might be an LP issue but who knows maybe you can look into that too

**Comment by DaFeiMao233** [comment]
不是edxp挂不了幸运破解器，是幸运破解器不支持Android9和8.1.0

**Comment by DaFeiMao233** [comment]
这没办法，勾选重启就卡一屏

**Comment by DaFeiMao233** [comment]
这不是edxp的bug，需要的话请到隔壁幸运破解器去提交你的问题

**Comment by solohsu** [comment]
Fixed in  [v0.2.9.8_beta1](https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.8_b1)

**Comment by kusalux** [comment]
Thx. That rly works. Well, LP would not recognize Xposed functions on used RR-O i reverted to for the time being, but that might be some LP/Oreo bug too? Will test Pie (tough unsure if today) and report back. But anyway - it wont get stuck on boot-loop.
