### ISSUE TITLE
[BUG] Not installed with Riru v22.0

### ISSUE THREAD

**Issue by KonstantIMP** [ElderDrivers/EdXposed#641]
**What happened?**

When I tried install EdXposed YAHFA (Latest) with the newest Riru 22.0 I had an error.
EdXposed think that Riru is not installed

**Xposed/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**
Only Riru 22.0 from official Riru GitHub repository

**EdXposedRiru/Versions of EdXposed and Riru**

EdXposed: SandHook v0.4.6.4.4563

Riru: Riru v22.0

**Logcat**

- Copying zip to temp directory
- Installing EdXposed-SandHook-v0.4.6.4.4563.-release.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*****************
 Riru - EdXposed 
*****************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- EdXposed Version v0.4.6.4 (4563) (SandHook)
- Android sdk: 30
- Magisk version: 21100
******************************
! Requirement module 'Riru - Core' is not installed
! You can download from 'Magisk Manager' or https://github.com/RikkaApps/Riru/releases
******************************
! Installation failed

**Comment by KonstantIMP** [comment]
It is because Riru has chenged its path.
From official changelog :
RIRU_PATH has been changed to /data/adb/riru for hide purpose. If you have other files in /data/misc/riru, move them here (or anywhere else if you want).

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/blob/b0af399e3780fa762e321f81d35d7f4d26295818/edxp-core/template_override/post-fs-data.sh#L13
Yes, it seems should be changed.

**Comment by KonstantIMP** [comment]
It is also in customeze.sh file

**Comment by KonstantIMP** [comment]
I changed them, but Manager doesn't see edxposed right now...

**Comment by uaegangster111** [comment]
I am also having the same problem .

**Comment by Raslin777** [comment]
Tried coping files from /data/misc/riru to /data/adb/riru does not work. No edxposed till updated to work...

**Comment by MlgmXyysd** [comment]
use latest ci build

**Comment by alisal97** [comment]
I get the same error using 0.5.x.x canary builds.

**Comment by chengyikan** [comment]
Magisk更新 Riru v22.0以后找不到 Riru-core 使其Riru-edxposed模块无法安装
