### ISSUE TITLE
[BUG] Riru更新位v22.0 后不能安装EdXposed：提示找不到Riru-core模块

### ISSUE THREAD

**Issue by pinetower** [ElderDrivers/EdXposed#645]
Riru更新位v22.0 后不能安装EdXposed：提示找不到Riru-core模块。

**Comment by JasonKhew96** [comment]
@pinetower 用 4568 或以上
https://ci.appveyor.com/project/ElderDrivers/edxposed/history

**Comment by QkiZMR** [comment]
https://github.com/RikkaApps/Riru/releases
New version of Riru (v22) require changes in module

**Comment by kotori2** [comment]
I added support 17 days ago. 
https://github.com/ElderDrivers/EdXposed/pull/623

**Comment by yujincheng08** [comment]
YOU DESERVE THIS

**Comment by mwdotzom** [comment]
一样的问题，用0.5.0 4568版本后卡开机logo，MIUI12

**Comment by mwdotzom** [comment]
一样的问题，用0.5.0 4568版本后卡开机logo，MIUI12

**Comment by klever1988** [comment]
> 一样的问题，用0.5.0 4568版本后卡开机logo，MIUI12

yahfa还是sandhook？目前卡logo有twrp能解吗，不敢升级啊。。

**Comment by kotori2** [comment]
@klever1988 这是issue tracker不是论坛，要解决问题自己去读issues和pr

**Comment by chengyikan** [comment]
magisk安装Riru v22.0后,无法安装Riru-EdXposed请及时解决谢谢！
