### ISSUE TITLE
Riru Core not found

### ISSUE THREAD

**Issue by omensight** [ElderDrivers/EdXposed#649]
I have this problem installing the latest version of EdXposed 
`- Copying zip to temp directory
- Installing EdXposed-YAHFA-v0.4.6.4.4563.-release.zip
- Device is system-as-root
Archive:  /data/user/0/qzjnzf.zqskv.tk.i/cache/flash/install.zip
  inflating: module.prop
*****************
 Riru - EdXposed 
*****************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/qzjnzf.zqskv.tk.i/cache/flash/install.zip
  inflating: customize.sh
- EdXposed Version v0.4.6.4 (4563) (YAHFA)
- Android sdk: 29
- Magisk version: 21100
******************************
! Requirement module 'Riru - Core' is not installed
! You can download from 'Magisk Manager' or https://github.com/RikkaApps/Riru/releases
******************************
! Installation failed
`

**Comment by kotori2** [comment]
#645 (comment)
PLEASE READ BEFORE YOU SUBMIT AN ISSUE
