### ISSUE TITLE
[BUG]edxp已经激活，但功能几乎全部失效

### ISSUE THREAD

**Issue by DaFeiMao233** [ElderDrivers/EdXposed#65]
什么情况/What happened?

0.2.9.5都可以正常使用，到0.2.9.7功能几乎全部失效了，比如文本自定义等模块，没法影响到除Xposed Installer以外的其他任何软件。

Xposed模块列表/Xposed Module List

爱字体
核心破解
绿色守护
蚂蚁森林助手
淘饭饭
微X模块
QX模块
文本自定义
无障碍-Daemon
验证码提取器
应用变量
App Translator
base.apk
BeautyHeaderPlugin
GoogleAPP助手
GravityBox [O]
Q++模块
QQ斗图神器
Screenshot Delay Remover - Mod
spQQ机器人

Magisk模块列表/Magisk Module List

App Ops System Plugin
Busybox for Android NDK
DNS Switcher
IOS Pro最终版
Magisk Google DNS
Magisk Manager for Recovery Mode(MM汉化版)
小米8刘海对齐
YouTube Vanced - Magisk Repo
Magisk SELinux Manager
Riru - Core
Riru - Ed Xposed

EdXposed及Riru版本/Versions of EdXposed and Riru

EdXposed: v0.2.9.7_beta

Riru: v11

相关Logcat/Logcat

我没有安装logcat。

**Comment by DaFeiMao233** [comment]
https://ooo.0o0.ooo/2019/02/11/5c60f9013cd88.png
https://ooo.0o0.ooo/2019/02/11/5c60f9153cac8.png

**Comment by rxzcums** [comment]
因为启用了核心破解。

**Comment by rxzcums** [comment]
请尝试禁用核心破解，重启手机。

**Comment by solohsu** [comment]
Try https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2 and report again.
