### ISSUE TITLE
[BUG] EdXposed causing Force Close Camera on Android 11 Pixel 4XL v0.5.0.6-YAHFA (4568)

### ISSUE THREAD

**Issue by bridges86406** [ElderDrivers/EdXposed#650]
When using the new riru (22) and YAHFA 4568 I noticed that my Camera app would continously force close.
Logs attached. [
[EdXposed_Verbose_20201123_180135.txt](https://github.com/ElderDrivers/EdXposed/files/5587185/EdXposed_Verbose_20201123_180135.txt)
](url)

**Comment by kotori2** [comment]
dup as #642
