### ISSUE TITLE
发现日志中几处edxposed未激活

### ISSUE THREAD

**Issue by njtony11** [ElderDrivers/EdXposed#651]
> `--------- beginning of head

EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: Google
Brand: google
Device: bonito
Product: bonito
Model: Pixel 3a XL
Fingerprint: google/bonito/bonito:11/RP1A.200720.009/6720564:user/release-keys
ROM description: bonito-user 11 RP1A.200720.009 6720564 release-keys
Architecture: arm64-v8a
Android build: RP1A.200720.009
Android version: 11
Android sdk: 30
EdXposed version: v0.5.0.6_4568-android_r (YAHFA)
EdXposed api: 91.0
Riru version:  ()
Riru api: 
Magisk: 21.1 (21100)
--------- beginning of main
--------- beginning of system
11-24 12:52:52.725   948   948 I EdXposed: onModuleLoaded: welcome to EdXposed!
11-24 12:52:52.725   948   948 I EdXposed: Start to install inline hooks
11-24 12:52:52.725   948   948 I EdXposed: Using api level 30
11-24 12:52:52.725   948   948 I EdXposed: Start to install Riru hook
11-24 12:52:52.819   948   948 I EdXposed: Riru hooks installed
11-24 12:52:52.899   948   948 I EdXposed: using installer org.meowcat.edxposed.manager
11-24 12:52:52.900   948   948 I EdXposed: data path prefix: /data/user_de/0/
11-24 12:52:52.900   948   948 I EdXposed:   application list mode: true
11-24 12:52:52.900   948   948 I EdXposed:     using whitelist: false
11-24 12:52:52.900   948   948 I EdXposed:   dynamic modules mode: false
11-24 12:52:52.900   948   948 I EdXposed:   resources hook: false
11-24 12:52:52.900   948   948 I EdXposed:   deopt boot image: false
11-24 12:52:52.900   948   948 I EdXposed:   no module log: false
11-24 12:52:52.900   948   948 I EdXposed:   hidden api bypass: true
11-24 12:52:52.901   948   948 I EdXposed:   whitelist: org.meowcat.edxposed.manager
11-24 12:52:52.901   948   948 I EdXposed:   whitelist: com.android.vendinf
11-24 12:52:52.901   948   948 I EdXposed:   whitelist: eu.faircode.xlua
11-24 12:52:52.901   948   948 I EdXposed:   whitelist: com.yuanwofei.cardemulator.pro
11-24 12:52:52.903   948   948 I EdXposed:   blacklist: com.google.android.gms
11-24 12:52:52.903   948   948 I EdXposed:   blacklist: com.google.android.gsf
11-24 12:52:52.903   948   948 I EdXposed:   blacklist: com.android.vending
11-24 12:52:52.905   948   948 I EdXposed: ART hooks installed
11-24 12:52:53.287   949   949 I EdXposed: onModuleLoaded: welcome to EdXposed!
11-24 12:52:53.287   949   949 I EdXposed: Start to install inline hooks
11-24 12:52:53.287   949   949 I EdXposed: Using api level 30
11-24 12:52:53.287   949   949 I EdXposed: Start to install Riru hook
11-24 12:52:53.337   949   949 I EdXposed: Riru hooks installed
11-24 12:52:53.392   949   949 I EdXposed: using installer org.meowcat.edxposed.manager
11-24 12:52:53.392   949   949 I EdXposed: data path prefix: /data/user_de/0/
11-24 12:52:53.392   949   949 I EdXposed:   application list mode: true
11-24 12:52:53.392   949   949 I EdXposed:     using whitelist: false
11-24 12:52:53.392   949   949 I EdXposed:   dynamic modules mode: false
11-24 12:52:53.392   949   949 I EdXposed:   resources hook: false
11-24 12:52:53.392   949   949 I EdXposed:   deopt boot image: false
11-24 12:52:53.392   949   949 I EdXposed:   no module log: false
11-24 12:52:53.392   949   949 I EdXposed:   hidden api bypass: true
11-24 12:52:53.392   949   949 I EdXposed:   whitelist: org.meowcat.edxposed.manager
11-24 12:52:53.392   949   949 I EdXposed:   whitelist: com.android.vendinf
11-24 12:52:53.392   949   949 I EdXposed:   whitelist: eu.faircode.xlua
11-24 12:52:53.392   949   949 I EdXposed:   whitelist: com.yuanwofei.cardemulator.pro
11-24 12:52:53.392   949   949 I EdXposed:   blacklist: com.google.android.gms
11-24 12:52:53.392   949   949 I EdXposed:   blacklist: com.google.android.gsf
11-24 12:52:53.392   949   949 I EdXposed:   blacklist: com.android.vending
11-24 12:52:53.394   949   949 I EdXposed: ART hooks installed
11-24 12:52:56.317   948   948 I EdXposed-Bridge: Loading modules from /data/app/com.android.vendinf-r6eHJ-lqSvkFKU-c7Qd5QQ==/base.apk
11-24 12:52:56.411   948   948 I EdXposed-Bridge:   Loading class zone.jasi2169.patcher.Xposed
11-24 12:52:56.426   948   948 I EdXposed-Bridge: Loading modules from /data/app/eu.faircode.xlua-U3jKftwn6J8NDHN8tERYXg==/base.apk
11-24 12:52:56.510   948   948 I EdXposed-Bridge:   Loading class eu.faircode.xlua.XLua
11-24 12:52:56.514   948   948 I EdXposed-Bridge: Loading modules from /data/app/~~5dUqBsinWlGVT-NkOpw9_g==/com.yuanwofei.cardemulator.pro-hDYX8LKs_iEKuSwX37HKbQ==/base.apk
11-24 12:52:56.587   948   948 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
11-24 12:53:02.601  1993  1993 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.systemui
11-24 12:53:02.601  1993  1993 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.systemui
11-24 12:53:03.126   949   949 W EdXposed: skip injecting into WebViewLoader-armeabi-v7a because it's isolated
11-24 12:53:03.126   949   949 W EdXposed: skip injecting xposed into WebViewLoader-armeabi-v7a because it's whitelisted/blacklisted
11-24 12:53:03.178   948   948 W EdXposed: skip injecting into WebViewLoader-arm64-v8a because it's isolated
11-24 12:53:03.178   948   948 W EdXposed: skip injecting xposed into WebViewLoader-arm64-v8a because it's whitelisted/blacklisted
11-24 12:53:03.390   949   949 W EdXposed: skip injecting into webview_zygote because it's a child zygote
11-24 12:53:03.390   949   949 W EdXposed: skip injecting xposed into webview_zygote because it's whitelisted/blacklisted
11-24 12:53:03.847  2396  2396 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.nexuslauncher
11-24 12:53:03.847  2396  2396 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.nexuslauncher
11-24 12:53:04.066  2537  2537 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.quicinc.cne.CNEService
11-24 12:53:04.066  2537  2537 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.quicinc.cne.CNEService
11-24 12:53:04.453  2631  2631 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.grilservice
11-24 12:53:04.453  2631  2631 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.grilservice
11-24 12:53:04.646  2713  2713 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.ext.services
11-24 12:53:04.646  2713  2713 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.ext.services
11-24 12:53:06.522  2865  2865 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.cellbroadcastreceiver
11-24 12:53:06.523  2865  2865 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.cellbroadcastreceiver
11-24 12:53:07.132  2932  2932 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.wellbeing
11-24 12:53:07.132  2932  2932 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.wellbeing
11-24 12:53:07.561   948   948 W EdXposed: skip injecting xposed into com.google.android.gms.persistent because it's whitelisted/blacklisted
11-24 12:53:08.979  3081  3081 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.dialer
11-24 12:53:08.979  3081  3081 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.dialer
11-24 12:53:09.291  3128  3128 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.android.providers.blockednumber
11-24 12:53:09.291  3128  3128 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.android.providers.blockednumber
11-24 12:53:09.782  3179  3179 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.ims
11-24 12:53:09.782  3179  3179 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.ims
11-24 12:53:10.083  3224  3224 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.apps.scone
11-24 12:53:10.083  3224  3224 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.apps.scone
11-24 12:53:10.185  3253  3253 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.apps.carrier.carrierwifi
11-24 12:53:10.185  3253  3253 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.apps.carrier.carrierwifi
11-24 12:53:12.045   948   948 W EdXposed: skip injecting xposed into com.google.android.gms because it's whitelisted/blacklisted
11-24 12:53:13.726   948   948 W EdXposed: skip injecting xposed into com.google.process.gservices because it's whitelisted/blacklisted
11-24 12:53:13.767  3665  3665 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.photos
11-24 12:53:13.767  3665  3665 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.photos
11-24 12:53:13.826  3687  3687 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.providers.media.module
11-24 12:53:13.826  3687  3687 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.providers.media.module
11-24 12:53:13.880  3708  3708 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.as
11-24 12:53:13.880  3708  3708 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.as
11-24 12:53:13.987  3746  3746 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.nfc
11-24 12:53:13.987  3746  3746 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.nfc
11-24 12:53:14.275  3822  3822 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.SSRestartDetector
11-24 12:53:14.275  3822  3822 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.SSRestartDetector
11-24 12:53:14.790  3880  3880 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.mtp
11-24 12:53:14.790  3880  3880 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.mtp
11-24 12:53:14.867   949   949 W EdXposed: skip injecting xposed into com.android.vending because it's whitelisted/blacklisted
11-24 12:53:15.971  4012  4012 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.messaging
11-24 12:53:15.971  4012  4012 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.messaging
11-24 12:53:19.485   949   949 I EdXposed-Bridge: Loading modules from /data/app/com.android.vendinf-r6eHJ-lqSvkFKU-c7Qd5QQ==/base.apk
11-24 12:53:19.612   949   949 I EdXposed-Bridge:   Loading class zone.jasi2169.patcher.Xposed
11-24 12:53:19.618   949   949 I EdXposed-Bridge: Loading modules from /data/app/eu.faircode.xlua-U3jKftwn6J8NDHN8tERYXg==/base.apk
11-24 12:53:19.681   949   949 I EdXposed-Bridge:   Loading class eu.faircode.xlua.XLua
11-24 12:53:19.686   949   949 I EdXposed-Bridge: Loading modules from /data/app/~~5dUqBsinWlGVT-NkOpw9_g==/com.yuanwofei.cardemulator.pro-hDYX8LKs_iEKuSwX37HKbQ==/base.apk
11-24 12:53:19.747   949   949 I EdXposed-Bridge:   Loading class com.yuanwofei.cardemulator.xposed.MainHook
11-24 12:53:20.049   948   948 W EdXposed: skip injecting xposed into com.google.process.gapps because it's whitelisted/blacklisted
11-24 12:53:22.663  4391  4391 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.printspooler
11-24 12:53:22.663  4391  4391 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.printspooler
11-24 12:53:23.603  4463  4463 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.carriersetup
11-24 12:53:23.603  4463  4463 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.carriersetup
11-24 12:53:24.681   949   949 W EdXposed: skip injecting xposed into com.android.vending:download_service because it's whitelisted/blacklisted
**11-24 12:53:28.421  4787  4787 D EdXposedManager: EdXposed is not active**
**11-24 12:53:28.422  4787  4787 D EdXposedManager: EdXposed is not active**
11-24 12:53:28.422  4787  4787 D EdXposedManager: ApplicationList: Force add modules to list
**11-24 12:53:28.748  4787  4787 D EdXposedManager: EdXposed is not active**
11-24 12:53:34.528  5049  5049 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.ruet_cse_1503050.ragib.appbackup.pro
11-24 12:53:34.528  5049  5049 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.ruet_cse_1503050.ragib.appbackup.pro
11-24 12:53:40.816  5372  5372 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.externalstorage
11-24 12:53:40.816  5372  5372 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.externalstorage
11-24 12:53:44.723  5636  5636 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.RilConfigService
11-24 12:53:44.724  5636  5636 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.RilConfigService
11-24 12:53:47.104  5747  5747 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.managedprovisioning
11-24 12:53:47.104  5747  5747 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.managedprovisioning
11-24 12:53:49.807  5830  5830 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.docs
11-24 12:53:49.807  5830  5830 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.docs
11-24 12:53:51.350  5926  5926 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.gcs
11-24 12:53:51.350  5926  5926 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.gcs
11-24 12:53:52.474  5969  5969 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.maps
11-24 12:53:52.474  5969  5969 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.maps
11-24 12:53:55.421  6053  6053 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.messaging
11-24 12:53:55.421  6053  6053 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.messaging
11-24 12:53:56.392  6090  6090 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.nbu.files
11-24 12:53:56.392  6090  6090 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.nbu.files
**11-24 12:53:58.278  4787  4787 D EdXposedManager: EdXposed is not active**
11-24 12:54:05.553  6389  6389 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.contacts
11-24 12:54:05.553  6389  6389 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.contacts
11-24 12:54:11.266  6660  6660 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.chrome
11-24 12:54:11.266  6660  6660 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.chrome
11-24 12:54:11.383  6654  6654 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.calendar
11-24 12:54:11.383  6654  6654 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.calendar
11-24 12:54:11.511   948   948 W EdXposed: skip injecting xposed into com.google.android.gms.ui because it's whitelisted/blacklisted
11-24 12:54:12.003   948   948 W EdXposed: skip injecting xposed into com.google.android.gms.unstable because it's whitelisted/blacklisted
11-24 12:54:13.542  6868  6868 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.onetimeinitializer
11-24 12:54:13.542  6868  6868 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.onetimeinitializer
11-24 12:54:14.750  6955  6955 E EdXposed: can't access config path, using snapshot use_white_list: /data/user_de/0/com.google.android.packageinstaller
11-24 12:54:14.750  6955  6955 E EdXposed: can't access config path, using snapshot black list: /data/user_de/0/com.google.android.packageinstaller
11-24 12:54:16.969  7038  7038 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.contacts
11-24 12:54:16.969  7038  7038 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.contacts
11-24 12:54:17.603  7107  7107 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.storagemanager
11-24 12:54:17.603  7107  7107 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.storagemanager
11-24 12:54:20.439  7257  7257 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.youtube
11-24 12:54:20.439  7257  7257 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.youtube
11-24 12:54:23.628  7451  7451 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.intelligence.sense
11-24 12:54:23.628  7451  7451 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.intelligence.sense
11-24 12:54:24.533  7486  7486 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.qualcomm.atfwd
11-24 12:54:24.533  7486  7486 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.qualcomm.atfwd
11-24 12:54:26.160   948   948 W EdXposed: skip injecting xposed into com.google.android.gms.feedback because it's whitelisted/blacklisted
11-24 12:54:48.241  8070  8070 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/org.adaway
11-24 12:54:48.241  8070  8070 E EdXposed: can't access config path, using snapshot black list: /data/user/0/org.adaway
11-24 12:54:54.190  8127  8127 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.externalstorage
11-24 12:54:54.190  8127  8127 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.externalstorage
11-24 12:54:56.531  8239  8239 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.android.providers.calendar
11-24 12:54:56.531  8239  8239 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.android.providers.calendar
**11-24 12:55:14.028  4787  4787 D EdXposedManager: EdXposed is not active**
11-24 12:55:31.205  8661  8661 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.documentsui
11-24 12:55:31.205  8661  8661 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.documentsui
11-24 12:55:32.862  8734  8734 E EdXposed: can't access config path, using snapshot use_white_list: /data/user/0/com.google.android.apps.docs
11-24 12:55:32.862  8734  8734 E EdXposed: can't access config path, using snapshot black list: /data/user/0/com.google.android.apps.docs
`
edxposed manager 显示框架已激活，但是查看日志的时候发现有几处EdXposed is not active，不知道但是不是正常现象，谢谢

**Comment by kotori2** [comment]
魔法问题，不影响
