### ISSUE TITLE
[BUG] the module does not recognize the riru core, and now it does not install.

### ISSUE THREAD

**Issue by sadfado00** [ElderDrivers/EdXposed#652]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:

Riru:

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/issues/645#issuecomment-732002147

**Comment by sadfado00** [comment]
![Uploading Screenshot_Magisk_Manager_20201124-035949.png…]()
