### ISSUE TITLE
Riru 22.0 undetected

### ISSUE THREAD

**Issue by enetec1** [ElderDrivers/EdXposed#653]
On my Motorola Z2 with Android 9 if I upgrade to new Riru v.22.0, Riru EdXposed is unabled to detect Riru and refuse to install and/or to start. 

Is there a version compatible with new Riru release? 

What is minimum version required eventually? 

Thanx a lot!

**Comment by kotori2** [comment]
Riru v22 + latest canary build. 
Or downgrade to v21 if you don't want to use canary.

**Comment by slimshouki** [comment]
@kotori2 
Not working mate
Latest build 4573 with riru v22.
Framework cannot see riru installed

**Comment by slimshouki** [comment]
@kotori2 
After 4576 build all is fine except some modules fucntions are broken like customiuizer. Which log do you need? Verbose - module - catlog

**Comment by kotori2** [comment]
> After 4576 build all is fine except some modules fucntions are broken like customiuizer. 

Expected behaviour because of the breaking changes from Riru. 
Send error report to these modules please.

**Comment by eierfrucht** [comment]
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: HUAWEI
Brand: HONOR
Device: HWDUK
Product: DUK
Model: DUK-L09
Fingerprint: HONOR/DUK-L09/HWDUK:9/HUAWEIDUK-L09/215C10:user/release-keys
ROM description: DUK-L09-user 9.1.0 HUAWEIDUK-L09 215-OVS-LGRP2 release-keys
Architecture: arm64-v8a
Android build: HUAWEIDUK-L09
Android version: 9
Android sdk: 28
EdXposed version: v0.4.6.4 (4563) (YAHFA)
EdXposed api: 91.0
Riru version:  ()
Riru api: 
Magisk: 20.4 (20400)
--------- beginning of main
--------- beginning of system
--------- beginning of crash
11-25 18:32:44.069  6512  6512 D EdXposedManager: EdXposed is not active
11-25 18:32:44.070  6512  6512 D EdXposedManager: EdXposed is not active

**Comment by slimshouki** [comment]
> --------- beginning of head
> EdXposed Log
> Powered by Log Catcher
> QQ support group: 855219808
> Telegram support group: @Code_Of_MeowCat
> Telegram channel: @EdXposed
> --------- beginning of information
> Manufacturer: HUAWEI
> Brand: HONOR
> Device: HWDUK
> Product: DUK
> Model: DUK-L09
> Fingerprint: HONOR/DUK-L09/HWDUK:9/HUAWEIDUK-L09/215C10:user/release-keys
> ROM description: DUK-L09-user 9.1.0 HUAWEIDUK-L09 215-OVS-LGRP2 release-keys
> Architecture: arm64-v8a
> Android build: HUAWEIDUK-L09
> Android version: 9
> Android sdk: 28
> EdXposed version: v0.4.6.4 (4563) (YAHFA)
> EdXposed api: 91.0
> Riru version:  ()
> Riru api: 
> Magisk: 20.4 (20400)
> --------- beginning of main
> --------- beginning of system
> --------- beginning of crash
> 11-25 18:32:44.069  6512  6512 D EdXposedManager: EdXposed is not active
> 11-25 18:32:44.070  6512  6512 D EdXposedManager: EdXposed is not active

Use new canary build from manager

**Comment by eierfrucht** [comment]
Since you can't even install EdXposed with Riru 22 the root of the issue could be narrowed down by replicating the Riru presence checks from EdXposed installation script.

https://i.postimg.cc/ZqNpng9K/216w-VTu-Yp40-1.jpg
