### ISSUE TITLE
无法安装，已装riru

### ISSUE THREAD

**Issue by young1023x2** [ElderDrivers/EdXposed#656]
更新了riru(22),edxposed失效，想重装均安装失败，系统安卓10。
![20201125_125807](https://user-images.githubusercontent.com/62231819/100185238-523a2a00-2f1e-11eb-8555-680d6b1dd148.jpg)
![20201125_125850](https://user-images.githubusercontent.com/62231819/100185247-58300b00-2f1e-11eb-99e4-5b39ea634868.jpg)
![20201125_125831](https://user-images.githubusercontent.com/62231819/100185251-5c5c2880-2f1e-11eb-85cf-e8b4bb4e6311.jpg)

**Comment by kotori2** [comment]
https://github.com/ElderDrivers/EdXposed/issues/645#issuecomment-732002147
