### ISSUE TITLE
[BUG] 0.5.0.6 (457x-4586) bootloops

### ISSUE THREAD

**Issue by enetec1** [ElderDrivers/EdXposed#657]
I've tested EdXposed Sandhook v.0.5.0.6 (4573) on my Moto Z2 with Android 9 but it bootloops on reboot. 

Previous v.0.5.0.6 (4569), reinstalled, boots fine. 
(but it doesn't work with some old modules as I already reported, while v.0.4.6.4 (4563) works fine at all - but not with Riru v.22, "not found").

Will you ever release a v.0.4.x.x working fine with Riru v.22?

I've no catlogs, sorry...

**Comment by kotori2** [comment]
Please provide logcat, ot it won't be fixed.
Also we won't release v0.4.x with Riru v22

**Comment by enetec1** [comment]
I needed to do multiple actions and reboots to have system running fine again... Logs have been overwritten I think... 

If you can link me a *good* guide to preserve them I'll try with the next release...

**Comment by kotori2** [comment]
> Logs have been overwritten I think..

Grab a PC and execute
```
adb logcat > aaa.txt
adb logcat > bbb.txt
```
etc

**Comment by enetec1** [comment]
> If you simply googling you can easily found [tutorial](https://forum.xda-developers.com/showthread.php?t=2774386) everywhere.

Following tutorial I got a "working logcat", not including errors generated during bootloop... 

Is there a way to preserve them by TWRP e.g. using file manager to save them?

**Comment by kotori2** [comment]
> not including errors generated during bootloop

logcats generates real-time during boot. Just do them while you encounter boot loop.
> Is there a way to preserve them by TWRP e.g. using file manager to save them?

Unfortunately no.

**Comment by enetec1** [comment]
Latest 4586 master still bootloops on my Moti Z2 with Android 9 (even with Riru 22.4 too...). 

I'm working to provide a logcat...

**Comment by enetec1** [comment]
[Catlog](https://mega.nz/file/08R0nDaR#DtyqPR6lWFT0ru3TDOVxz4tMB3WG9n-YaQVfmCrvMso)

**Comment by enetec1** [comment]
@kotori2 you can remove NeedInfo tag...  ;)

**Comment by kotori2** [comment]
Sorry but I currently don't have time looking into it.

**Comment by yujincheng08** [comment]
duplicate to #688

**Comment by enetec1** [comment]
> Sorry but I currently don't have time looking into it.

Ok. You asked for a logcat and I sent it. I only asked to remove the tag...

**Comment by enetec1** [comment]
> duplicate to #688

Read #688, probably you are right... it seems my report was right... Again.;)
