### ISSUE TITLE
[BUG] "Riru - Core is missing" after upgrade to Riru 22. Impossible to run or reinstall EdXposed from Magisk Repo.

### ISSUE THREAD

**Issue by eierfrucht** [ElderDrivers/EdXposed#663]
After upgrading to Riru 22, a previously working copy of EdXposed 4.6.4 (YAHFA) no longer loads at boot: https://i.postimg.cc/TYkr4nMG/iunkkf-TVVso-1.jpg

When I try to reinstall EdXposed from Magisk Repo, installation fails at 'Riru Core is Missing': https://i.postimg.cc/ZqNpng9K/216w-VTu-Yp40-1.jpg

Device information:

Device: Huawei Honor 8 Pro (DUK-L09)
OS: EMUI 9.1.0.215
Additional context

Due to Magisk 20.4, I manually rebooted the device more than just twice, as demanded by Riru 22 install log. Storage Isolation is still fully functional (upgraded to latest module & app) so Riru 22 is basically working for stuff other than EdXposed.

**Comment by kotori2** [comment]
@eierfrucht https://github.com/ElderDrivers/EdXposed/issues/653#issuecomment-732815190
