### ISSUE TITLE
[BUG] 4576版本，xposed edge模块不生效，微x多开的微信没生效

### ISSUE THREAD

**Issue by soulpursuit** [ElderDrivers/EdXposed#666]
**什么情况/What happened?*
 4576版本，
xposed edge模块不生效，4569的s版则能正常使用，

4576版本微x多开的微信没生效
4576版本，小爱同学报错

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:
4576
Riru:
22.0
![Screenshot_2020-11-26-11-02-58-066_com miui bugreport](https://user-images.githubusercontent.com/48674277/100303552-b1a84080-2fd7-11eb-8032-149074a45848.jpg)

**相关Logcat/Logcat**

有定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
[EdXposed_Verbose_20201126_110354.txt](https://github.com/ElderDrivers/EdXposed/files/5600260/EdXposed_Verbose_20201126_110354.txt)

**Comment by kotori2** [comment]
模块问题
