### ISSUE TITLE
android 11 xprivacy lua 

### ISSUE THREAD

**Issue by reyis4402** [ElderDrivers/EdXposed#667]
Hello there
I installed the edxposed developer package for android 11 but I ran into this error. What do I have to do to use the xprivacy lua module?
![Screenshot_20201126-121650_EdXposed_Manager](https://user-images.githubusercontent.com/60405617/100331801-e664c980-2fd0-11eb-98b4-f6a1819163ff.png)

**Comment by kotori2** [comment]
@reyis4402 Use YAHFA #662

**Comment by reyis4402** [comment]
Android 11 
![Screenshot_20201126-122456_Magisk_Manager](https://user-images.githubusercontent.com/60405617/100332421-a9e59d80-2fd1-11eb-901c-aab0c9f0c358.png)

**Comment by reyis4402** [comment]
These are the edxposed packages I have installed
![20201126_122223](https://user-images.githubusercontent.com/60405617/100332491-bec23100-2fd1-11eb-9c5d-7d58af42c73c.jpg)

**Comment by JasonKhew96** [comment]
@reyis4402 get canary build
https://github.com/ElderDrivers/EdXposed/issues/665
