### ISSUE TITLE
Can't install either of the versions of Riru EdXposed

### ISSUE THREAD

**Issue by ChandlerWaterson** [ElderDrivers/EdXposed#668]
First of all, I have installed Riru as the core service for all Riru family services. Nevertheless, when I tried to install Riru EdXposed, my magisk first reported that the EdXposed could be installed due to the lack of Riru core. The truth is that the core was properly installed and activated and I have already checked it under data/adb/riru but nothing there showed it was disabled or having any problems. Afterwards, I just tried to do the entries process for a few time but the same result came to me again and again.
  It used to work well while I was using lineage os. I am currently using Evolution X rom, a pixel os based third party rom and twrp recovery plus fine installed magisk. I am really confused right now how can I solve this problem. Wish to get some help, thank you!

EdXposed version:
v0.4.6.4. (YAHFA) & (SandHook)
Riru version:
v22.4
Magisk version:
20.4

Logcat (nothing special, only says Riru not installed, so I didn't post here)

**Comment by kotori2** [comment]
Use Canary builds if you wanna try Riru v22
#665
