### ISSUE TITLE
[BUG] 这几次edxp更新了sepolicy之后，edge pro就出错啦

### ISSUE THREAD

**Issue by phoenixxie7** [ElderDrivers/EdXposed#673]
**什么情况/What happened?**

Selinux设置为enforce模式edge pro出错，现在只能用permissive才能正常使用edge pro。其他模块暂时没发现问题

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v5.0.6_456x-v5.0.6_4577

Riru: 22.4 

**相关Logcat/Logcat**

000-00:00:16.481  Xposed-edge-pro-v6.0.1-beta-2010251622, activated by EdXposed. 
  OnePlus IN2010, OnePlus8, Android 11, SDK 30, ROM: IN2010_15_201101, SELinux enforced.
000-00:00:16.530  System hooked
000-00:00:20.818  Initializing...
000-00:00:20.818  Screen size: 1080, 2400
000-00:00:20.580  System ready.
000-00:00:20.884  System booted.
000-00:00:20.911  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
000-00:00:20.911  Settings not loaded!
000-00:00:20.913  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/prefs: open failed: EACCES (Permission denied)
000-00:00:20.913  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/hidden_apps: open failed: EACCES (Permission denied)
000-00:00:20.913  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/alarms: open failed: EACCES (Permission denied)
000-00:00:20.913  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/variables: open failed: EACCES (Permission denied)
000-00:00:20.914  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/multi_actions: open failed: EACCES (Permission denied)
000-00:00:20.914  Failed to reload settings!
000-00:00:20.914  Package folder can read.
000-00:00:20.914  Module initialed.
000-00:00:32.957  Boot completed
000-00:00:36.038  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/prefs: open failed: EACCES (Permission denied)
000-00:00:36.038  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/hidden_apps: open failed: EACCES (Permission denied)
000-00:00:36.038  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/alarms: open failed: EACCES (Permission denied)
000-00:00:36.039  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/variables: open failed: EACCES (Permission denied)
000-00:00:36.039  java.io.FileNotFoundException: /data/user_de/0/com.jozein.xedgepro/prefs/multi_actions: open failed: EACCES (Permission denied)
000-00:00:36.039  Failed to reload settings!

**Comment by kotori2** [comment]
@phoenixxie7 Read config directly from data partition is not recommended. Tell the developers to change their config location.
