### ISSUE TITLE
[BUG] some.modules not working as supposed to do

### ISSUE THREAD

**Issue by slimshouki** [ElderDrivers/EdXposed#677]
**什么情况/What happened?** some modules not are not working like xposes edge and other not fully functioning such as customiuizer (min. Autobrightness not working)

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List** chromepie-unlimited call log-customizer-xposed edge pro-instapref-Wa tweaker-Nfg multi crack

允许截图/Screenshot allowed 
![IMG_20201127_152822](https://user-images.githubusercontent.com/74891073/100454292-49d02380-30c5-11eb-8e1d-4205f2aa5537.jpg)

**Magisk模块列表/Magisk Module List** riru core- edxposed - riru clipboard- gms doze

允许截图/Screenshot allowed 
![Screenshot_2020-11-27-15-28-37-249_iqgna twkk fy ms](https://user-images.githubusercontent.com/74891073/100454311-518fc800-30c5-11eb-94d7-ef459b8e70fe.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6_4583

Riru: 22.4

**相关Logcat/Logcat**
[Verbose log](https://drive.google.com/file/d/1mDeExfnaX1XpcRk_42xpMAAZHFnRA-TV/view?usp=drivesdk) 
[Modules log](https://drive.google.com/file/d/1m8_-M29fzZ7eeVO43e85bJZTAMOrQ9ia/view?usp=drivesdk) 

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by kotori2** [comment]
Module specific issue is not accepted here.

**Comment by slimshouki** [comment]
> Module specific issue is not accepted here. 

Ok sorry
