### ISSUE TITLE
可以再完善一下EdXposed Manager

### ISSUE THREAD

**Issue by ceadmond** [ElderDrivers/EdXposed#68]
1.现在的2.0版本依然和原版Xposed Installer一样，会提示当前sdk版本过高不支持的warning，这个可以去除掉了
2.原版Xposed Installer有多个图标，可在设置里面选择，但是其实也就那个圆形的白底图标还可以，其他可以不要了，或者考虑重绘一个新的图标，并且有adaptive icon

**Comment by solohsu** [comment]
可以有但并不是那么重要（并不影响正常功能），目前优先解决可用性问题。
如果有能力，欢迎自行修改并提交pull requests。
