### ISSUE TITLE
[BUG] 4569之后双开应用不加载模块

### ISSUE THREAD

**Issue by klever1988** [ElderDrivers/EdXposed#683]
**什么情况/What happened?**

双开应用不加载，原应用正常。4569是正常的，4569之后跳着测试到4586数个版本都不行。

**Xposed模块列表/Xposed Module List**

![image](https://user-images.githubusercontent.com/56048681/100485471-247dfc80-313b-11eb-9394-a43a8b89f05b.png)

**Magisk模块列表/Magisk Module List**

![image](https://user-images.githubusercontent.com/56048681/100485465-1def8500-313b-11eb-9000-b7ebf1da98ed.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

![image](https://user-images.githubusercontent.com/56048681/100485552-74f55a00-313b-11eb-8b8d-bd28982c76fc.png)

**相关Logcat/Logcat**

[EdXposed_Modules_20201128_052749.txt](https://github.com/ElderDrivers/EdXposed/files/5609614/EdXposed_Modules_20201128_052749.txt)
[EdXposed_Verbose_20201128_052807.txt](https://github.com/ElderDrivers/EdXposed/files/5609615/EdXposed_Verbose_20201128_052807.txt)

**Comment by kotori2** [comment]
怎么个双开法

**Comment by klever1988** [comment]
> 怎么个双开法

miui内置的应用双开

**Comment by jinbolin227** [comment]
不只双开，还有QQ微信插件无法激活

**Comment by wzgrx** [comment]
双开21.3riru和稳定版edxp是可以用的，升级到224和测试版，双开失效

**Comment by 06ji** [comment]
双开的app是无法使用模块，小米系统

**Comment by wzgrx** [comment]
> 双开的app是无法使用模块，小米系统

是的，最新测试版双开失效，还有一些模块无法激活

**Comment by JasonKhew96** [comment]
亲测 练药壶 (Island) 有效，必须克隆 EdXposed Manager + 模块 + 指定应用
另外设置 EdXposed Manager，激活模块，作用域之类的

版本详情:
EdXposed YAHFA - `f6cab13e22b1051664d294133c0adad6504e67bf`
EdXposed Manager R - `5502e3281530b41db967b1a4a49e39b913d601bf`

**Comment by kotori2** [comment]
请清楚地提供到底是双开什么应用的时候抓的日志并发现不行，并且尽可能使用debug版，要不然三千多行日志你还能指望别人一行一行帮你读吗

**Comment by 06ji** [comment]
> 请清楚地提供到底是双开什么应用的时候抓的日志并发现不行，并且尽可能使用debug版，要不然三千多行日志你还能指望别人一行一行帮你读吗

刷了debug，如何抓日志。。。双开微信，双开淘宝，双开支付宝等等，模块是没加载在双开上

**Comment by kotori2** [comment]
> 亲测 练药壶 (Island) 有效，必须克隆 EdXposed Manager + 模块 + 指定应用
> 另外设置 EdXposed Manager，激活模块，作用域之类的
> 
> 版本详情:
> EdXposed YAHFA - `f6cab13e22b1051664d294133c0adad6504e67bf`
> EdXposed Manager R - `5502e3281530b41db967b1a4a49e39b913d601bf`

@06ji 先把manager克隆了

**Comment by 06ji** [comment]
> > 亲测 练药壶 (Island) 有效，必须克隆 EdXposed Manager + 模块 + 指定应用
> > 另外设置 EdXposed Manager，激活模块，作用域之类的
> > 版本详情:
> > EdXposed YAHFA - `f6cab13e22b1051664d294133c0adad6504e67bf`
> > EdXposed Manager R - `5502e3281530b41db967b1a4a49e39b913d601bf`
> 
> @06ji 先把manager克隆了

4586双开edxp，双开的app是生效了，4587双开失效了。。。

**Comment by wzgrx** [comment]
最新测试版4589双开还是失效，啥时候修好了替我一下
