### ISSUE TITLE
[TODO] stable EdXposed  0.4.6.x 4563 compatible with Riru v.22.x

### ISSUE THREAD

**Issue by enetec1** [ElderDrivers/EdXposed#689]
EdXposed v.0.4.6.4 (4563) is the last known good version which is fully compatible even with A LOT of Xposed old modules and very stable. 

Successive versions v.0.5.x.x has (up to now...) reduced modules compatibility and/or bootloop issues. 

The only issue is that 4563 is not able to detect Riru v.22.x... 

So, I think it wouldn't be a bad idea to release a (last?) *stable* v.0.4.6.x based on 4563 and only with path detection of Riru modified to work with v.22.x too...

**Comment by kotori2** [comment]
> reduced modules compatibility

Actually caused by breaking changes from Riru v22. So there is no 0.4.6.x release.

**Comment by enetec1** [comment]
> > reduced modules compatibility
> 
> Actually caused by breaking changes from Riru v22. So there is no 0.4.6.x release.

Prove it. Release it and we'll try...  😏

**Comment by yujincheng08** [comment]
@enetec1 Who are you? Why should we prove it to you? It's a waste of time. Plz lock this thread @kotori2 .

**Comment by kotori2** [comment]
> > > reduced modules compatibility
> > 
> > 
> > Actually caused by breaking changes from Riru v22. So there is no 0.4.6.x release.
> 
> Prove it. Release it and we'll try... 😏

https://git-scm.com/docs/git-cherry-pick

**Comment by enetec1** [comment]
> @enetec1 Who are you? Why should we prove it to you? It's a waste of time. Plz lock this thread @kotori2 .

Look on XDA...  ;)

**Comment by enetec1** [comment]
Reported on Riru GitHub as above...

**Comment by enetec1** [comment]
Just closed as "stupid issue" by Kikka...  ;)

I think he is not so "convinced" about Riru v.22.x broking EdXposed modules compatibility... 😏

**Comment by enetec1** [comment]
I've done some extensive tests... 

Moto Z2 Force on Android P stock

Riru - EdXposed - Behaviour
---------------------------------------------
v.21.x - 0.4.6.x (4563) - All fine
v.22.x - 0.4.6.x (4563) - Xposed not loaded (Riru not found) 
v.22.x - 0.5.0.x (4569) - Old Xposed modules don't work well
v.21.x - 0.5.0.x (4569) - Xposed not loaded (Riru not found) 
v.21.x - 0.5.0.x (4562) - Old Xposed modules don't work well (!!)
v.22.x - 0.5.0.x (>4570) - Bootloops

So, @kotori2 I think you should reopen this, eventually with a modified title "0.5.x.x. versions break compatibility with old Xposed modules", since it's clear that it. Is *NOT* a Riru v.22.x issue at all... (v21 + 4562 fail...!)

@yujincheng08 ...and now?  😏

**Comment by kotori2** [comment]
> Just closed as "stupid issue" by Rikka...

Indeed
