### ISSUE TITLE
[BUG] Are you using the deprecated DexFile APIs?

### ISSUE THREAD

**Issue by acestars** [ElderDrivers/EdXposed#690]
Magisk: 1469b82a (21101)
Magisk Manager: 1469b82a (315)
Riru: 22.4
Edxposed: Yahfa 4568-4586
Edxposed Manager: 45700
Android: 9
OS: Lineage OS 16
Device: Xiaomi Redmi Note 2

Issue Yahfa
1. Remove Riru v21.3 and removed Edxposed Yahfa 4565 from magisk manager and reboot
2. Install Riru 22.4. Reboot. The phone booted normally.
[logcat-sandhook.txt](https://github.com/ElderDrivers/EdXposed/files/5611342/logcat-sandhook.txt)
3. Install Edxposed YAHFA 4568-4586. Reboot. the phone booted into homescreen without lock screen and notification.

In logcat i can see multiple "Are you using the deprecated DexFile APIs?" and recompile the apk (dex2oat) recursively.
[logcat-yahfa.txt](https://github.com/ElderDrivers/EdXposed/files/5611341/logcat-yahfa.txt)

Issue Sandhook:
It is bootloop not in boot animation but in lock screen.
[logcat-sandhook.txt](https://github.com/ElderDrivers/EdXposed/files/5611344/logcat-sandhook.txt)

**Comment by yujincheng08** [comment]
You have too many modules enabled. Plz disable them all and check if you can boot normally.

**Comment by acestars** [comment]
i have already disabled all module but still error.

[logcat10.txt](https://github.com/ElderDrivers/EdXposed/files/5613762/logcat10.txt)

**Comment by yujincheng08** [comment]
No.
`de.Maxr1998.xposed.maxlock`, `net.jzhang.powernap`, `net.iptux.xposed.callrecording`, `ru.sxbuIDfx.pFSOyagrF`, `tw.fatminmin.xposed.minminguard`, `org.meowcat.edxposed.manager`, `com.android.vendinf`, `com.oasisfeng.greenify`, `eu.faircode.xlua`, ...
They are NOT disabled.

Check your log with `EdXposed-Bridge: Loading modules` please.

**Comment by acestars** [comment]
Im sorry i misunderstood about the module, i thought magisk modules. okay i will try again.

**Comment by yujincheng08** [comment]
So this is not EdXposed's issue.
