### ISSUE TITLE
[BUG] canary最新版YAHFA-4586刷入后开机卡米

### ISSUE THREAD

**Issue by EWF54Y6U7I** [ElderDrivers/EdXposed#691]
**什么情况/What happened?**

无法开机，在开机第二屏中一直加载（非无限重启），
设备是：小米MIX2s
系统是：MIUI9.6|稳定版(9.6.10.0(ODGCNFD))，安卓8.0.0
EdXposed Manager 是45756

**Xposed模块列表/Xposed Module List**

允许截图/Screenshot allowed
![edxpmodule](https://user-images.githubusercontent.com/55339634/100536135-6309d900-3259-11eb-942f-85e197130aa3.jpg)

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed
![magisk](https://user-images.githubusercontent.com/55339634/100536170-99475880-3259-11eb-9271-1b62f0250775.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:**EdXposed-SandHook-v0.5.0.6_4586-master-release.zip** and **EdXposed-YAHFA-v0.5.0.6_4586-master-release.zip**
两个都试过，日志为刷入YAHFA后获取的

Riru: v22.4，(原本是v22.0，以为是Riru的问题，升了22.4也是这样)

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
以下为日志文件：
[logs.zip](https://github.com/ElderDrivers/EdXposed/files/5611838/logs.zip)
> 日志说明：压缩包中Log-Catcher文件夹内是用[这个模块](https://github.com/Howard20181/Log-Catcher)获取的，小工具文件夹是按照群里[这条消息](https://t.me/CodeOfMeowCat/464343)获取的日志

**Comment by kotori2** [comment]
duplicate #688
