### ISSUE TITLE
[BUG] Bootloop in EMUI8

### ISSUE THREAD

**Issue by 1024mb** [ElderDrivers/EdXposed#695]
**什么情况/What happened?**

Phone bootloops whenever I install EdXposed, I've tried installing Riru, then rebooting = it all went well. Install EdXposed (any of the two available) and bootloops.

Phone is a Huawei P8 Lite 2017 using EMUI 8.0.0.388 Android 8.0.0.

**Xposed模块列表/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**

- Riru
- EdXposed /YAHFA or SandHook/, it happens with both.

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.4.6.4

Riru: 21.3

**相关Logcat/Logcat**

Logcat while booting (taken from adb) when Riru + EdXposed Sandhook were installed.

[logcat2.txt](https://github.com/ElderDrivers/EdXposed/files/5612724/logcat2.txt)

**Comment by yujincheng08** [comment]
Try riru22 and latest canary. 0.4.6.4 is obsolete.

**Comment by 1024mb** [comment]
> 
> 
> Try riru22 and latest canary. 0.4.6.4 is obsolete.

Installed Riru v22.4, rebooted to check and booted OK, installed latest build 0.5.0.6 (4586) but it bootloops again. Here is a new logcat taken when booting: 
[logcat3.txt](https://github.com/ElderDrivers/EdXposed/files/5613144/logcat3.txt)

**Comment by yujincheng08** [comment]
Duplicate to #688 now. Please wait for a fix or use the workaround.

**Comment by 1024mb** [comment]
> 
> 
> Duplicate to #688 now. Please wait for a fix or use the workaround.

Thanks, should this be closed?

**Comment by yujincheng08** [comment]
yes. You can close this and subscribe that issue.
