### ISSUE TITLE
[Proposal] Move configurations elsewhere instead of the data dir of the manager

### ISSUE THREAD

**Issue by yujincheng08** [ElderDrivers/EdXposed#696]
# Motivation
Storing configurations in the installer's data dir is outdated and easily detected. If moved elsewhere, the manager's target SDK can be higher than 27, and randomizing the package name is feasible.

# Background
`/data/adb` is the common choice of magisk modules to store their configurations because it's protected by selinux and cannot be detected by using `fstat` (always returns permission denied no matter if it exists). However, one problem with this directory is that even if we change its context and owner, normal apps cannot access it, preventing non-root manager from editing configurations.
`/data/misc` is another common choice. It can not be listed without permissions but it's accessible to normal apps if the correct context and owner are set. However, it can be detected by `fstat` (return permission denied if it exists and no such file or dir if not exists).

# Strategy
Based on the different properties of the above two directories, we proposed to combine to use them both for the accessibility of the non-root manager and the indetectability of normal apps.
We store things in a randomly named directory in `/data/misc` mounted by magisk, and the file name is store in `/data/adb/edxp`. The randomly named directory cannot be detected by normal apps because its name is random and `/data/misc` is not listable. `/data/adb/edxp` cannot be detected by normal apps either because it's protected by selinux. The manager can access this directory because the backend of EdXposed can tell the manager the path and set proper permission for the manager.
The context we proposed to use is `u:object_r:magisk_file:s0` because it's accessible by zygote and normal app without further sepolices. (The context of `/data/local/tmp`.)
Furthermore, it has an advantage that we can implement a new XSharePreference for communication between the modules and their hooked apps.

Comments are welcomed if this strategy has any permission problem or anti-detection defect.

**Comment by kotori2** [comment]
> The manager can access this directory because the backend of EdXposed can tell the manager the path and set proper permission for the manager.


> ... and randomizing the package name is feasible.

They are actually conflicted.

**Comment by yujincheng08** [comment]
no. we can save the installer's package name in /data/misc. So zygote knows the installer's package name.

**Comment by kotori2** [comment]
> So zygote knows the installer's package name.

And everyone knows

**Comment by yujincheng08** [comment]
BUT the directory name in /data/misc/ is randomized! They cannot know.

**Comment by yujincheng08** [comment]
Let me clarify how random package name works:
We will store that package name in the random directory in `/data/misc`. Definitely, it has a default value of the default package name of the installer. So we can recognize the installer at the very beginning.

When we try to randomize the package name of the installer, the installer can write its new package name to the random directory in `/data/misc/` before asking the user to install it. So, we can also recognize the new random package name.

Further, if we ever detect that an app with the default package name of the installer launch, we will reset the stored package name of the installer. This is a fallback for users who reinstall the original manager or forget the randomized one.

**Comment by XspeedPL** [comment]
On the topic of providing configuration files, I think looking into the new "rirud" is a good start.

**Comment by kotori2** [comment]
@XspeedPL rirud is too complex tbh

**Comment by yujincheng08** [comment]
No. The new "rirud" does provide ways to read new files without permission in zygote. But how about SharePreferences?
