### ISSUE TITLE
v0.2.9.8_beta1导致无限重启

### ISSUE THREAD

**Issue by Morningtea7** [ElderDrivers/EdXposed#70]
开机后会卡在锁屏界面，系统界面会自动重启数次，几分钟后手机重启。机型华为P20 Pro，运行原生安卓9。v0.2.9.7没有这个问题。

**Comment by solohsu** [comment]
Try https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2

**Comment by QGB** [comment]
nexus6p same question
