### ISSUE TITLE
[BUG] Gravitybox (q) not working anymore after recent riru update

### ISSUE THREAD

**Issue by techIndia-hacker** [ElderDrivers/EdXposed#702]
**什么情况/What happened?**
Device :- 1+ 7T

Gravitybox 1.0.0.1 not working anymore since a week after recent riru core update

**Xposed模块列表/Xposed Module List**
![Screenshot_20201202-095601](https://user-images.githubusercontent.com/58086339/100828275-ca57a100-3484-11eb-833f-b167fc152399.jpg)

**Magisk模块列表/Magisk Module List**
![Screenshot_20201202-095649](https://user-images.githubusercontent.com/58086339/100828300-d6dbf980-3484-11eb-9b72-c4dcdb13447c.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.5.0.6_4586-master yahfa
Edxposed manager - 4.6.0-pre

Riru: 22.4

**相关Logcat/Logcat**
It's empty due to unknown reasons
![Screenshot_20201202-100934](https://user-images.githubusercontent.com/58086339/100829066-81a0e780-3486-11eb-8be3-87cab8ee089f.jpg)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by nivicentiu** [comment]
Riru 22+ is not backwards compatible and all modules need an update.

Read release notes for v22.0 - https://github.com/RikkaApps/Riru/releases

**Comment by christophe-95** [comment]
In fact, gravitybox works but you need to re-apply your changes after reboot !

**Comment by techIndia-hacker** [comment]
No over 90% of the mods aren't working

**Comment by kotori2** [comment]
https://github.com/GravityBox/GravityBox/issues/2089
