### ISSUE TITLE
Update EdXposed 0.4.6.x with Riru v22 API changes

### ISSUE THREAD

**Issue by nivicentiu** [ElderDrivers/EdXposed#704]
Riru updated its API with v22 and EDXposed 0.4.6.4 4563 doesn't work with it.

**From https://github.com/RikkaApps/Riru-ModuleTemplate/blob/master/README.md#api-changes**

_Starting v22.0, Riru has switched to "native bridge" (ro.dalvik.vm.native.bridge) to inject zygote, this will lead Riru and modules be loaded later (LoadNativeBridge vs \_\_attribute\_\_((constructor))).
For most modules, this should have no problem, but modules like Xposed frameworks may have to make changes._

**Release notes from v22.0 - https://github.com/RikkaApps/Riru/releases**

_Riru v22 has a new hide mechanism which makes detection "not that easy".
Because of this, **all modules must change.** If your module hasn't updated, ask the module developer to make changes. For 99% modules, this is super easy._

**Comment by yujincheng08** [comment]
You should have read the pinned issue.

**Comment by nivicentiu** [comment]
Ah, thanks.... So, will canary work with Android 9? That's what I have.... I see that Canary version 5 is for Android 11.

**Comment by yujincheng08** [comment]
Actually no, #688
