### ISSUE TITLE
Banking app detects EdXposed

### ISSUE THREAD

**Issue by nivicentiu** [ElderDrivers/EdXposed#705]
App: https://play.google.com/store/apps/details?id=ro.btrl.pay

**Xposed Module List** - none

**Magisk Module List** - none, except Riru and EdXposed
Riru v21.3
EdXposed v0.4.6.4 (4563)

SafetyNet passes
App is blacklisted in EdXposed Manager

App registers Device ID with servers once it detects root, so app data needs to be erased and the Device ID needs to be changed with the following app:
https://play.google.com/store/apps/details?id=com.silverlab.app.deviceidchanger.free

**Comment by yujincheng08** [comment]
Try canary.

**Comment by nivicentiu** [comment]
Does Canary work on Android 9?

**Comment by yujincheng08** [comment]
Unfortunately, not yet #688. Plz wait patiently.

**Comment by nivicentiu** [comment]
Will do. thanks

**Comment by kotori2** [comment]
#688 was fixed so I'm closing this

**Comment by nivicentiu** [comment]
Can you wait until I validate?

**Comment by kotori2** [comment]
It can be re-open if something goes wrong.
