### ISSUE TITLE
[BUG] 安装并激活哔哩哔哩漫游模块，开机会卡在警告界面

### ISSUE THREAD

**Issue by dytfy666** [ElderDrivers/EdXposed#706]
**什么情况/What happened?**

安装并激活哔哩哔哩漫游模块，开机会卡在警告界面

**Xposed模块列表/Xposed Module List**
![Screenshot_20201203_132434_org meowcat edxposed manager](https://user-images.githubusercontent.com/58970365/100967771-049b6e00-356b-11eb-9fbb-6132d3f8bc3b.jpg)

**Magisk模块列表/Magisk Module List**

![Screenshot_20201203_132420_com topjohnwu magisk](https://user-images.githubusercontent.com/58970365/100967777-09f8b880-356b-11eb-8be8-8a931515f188.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:v0.4.6.4(4563)(YAHFA)

Riru:v21.3

**相关Logcat/Logcat**
[logcat.txt](https://github.com/ElderDrivers/EdXposed/files/5633844/logcat.txt)

下面是提取的一部分日志，以及哔哩哔哩漫游作者给我回复的消息，希望有用

12-02 22:11:56.120 F/zygote64( 2875): jni_internal.cc:619] JNI FatalError called: (system_server) Not whitelisted : /data/app/me.iacn.biliroaming-LmQ2RxHsEZFGN_2BisV1tA==/base.apk

这跟漫游没啥关系。漫游会在initzygote打开自己的apk以获取resource，而是zygote在fork的时候会检查打开文件白名单。EdXposed理论会吧/data/app的文件加到白名单。

**Comment by yujincheng08** [comment]
没错，还是我。
安卓Q或以上可以试试canary

**Comment by dytfy666** [comment]
> 没错，还是我。
> 安卓Q或以上可以试试canary

ok。我去试试，谢谢大佬，看我救砖模块16次哈哈哈

**Comment by dytfy666** [comment]
> 没错，还是我。
> 安卓Q或以上可以试试
尝试了一下，EMUI9还是只能用custom版本的magisk，然后最高版本是20.1，不能安装cannary版本的edx。...我再等等叭，就不该手欠乱搞，我之前是可以用的，

**Comment by dytfy666** [comment]
> 没错，还是我。
> 安卓Q或以上可以试试canary

尝试了一下，EMUI9还是只能用custom版本的magisk，然后最高版本是20.1，不能安装cannary版本的edx。...我再等等叭，就不该手欠乱搞，我之前是可以用的，

**Comment by FirstGuion** [comment]
所以为什么不更新到riru23以及edxp cannary版试试呢
