### ISSUE TITLE
[BUG] Exposed 0.5.0.6 4587 doesn't load modules

### ISSUE THREAD

**Issue by RaphaelGreen** [ElderDrivers/EdXposed#709]
**什么情况/What happened?**
Installed. Activated. Doesn't want to load any modules.

**Xposed模块列表/Xposed Module List**
Lucky Patcher
Min Min Guard
允许截图/Screenshot allowed
![Screenshot_20201204-221856](https://user-images.githubusercontent.com/75275527/101211593-17539700-3680-11eb-8360-d0bed453090a.jpg)
![Screenshot_20201204-221832](https://user-images.githubusercontent.com/75275527/101211601-1884c400-3680-11eb-9784-d4ba99289325.jpg)

**Magisk模块列表/Magisk Module List**
![Screenshot_20201204-223330](https://user-images.githubusercontent.com/75275527/101212175-f5a6df80-3680-11eb-8a84-fab50f6c0de8.jpg)
![Screenshot_20201204-223350](https://user-images.githubusercontent.com/75275527/101212194-fb9cc080-3680-11eb-8885-51114f882034.jpg)
![Screenshot_20201204-223358](https://user-images.githubusercontent.com/75275527/101212197-fc355700-3680-11eb-83e1-7bc40da7f1b0.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**
Exposed YAHFA 0.5.0.6 4587
Riru v23.0
Exposed manager 4.5.7

**相关Logcat/Logcat**
[EdXposed_Verbose_20201204_223825.txt](https://github.com/ElderDrivers/EdXposed/files/5645340/EdXposed_Verbose_20201204_223825.txt)

[EdXposed_Verbose_20201204_223825.txt](https://github.com/ElderDrivers/EdXposed/files/5645345/EdXposed_Verbose_20201204_223825.txt)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module
Information about smartphone and Android:
Android 11
Oxygen OS 11.0.5.6
OnePlus 8T

**Comment by RaphaelGreen** [comment]
New version of exposed 4589. Same problem.
[EdXposed_Modules_20201207_121453.txt]
(https://github.com/ElderDrivers/EdXposed/files/5651976/EdXposed_Modules_20201207_121453.txt)
[EdXposed_Verbose_20201207_121525.txt](https://github.com/ElderDrivers/EdXposed/files/5651977/EdXposed_Verbose_20201207_121525.txt)

**Comment by RaphaelGreen** [comment]
[EdXposed_Verbose_20201207_121525.txt](https://github.com/ElderDrivers/EdXposed/files/5651984/EdXposed_Verbose_20201207_121525.txt)
[EdXposed_Modules_20201207_121453.txt](https://github.com/ElderDrivers/EdXposed/files/5651985/EdXposed_Modules_20201207_121453.txt)

**Comment by kotori2** [comment]
Please try more recent builds. 4589 is confirmed broken.

**Comment by xz-dev** [comment]
也许是配置文件未生成的问题，疑似 edxposed manager 的 bug，建议检查 /data/misc/edxp 文件夹下的配置文件

**Comment by hamedsbt** [comment]
I have the same issue, where I can download 4589 builds?

**Comment by dcoolArne** [comment]
I have the same problem with the new alpha release and riru 23.1 on Android 9

**Comment by dcoolArne** [comment]
Update, some modules work, like luky patcher and no device check, but others like firefeds, greenify or YouTube background playback only work on the old version.

**Comment by ShibaPonPon** [comment]
I want to add my experience, my module is xprivacylua, it seems that the difference is between the rom, I tried with both LOS 10 and CrDroid 10, the latest edxposed worked on LOS but not CrDroid, I tried downgrading the CrDroid 4.6.4 to no avail, but downgrading to 4.6.1 works, as referenced on #572 , the problems seems to stem from sepolicy.rules

**Comment by dcoolArne** [comment]
This is probably only realated to modules that didn't get updated yet. All my stuff works now.

**Comment by heinhuiz** [comment]
>4.6.4 works, just use riru v21 and edxposed 4.6.4, latest edxposed(5.x.x) has problems with older modules

I've have XPrivacyLua working with Magisk 20.4 and EdXposed 0.5.0.6, but not loading with Magisk 21.2 and same EX.
