### ISSUE TITLE
[BUG]  一加8T安卓R, Riru-v23(50),  EdXposed-v0.5.0.6_r_4587卡在启动画面

### ISSUE THREAD

**Issue by ml863606** [ElderDrivers/EdXposed#710]
**什么情况/What happened?**

一加8T安卓R, EdXposed4587卡在启动画面

**Xposed模块列表/Xposed Module List**

`com.oasisfeng.nevo.xposed
com.kapp.ifont
cn.wq.myandroidtoolsxposed
com.surcumference.fingerprintpay
com.crossbowffs.nekosms
tw.fatminmin.xposed.minminhide
com.sudocode.sudohide
com.qihoo.tbtool
github.tornaco.xposedmoduletest
com.lerist.xposed.apptranslator
name.caiyao.sporteditor
com.ext.star.wars
com.wpengapp.xposed
com.sollyu.xposed.hook.model
com.rikka.q
com.fuckcoolapk
com.modosa.unblockdarkmode
pansong291.xposed.quickenergy.qiufeng
com.android.z
github.tornaco.android.thanos
com.yuanwofei.cardemulator.pro
com.test.learnhook
com.kelvin.gai_ji_zh
com.silentservices.hushsms
com.fkzhang.qqxposed
name.caiyao.pdd_tool
com.sky.xposed.share
com.gojek.galau.ggtools
com.example.wx_plug_in3
com.kelvin.wesport
com.dilidili.vip
com.fkzhang.wechatxposed
net.androidwing.droidsword
com.specher.music163
com.jy.xposed.web
com.csw.xposedclipboard
com.sky.xposed.rmad
zzz.zzzz.fakeads
com.plus.boy
com.viewblocker.jrsen
com.ceco.q.gravitybox
me.weishu.corepatch
com.plus.dy
me.veryyoung.wechat.luckymoney
com.wuxianlin.luckyhooker
com.conch.bluedhook
ccc71.at.free
com.jizhi.optheme
com.zengdq.peixunxposed
com.sky.xposed.aweme
com.blanke.mdwechat
x.hook.emojihook
com.joshcai.mdwechat
wovow.youtubehelper
com.fifsource.android.noplaygames
com.mhook.alipay
com.flarejune.perfectcolorbar
pansong291.xposed.quickenergy
com.shatyuka.zhiliao
me.lee.adaway
com.raincat.unblockmusicpro
com.aviraxp.nomoregoogleplayservices
com.fakemygps.android
com.mhook.dialog.beta
com.tianxingjian.screenshot
pub.chara.cwui.pretendsharing_xposed
com.mhook.dialog
com.yaerin.xposed.hide
com.chenxiabin.xposed.ding
me.zjns.lovecloudmusic
com.jozein.xedgepro
com.android.vendinf
eu.faircode.xlua
com.jy.xposed.skip
com.flarejune.xposedblacklist
com.cofface.ivader
me.iacn.biliroaming
wechat.simpleforwarder
nil.nadph.qnotified
akhil.alltrans
com.android.vendine
com.modosa.switchnightui
nnnn.aaaaa.nevercrash
com.specher.ss
bin.xposed.Unblock163MusicClient
com.flo354.xposed.applocale
ml.qingsu.fuckview
zorro.xprivacy
ru.sxbuIDfx.pFSOyagrF
zzz.zzzz.fake_alipay
org.meowcat.edxposed.manager
com.oasisfeng.greenify
me.qiwu.MusicNotification
com.coderstory.toolkit
com.raincat.dolby_beta
top.fols.aapp.eternalprocessxposed
com.u.awemepartner
com.sky.xposed.rimet
cn.nexus6p.QQMusicNotify
com.diwa.xmodul
com.mx.accessibilitycontroller
club.youppgd.adhook
me.zpp0196.qqpurify
com.raincat.unblockneteasemusic
cat.dcat.roothide
cn.jk.whorapemyclipboard
com.cataclysm.i
com.devadvance.rootcloak2
site.cyningxu.grouphelper
com.elderdrivers.qmusic
kw.crack
com.sltpaya.yybxposed
com.omarea.vtools
com.github.char101.qslock
com.qianbajin.sportaccelerator
cn.kwaiching.hook
com.javaer.jdouyin
me.dannyit.wechat.chum
ma.wanam.youtubeadaway`

**Magisk模块列表/Magisk Module List**
`riru全家桶
隐藏底部导航条(Fullscreen/Immersive Gesture (Q-R))
Log Catcher
移除证书(Move Certificates)

`

允许截图/Screenshot allowed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

Riru:  v23(50)
EdXposed:  v0.5.0.6_4587-master(YAHFA)

**相关Logcat/Logcat**

[错误日志.zip](https://github.com/ElderDrivers/EdXposed/files/5646474/default.zip)

**Comment by kotori2** [comment]
我们没有时间帮你一个个测一百一十九个模块。

**Comment by MlgmXyysd** [comment]
在 提交 傻问题 之前，请先 阅读 http://edxp.meowcat.org/assets/EdXposedIssuesReport_cn.txt

**Comment by ml863606** [comment]
我以为是新版的ed和手机不兼容. 没想起来有可能是和模块冲突了,   确实犯傻了,  感谢 解答
