### ISSUE TITLE
[BUG] Camera app issue

### ISSUE THREAD

**Issue by RGBok** [ElderDrivers/EdXposed#711]
**什么情况/What happened?**
Camera app crashes when edxposed is installed

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

Jasi Patcher (disabled)

**Magisk模块列表/Magisk Module List**

Riru Core
EdXposed YAHFA

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.5.0.6_4586-master (YAHFA)

Riru: Riru v23.0 (50, API v10) is in use.

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by kotori2** [comment]
Add camera to black list or usr white list

**Comment by RGBok** [comment]
I followed instructions. No luck. Camera still not functional.

**Comment by kotori2** [comment]
> EdXposed: v0.5.0.6_4586-master (YAHFA)

Outdated.

**Comment by RGBok** [comment]
That done it. Thank you so much. 👍

**Comment by xxyzuo** [comment]
安卓11，pixel3，已将相机加入Edxposed黑名单，还是闪退无法运行
EdXposed：v0.5.0.6_4589-master（YAHFA）
Riru：正在使用Riru v23.0（50，API v10）
