### ISSUE TITLE
Android 11 - One UI 3.0 - Are these EdXposed logs correct (spam)?

### ISSUE THREAD

**Issue by psychopathologist** [ElderDrivers/EdXposed#712]
**What happened?**

Modules and Verbose logs are completely full of the duplicated info (also some weird ones). Spam?

**Xposed Module List**

EdXposed Manager (for testings purposes only)

**Magisk Module List**

![Screenshot_20201206-090755 1](https://user-images.githubusercontent.com/73371654/101279845-f97f5280-37a3-11eb-948c-e769a383e7a9.jpg)

**Versions of EdXposed and Riru**

EdXposed:
![Screenshot_20201206-090715_EdXposed_Manager 1](https://user-images.githubusercontent.com/73371654/101279875-38150d00-37a4-11eb-9014-917abc93c8bf.jpg)

Riru:
v23.0

**Logcat**

Modules:
[EdXposed_Modules_20201206_090634[1].txt](https://github.com/ElderDrivers/EdXposed/files/5648730/EdXposed_Modules_20201206_090634.1.txt)

Verbose:
[EdXposed_Verbose_20201206_090642[1].txt](https://github.com/ElderDrivers/EdXposed/files/5648732/EdXposed_Verbose_20201206_090642.1.txt)

I'm running samsung stock one ui 3.0 (android 11). Any info about the "issue" would be great.
Thank you!

**Comment by psychopathologist** [comment]
And, by the way, will resource hooking be available at some point? Even just for simple ones, like replacing integers, bools?

**Comment by yujincheng08** [comment]
This is expected.

**Comment by psychopathologist** [comment]
> This is expected.

Thanks for the info.
It's indeed a weird behavior. I'm a module developer and I coud'nt remember seeing this before (at least till latest android p yahfa build). Hope you (edxposed devs) could fix this when possible, to keep things as clean as they were before.

**Comment by kotori2** [comment]
@psychopathologist It is a new feature to prevent detection from white listed apps

**Comment by yujincheng08** [comment]
Many logs are added to the verbose log. However, we didn't add any new log to the module log.

**Comment by Mikanoshi** [comment]
I get bug reports with such logs all the time. Considering I can locate and read the Xposed log automatically at all to include it in crash report. All these detection protections are just a nightmare for devs.

**Comment by kotori2** [comment]
That's why adb logcat was designed as a "rolling buffer" instead of writing
to file as a static storage. If you wanna get real time logs, just enter
adb logcat when you need them on PC. The logs shows in EdXp manager is
designed for those who doesn't know about dev things.

Mikanoshi <notifications@github.com> 于 2020年12月7日周一 04:10写道：

**Comment by Mikanoshi** [comment]
I don't need a realtime log, I need all the Xposed logs since boot.
Are you suggesting to grep logcat? I don't think log buffer is unlimited.

**Comment by psychopathologist** [comment]
> @psychopathologist It is a new feature to prevent detection from white listed apps
Thank you for the info!

**Comment by psychopathologist** [comment]
> Many logs are added to the verbose log. However, we didn't add any new log to the module log.

The module log I shared is totally confused with duplicate information. Shouldn't it be like this... ?
`
...
--------- beginning of main
--------- beginning of system
12-06 09:04:23.806  6749  6749 I EdXposed-Bridge: Loading modules from /data/app/~~inszyB_mS3zUoKc0sPrJsw==/org.meowcat.edxposed.manager-oF9mmJFgrn3XA9cMzH6BiQ==/base.apk
12-06 09:04:23.897  6749  6749 I EdXposed-Bridge:   Loading class org.meowcat.edxposed.manager.xposed.Enhancement
`

**Comment by yujincheng08** [comment]
Yes. Modules are loaded each time a hooked app is launched.

**Comment by personaingrata** [comment]
question @psychopathologist 
is edxposed working for you on your s20 Aandroid 11? i'm asking because i have also the s20 phone and i haven't updated yet to A11 because of edxposed.

any info about and with versions (magisk, riru, edxposed) much appreciated.

**Comment by psychopathologist** [comment]
> question @psychopathologist
> is edxposed working for you on your s20 Aandroid 11? i'm asking because i have also the s20 phone and i haven't updated yet to A11 because of edxposed.
> 
> any info about and with versions (magisk, riru, edxposed) much appreciated.

Sure it is! Just go ahead and install latest magisk canary, latest riru core, and this yahfa build (0.5.0.6_4589-master) from here:
https://ci.appveyor.com/project/ElderDrivers/edxposed/builds/36685363/artifacts

Btw, @yujincheng08 and @kotori2 , 4589 is the latest working build, at least on samsung one ui 3.0 (android 11), the two subsequent builds (4590 / 4581) end up in bootloop. How can I help you to fix up this issue? How can I take logs from a bootlooping device, and which log you need? Tia.

**Comment by yujincheng08** [comment]
@psychopathologist #717

**Comment by psychopathologist** [comment]
> @psychopathologist #717

Thank you for the info. Gonna wait till next builds then.
You all are just rocking on the development (keep it up!). Congrats!!

**Comment by kotori2** [comment]
> I don't need a realtime log, I need all the Xposed logs since boot.

@Mikanoshi 
I think it's not a do-able thing since we changed everything to post zygote... 
If you think it's log spamming, you can use your own log functions instead of Xposed Bridge and reset them every time when the app boots.
