### ISSUE TITLE
Edxposed eat my boot partition?

### ISSUE THREAD

**Issue by lucastmendoncaf** [ElderDrivers/EdXposed#716]
什么情况/What happened?

I tried to reboot using the edxposed app, using the reboot to system and after that the is only booted to twrp, i tried flashing the miui again but nothing, so i wipe data flashed again and it shows the miui logo but dont boot to system. after a while i go back to twrp

Xposed模块列表/Xposed Module List:
dont worked too
允许截图/Screenshot allowed:

Magisk模块列表/Magisk Module List:
miui no cutout 
systemless...

允许截图/Screenshot allowed

EdXposed及Riru版本/Versions of EdXposed and Riru
all the lastest

EdXposed:

Riru: v23

DEvice is a redmi k30 5g, with xiaomi.eu 20.12.2 miui 12

**Comment by lucastmendoncaf** [comment]
i m editing it

**Comment by kotori2** [comment]
> Edxposed eat my boot partition

It will touch your boot partition.

**Comment by lucastmendoncaf** [comment]
> > Edxposed eat my boot partition
> 
> It will touch your boot partition.

i was showing that was inactivve, there is a fix? it doest boot up even i dirty flashed

**Comment by lucastmendoncaf** [comment]
> > Edxposed eat my boot partition
> 
> It will touch your boot partition.

There is something to open this issue again?
only wiping solved that
