### ISSUE TITLE
[BUG] v0.4.6.4.4563 的可能是异常CPU占用导致耗电

### ISSUE THREAD

**Issue by djun** [ElderDrivers/EdXposed#718]
**什么情况/What happened?**

该版本在系统正常运行时会有两个busybox standalone进程一直在跑 /data/adb/modules/riru_edxposed/post-fs-data.sh 这个脚本 ，
两个进程分别有接近10%的CPU占用，比较耗电。

在v0.4.6.4.4563出现此情况，刷回v0.4.6.2.4529此问题消失。
使用的是YAHFA版本。

**Xposed模块列表/Xposed Module List**

(无)

**Magisk模块列表/Magisk Module List**

(无)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:  v0.4.6.4.4563 (YAHFA)

Riru:  v21.3

**相关Logcat/Logcat**

(无)

**Comment by yujincheng08** [comment]
4.x is outdated.

**Comment by Mikanoshi** [comment]
Busybox? It's just a logcat. You can disable verbose log and it will be 1 process only.
Mine uses 0.0-1.0% out of 800% (8 cores and it's 740% idle), basically nothing.
How many logs does your ROM write if it's 10%, are you on debug ROM? :)
