### ISSUE TITLE
红米note3类原生aex4.6安卓7.1.2激活不了

### ISSUE THREAD

**Issue by swh922** [ElderDrivers/EdXposed#72]
-刷入0.2.9.8beta1重启后显示框架未安装

**Comment by zhenchao** [comment]
请使用EdXposed Installer，v0.2.9.8开始，不再使用Xposed Installer，原本Xposed Installer的功能都已集成到EdXposed Installer中了。

**Comment by swh922** [comment]
@zhenchao 就是用的edxposed，没用啊

**Comment by johoney** [comment]
安卓7，你还是用回真xp好了

**Comment by swh922** [comment]
@johoney 官方XP启动慢，还各种卡顿

**Comment by johoney** [comment]
我红米note4x觉得没影响啊，不过edxposed不支持资源hook，而且他最佳适配在8和9，算了吧。

**Comment by johoney** [comment]
havoc感觉挺流畅的，换成pe刷xp确实感觉卡

**Comment by kkwpsv** [comment]
mi5 miui android 8.0同样这样 之前0.2.9.7正常

**Comment by kkwpsv** [comment]
我的MI5清空davilk缓存，然后重启了几次又好了。。

**Comment by i1itione** [comment]
Nextbit Robin 原廠 7.1.1 安裝 EdXposed 後（尚未安裝任何 Xposed Module）則是直接 bootloop，
不過在 LineageOS 15.1 上則正常，希望有機會讓 Nougat 也能順利使用 EdXposed。

**Comment by solohsu** [comment]
Duplicate with #66.
