### ISSUE TITLE
[PROPOSAL] Merge YAHFA and SandHook into one package

### ISSUE THREAD

**Issue by kotori2** [ElderDrivers/EdXposed#725]
Current EdXposed source code is kinda messed up with dependencies, such as SandHook calling YAHFA's functions. And it's hard for developers to handle double way dependencies and the build scripts. Also [some ppl](https://github.com/topjohnwu) don't like seeing 2 EdXposed packages in the repository.
So technically we could move everything back into one submodule, and build only one shared library with only one dex file. Users can use volume keys to select between YAHFA and SandHook during installation, then we just create a flag in `/data/misc/edxp_` to specify which backend we are loading. And it should be switch-able in EdXposed Manager.

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/commit/0ffff4b40a2d514e6201d76c4fb47bd93c1a20ee
