### ISSUE TITLE
Diference YAHFA and SandHook ? 

### ISSUE THREAD

**Issue by Tatuatul** [ElderDrivers/EdXposed#726]
what is the difference between the two?
why does it appear first YAHFA  and after SandHook ?
is there a difference between them?
who is YAHFA  and who is SandHook? thank's.

**Comment by kotori2** [comment]
> what is the difference between the two?

One spells "Y-A-H-F-A" and the other spells "S-a-n-d-H-o-o-k"

> why does it appear first YAHFA and after SandHook ?

Because YAHFA appear first then SandHook

> is there a difference between them?

Yes there are. Please refer to their technical documents. 

> who is YAHFA and who is SandHook?

It's not CyberPunk 2077. They are projects not human.
