### ISSUE TITLE
[BUG] Google camera 8.x crashes upon opening

### ISSUE THREAD

**Issue by peterandreasrothe** [ElderDrivers/EdXposed#727]
**什么情况/What happened?**
After Nov 17th app update to Google camera v 8.1 the app will crash upon opening of Edxposed is enabled. 

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**
Fingerface
Edge Sense

**Magisk模块列表/Magisk Module List**
Busybox
Riru v23
Riru-edXposed v 0.5.1.0-4603
Systemless host
Substratum lite overlay helper
Volte får pixel 4/4xl

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed: 0.5.1.0-4603 

Riru: 23

**相关日志/Related Logs**

https://pastebin.com/pa9tJ4Em

为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

**Comment by yujincheng08** [comment]
blacklist it

**Comment by kotori2** [comment]
Add GCam to black list
