### ISSUE TITLE
[bug]4589以后黑名单失效

### ISSUE THREAD

**Issue by 06ji** [ElderDrivers/EdXposed#729]
手机：小米9
系统：android10 MIUI12
测试拉黑支付宝，还是能加载蚂蚁模块，人脸过不了

4489以后黑名单失效，S版Y版都测试过，4487人脸可过

还有，S版在EDXP管理器显示是未激活，Y版是正常

**Comment by yujincheng08** [comment]
拉黑之后重启过了吗？

**Comment by kotori2** [comment]
只要是模块没加载都可以认为是黑名单有效
另外据说支付宝会检测magisk修改过的文件，跟edxp无关
