### ISSUE TITLE
[BUG]  要你命三千模块无效

### ISSUE THREAD

**Issue by weigeloveu** [ElderDrivers/EdXposed#73]
**什么情况/What happened?**
要你命三千模块无效
*Xposed模块列表/Xposed Module List**
![screenshot_20190212-123053_edxposed_installer](https://user-images.githubusercontent.com/19830500/52611831-5371a280-2ec2-11e9-8533-fe8dfbb65638.png)

**Magisk模块列表/Magisk Module List**

![screenshot_20190212-123118_magisk_manager](https://user-images.githubusercontent.com/19830500/52611845-64baaf00-2ec2-11e9-947c-12ff6414847c.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.2.9.8

Riru:11

**相关Logcat/Logcat**

Sorry,模块不生效，抓不到log

**Comment by solohsu** [comment]
This module is using resources hooks, which is not supported by EdXposed.
