### ISSUE TITLE
[BUG] 0.5.1.0 not hooking / loading modules

### ISSUE THREAD

**Issue by XspeedPL** [ElderDrivers/EdXposed#731]
**What happened?**
EdXposed is not loading itself or any modules. 

**Versions**
Device: Sony G8141
Android: 9.0
EdXposed: 0.5.1.0 (commit 0114350)
Riru: 23

**Logs**
[cat.log](https://github.com/ElderDrivers/EdXposed/files/5713208/cat.log)
[edx.log](https://github.com/ElderDrivers/EdXposed/files/5713210/edx.log)

**Comment by yujincheng08** [comment]
?

**Comment by XspeedPL** [comment]
Sorry, the enter key while editing the title posted the whole incomplete issue...

**Comment by yujincheng08** [comment]
This log isn't useful. We adb logcat with debug version of edxp.

**Comment by XspeedPL** [comment]
[edx_logcat.txt](https://github.com/ElderDrivers/EdXposed/files/5688279/edx_logcat.txt)
Here you go. Though at the first glance I don't see anything useful here either.

**Comment by yujincheng08** [comment]
You are not using the debug ver.

**Comment by XspeedPL** [comment]
README tells me: `Canary: Debug version. Automatically build by CI.`
And I did get build 4608 from appveyor.
If not, where do I get it?

**Comment by kotori2** [comment]
[here](https://github.com/ElderDrivers/EdXposed/actions)

**Comment by XspeedPL** [comment]
[Log_2020-12-14_12-07-28.txt](https://github.com/ElderDrivers/EdXposed/files/5688616/Log_2020-12-14_12-07-28.txt)
Here

**Comment by XspeedPL** [comment]
[logcat.log](https://github.com/ElderDrivers/EdXposed/files/5689929/logcat.log)
[edxposed-all.log](https://github.com/ElderDrivers/EdXposed/files/5689930/edxposed-all.log)
Proper logs here, should have more info.

**Comment by XspeedPL** [comment]
Modules are listed correctly, yes, but none of them are loaded.
There are no usual initialization messages from any of the modules.

**Comment by yujincheng08** [comment]
Wired device. It's apk dir is `/data/app/org.meowcat.edxposed.manager-3sQIDV6uVO4ri7HtRTwpSw==/base.apk`.
My `GetAppInfoFromDir` is not working.

**Comment by rhjdvsgsgks** [comment]
i have same problem on similar device (a sony mobile with Android 9.0 stock rom) after upgrading to 4601 (until 4613), it take effect as "not active" yellow warning and anywebview module not working, besides that any other module both works

**Comment by kotori2** [comment]
@rhjdvsgsgks just guessing, your issue is most probably #728 instead of this.

**Comment by kotori2** [comment]
@XspeedPL Your logs looks pretty odd.
1. The `logcat.log` was captured from `12-14 16:12:56.489` to `12-14 16:14:08.336`, and it simply doesn't contains useful logs because it was captured with release build, while `edxposed-all.log` was captured from `12-14 16:21:58.773` to `12-14 16:25:30.464` and it is the correct debug log, but it doesn't contain system crash logs.
2. I found 2 possible crash points, which are:
```
12-14 16:13:36.534  3233  3240 W System  : A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
12-14 16:13:36.534  3233  3240 W System  : java.lang.Throwable: Explicit termination method 'close' not called
12-14 16:13:36.534  3233  3240 W System  : 	at dalvik.system.CloseGuard.open(CloseGuard.java:221)
12-14 16:13:36.534  3233  3240 W System  : 	at java.io.FileInputStream.<init>(FileInputStream.java:168)
12-14 16:13:36.534  3233  3240 W System  : 	at com.android.internal.os.AtomicFile.openRead(AtomicFile.java:147)
12-14 16:13:36.534  3233  3240 W System  : 	at com.android.server.storage.CacheQuotaStrategy.setupQuotasFromFile(CacheQuotaStrategy.java:301)
12-14 16:13:36.534  3233  3240 W System  : 	at com.android.server.usage.StorageStatsService$H.handleMessage(StorageStatsService.java:508)
12-14 16:13:36.534  3233  3240 W System  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-14 16:13:36.534  3233  3240 W System  : 	at android.os.Looper.loop(Looper.java:280)
12-14 16:13:36.534  3233  3240 W System  : 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-14 16:13:36.534  3233  3240 W System  : 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
```
and the other is
```
12-14 16:13:36.700  3233  3233 I SystemServer: StartObservingNativeCrashes
12-14 16:13:36.700  3233  3532 I SystemServer: WebViewFactoryPreparation
12-14 16:13:36.701   865  1703 D audio_hw_primary: adev_set_parameters: enter: BT_SCO=off
12-14 16:13:36.701   865  1703 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
12-14 16:13:36.702  3233  3532 W SystemImpl: Tried to enable com.google.android.webview for user 0: java.lang.IllegalArgumentException: Unknown package: com.google.android.webview
12-14 16:13:36.702  3233  3569 D BluetoothManagerService: Trying to bind to profile: 1, while Bluetooth was disabled
12-14 16:13:36.703  3233  3532 E WebViewUpdater: error preparing webview provider from system server
12-14 16:13:36.703  3233  3532 E WebViewUpdater: com.android.server.webkit.WebViewUpdater$WebViewPackageMissingException: Could not find a loadable WebView package
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.webkit.WebViewUpdater.findPreferredWebViewPackage(WebViewUpdater.java:320)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.webkit.WebViewUpdater.prepareWebViewInSystemServer(WebViewUpdater.java:142)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.webkit.WebViewUpdateServiceImpl.prepareWebViewInSystemServer(WebViewUpdateServiceImpl.java:95)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.webkit.WebViewUpdateService.prepareWebViewInSystemServer(WebViewUpdateService.java:127)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.SystemServer.lambda$startOtherServices$3(SystemServer.java:1861)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.server.-$$Lambda$SystemServer$Y1gEdKr_Hb7K7cbTDAo_WOJ-SYI.run(Unknown Source:2)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-14 16:13:36.703  3233  3532 E WebViewUpdater: 	at com.android.internal.util.ConcurrentUtils$1$1.run(ConcurrentUtils.java:62)
```
For the first one, it was already been fixed in 389138f455ce1a2100a97f94427eb15c09a4bfc5, and the second one seems like system issue or module issue. Please double check them. 
Also I saw some core patch related logs, maybe from LP, which proof that the framework is working.

**Comment by XspeedPL** [comment]
Sorry about that, I might have mixed up the log files.
Also, this time I triple-checked that the package I installed was the debug variant (commit 0114350).

Here are the log files: [cat.log](https://github.com/ElderDrivers/EdXposed/files/5713208/cat.log), [edx.log](https://github.com/ElderDrivers/EdXposed/files/5713210/edx.log)

**Comment by rhjdvsgsgks** [comment]
> @rhjdvsgsgks just guessing, your issue is most probably #728 instead of this.

your guess is right, same as #728 , after update to 4616 , the yellow warning been fixed

**Comment by kotori2** [comment]
Global mode, EdXp only loaded for few apps, any idea? @yujincheng08 
```
12-18 02:59:30.178  2809  2809 W EdXposed: installer not set, using default one org.meowcat.edxposed.manager
12-18 02:59:30.180  2809  2809 D EdXposed: module scope is not set for xeed.xposed.cbppmod
12-18 02:59:30.180  2809  2809 D EdXposed: module scope is not set for org.meowcat.edxposed.manager
12-18 02:59:30.180  2809  2809 I EdXposed: base config path: /data/misc/edxp_5wHrKEn3svJ7EsBO/0
12-18 02:59:30.180  2809  2809 I EdXposed:   using installer package name: org.meowcat.edxposed.manager
12-18 02:59:30.180  2809  2809 I EdXposed:   using whitelist: false
12-18 02:59:30.180  2809  2809 I EdXposed:   deopt boot image: false
12-18 02:59:30.180  2809  2809 I EdXposed:   no module log: false
12-18 02:59:30.180  2809  2809 I EdXposed:   resources hook: false
12-18 02:59:30.180  2809  2809 I EdXposed:   white list: 
12-18 02:59:30.180  2809  2809 I EdXposed:  
12-18 02:59:30.180  2809  2809 I EdXposed:   black list: 
12-18 02:59:30.180  2809  2809 I EdXposed:  
12-18 02:59:30.180  2809  2809 I EdXposed:   module list: 
12-18 02:59:30.180  2809  2809 I EdXposed:  org.meowcat.edxposed.manager
12-18 02:59:30.180  2809  2809 I EdXposed: xeed.xposed.cbppmod
...
12-18 02:59:55.072  6313  6313 D EdXposed: processName=com.qualcomm.qti.qms.service.connectionsecurity, packageName=com.qualcomm.qti.qms.service.connectionsecurity, appDataDir=/data/user/0/com.qualcomm.qti.qms.service.connectionsecurity
12-18 02:59:55.073  6313  6313 D EdXposed: LoadedApk#<init> starts: pkg=com.qualcomm.qti.qms.service.connectionsecurity, prc=com.qualcomm.qti.qms.service.connectionsecurity
12-18 02:59:55.073  6313  6313 D EdXposed: LoadedApk#<init> ends: /system/vendor/app/ConnectionSecurityService/ConnectionSecurityService.apk: pkg=com.qualcomm.qti.qms.service.connectionsecurity, prc=com.qualcomm.qti.qms.service.connectionsecurity
...
12-18 03:00:01.756  7534  7534 D EdXposedManager: EdXposed is not active
12-18 03:00:01.757  7534  7534 I chatty  : uid=10341(org.meowcat.edxposed.manager) identical 4 lines
12-18 03:00:01.757  7534  7534 D EdXposedManager: EdXposed is not active
```

**Comment by yujincheng08** [comment]
No Idea. There should be logs for all launching apps no matter injecting is successful or not.

**Comment by kotori2** [comment]
@yujincheng08 True. 
My guess is Riru not working properly. They seems fixed bugs for Android 10- in Riru v23.1, @XspeedPL could you please try it out?

**Comment by XspeedPL** [comment]
FYI, the recent logs are from me booting up the device, entering SIM PIN, then launching and closing EdXposed Manager.

I just tried out Riru 23.1, but it didn't change anything.
It is supposed to address Riru Hide issues, which I wasn't using anyway.

**Comment by XspeedPL** [comment]
After checking the logs after the latest update, there is a ton of `GetOatQuickMethodHeader: isHooked but not backup, fallback to system` messages.

Also another thing I've noticed after debugging my modules, zygote init methods are running, but handle package methods are not.

**Comment by XspeedPL** [comment]
Turns out my build props file was damaged, and long story short I was missing the 64 bit libraries, which resulted in only 32 bit processes being hooked.

Sorry for all the trouble
