### ISSUE TITLE
[BUG] ROG Phone 3 EdXposed framework is installed, but not active!

### ISSUE THREAD

**Issue by kartikbilla007** [ElderDrivers/EdXposed#733]
I have installed everything latest on my currently latest phone but the framework doesn't seem to work, what's the problem? Attaching the screenshot with log: 
![Screenshot_20201215-232053382](https://user-images.githubusercontent.com/16859254/102313068-21ea1800-3f2d-11eb-9d31-421620b9f07f.jpg)
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: asus
Brand: asus
Device: ASUS_I003_1
Product: ZS661KS
Model: ASUS_I003DD
Fingerprint: asus/WW_I003D/ASUS_I003_1:10/QKQ1.200419.002/17.0823.2007.32-0:user/release-keys
ROM description: WW_I003D-user 10 QKQ1.200419.002 17.0823.2007.32-0 release-keys
Architecture: arm64-v8a
Android build: QKQ1.200419.002
Android version: 10
Android sdk: 29
EdXposed version: v0.5.1.0_4613-master (YAHFA)
EdXposed api: 93
Riru version: v23.0 (50)
Riru api: 10
Magisk: 20.4 (20400) ***(On ROG 3 phone this is latest magisk available)***
--------- beginning of main
--------- beginning of system
++++++++++++++
Tried (YAHFA) 4.5.7 stable release by modifying the RIRU_PATH from /data/misc/riru to /data/adb/riru and the exposed apk manager won't even detect that the framework has been installed.

**Comment by kotori2** [comment]
0.4.5.7 stable will not working with Riru v22+
Also please capture logs with debug build.

**Comment by kartikbilla007** [comment]
How to capture logs with debug build? Where's the debug build?

**Comment by kotori2** [comment]
[here](https://github.com/ElderDrivers/EdXposed/actions)
> How to capture logs with debug build? 

You can find log capturing tutorials all around the web.

**Comment by kartikbilla007** [comment]
I tried, the search is too wide. Can you please share one such tutorial?

**Comment by kotori2** [comment]
https://www.google.com/search?q=xda+adb+logcat&oq=xda+adb+logcat

**Comment by kartikbilla007** [comment]
> https://www.google.com/search?q=xda+adb+logcat

Thank you very much for that!

**Comment by kartikbilla007** [comment]
![Screenshot_20201216-000210887](https://user-images.githubusercontent.com/16859254/102315946-409edd80-3f32-11eb-8b6d-fc544d893c08.jpg)
![Screenshot_20201216-000108206](https://user-images.githubusercontent.com/16859254/102315947-41377400-3f32-11eb-956f-3783ea22301b.jpg)
Is it this one?

**Comment by kotori2** [comment]
@kartikbilla007 save everything into a file and post them here please.

**Comment by kartikbilla007** [comment]
[0_logcat_12-20-2020_20-02-31.txt](https://github.com/ElderDrivers/EdXposed/files/5726465/0_logcat_12-20-2020_20-02-31.txt)
[1608583872877_0_logcat_12-20-2020_20-03-41.txt](https://github.com/ElderDrivers/EdXposed/files/5726467/1608583872877_0_logcat_12-20-2020_20-03-41.txt)

**Comment by kartikbilla007** [comment]
![Screenshot_20201222-151428800](https://user-images.githubusercontent.com/16859254/102937938-7ed35a00-4468-11eb-918e-fad7a239a483.jpg)
