### ISSUE TITLE
[BUG] android 11 boot loop

### ISSUE THREAD

**Issue by green1052** [ElderDrivers/EdXposed#738]
**什么情况/What happened?**
When you reboot after installing edxposed,
Takes an infinite boot.

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed: 0.5.1.0_4616

Riru: 23.0

**相关日志/Related Logs**

为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

**Comment by green1052** [comment]
[a.txt](https://github.com/ElderDrivers/EdXposed/files/5713023/a.txt)

**Comment by NYCJames** [comment]
Did you use sandhook?

**Comment by green1052** [comment]
I've tried both.

**Comment by RaphaelGreen** [comment]
Same version, OnePlus 8t. Bootloop

**Comment by yujincheng08** [comment]
useless log.

**Comment by green1052** [comment]
> 
> 
> useless log.

Do I need to install the edxposed debug?

https://github.com/ElderDrivers/EdXposed/actions/runs/429392243

**Comment by kotori2** [comment]
> useless log.

^^
No module even loaded by Magisk.
