### ISSUE TITLE
[BUG] [0.5.1.0_4616] android11 EdXposed 显示已安装但未激活,YAHFA和SandHook都不行

### ISSUE THREAD

**Issue by guangdeshishe** [ElderDrivers/EdXposed#739]
**什么情况/What happened?**

Android11显示已安装但未激活
![Screenshot_20201218-111136_EdXposed Manager](https://user-images.githubusercontent.com/7502616/102572199-668cd380-4126-11eb-8bb2-eb9adba8e3f7.jpg)

**Xposed模块列表/Xposed Module List**

什么都没装
![Screenshot_20201218-112504_EdXposed Manager](https://user-images.githubusercontent.com/7502616/102572237-7c01fd80-4126-11eb-8b0e-d45787127302.jpg)

**Magisk模块列表/Magisk Module List**
只安装了Riru_core和Edxposed
![Screenshot_20201218-112452](https://user-images.githubusercontent.com/7502616/102572287-9a67f900-4126-11eb-9c09-d540638e23a3.jpg)

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed:0.5.1.0_4616

Riru:23

**相关日志/Related Logs**

--------- beginning of head EdXposed Log Powered by Log Catcher QQ support group: 855219808 Telegram support group: @Code_Of_MeowCat Telegram channel: @EdXposed --------- beginning of information Manufacturer: samsung Brand: samsung Device: bloomq Product: bloomq Model: SM-F7000 Fingerprint: samsung/bloomqzc/bloomq:11/RP1A.200720.012/F7000ZCE3CTL5:eng/test-keys ROM description: bloomqzc-eng 11 RP1A.200720.012 F7000ZCE3CTL5 test-keys Architecture: arm64-v8a Android build: RP1A.200720.012 Android version: 11 Android sdk: 30 EdXposed version: v0.5.1.0_4616-master (YAHFA) EdXposed api: 93 Riru version: v23.0 (50) Riru api: 10 Magisk: 21.1 (21100) --------- beginning of main --------- beginning of kernel --------- beginning of system 12-18 11:08:44.027 924 924 I EdXposed: onModuleLoaded: welcome to EdXposed! 12-18 11:08:44.034 924 924 I EdXposed: Got base config path: /data/misc/edxp_2XPg5ONXDqcLbtIq 12-18 11:08:44.039 923 923 I EdXposed: onModuleLoaded: welcome to EdXposed! 12-18 11:08:44.051 923 923 I EdXposed: Got base config path: /data/misc/edxp_2XPg5ONXDqcLbtIq 12-18 11:08:46.635 923 923 W EdXposed: installer not set, using default one org.meowcat.edxposed.manager 12-18 11:08:46.637 923 923 E EdXposed: filesystem error: in directory_iterator::directory_iterator(...): No such file or directory [/data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/whitelist/] 12-18 11:08:46.637 923 923 E EdXposed: filesystem error: in directory_iterator::directory_iterator(...): No such file or directory [/data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/blacklist/] 12-18 11:08:46.637 923 923 E EdXposed: Cannot access path /data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/modules.list 12-18 11:08:46.637 923 923 I EdXposed: base config path: /data/misc/edxp_2XPg5ONXDqcLbtIq/0 12-18 11:08:46.637 923 923 I EdXposed: using installer package name: org.meowcat.edxposed.manager 12-18 11:08:46.637 923 923 I EdXposed: using whitelist: false 12-18 11:08:46.638 923 923 I EdXposed: deopt boot image: false 12-18 11:08:46.638 923 923 I EdXposed: no module log: false 12-18 11:08:46.638 923 923 I EdXposed: resources hook: false 12-18 11:08:46.639 923 923 I EdXposed: white list: 12-18 11:08:46.639 923 923 I EdXposed: 12-18 11:08:46.639 923 923 I EdXposed: black list: 12-18 11:08:46.639 923 923 I EdXposed: 12-18 11:08:46.639 923 923 I EdXposed: module list: 12-18 11:08:46.639 923 923 I EdXposed: 12-18 11:08:47.075 1186 1186 I EdXposed: Loaded /data/misc/edxp_2XPg5ONXDqcLbtIq/framework/edservice.dex with size 53364 12-18 11:08:47.086 1186 1186 W EdXposed: Installed EdXposed Service 12-18 11:09:08.325 924 924 W EdXposed: installer not set, using default one org.meowcat.edxposed.manager 12-18 11:09:08.326 924 924 E EdXposed: filesystem error: in directory_iterator::directory_iterator(...): No such file or directory [/data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/whitelist/] 12-18 11:09:08.326 924 924 E EdXposed: filesystem error: in directory_iterator::directory_iterator(...): No such file or directory [/data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/blacklist/] 12-18 11:09:08.326 924 924 E EdXposed: Cannot access path /data/misc/edxp_2XPg5ONXDqcLbtIq/0/conf/modules.list 12-18 11:09:08.326 924 924 I EdXposed: base config path: /data/misc/edxp_2XPg5ONXDqcLbtIq/0 12-18 11:09:08.327 924 924 I EdXposed: using installer package name: org.meowcat.edxposed.manager 12-18 11:09:08.327 924 924 I EdXposed: using whitelist: false 12-18 11:09:08.327 924 924 I EdXposed: deopt boot image: false 12-18 11:09:08.327 924 924 I EdXposed: no module log: false 12-18 11:09:08.327 924 924 I EdXposed: resources hook: false 12-18 11:09:08.327 924 924 I EdXposed: white list: 12-18 11:09:08.327 924 924 I EdXposed: 12-18 11:09:08.327 924 924 I EdXposed: black list: 12-18 11:09:08.327 924 924 I EdXposed: 12-18 11:09:08.327 924 924 I EdXposed: module list: 12-18 11:09:08.327 924 924 I EdXposed: 12-18 11:09:09.954 1186 1186 I EdXposed: registered package receiver 12-18 11:09:38.869 6310 6310 I EdXposed: Loaded /data/misc/edxp_2XPg5ONXDqcLbtIq/framework/edxp.dex with size 296320 12-18 11:09:38.883 6310 6310 I EdXposed: Loaded /data/misc/edxp_2XPg5ONXDqcLbtIq/framework/eddalvikdx.dex with size 766268 12-18 11:09:38.885 6310 6310 I EdXposed: Loaded /data/misc/edxp_2XPg5ONXDqcLbtIq/framework/eddexmaker.dex with size 64416 12-18 11:09:39.008 6310 6310 I EdXposed: Start to install inline hooks 12-18 11:09:39.008 6310 6310 I EdXposed: Using api level 30 12-18 11:09:39.008 6310 6310 I EdXposed: Start to install Riru hook 12-18 11:09:39.081 6310 6310 I EdXposed: Riru hooks installed 12-18 11:09:39.118 6310 6310 I EdXposed: ART hooks installed 12-18 11:09:39.204 6310 6310 I EdXposed: Loading modules for org.meowcat.edxposed.manager 12-18 11:09:39.710 6310 6310 D EdXposedManager: EdXposed is not active 12-18 11:09:39.712 6310 6310 D EdXposedManager: ApplicationList: Force add modules to list 12-18 11:09:40.054 6310 6310 D EdXposedManager: EdXposed is not active 12-18 11:09:41.663 923 923 E EdXposed: can't parse /data/system
为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

**Comment by kotori2** [comment]
> 为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
