### ISSUE TITLE
[BUG] Cubot Magic bootloop

### ISSUE THREAD

**Issue by arisboch** [ElderDrivers/EdXposed#74]
**什么情况/What happened?**

I tried to install it on my Cubot Magic, (Riru caused no issue, it was only after I installed the EdXposed module that the device was stuck in a bootloop (had to use uninmod to uninstall the module)), but it sent my device into a bootloop. Oh, and the phone became unusable because of a force-close message for the Google Play services popping up all the time even after I uninstalled the modules.

**Xposed模块列表/Xposed Module List**

None, as I didn't get Xposed to run because of the bootloop.

**Magisk模块列表/Magisk Module List**

- GBoard Themes
- Busybox for Android

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.8_beta1

Riru: v10

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

I couldn't get that one because the phone became unusable due to this annoying error message.

**Comment by solohsu** [comment]
These modules don't modify system permanently. You may want to use [Magisk Manager for Recovery Mode (mm)](https://forum.xda-developers.com/apps/magisk/module-tool-magisk-manager-recovery-mode-t3693165) to unintall magisk modules completely.
