### ISSUE TITLE
[BUG] boot loop

### ISSUE THREAD

**Issue by green1052** [ElderDrivers/EdXposed#741]
**什么情况/What happened?**
Rebooting after installing EdXposed will result in an infinite boot.

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**
Busybox for android NDK 1.31.1
Twemoji 12.1.5

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed: 0.5.1.0_4616

Riru: 23.0

**相关日志/Related Logs**

为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

I tried to find an error with Log Catcher,
Nothing's coming out.

**Comment by yujincheng08** [comment]
no log, no fix.

**Comment by kotori2** [comment]
We can't locate the bug without log.
