### ISSUE TITLE
[BUG] installed but not active

### ISSUE THREAD

**Issue by green1052** [ElderDrivers/EdXposed#745]
**什么情况/What happened?**

如无法开机/模块无效等

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**
twemoji
busybox

**EdXposed及Riru版本/Version of EdXposed and Riru**

EdXposed: 0.5.1.2_4635

Riru: 23.1

**相关日志/Related Logs**

为了帮助我们定位问题，请使用debug版EdXposed模块抓日志。
Please capture log with debug version, otherwise it won't help us locating the issue.

**Comment by green1052** [comment]
[EdXposed_Verbose_20201220_134905.txt](https://github.com/ElderDrivers/EdXposed/files/5720562/EdXposed_Verbose_20201220_134905.txt)
[EdXposed_Modules_20201220_134908.txt](https://github.com/ElderDrivers/EdXposed/files/5720563/EdXposed_Modules_20201220_134908.txt)

**Comment by green1052** [comment]
[EdXposed_Modules_20201220_141019.txt](https://github.com/ElderDrivers/EdXposed/files/5720571/EdXposed_Modules_20201220_141019.txt)
[EdXposed_Verbose_20201220_141022.txt](https://github.com/ElderDrivers/EdXposed/files/5720572/EdXposed_Verbose_20201220_141022.txt)

debug

**Comment by kotori2** [comment]
Please grab logs with adb and debug build. Something is crashing but it doesn't showed up in EdXposed log.
