### ISSUE TITLE
0.5.1.3 on Oreo: very slow, modules are broken

### ISSUE THREAD

**Issue by watchmakerful** [ElderDrivers/EdXposed#748]
Android 8.1 Oreo, Nexus 5X (the last official build).
EdXposed 0.5.1.3 Sandhook, Riru 23.1, Magisk 21.1.
Some modules are broken:
XToast: does not load at all.
GravityBox [O]: features related to the navigation bar do not load or load incorrectly.
Also the system is extremely slow, a full startup takes 15..20 minutes instead of 2 minutes on 0.4.6.4 (+Riru 19). Every application launch takes up to 10 seconds (less than one second on 0.4.6.4).
EdXposed 0.5.1.3 YAHFA: boot animation then black screen with backlight.
Logs from 0.5.1.3 Sandhook: from power on until loading all desktop widgets.
[2020-12-22_023051_logcat.txt](https://github.com/ElderDrivers/EdXposed/files/5727194/2020-12-22_023051_logcat.txt)

**Comment by MlgmXyysd** [comment]
>Notes:
>If you feel the system is running slowly, turn on Xposed Hide(White).

**Comment by watchmakerful** [comment]
I'll try it, but what about broken modules? GravityBox: no navbar height adjustment, incorrect functions of navbar buttons, no longpress actions, no charging LED. XToast: does not load at all.
>>turn on Xposed Hide(White)
Which particular options? App List Mode + White List? Instant module list?

**Comment by MlgmXyysd** [comment]
Upgrade Manager Preview https://t.me/MlgmXyysd_bibilailai/488 first

**Comment by watchmakerful** [comment]
OK, I'll try it tomorrow.

**Comment by MlgmXyysd** [comment]
The issue will be closed: template errors 
https://github.com/ElderDrivers/EdXposed/issues/new/choose
