### ISSUE TITLE
0.5.1.3 YAHFA on Oreo: black screen

### ISSUE THREAD

**Issue by watchmakerful** [ElderDrivers/EdXposed#749]
Nexus 5X, Android 8.1, EdXposed 0.5.1.3 YAHFA, Magisk 21.1, Riru 23.
No boot at all: Android boot animation, then black screen with backlight. And no logs: ADB does not connect (or connects but nothing in the shell). 0.4.6.4 and older versions work fine (both YAHFA and Sandhook).

**Comment by MlgmXyysd** [comment]
Closing: template errors https://github.com/ElderDrivers/EdXposed/issues/new/choose
