### ISSUE TITLE
[BUG] Doesn't seem to work on xiaomi.eu MIUI 10.3 (Xiaomi Mi Mix 2S)

### ISSUE THREAD

**Issue by zacchi4k** [ElderDrivers/EdXposed#75]
**What happened?**
ROM is xiaomi.eu MIUI 10.3 24/01/2019; Android 9
After installing both Magisk modules, the Xposed Installer shows the green check mark, but the modules don't seem to work. I've tried installing XInsta, which is included in the list of supported modules, but no matter what, it doesn't want to function. I've tried cleaning the ART cache from recovery, adding Instagram to the compat mode list, forcing resetting compiled code, enabling global mode, but nothing seems to help. Am I doing something wrong or is this a compatibility issue?
![screenshot_2019_02_12_22_12_58_982_com](https://user-images.githubusercontent.com/10375754/52668356-a1fb5d00-2f13-11e9-9db1-ef7853a0d646.png)
![screenshot_2019-02-12-22-13-20-654_com topjohnwu magisk](https://user-images.githubusercontent.com/10375754/52668361-a32c8a00-2f13-11e9-9708-7e4485c7f67e.png)

**Xposed模块列表/Xposed Module List**
XInsta

**Magisk Module List**
![screenshot_2019-02-12-22-07-50-881_com topjohnwu magisk](https://user-images.githubusercontent.com/10375754/52668335-9871f500-2f13-11e9-9a69-60482c8ddb6c.png)
![screenshot_2019-02-12-22-07-52-995_com topjohnwu magisk](https://user-images.githubusercontent.com/10375754/52668338-9a3bb880-2f13-11e9-98dd-29fc75413a0a.png)

**/Versions of EdXposed and Riru**
EdXposed: v0.2.9.8_beta1
Riru: v11

**Logcat**
It can help us to locate issue, must use our logcat module

**Comment by aefj11** [comment]
我的mix 2s也一样，显示不兼容，安装了微X以后，微信也打不开了

**Comment by iamdexter** [comment]
It can be Instagram version problem? Se the xda thread of Xinsta to know what are the lastest hooks...

**Comment by zacchi4k** [comment]
@iamdexter I tried looking in the XDA thread but I can't find any info about what the latest books are.

**Comment by iamdexter** [comment]
> @iamdexter I tried looking in the XDA thread but I can't find any info about what the latest hooks are.

https://github.com/iHelp101/XInsta/blob/master/Hooks.txt
Look for the bigger number in this case 1399065 that is the instagram version that work..
But try downloading from the app the pastebin hooks... and open the file in your phone... it is more updated than github...
verions after that may or work but usually do not work...

**Comment by zacchi4k** [comment]
@iamdexter I can't find those numbers inside the Instagram app or the app info screen. All I can find is the version number but that's different from those numbers

**Comment by solohsu** [comment]
https://www.apkmirror.com/uploads/?q=instagram-instagram
You can check versionName and its corresponding versionCode here.

**Comment by solohsu** [comment]
Try https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2
If you got a XInsta problem, raise another issue for it.

**Comment by zacchi4k** [comment]
It works perfectly now, thank you for all your amazing work

**Comment by taboo180** [comment]
> It works perfectly now, thank you for all your amazing work

What did you do to get it working in the end bud? I seem to have your same initial problem.
