### ISSUE TITLE
[BUG] Manager shows yellow when riru hide is enabled.

### ISSUE THREAD

**Issue by eebssk1** [ElderDrivers/EdXposed#750]
米米米米米米米米米米 MiUI 12.0.5 Android10 米米米米米米米米米米
EdXposed 4646 v0.5.1.3 release
YAHfA var

Manager shows yellow when riru hide is enabled.
LP's core patch is working,as well as greenify's xposed mode.
Most other modules are working I assume.
Manager's enhanced mode is not working somehow.

Only tested with YAHfA yet.

Full log looks normal as usual.

Debug log: TBD.

**Comment by eebssk1** [comment]
The problem will be randomly gone if you clean the dalvik-cache in TWRP.Weired.
@kotori2 @MlgmXyysd

**Comment by kotori2** [comment]
30fa70d43ebe70fa4e4238f235ff11dfaeafab4e not working. Needs further investigation.

**Comment by Crescendo-BLYAT** [comment]
Any idea where I can get Magisk Manager - ALPHA version matching the framework build number?
Or any latest Manager version?

**Comment by dcoolArne** [comment]
The easiest way is to download android studio and build it yourself from the latest github download.

**Comment by kotori2** [comment]
Should be fixed in 6bb00dfcc441cbc39428af79e45f4992597523c4
