### ISSUE TITLE
[PROPOSAL] Automatic handling of old preferences files

### ISSUE THREAD

**Issue by XspeedPL** [ElderDrivers/EdXposed#751]
The new preferences location redirection hook works great, but there is no easy way of migrating preferences from old location to the new one.
The built-in hook should try to move the preferences files to the new location.

Things to consider:
- Whether to move all files preemptively or check each file when it's requested from app or module side
- Old files might be stored in either `/data/data/` or `/data/user_de/0/` (should those be redirected as well?)
- The files may have dirty other tricks applied on them, chmod/chown/selinux reset might be necessary

**Comment by yujincheng08** [comment]
Actually, it's impossible. Edxp now has no permission to read private files unless new sepolicy is introduced. We want to keep sepolicy as less as possible, so...

**Comment by XspeedPL** [comment]
Can't app side at least access both their data directory and preferences in `/data/misc/edxp_*/*/prefs/`?

**Comment by kotori2** [comment]
@XspeedPL Maybe just add a method in XposedBridge to locate where the random folder is?

**Comment by yujincheng08** [comment]
Apps can access their data directory easily, And preferences in `/data/misc/...` can also access by using `getSharedPreferences`.

**Comment by XspeedPL** [comment]
Aside from porting data from older versions, it would be nice if users could open the app and set preferences even before the device is first rebooted.

@yujincheng08 so, couldn't the app-side hook be modified to migrate the files then?

**Comment by yujincheng08** [comment]
If you have any idea, you can modify these codes and fire a new pr:

https://github.com/ElderDrivers/EdXposed/blob/e7a47201698ed889d6023defb2d9b280383ca71e/edxp-common/src/main/java/com/elderdrivers/riru/edxp/_hooker/impl/HandleBindApp.java#L81-L100

**Comment by Mikanoshi** [comment]
> it would be nice if users could open the app and set preferences even before the device is first rebooted

First rebooted after module install? Is there a check that redirect only applies to active modules? I think it's already working for any module as long as framework is active.

> developers could just load prefs from hardcoded file paths and feed it into the edxp one

I already have a backup/restore option that uses getSharedPreferences(), so user must manually backup before update and then restore to put them in a redirected file. Doing it automatically would be better though.

**Comment by XspeedPL** [comment]
> First rebooted after module install? Is there a check that redirect only applies to active modules? I think it's already working for any module as long as framework is active.

Yes, I meant reboot after install. If you have "Instant module list" enabled this might not be a problem, since it should hook configuration app from the first run.
Otherwise you have a situation where the app generates preferences inside `/data/data/` first and after a reboot it tries to read from `/data/misc/` which may force users to configure everything from scratch again.

> user must manually backup before update and then restore

That's always also an option, but it's annoying as hell. Also if an user misses your warning, downgrading the app without losing data is tricky.

**Comment by Mikanoshi** [comment]
> Otherwise you have a situation where the app generates preferences inside /data/data/ first and after a reboot it tries to read from /data/misc/ which may force users to configure everything from scratch again.

But EdXposed is already active and already has a hook that checks if app is a module and redirects its prefs, how would app write to /data/data or /data/user_de? I don't see any condition, all appropriate modules will be hooked and redirected right away.

**Comment by XspeedPL** [comment]
My bad, that was a mistake on my part.
So the only scenario that needs handling is an upgrade.

I have a small prototype in the works, once all is okay I will make the pull request.

On a side note: Android is able to read symlinked preferences files, at least on my device.
Would it make sense to ditch redirection hooks and just symlink shared_prefs or individual files over?

**Comment by XspeedPL** [comment]
My bad, that was a mistake on my part.
So the only scenario that needs handling is an upgrade.

I have a small prototype in the works, once all is okay I will make the pull request.

On a side note: Would it make sense to ditch the whole redirection business in favor of symlinks?
Symlinked preferences files seems to work well on my device so far.
