### ISSUE TITLE
[BUG] New XSharedPreferences flow fails during initZygote

### ISSUE THREAD

**Issue by XspeedPL** [ElderDrivers/EdXposed#753]
According to the new XSharedPreferences docs, the mechanism is supposed to support loading during initZygote.
However at [this (XposedInit.java)](https://github.com/ElderDrivers/EdXposed/blob/e7a47201698ed889d6023defb2d9b280383ca71e/xposed-bridge/src/main/java/de/robv/android/xposed/XposedInit.java#L472) point the `XposedInit.loadedModules` list is empty, so [this (XSharedPreferences.java)](https://github.com/ElderDrivers/EdXposed/blob/e7a47201698ed889d6023defb2d9b280383ca71e/xposed-bridge/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L69) fails and paths to `/data/data/` are returned.

**Comment by coderstory** [comment]
@yujincheng08
