### ISSUE TITLE
[BUG] 从0.4.6.4更新到0.5.1.3开机后，“系统界面”无法启动

### ISSUE THREAD

**Issue by Gokou-Ruri** [ElderDrivers/EdXposed#754]
**什么情况/What happened?**

首先我尝试了YAHFA版本，发现会BOOTLOOP。于是进入REC，在/data/adb/里删除了edxp的模块目录，并清除了cache和dalvik-cache，开机后在magisk中安装了sandhook版本，能够成功开机，但桌面背景是全黑的，也没有状态栏，即“系统界面”未启动，且CPU占用基本满载，启动其它APP非常卡顿。
于是我在magisk中卸载了sandhook，重启后再次安装YAHFA版本，这次可以开机了，但和sandhook版本表现完全相同，“系统界面”依旧无法启动，CPU负载依旧很高。
无论安装YAHFA或是sandhook版本，在管理器中都有显示edxposed已安装。

**Xposed模块列表/Xposed Module List**

已发现造成问题的xposed模块是Perfect Color Bar、应用管理、上帝模式等（大概是这些模块中的部分功能可能有涉及到“系统界面”，启用其中任意一个模块都会导致开机后，“系统界面”无法启动。），无影响的模块则大多为只hook第三方APP的模块，例如指纹支付、假装分享等模块。

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 9.0（AOSiP）

Magisk: v21

Riru: v23

EdXposed: 0.5.1.3

**相关日志/Related Logs**

**Comment by MlgmXyysd** [comment]
>相关日志/Related Logs

**Comment by kotori2** [comment]
> 已发现造成问题的xposed模块是Perfect Color Bar
