### ISSUE TITLE
[BUG]  魅族17 Flyme8.2 Android 11 卡开机动画

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#758]
**什么情况/What happened?**

 **卡开机动画**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 21.0

Riru: 23.1

EdXposed: 0.5.1.3_4648-master

**相关日志/Related Logs**

[all_2020-12-23_20-25-50.log](https://github.com/ElderDrivers/EdXposed/files/5735111/all_2020-12-23_20-25-50.log)
[kmsg_2020-12-23_20-25-50.log](https://github.com/ElderDrivers/EdXposed/files/5735115/kmsg_2020-12-23_20-25-50.log)

**Comment by coderstory** [comment]
debug版本日志

[all_2020-12-23_20-35-19.log](https://github.com/ElderDrivers/EdXposed/files/5735161/all_2020-12-23_20-35-19.log)
[kmsg_2020-12-23_20-35-19.log](https://github.com/ElderDrivers/EdXposed/files/5735162/kmsg_2020-12-23_20-35-19.log)

**Comment by yujincheng08** [comment]
```
12-23 20:35:39.958  3370  3370 F DEBUG   : backtrace:
12-23 20:35:39.958  3370  3370 F DEBUG   :       #00 pc 00000000002a562c  /apex/com.android.art/lib64/libart.so!libart.so (offset 0x1d8000) (art::gc::Heap::WaitForGcToComplete(art::gc::GcCause, art::Thread*)+412) (BuildId: e1bf5fabd83d3e5b9b91f193aac14578)
12-23 20:35:39.958  3370  3370 F DEBUG   :       #01 pc 00000000000e9760  /system/lib64/libriru_b23a.so (art::gc::Heap::WaitForGcToComplete(void*, art::gc::GcCause, void*)+60) (BuildId: dfcb4b05ff9fd2be34518cabe13551a71b36fbb1)
12-23 20:35:39.958  3370  3370 F DEBUG   :       #02 pc 00000000000e9704  /system/lib64/libriru_b23a.so (art::gc::Heap::WaitForGcToComplete(art::gc::GcCause, void*) const+52) (BuildId: dfcb4b05ff9fd2be34518cabe13551a71b36fbb1)
12-23 20:35:39.958  3370  3370 F DEBUG   :       #03 pc 00000000000e96a8  /system/lib64/libriru_b23a.so (edxp::Heap_waitForGcToComplete(_JNIEnv*, _jclass*, long)+40) (BuildId: dfcb4b05ff9fd2be34518cabe13551a71b36fbb1)
```

Offset of Heap in ur device is wrong...
