### ISSUE TITLE
[BUG] v 0.5.1.3_4646 master YAHFA. Doesn't load modules.

### ISSUE THREAD

**Issue by RaphaelGreen** [ElderDrivers/EdXposed#760]
I have updated my exposed module from 0.5.0.6 4569 to new 0.5.1.3 4646 and got problem with not loading of modules. It shows that I have installed and activated all modules properly, but in real case it doesn't work.
**Xposed模块列表/Xposed Module List**

![Screenshot_20201224-024658](https://user-images.githubusercontent.com/75275527/103046858-58114280-4592-11eb-896a-12bab0ba6fa9.jpg)

**Magisk模块列表/Magisk Module List**

![Screenshot_20201224-024559](https://user-images.githubusercontent.com/75275527/103046796-31530c00-4592-11eb-94ec-891582675304.jpg)
![Screenshot_20201224-024551](https://user-images.githubusercontent.com/75275527/103046799-331ccf80-4592-11eb-863e-7fa93fc60bea.jpg)

**版本信息/Versions**
![Screenshot_20201224-024525](https://user-images.githubusercontent.com/75275527/103046805-3c0da100-4592-11eb-9ff8-dc38d782a7e8.jpg)
![Screenshot_20201224-022919](https://user-images.githubusercontent.com/75275527/103046823-42038200-4592-11eb-860d-ea29b80240d5.jpg)

Android: 10
![Screenshot_20201224-024745](https://user-images.githubusercontent.com/75275527/103046880-6c553f80-4592-11eb-8bcd-b5e9cf5743d4.jpg)
**相关日志/Related Logs**
[EdXposed_Verbose_20201224_022846.txt](https://github.com/ElderDrivers/EdXposed/files/5737600/EdXposed_Verbose_20201224_022846.txt)
[EdXposed_Modules_20201224_022836.txt](https://github.com/ElderDrivers/EdXposed/files/5737602/EdXposed_Modules_20201224_022836.txt)

**Comment by ghArthur8** [comment]
I don't add modules, either

**Comment by elesbb** [comment]
All I had to do was toggle off then back on all my modules inside the "modules" list. So inside your first screenshot, toggle them off, then back on, reboot, should work.

**Comment by Jaitsu** [comment]
I have the same problem on a Xiaomi Mi MIX 3, also with MinMinGuard (along with other modules) on this version and newer (that is, it also affects the current Canary, 5.1.4_4655. Toggling my modules off and on as @elesbb suggested did not work for me. Rolling back to a copy I of Canary 0.5.0.6_4586 I still have corrects the issue.

**Comment by tolgagunok** [comment]
Same problem here, minminguard stops working. It is the main reason that i use edxposed so new versions are no go for me.

**Comment by Jaitsu** [comment]
Is there an archive somewhere of Canary versions? I'd happily try some to track down where the breaking change for this is. I know there was a change to SEPolicy not too long ago that might be worth testing immediately before and after.

**Comment by ouyangchun1997** [comment]
![Screenshot_20210107-110502.jpg](https://user-images.githubusercontent.com/42675200/103847005-4ecbbe00-50da-11eb-86cf-0b2d3aa3aa35.jpg)
Same issue but I tried a lot, 4655 is functional.

**Comment by axelcostaspena** [comment]
My case is stranger: after some tests with some versions, installed latest canary for magisk, edxposed manager and edxposed yahfa, and everything was working, installed gravitybox and tweaked some settings...

after a couple of days, this began happening :O

no module deactivate or reinstall fix this

**Comment by DrSaad77** [comment]
> All I had to do was toggle off then back on all my modules inside the "modules" list. So inside your first screenshot, toggle them off, then back on, reboot, should work.

I had the same issue. Recently I updated to Riru 23.3 + EdXposed SandHook 0.5.1.4 CANARY. And did everything, Used EdXposed uninstaller, remove + Cleaned Cache/Dalvik, Until I tried toggle off >> Reboot then, toggle ON >>Reboot.
I guess, before trying any update/Uninstall, Module should be desactivated, then Reactivated at the end, if EdXposed keeped on the device.

**Comment by Jaitsu** [comment]
Got all my modules working again after being affected by this previously, on the latest 0.5.2.0_4671 build, under both Sandhook and YAHFA (though now to enable YAHFA I'm doing so by modifying customize.sh - is there a better way to do this now that the zips are merged...?)

At first I encountered the same issue, but after a complete uninstall (including running the uninstaller zip) and reinstalling, then re-enabling modules, everything seems to be working properly.

**Comment by yvvivek9** [comment]
Had the same issue and got it solved, i had actually installed magisk and its module in my internal storage but my edxposed manager was installed to my external storage. the module was detected as soon as i shifted edxposed manager to internal and did a reboot
