### ISSUE TITLE
[MORE INFO] XSharedPreference

### ISSUE THREAD

**Issue by fOmey** [ElderDrivers/EdXposed#762]
The wiki page mentions "XSharedPreference", is this a typo? Undefined in legacy xposed API.

https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreference

```
    private static SharedPreferences getPref(String path) {
        SharedPreferences pref = new XSharedPreference(BuildConfig.APPLICATION_ID, path);
        return pref.getFile().canRead() ? pref : null;
    }
```

[SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences) also doesn't support "getFile()", undefined.. unless I'm missing something here?

I'd like to take advantage of the changes in the latest API update, but its not clear how exactly I go about doing so when the examples are broken.

**Comment by kotori2** [comment]
Should be `XSharedPreferences`. Fixed.
