### ISSUE TITLE
[BUG] 缓存目录不会自动创建

### ISSUE THREAD

**Issue by coderstory** [ElderDrivers/EdXposed#769]
/data/misc/edxxxxx/cache 删掉后 不会自动创建
需要手动创建才行 有时候 想手动删下缓存

**Comment by kotori2** [comment]
缓存目录在安装的时候才创建，要不然加一个hook查一次慢死了

**Comment by yujincheng08** [comment]
`rm /data/misc/edxxxxx/cache/*`

**Comment by kotori2** [comment]
`rm /data/misc/edxp_*/cache/*`

**Comment by coderstory** [comment]
> 缓存目录在安装的时候才创建，要不然加一个hook查一次慢死了

可以在开机的时候 检查一次
