### ISSUE TITLE
文本自定义无法使用，微X模块会让微信无法打开钱包

### ISSUE THREAD

**Issue by DaFeiMao233** [ElderDrivers/EdXposed#77]
什么情况/What happened?

文本自定义失效(在0.2.9.5里使用正常，到0.2.9.7里就失效了，到现在还没有修复)，微X模块启用后微信的钱包打不开了，打开就闪退(在0.2.9.1里没这个问题到了0.2.9.5里就有这种问题了，但不是每次都会闪退，到现在是一直会闪退)

Xposed模块列表/Xposed Module List

爱字体
绿色守护
蚂蚁森林助手
淘饭饭
微X模块
QX模块
文本自定义
无障碍-Daemon
验证码提取器
应用变量
App Translator
base.apk
BeautyHeaderPlugin
GoogleAPP助手
GravityBox [O]
Q++模块
QQ斗图神器
Screenshot Delay Remover - Mod
spQQ机器人

Magisk模块列表/Magisk Module List

App Ops System Plugin
Busybox for Android NDK
DNS Switcher
IOS Pro最终版
Magisk Google DNS
Magisk Manager for Recovery Mode(MM汉化版)
小米8刘海对齐
YouTube Vanced - Magisk Repo
Magisk SELinux Manager
Riru - Core
Riru - Ed Xposed
LogCat
安卓O样式音乐通知
miui10通知栏去白边

EdXposed及Riru版本/Versions of EdXposed and Riru

EdXposed: v0.2.9.8_beta1

Riru: v11

相关Logcat/Logcat

logcat不知为何并不会抓取日志，最近的日志也在1970年8月。

**Comment by whc200187** [comment]
我微x和qx装了之后微信和tim根本打不开。
riru 10
edxposed 0.2.9.8_beta1
请指教，你是怎么安装微x可以使用的？

**Comment by tianma8023** [comment]
@DaFeiMao233 
你好，我是 [验证码提取器 XposedSmsCode](https://github.com/tianma8023/XposedSmsCode) 的作者，微信钱包打不开是 EdXposed 环境下，我这边的模块导致的，具体原因不清楚，所以在最新版本(1.6.0)的模块中，为已经屏蔽掉微信捐赠来处理这个问题了，实在是抱歉 QuQ

**Comment by lukemin** [comment]
> @DaFeiMao233
> 你好，我是 [验证码提取器 XposedSmsCode](https://github.com/tianma8023/XposedSmsCode) 的作者，微信钱包打不开是 EdXposed 环境下，我这边的模块导致的，具体原因不清楚，所以在最新版本(1.6.0)的模块中，为已经屏蔽掉微信捐赠来处理这个问题了，实在是抱歉 QuQ

不用你的模块也不行

**Comment by tianma8023** [comment]
@lukemin
是嘛，那可能别的模块也有同样的问题吧。也许是edxp的问题。

**Comment by tianma8023** [comment]
@solohsu
最开始是因为有用户反馈，然后我自测（只勾选我这个模块+edxposed），确实打不开微信钱包。但奇怪的是，其实我并没有hook与微信钱包相关的代码部分。

很抱歉，日志没有 :( 也正因为没有抓到相关错误日志，我也不知道是为什么就打不开了...

**Comment by lukemin** [comment]
> @tianma8023 你当时是如何定位到是你的模块的问题的，有什么相关的日志能提供下吗？

每次启动微信都要卡上几秒才行，能优化一下吗？
并不是所有的模块会使得微信打不开钱包。

**Comment by solohsu** [comment]
@tianma8023 今天看了下打开支付闪退的问题，是因为你hook QrRewardSelectMoneyUI这个类的时候，触发了类的初始化。在初始化父类的一个静态成员变量的时候，用到了Context，由于此时app的Context还没有拿到（handleBindApplication尚未执行），所以会抛出NPE。具体可以参考附件的crash堆栈，以及看一下微信的相应类的代码。
解决方案就是把hookQrRewardSelectMoneyUI移到app启动完成后执行，比如移到LauncherUIOnCreateHook的after方法里。我测试了这样修改之后就没问题了。
[crash.log](https://github.com/ElderDrivers/EdXposed/files/2942032/crash.log)

**Comment by tianma8023** [comment]
@solohsu  十分感谢！

**Comment by solohsu** [comment]
18bd0a8c0f311e2bb1bcb235cb6d11de01785a79
这个提交应该修复了类似的Class过早初始化导致的一系列问题。
