### ISSUE TITLE
[BUG] build error with Dobby

### ISSUE THREAD

**Issue by Jokerman1991** [ElderDrivers/EdXposed#772]
<Basic info>
branch: master

last commit: Fix permission, commit 454de34a92fb5b3965c346f709c35fef721d037b
Author: Jim Wu <mlgmxyysd@meowcat.org>
Date:   Fri Dec 25 12:38:35 2020 +0800 

<Bug Info>
build error with Dobby, error log:

  FAILED: /home/xxx/EdXposed/edxp-core/build/intermediates/cmake/release/obj/armeabi-v7a/libriru_edxp.so 
  : && /home/xxx/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi26 --gcc-toolchain=/home/xxx/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/xxx/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -std=c++17 -ffixed-x18 -Qunused-arguments -frtti -fomit-frame-pointer -fvisibility=hidden -fvisibility-inlines-hidden -O2 -s -Wno-unused-value -fomit-frame-pointer -Oz -DNDEBUG  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libriru_edxp.so -o /home/xxx/EdXposed/edxp-core/build/intermediates/cmake/release/obj/armeabi-v7a/libriru_edxp.so main/CMakeFiles/riru_edxp.dir/src/config_manager.cpp.o main/CMakeFiles/riru_edxp.dir/src/edxp_context.cpp.o main/CMakeFiles/riru_edxp.dir/src/main.cpp.o main/CMakeFiles/riru_edxp.dir/src/native_hook.cpp.o main/CMakeFiles/riru_edxp.dir/src/resource_hook.cpp.o main/CMakeFiles/riru_edxp.dir/src/riru_hook.cpp.o main/CMakeFiles/riru_edxp.dir/src/rirud_socket.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/art_class_linker.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/art_heap.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/edxp_config_manager.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/edxp_pending_hooks.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/edxp_resources_hook.cpp.o main/CMakeFiles/riru_edxp.dir/src/jni/edxp_yahfa.cpp.o  -ffixed-x18 external/yahfa/libyahfa.a external/xhook/libxhook.a external/android/libandroid.a external/Dobby/libdobby.a /home/jokerman/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/26/liblog.so -ffixed-x18 -llog -latomic -lm && :
  ld: error: undefined symbol: linker_get_solist()
  >>> referenced by native_hook.cpp:52 (/home/jokerman/space/clean/work/EdXposed/edxp-core/src/main/cpp/main/src/native_hook.cpp:52)
  >>>               main/CMakeFiles/riru_edxp.dir/src/native_hook.cpp.o:(edxp::InstallInlineHooks())
  
  ld: error: undefined symbol: linker_soinfo_get_realpath
  >>> referenced by native_hook.cpp:55 (/home/jokerman/space/clean/work/EdXposed/edxp-core/src/main/cpp/main/src/native_hook.cpp:55)
  >>>               main/CMakeFiles/riru_edxp.dir/src/native_hook.cpp.o:(edxp::InstallInlineHooks())
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by yujincheng08** [comment]
CI doesn't throw any errors. So it's your problem.

**Comment by Jokerman1991** [comment]
> CI doesn't throw any errors. So it's your problem.

Thanks so much. I'm new player with CI. It still makes me confused that which part of build environments got wrong with me.

ndk: /home/xxx/Android/Sdk/ndk/22.0.7026061
clang++: /home/xxx/Android/Sdk/ndk/22.0.7026061/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ 
llvm: /home/xxx/Android/Sdk/ndk/22.0.7026061/toolchains/llvm

All the CMakeLists files kept unmodified. Could you please give some clue?

**Comment by yujincheng08** [comment]
It's not the toolchain's problem. It's that you are using an incompatible version of Dobby.

**Comment by Jokerman1991** [comment]
> It's not the toolchain's problem. It's that you are using an incompatible version of Dobby.

Got it. I just cloned Dobby from github into my project. It's updated with master brunch. Latest commit of Dobby is below:

commit f93af7cbc95c0f472408d30fdba137019aa91c9a
Author: LoveSy <shana@zju.edu.cn>
Date:   Mon Dec 21 02:29:08 2020 +0800

    fix GetOatQuickMethodHeader

Could you please tell me which version or commit is available for edxp build?

**Comment by kotori2** [comment]
> Could you please tell me which version or commit is available for edxp build?

Please make use of git submodules.

**Comment by yujincheng08** [comment]
what?
I think we told you to use submodule in tg group instead of cloning yourself. Do you know why git submodule fix the commit hash?

**Comment by Jokerman1991** [comment]
> what?
> I think we told you to use submodule in tg group instead of cloning yourself. Do you know why git submodule fix the commit hash?

Got it. I made a stupid mistake. Thanks so much again.

**Comment by Jokerman1991** [comment]
> > Could you please tell me which version or commit is available for edxp build?
> 
> Please make use of git submodules.
> 
> ```
> git submodule update --init --recursive
> ```

Got it. I made a stupid mistake. Thanks so much again.
