### ISSUE TITLE
使用新版XSharedPreferences的一些問題

### ISSUE THREAD

**Issue by jayjd** [ElderDrivers/EdXposed#774]
Riru V23.1
EdXp 0.5.1.3
Magisk 20.4  8.0.3
系統 android 10

使用新版的XSharedPreferences 
通過目錄 文件已經生成 權限也是沒有問題的

就是沒有讀取文件的權限

**Comment by yujincheng08** [comment]
确定是worldreadble？确定读取时候路径是对的？啥信息都没有隔空抓药呢？

**Comment by jayjd** [comment]
> 确定是worldreadble？确定读取时候路径是对的？啥信息都没有隔空抓药呢？

解決了 文件錯誤,打擾了
