### ISSUE TITLE
[BUG] 无法Hook包名 'com.android.phone'

### ISSUE THREAD

**Issue by tianma8023** [ElderDrivers/EdXposed#78]
**什么情况/What happened?**
我是 [XposedSmsCode](https://github.com/tianma8023/XposedSmsCode) 的开发者，我在适配 `EdXposed` 的过程中，发现核心 Hook 的部分 [SmsHandlerHook](https://github.com/tianma8023/XposedSmsCode/blob/master/app/src/main/java/com/github/tianma8023/xposed/smscode/xp/SmsHandlerHook.java) 没办法成功 Hook，原因在于没办法 Hook 包 `com.android.phone`，以至于整个模块无效。在 `rovo98` 的 `Xposed` 中能正常运转。

**Xposed模块列表/Xposed Module List**
![screenshot_2019-02-15-13-01-51-637_com solohsu an](https://user-images.githubusercontent.com/7833704/52835568-efe5b000-3121-11e9-823c-8f4e3af776ae.png)

**Magisk模块列表/Magisk Module List**
![screenshot_2019-02-15-12-48-49-572_com topjohnwu](https://user-images.githubusercontent.com/7833704/52835272-bfe9dd00-3120-11e9-8635-86787406137d.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

Rom：Xiaomi.eu 9.1.24 MIUI10 - Android 9.0

Magisk: v18.1

EdXposed: 0.2.9.8_beta1

Riru: riru-core-v11

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by solohsu** [comment]
目前默认情况下是黑名单模式，会导致有些进程无法被hook到，比如com.android.phone进程，后续会着手解决一下这个问题。
当前版本的话你可以先把EdXp设置里的全局模式开关打开，重启后应该就可以hook到phone进程了。

**Comment by tianma8023** [comment]
@solohsu 
我这边已经按照你说的开了全局模式了，log显示 `com.android.phone` 进程能被hook了，但是还是未能成功hook住方法（`com.android.internal.telephony.InboundSmsHandler#dispatchIntent()`），最后结果就是模块失效。

经过我的观察，我发现开了全局模式后，`com.android.phone` 进程会被反复加载的比较频繁，而在 rovo89 的 Xposed 以及 太极·magisk 中却是在开机过程中加载一次（正常表现），在这俩上也能正常工作。我只是反馈一下观察到的结果，具体产生这样差别的原因我不清楚 :(

**Comment by solohsu** [comment]
```
2019-02-17 17:46:06.466 2750-2750/? I/EdXposed-Bridge: handler = class com.android.internal.telephony.InboundSmsHandler
2019-02-17 17:48:53.302 2750-2979/? I/EdXposed-Bridge: before handler dispatchIntent
2019-02-17 17:48:53.312 2750-2979/? I/EdXposed-Bridge: after handler dispatchIntent
2019-02-17 17:48:53.338 2750-2979/? I/EdXposed-Bridge: before handler dispatchIntent
2019-02-17 17:48:53.343 2750-2979/? I/EdXposed-Bridge: after handler dispatchIntent
```
我测试是可以hook到方法，至于你说的模块失效不清楚是什么原因导致。
另外反复加载是什么问题，能否具体描述一下。我这里只回调了一次`com.android.phone`。

**Comment by solohsu** [comment]
Fixed with https://github.com/ElderDrivers/EdXposed/releases/tag/v0.2.9.9_b2
