### ISSUE TITLE
skip injecting into android because sepolicy was not loaded properly

### ISSUE THREAD

**Issue by qq79480765** [ElderDrivers/EdXposed#782]
Here is the log information:

Android build: RP1A.200720.011
Android version: 11
Android sdk: 30
EdXposed version: v0.5.1.4_4655-master (YAHFA)
EdXposed api: 93
Riru version: v23.1 (51)
Riru api: 10
Magisk: 3f9a6441-lite (21201)
--------- beginning of main
--------- beginning of system
12-31 12:01:26.090   728   728 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-31 12:01:26.098   728   728 I EdXposed: Got base config path: /data/misc/edxp_JtFug6A5LcwjFhtX
12-31 12:01:26.115   727   727 I EdXposed: onModuleLoaded: welcome to EdXposed!
12-31 12:01:26.117   727   727 I EdXposed: Got base config path: /data/misc/edxp_JtFug6A5LcwjFhtX
12-31 12:01:27.652   727   727 W EdXposed: installer not set, using default one org.meowcat.edxposed.manager
12-31 12:01:27.654   727   727 I EdXposed: base config path: /data/misc/edxp_JtFug6A5LcwjFhtX/0
12-31 12:01:27.654   727   727 I EdXposed:   using installer package name: org.meowcat.edxposed.manager
12-31 12:01:27.654   727   727 I EdXposed:   using whitelist: true
12-31 12:01:27.654   727   727 I EdXposed:   deopt boot image: false
12-31 12:01:27.654   727   727 I EdXposed:   no module log: false
12-31 12:01:27.654   727   727 I EdXposed:   resources hook: false
12-31 12:01:27.654   727   727 I EdXposed:   white list: 
12-31 12:01:27.654   727   727 I EdXposed:  com.eg.android.AlipayGphone
12-31 12:01:27.654   727   727 I EdXposed: club.youppgd.adhook
12-31 12:01:27.654   727   727 I EdXposed: com.cofface.ivader
12-31 12:01:27.654   727   727 I EdXposed: io.enpass.app
12-31 12:01:27.654   727   727 I EdXposed: com.sollyu.xposed.hook.model
12-31 12:01:27.654   727   727 I EdXposed: z.em.energy
12-31 12:01:27.654   727   727 I EdXposed: cn.kwaiching.hook
12-31 12:01:27.654   727   727 I EdXposed: com.github.tianma8023.xposed.smscode
12-31 12:01:27.654   727   727 I EdXposed: android
12-31 12:01:27.654   727   727 I EdXposed: name.mikanoshi.customiuizer
12-31 12:01:27.654   727   727 I EdXposed: chili.xposed.chimi
12-31 12:01:27.654   727   727 I EdXposed: com.jozein.xedgepro
12-31 12:01:27.654   727   727 I EdXposed: org.meowcat.edxposed.manager
12-31 12:01:27.654   727   727 I EdXposed:   black list: 
12-31 12:01:27.654   727   727 I EdXposed:  com.google.android.gsf
12-31 12:01:27.654   727   727 I EdXposed: com.google.android.gms
12-31 12:01:27.654   727   727 I EdXposed:   module list: 
12-31 12:01:27.654   727   727 I EdXposed:  club.youppgd.adhook
12-31 12:01:27.654   727   727 I EdXposed: z.em.energy
12-31 12:01:27.654   727   727 I EdXposed: com.jozein.xedgepro
12-31 12:01:27.654   727   727 I EdXposed: org.meowcat.edxposed.manager
12-31 12:01:27.659   727   727 I EdXposed: Loaded /data/misc/edxp_JtFug6A5LcwjFhtX/framework/edxp.dex with size 166168
12-31 12:01:27.669   727   727 I EdXposed: Loaded /data/misc/edxp_JtFug6A5LcwjFhtX/framework/eddalvikdx.dex with size 766268
12-31 12:01:27.669   727   727 I EdXposed: Loaded /data/misc/edxp_JtFug6A5LcwjFhtX/framework/eddexmaker.dex with size 64856
12-31 12:01:27.691  1353  1353 E EdXposed: skip injecting into android because sepolicy was not loaded properly
12-31 12:01:27.692  1353  1353 I EdXposed: Loaded /data/misc/edxp_JtFug6A5LcwjFhtX/framework/edservice.dex with size 53424
12-31 12:01:27.693  1353  1353 W EdXposed: Installed EdXposed Service
12-31 12:01:37.427   728   728 W EdXposed: installer not set, using default one org.meowcat.edxposed.manager
12-31 12:01:37.427   728   728 I EdXposed: base config path: /data/misc/edxp_JtFug6A5LcwjFhtX/0
12-31 12:01:37.427   728   728 I EdXposed:   using installer package name: org.meowcat.edxposed.manager
12-31 12:01:37.427   728   728 I EdXposed:   using whitelist: true

![Uploading Screenshot_2021-01-01-08-11-10-723_bin.mt.plus.jpg…]()

**Comment by kotori2** [comment]
My guess is you are not using latest Manager.
Also please grab logs with debug build.

**Comment by qq79480765** [comment]
here is infomation,usingthe lasted edxpsed manager and edxpsed moudle 。by the way,this is using magisk-lite 。The problem will not exist when using original magisk，but the problem not exist on the other phone that  version of android system  is 9 。
Manufacturer: Xiaomi
Brand: Redmi
Device: cezanne
Product: cezanne
Model: M2006J10C
Fingerprint: Redmi/cezanne/cezanne:11/RP1A.200720.011/20.12.16:user/release-keys
ROM description: cezanne-user 11 RP1A.200720.011 20.12.16 release-keys
Architecture: arm64-v8a
Android build: RP1A.200720.011
Android version: 11
Android sdk: 30
EdXposed version: v0.5.1.4_4655-master (YAHFA)
EdXposed api: 93
Riru version: v23.1 (51)
Riru api: 10
Magisk: 3f9a6441-lite (21201)

**Comment by qq79480765** [comment]
Except for this problem that skip android , everything else is normal。

**Comment by qq79480765** [comment]
ed xposed manager version is 4.6.0pre(45758)

**Comment by yujincheng08** [comment]
its none of edxp's bussiness. report to magisk instead.

**Comment by qq79480765** [comment]
> its none of edxp's bussiness. report to magisk instead.

ok，3q
