### ISSUE TITLE
[BUG] 0.5.1.4_4655 YAHFA and SandHook not working

### ISSUE THREAD

**Issue by maidmeow4** [ElderDrivers/EdXposed#784]
**什么情况/What happened?**

version `0.5.1.4_4655` EdXposed framework not working, both variants were tried.
EdXposed manager says framework is installed but not active, all xposed modules not having effect.
Tried switching on "Skip status check", but no luck.

**Xposed模块列表/Xposed Module List**

Greenify , Burnt Toast Revived , GravityBox [P] , RootCloak

**Magisk模块列表/Magisk Module List**

Energized Protection , Riru , Riru - EdXposed , Riru - IFW Enhance , Riru - Location Report Enabler , Riru - Fingerprint pay - WeChat , Riru - Fingerprint pay - Alipay , Systemless Hosts

**版本信息/Versions**

Android: stock Android 9 running on a Sony G8342

Magisk: 21.2

Riru: 23.1

EdXposed: 0.5.1.4_4655

**相关日志/Related Logs**

[EdXposed_Modules_20210104_084137.txt](https://github.com/ElderDrivers/EdXposed/files/5762535/EdXposed_Modules_20210104_084137.txt)

**Comment by kotori2** [comment]
@maidmeow4 Please try pinned FAQ first

**Comment by maidmeow4** [comment]
Tried, manager says EdXposed framework is active now, but modules still not
working.

双草酸酯 <notifications@github.com> 于 2021年1月4日周一 13:23写道：

**Comment by kotori2** [comment]
> but modules still not working.

Module specific issue then. 

```
01-04 08:38:12.133  5390  5390 I EdXposed-Bridge: Loading modules from /data/app/me.rapperskull.burnttoastrevived-b4l87GziTOAwgE4e4JhQjQ==/base.apk
01-04 08:38:12.174  5354  5354 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
01-04 08:38:12.179  5354  5354 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
01-04 08:38:12.242  5390  5390 I EdXposed-Bridge:   Loading class me.rapperskull.burnttoastrevived.Main
01-04 08:38:12.252  5390  5390 I EdXposed-Bridge: Loading modules from /data/app/com.oasisfeng.greenify-b6XJv-qcTmukqw786o_4kQ==/base.apk
01-04 08:38:12.353  5390  5390 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
01-04 08:38:12.358  5390  5390 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
01-04 08:38:13.034  5491  5491 I EdXposed-Bridge: Loading modules from /data/app/com.devadvance.rootcloak2-q7aUw6unVTVyHv4S5iuBwA==/base.apk
01-04 08:38:13.037  5491  5491 I EdXposed-Bridge:   Loading class com.devadvance.rootcloak2.RootCloak
01-04 08:38:13.042  5491  5491 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-Agvs3ZKK2EILVDED9NCnqQ==/base.apk
01-04 08:38:13.045  5491  5491 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
```

They all loaded successfully.
