### ISSUE TITLE
[BUG] EdXposed 0.5+ is just broken

### ISSUE THREAD

**Issue by HanabishiRecca** [ElderDrivers/EdXposed#785]
Hello guys. I'm using Xposed/EdXposed for a very long time. For many years, since Android 4. And all this time it worked perfectly. 0.4.6.4 works perfectly. But recent 0.5+ is just broken. Literally **nothing** works here. All the modules don't work properly, system faces glitches, bootloops, crashes and rest exotic errors in the log. I've spent a few days fighting against it, reinstalled entire system from scratch for a several times. But this is just pointless.
And this is not just my personal case. I've discussed on the forums and modules issue trackers, this is a massive problem, a lot of people complaining about it. The only effective advice there is "rollback to 0.4.6.4".

Why did you need to break working software? Because of useless google SafetyNet s**t? Does Riru forced you to do that?

Technical info:
Android 10 / LineageOS 17.1 Official
Magisk 20.4
Riru 23.1
EdXposed 0.5.1.4-4655 (also tried many different 0.5.X versions including canary)

**Comment by yujincheng08** [comment]
We didn't break it. It works for us. DONT spread rumors.

**Comment by HanabishiRecca** [comment]
@yujincheng08 yeah, I understand that the bare EdXposed by itself is working. You can say "this is your modules issue". Ok, but without modules what the point?
And there are literally no modules updates in the repo since 0.5 appearance. Do you think this is ok state?
![Screenshot_EdXposed_Manager](https://user-images.githubusercontent.com/13597663/103533234-8eae5d80-4eae-11eb-8719-e8b46e7a1415.png)

**Comment by yujincheng08** [comment]
this is because repo.xposed.info is broken now. no one can sign in that site

**Comment by yujincheng08** [comment]
and all modules i use are working gracefully, including my own one.

**Comment by kotori2** [comment]
> And there are literally no modules updates in the repo since 0.5 appearance.

XDA provided Xposed repository for free in the past few years. If you can provide more **stable** storage server then XDA for module repositories, feel free to contact us.

> The only effective advice there is "rollback to 0.4.6.4".

Of course you can rollback. EdXposed is a GPL open source project, you can create your own fork.
