### ISSUE TITLE
能否支持面板顶栏美化？

### ISSUE THREAD

**Issue by DaFeiMao233** [ElderDrivers/EdXposed#79]
模块名为面板顶栏美化，附属模块(xposed模块)为BeautyHeaderPlugin![模块如图所示](https://ooo.0o0.ooo/2019/02/15/5c664e5d4a644.jpg)

**Comment by DaFeiMao233** [comment]
![](https://ooo.0o0.ooo/2019/02/15/5c664e5d4a644.jpg)

**Comment by zoums** [comment]
问题是。。不论支不支持，这模块都没有支持安卓9.0。

**Comment by DaFeiMao233** [comment]
@zoums 这模块作者是我基友，我可以让他支持9

**Comment by MlgmXyysd** [comment]
请先联系作者以使模块支持安卓9.0。

**Comment by solohsu** [comment]
Refer to #53
