### ISSUE TITLE
How to enable resources hook?

### ISSUE THREAD

**Issue by hatsune-miku** [ElderDrivers/EdXposed#791]
edxp version: 0.5.1.4_4655 YAHFA
edxp manager version: 4.5.7

"Disable Resource Hook" is not enabled but resource hook is not working (`handleInitPackageResources` never called )

**Comment by kotori2** [comment]
Resource hook is deprecated.

**Comment by XspeedPL** [comment]
There is functional code in XposedInit though. Is it unused?

**Comment by kotori2** [comment]
ref #789. Gonna create a new issue later.
