### ISSUE TITLE
Some apps not shown in XposedHide's app list

### ISSUE THREAD

**Issue by Sky-Walkrr** [ElderDrivers/EdXposed#794]
Recently, I updated my EdXposed to 0.5.1.4 and EdXposed Manager to v4.6.0. ROM is MIUI 12.5.

I tried to enable XposedHide(white list) for better performance.I can enable specific apps that I would like to hook instead of all the apps.

In module CustoMIUIzer, the 'Clean share menu' & 'Clean open with menu' are really useful for me.But when I turn on the EdXposed's XposedHide, these clean menu mods don't work anymore.The first idea came to me is that I must enable apps that take charge of those menus.Then I read the source code of custoMIUIzer, I found these related classes & methods:

```java
public static void CleanShareMenuHook() {
		Helpers.hookAllMethods("miui.securityspace.XSpaceResolverActivityHelper.ResolverActivityRunner", null, "run", new MethodHook() {
        ....

public static void CleanShareMenuServiceHook(LoadPackageParam lpparam) {
		Helpers.findAndHookMethod("com.android.server.pm.PackageManagerService"
        ....

public static void CleanOpenWithMenuHook() {
		Helpers.hookAllMethods("miui.securityspace.XSpaceResolverActivityHelper.ResolverActivityRunner", null, "run", new MethodHook() {
        ...

public static void CleanOpenWithMenuServiceHook(LoadPackageParam lpparam) {
		Helpers.findAndHookMethod("com.android.server.pm.PackageManagerService", lpparam.classLoader, "systemReady", new MethodHook() {
        ...
```

However, I could not see `miui.securityspace.XSpaceResolverActivityHelper` nor `com.android.server.pm.PackageManagerService` in the apps list.

Is there any thing I missed?How can I make clean menus mod work with EdXposed's XposedHide?

**Comment by kotori2** [comment]
> However, I could not see miui.securityspace.XSpaceResolverActivityHelper nor com.android.server.pm.PackageManagerService in the apps list.

They sounds like system classes and they will initialize in each app. So we should hook them in each individual app.

**Comment by Sky-Walkrr** [comment]
> > However, I could not see miui.securityspace.XSpaceResolverActivityHelper nor com.android.server.pm.PackageManagerService in the apps list.
> 
> They sounds like system classes and they will initialize in each app. So we should hook them in each individual app.

I tried adding more apps into white-list, these apps can be hooked now, but still not working.

**Comment by kotori2** [comment]
Sorry I just misread your question. 
For things like `com.android.server.pm.PackageManagerService` you should add "Android" into your Xposed Hide list. 
I guess `miui.securityspace.XSpaceResolverActivityHelper` is also in that package.

**Comment by Sky-Walkrr** [comment]
I turned off the XposedHide, now the hook is enable globally.But the clean menu mods are still not working...Well, it seems that the module CustoMIUIzer is not compat with MIUI 12.5(Based on Android 11) for now. Maybe it's nothing to do with EdXposed.


> For things like `com.android.server.pm.PackageManagerService` you should add "Android" into your Xposed Hide list.
> I guess `miui.securityspace.XSpaceResolverActivityHelper` is also in that package.

When CustoMIUIzer fixes their bug, I will test the Xposed Hide again. Thanks a lot for your reply!

**Comment by kotori2** [comment]
> Well, it seems that the module CustoMIUIzer is not compat with MIUI 12.5(Based on Android 11) for now. Maybe it's nothing to do with EdXposed.

~~maybe @Mikanoshi could help~~

**Comment by Mikanoshi** [comment]
I won't, Android 11 is not supported, they should learn to read 🤦‍♂️
