### ISSUE TITLE
[BUG] com.android.server.pm.PackageManagerService$Injector cannot be cast to android.content.Context

### ISSUE THREAD

**Issue by sn-o-w** [ElderDrivers/EdXposed#800]
**什么情况/What happened?**
For some reason, SnapTools doesn't work with Android R.
It used to work well on Android Q tho.

**Xposed模块列表/Xposed Module List**
- EdXposed Manager
- Lucky Patcher
- SnapTools

**Magisk模块列表/Magisk Module List**
- Riru
- Riru - EdXposed
- SELinux Permisive
- Universal GMS Doze

**版本信息/Versions**

- Android: 11
- Magisk: 21201 (Canary)
- Riru: 23.2
- EdXposed: 0.5.1.4

**相关日志/Related Logs**

Some logs:
[EdXposed_Verbose_20210111_053020.txt](https://github.com/ElderDrivers/EdXposed/files/5796482/EdXposed_Verbose_20210111_053020.txt)
[EdXposed_Modules_20210111_053014.txt](https://github.com/ElderDrivers/EdXposed/files/5796483/EdXposed_Modules_20210111_053014.txt)
Logcat + kmesg + dmesg + event.log -> [2021-01-11_05.31.zip](https://github.com/ElderDrivers/EdXposed/files/5796484/2021-01-11_05.31.zip)

**Comment by sn-o-w** [comment]
Do you have any ideas why is throwing the following error: `com.android.server.pm.PackageManagerService$Injector cannot be cast to android.content.Context` ?

I haven't seen this error on Android Q.

**Comment by yujincheng08** [comment]
module-specific.

**Comment by sn-o-w** [comment]
@yujincheng08 And is it possible to do something related to this?

**Comment by sn-o-w** [comment]
> module-specific.

Same module used to work well with same EdXposed version on Android Q.
