### ISSUE TITLE
[BUG] cannot see "Xposed Hide"menu

### ISSUE THREAD

**Issue by RockZhou8** [ElderDrivers/EdXposed#804]
**什么情况/What happened?**
Just upgrade to the latest version. I cannot find "Xposed Hide" in the Edxposed Manager.
刚从RiruV19.7+0.4.6.1(YAHFA)升级到V23.3+v0.5.1.4(sandhook)CANARY，Edxposed Manager的首页、菜单、设置里都没找到“Xposed Hide”这个功能。

**版本信息/Versions**

Android: 9 API 28 (MIUI10)

Magisk:v21.2

Riru:V23.3

EdXposed:v0.5.1.4(sandhook)CANARY

Edxposed Manager: v4.5.7

**Comment by kotori2** [comment]
@RockZhou8 左侧汉堡菜单里面，是黑白名单改名，另外你需要更新manager

**Comment by RockZhou8** [comment]
> @RockZhou8 左侧汉堡菜单里面，是黑白名单改名，另外你需要更新manager

的确manager没更新，还是V4.5.7
Thx.

**Comment by RockZhou8** [comment]
> @RockZhou8 左侧汉堡菜单里面，是黑白名单改名，另外你需要更新manager

还是v4.5.7，要自己编译？

https://github.com/ElderDrivers/EdXposedManager
latest:
v4.5.7
@MlgmXyysd MlgmXyysd released this on 3 Apr 2020 · 92 commits to master since this release

**Comment by RockZhou8** [comment]
> @RockZhou8 左侧汉堡菜单里面，是黑白名单改名，另外你需要更新manager

各模块都没生效，好像是SANDHOOK版不行，同机型别人用YAHFA又回卡开机，我又回退v19.3了

**Comment by kotori2** [comment]
> 还是v4.5.7，要自己编译？

某人拒绝在GitHub上更新Manager的APK，要你自己去Telegram群里下

> 各模块都没生效

同上。
