### ISSUE TITLE
EdXposed Framework is installed, but not active

### ISSUE THREAD

**Issue by kajahofman** [ElderDrivers/EdXposed#808]
**What happened?**
EdXposed Framework is installed, but not active. Please check the logs for details.

**Xposed Module List**
Core Patch
EdXposed Manager

**Magisk Module List**
ARCore/Playground Patcher
Riru
Riru - EdXposed

**Versions**
Android 11 (Corvus OS 13 R Beta Exalted 1848 - Redmi 5 Plus - codename vince)
Magisk 21.4
Riru 23.3
EdXposed 0.5.1.4_4655 (Sandhook)

**Related Logs**
[EdXposed_Verbose_20210118_231605.txt](https://github.com/ElderDrivers/EdXposed/files/5832598/EdXposed_Verbose_20210118_231605.txt)

**Comment by Blank517** [comment]
`2. Installed but not activated (yellow warning)
Make sure you installed latest Canary build of EdXposed and Manager, then go to Xposed Hide - find EdXposed Manager - select "Optimize with Speed mode", restart Manager app.`

**Comment by kajahofman** [comment]
Problem solved with different ROM installation.
