### ISSUE TITLE
[BUG] 自改 Swipeback2 對9.0 支持不好

### ISSUE THREAD

**Issue by Charles-Chan-HK** [ElderDrivers/EdXposed#82]
**什么情况/What happened?**
以前改了Swipeback2 的 可以在舊版的Xposed 7.0 上正常使用，到了大大的EDXposed 9.0 出現了BUG。背景變黑

**Xposed模块列表/Xposed Module List**
 Swipeback2 自改了 	
"findAndHookMethod("com.android.internal.policy.PhoneWindow", null, "setStatusBarColor", int.class, new XC_MethodHook() {" Xposed 7.0 以前可以正常使用

**Magisk模块列表/Magisk Module List**

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.2.9.8

Riru: V11

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

02-16 19:37:47.585 E/EdXposed-Bridge(1181): java.lang.NoSuchMethodError: com.android.server.am.ActivityRecord#isHomeActivity()#bestmatch
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:57)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:4)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at info.papdt.swipeback.mod.ModSwipeBack$6.afterHookedMethod(ModSwipeBack.java:208)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(Unknown Source:0)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at EdHooker46.hook(Unknown Source:412)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:835)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:551)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1156)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:490)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5132)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5106)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5097)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10084)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:122)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3303)
02-16 19:37:47.585 E/EdXposed-Bridge(1181): 	at android.os.Binder.execTransact(Binder.java:731)

**Comment by solohsu** [comment]
http://androidxref.com/9.0.0_r3/xref/frameworks/base/services/core/java/com/android/server/am/ActivityRecord.java
9.0的源码里确实没有这个isHomeActivity方法，至于背景变黑是不是因为找不到这个方法导致的，不太清楚。
