### ISSUE TITLE
[BUG] -1 0 1 this class does not implement any sub-interface of ixposedmod skipping it 

### ISSUE THREAD

**Issue by Android1500** [ElderDrivers/EdXposed#824]
i m making a xposed module which Mask Imei and its working but somehow its not Masking imei now and when i try to check log in edxposed manger i see edxposed loading my class but after this its showing ""this class does not implement any sub-interface of IXposedmod, skipping it

**`PLEASE HELP TO FIND ISSUE**

**My package : com.yuvi.pirate**

**EdXposed logs** 

[EdXposed_Modules_20210205_125115[1].txt](https://github.com/ElderDrivers/EdXposed/files/5934372/EdXposed_Modules_20210205_125115.1.txt)

**Comment by yujincheng08** [comment]
I think its ur bug. Its not EdXposed's bug.

**Comment by Android1500** [comment]
I think so..

**Comment by XspeedPL** [comment]
Come on, the error message cannot get any more simple.
Your `XposeHook` (typo btw?) class does not implement Xposed interfaces, like `IXposedHookLoadPackage` or `IXposedHookZygoteInit`.

**Comment by Android1500** [comment]
> Come on, the error message cannot get any more simple.
> Your `XposeHook` (typo btw?) class does not implement Xposed interfaces, like `IXposedHookLoadPackage` or `IXposedHookZygoteInit`.

Thanks Sir Issue Fixed !!
