### ISSUE TITLE
[BUG]  Unable to install edxposed

### ISSUE THREAD

**Issue by archz2** [ElderDrivers/EdXposed#825]
**What happened?**
I'm trying to install canary edxposed on my OnePlus 5T running Android 10.

The flashing goes successful in twrp but the framework doesn't get installed.

I'm using latest edxposed manager i.e. 4.6.2.

In magisk manager it shows as installed.
What should I do to run edxposed flawlessly?

I also tried these ways from magisk manager.

1. Directly from the modules list that shows up in the magisk modules list(v4677).

2. By flashing the zip manually within magisk.(v 4677) from internal storage.

3. Manually flashing zip v.4679 (canary version) from Magisk from internal storage.

Same results. ☹Tried both debug version and master version. 

![f1](https://user-images.githubusercontent.com/66735186/107112768-1f96a100-6880-11eb-9cf0-63d29da64343.jpg)
![f2](https://user-images.githubusercontent.com/66735186/107112769-202f3780-6880-11eb-9cc6-590f6d803b7b.jpg)

**Xposed Module List**
Gravity box 10.1.0

**Magisk Module List**
![screenshot magisk](https://user-images.githubusercontent.com/66735186/107112765-17d6fc80-6880-11eb-8728-a54f637b0dee.jpg)

**Versions**

Android:10

Magisk: 21.4

Riru: 23.4

EdXposed: 0.5.2.1_4679 (canary)

**Related Logs**
I cannot capture log.  The app says that it cannot write to sd card. 

The log anyway doesn't contain much info. 
![loggy1](https://user-images.githubusercontent.com/66735186/107112905-10fcb980-6881-11eb-9cb4-80e88f5025ba.jpg)

**Comment by weebee42** [comment]
Same thing happened to me on my Xcover4 (SM-G390F) running Pie. Everything else is as described above. The only thing I could add is the output from the riru app (indicating that it has successfully connected with edxp?):

![Screenshot_20210206-124327_Riru](https://user-images.githubusercontent.com/59530821/107117367-39cd8080-687a-11eb-8958-65065685ad55.jpg)

**Comment by archz2** [comment]
I downloaded and installed riru app from here.

https://github.com/RikkaApps/Riru

I'm getting this upon running it. 


![Screenshot_20210206-181708](https://user-images.githubusercontent.com/66735186/107118555-bf1b5a00-68a7-11eb-913b-ecebbc548c66.jpg)

It seems like riru is causing trouble? 
What do I do now?

**Comment by yujincheng08** [comment]
@archz2 You should capture boot log and report to riru. It's not EdXposed's problem.

**Comment by archz2** [comment]
> @archz2 You should capture boot log and report to riru. It's not EdXposed's problem.

How to do that?

**Comment by yujincheng08** [comment]
connect your phone to pc, power off ur phone, in cmd run `adb wait-for-device logcat > log.txt` and then power on ur phone.

**Comment by archz2** [comment]
I solved the issue finally. I thought that the whole trouble is with riru not getting installed which was affecting edxposed.

I flashed Riru 23.4 again from magisk. Even though it was already installed. I flashed it again on the existing installation.

Now edxposed is working fine. Thanks everyone for your support. 🙏🏻

**Comment by yujincheng08** [comment]
Many people encountered this problem. Of course, it can be solved by reinstalling Riru and I knew it. BUT it does not actually solve the problem! You should provide logcat to Riru to solve this problem completely.

**Comment by weebee42** [comment]
I found a solution at least for my problem: nothing is wrong with riru or edxp. Disabling the magisk module _Foxy Boot_ solved the problem. Now the manager finds edxp properly installed.

**Comment by drewcu** [comment]
Same problem with Riru 23.4 and Edxposed 4682 on Pie... After reboot, not properly installed. No problem on 4677.

Tried reinstalling Riru 23.4 and after rebooting, still not working as it should. Don't have "Foxy Boot" module.

Reverted to 4677 until Riru fixes this.
