### ISSUE TITLE
[BUG] Take screenshots on MIUI 12

### ISSUE THREAD

**Issue by xDonatello** [ElderDrivers/EdXposed#827]
I have a very strange problem. Since I upgraded to MIUI 12, screenshots very often don't start.
I tried everything to understand the cause, in the end my conclusion is this: having modules set to "enabled" in EdXposed Manager.
That is, the problem is not having active modules, but the fact that they are selected on "EdXposed Manager > Modules". I just uncheck all the modules and the problem disappears, without having to restart the device, so the modules are actually still active.

I know, it sounds silly, but I've done various tests.

Until recently I was on MIUI 11, with EdXposed 0.4.6.4 + EdXposed Manager 4.5.7, and this problem was not present.
Both EdXposed 0.5.1.3 (with Manager 4.5.7) and EdXposed Canary 0.5.2.2 (with Manager 4.6.2) have this problem, both SandHook and YAHFA. I also tried to change Magisk version (20.4 and 21.2).
I wanted to try EdXposed 0.4.6.4, but it is not compatible with the latest version of Riru Core, and older versions of Riru are no longer available on GitHub.

**Xposed模块列表/Xposed Module List**
CustoMIUIzer
Lucky Patcher
XMiTools

**Magisk模块列表/Magisk Module List**
Riru
EdXposed
Google Sans Plus Font
Universal SafetyNet Fix
Mi 9 lite Buffer Fix for Q

**版本信息/Versions**
Android: 10
Magisk: 21.2
Riru: 23.4
EdXposed: 0.5.2.1

**相关日志/Related Logs**
[EdXposed_Modules_20210209_031920.txt](https://github.com/ElderDrivers/EdXposed/files/5948312/EdXposed_Modules_20210209_031920.txt)
[EdXposed_Verbose_20210209_031931.txt](https://github.com/ElderDrivers/EdXposed/files/5948313/EdXposed_Verbose_20210209_031931.txt)

**Comment by MlgmXyysd** [comment]
Try to add `com.miui.screenshot` to the blacklist.

**Comment by xDonatello** [comment]
> Try to add `com.miui.screenshot` to the blacklist.

OMG, now it works! It was that simple...
Thanks so much
