### ISSUE TITLE
启用音量放大器后，黑名单疑似不工作[BUG] 

### ISSUE THREAD

**Issue by rxzcums** [ElderDrivers/EdXposed#83]
**什么情况/What happened?**

启用音量放大器（0.27-0.30）后，黑名单模式疑似不工作。
1.温州银行和中国移动，两个app均检测xp（检测到就拒绝运行或卡启动页）。
2.我将他们都加入edxp黑名单模式下的的黑名单中，两者均能运行（黑名单功能有效，因为防xp检测成功）
3.装上音量放大器后，两者都不能运行（黑名单功能失效？）
疑似音量放大器与edxp的黑名单功能冲突
我向音量的作者反映issue，对方表示不是音量放大器的锅。
https://github.com/bin456789/Unblock163MusicClient-Xposed/issues/175

**Xposed模块列表/Xposed Module List**

![screenshot_2019-02-17-16-25-09-648_com solohsu android edxp manager](https://user-images.githubusercontent.com/11990604/52910339-1d249080-32d1-11e9-84c7-dcbc85695d85.png)

**Magisk模块列表/Magisk Module List**

![screenshot_2019-02-17-16-25-17-835_com topjohnwu magisk](https://user-images.githubusercontent.com/11990604/52910347-3594ab00-32d1-11e9-9867-b281a3e90ad1.png)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 0.2.9.8

Riru: v12（v11结果一样）

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by rxzcums** [comment]
0.2.9.9 b1已解决，感谢！！

**Comment by rxzcums** [comment]
0.3.0.0 b2修复微X，稳定性大大提高，非常牛！
但是，这个issuse又复现了😭

**Comment by solohsu** [comment]
@rxzcums 这个问题确实很奇怪，只有音量放大器会导致这个问题。

**Comment by rxzcums** [comment]
是的，很奇怪。可能是放大器的某hook影响了黑名单功能，纯属猜测😏

**Comment by solohsu** [comment]
@rxzcums 同时打开黑名单和动态模块列表应该就可以了。在299上没问题是因为开了黑白名单默认就是动态模块列表了，并且还关不掉，其实是个bug。
现在只打开黑名单其实不够黑，是因为为了提升应用启动速度，修复了上述bug，默认在不开启动态模块列表的情况下，会在系统启动时加载一次模块列表，最终还是对所有应用产生了影响。

**Comment by rxzcums** [comment]
> @rxzcums 同时打开黑名单和动态模块列表应该就可以了。在299上没问题是因为开了黑白名单默认就是动态模块列表了，并且还关不掉，其实是个bug。
> 现在只打开黑名单其实不够黑，是因为为了提升应用启动速度，修复了上述bug，默认在不开启动态模块列表的情况下，会在系统启动时加载一次模块列表，最终还是对所有应用产生了影响。
> 至于为什么只有音量放大器会影响其他应用我也实在搞不清楚。

明白了，谢谢！👍

**Comment by solohsu** [comment]
Fixed with 47c500b96ded4da92aa59b7b8336ba556afa3716.
