### ISSUE TITLE
[BUG] xprivacylua cannot be activated in the latest riru and edxposed

### ISSUE THREAD

**Issue by Hxppdv** [ElderDrivers/EdXposed#831]
**什么情况/What happened?**
I have tried various ways and found that xprivacylua is activated properly on older versions of edxposed (0.4.6.4). The developer of xprivacylua said that this is a problem with edxposed, and I searched the internet for similar cases but none of them solved my problem.

**Xposed模块列表/Xposed Module List**
Xprivacylua

**Magisk模块列表/Magisk Module List**
riru
edxposed

**版本信息/Versions**

Android:
Adnroid 10

Magisk:
21408

Riru:
v23.5

EdXposed:
v0.5.2.1

**相关日志/Related Logs**

[EdXposed_Verbose_20210214_130830.txt](https://github.com/ElderDrivers/EdXposed/files/5977028/EdXposed_Verbose_20210214_130830.txt)

**Comment by MlgmXyysd** [comment]
@Hxppdv Try https://ci.appveyor.com/api/buildjobs/i521a77l6nqias5r/artifacts/edxp-core%2Frelease%2FEdXposed-v0.5.2.2_4683-master-release.zip instead

**Comment by Hxppdv** [comment]
@MlgmXyysd Still not working and once I activate xprivacylua in edxposed manager and restart the system, all apps start crashing, same problem occurs in v0.5.2.1, tried the 0.5.2.2 version you mentioned and the problem is still there. None of the other modules have this problem, and older versions of edxposed are working. 
[EdXposed_Verbose_20210214_154400.txt](https://github.com/ElderDrivers/EdXposed/files/5977155/EdXposed_Verbose_20210214_154400.txt)

**Comment by MlgmXyysd** [comment]
@Hxppdv https://ci.appveyor.com/api/buildjobs/i521a77l6nqias5r/artifacts/edxp-core%2Frelease%2FEdXposed-v0.5.2.2_4683-master-debug.zip
okay, use debug version to get logs

**Comment by Hxppdv** [comment]
@MlgmXyysd Okay, the log is here
[EdXposed_Verbose_20210214_160503.txt](https://github.com/ElderDrivers/EdXposed/files/5977166/EdXposed_Verbose_20210214_160503.txt)

**Comment by MlgmXyysd** [comment]
@Hxppdv No errors were found in the latest log

**Comment by MlgmXyysd** [comment]
@Hxppdv btw, there is always a rom fatal error in your log, it is recommended to submit it to the rom author (only suggestions, not related to this issue)

**Comment by Hxppdv** [comment]
> @Hxppdv btw, there is always a rom fatal error in your log, it is recommended to submit it to the rom author (only suggestions, not related to this issue)

@MlgmXyysd I think you mean the problem of all the apps crashing is a ROM problem, indeed after updating the ROM, the app crashing problem is solved,
but xprivacylua still can't be activated, here is the new log, hope it helps.
[EdXposed_Verbose_20210214_221950.txt](https://github.com/ElderDrivers/EdXposed/files/5977873/EdXposed_Verbose_20210214_221950.txt)

**Comment by Hxppdv** [comment]
@MlgmXyysd I'm sorry for the problem, it's strange but I finally found out after trying multiple ROMs that it's actually a ROM problem. Anyway thank you very much for your help!
