### ISSUE TITLE
[BUG] MIUI double open failure

### ISSUE THREAD

**Issue by SamoZ** [ElderDrivers/EdXposed#834]
**什么情况/What happened?**
MIUI 11.0.4.0版本双开微信模块失效。
尝试了双开 EdExposed Manager，但是双开的 EdExposed Manager 找不到模块，尝试安装，安装成功，模块仍然找不到。
data/0/config 复制到 data/999/ 下仍然失败。

**Xposed模块列表/Xposed Module List**
![Screenshot_2021-02-19-23-56-39-540_org meowcat ed](https://user-images.githubusercontent.com/25240164/108529398-661fdd00-730f-11eb-85ce-f93eceac5575.jpg)
![Screenshot_2021-02-19-23-59-37-979_org meowcat ed](https://user-images.githubusercontent.com/25240164/108529692-b139f000-730f-11eb-8821-9969403652ff.jpg)

**Magisk模块列表/Magisk Module List**
![Screenshot_2021-02-19-23-56-09-768_com topjohnwu](https://user-images.githubusercontent.com/25240164/108529422-6cae5480-730f-11eb-82c8-bc5969d6ef7a.jpg)
![Screenshot_2021-02-19-23-55-50-629_com topjohnwu](https://user-images.githubusercontent.com/25240164/108529703-b5660d80-730f-11eb-9107-3f5e4d4a8437.jpg)

**版本信息/Versions**

Android: 9

Magisk: 21.4

Riru: 23.5

EdXposed: 0.5.2.2_4683-master

![Screenshot_2021-02-20-00-08-59-645_com android se](https://user-images.githubusercontent.com/25240164/108529889-ecd4ba00-730f-11eb-9b12-397c0d2afdd2.jpg)

**相关日志/Related Logs**
[EdXposed_Modules_20210219_235858.txt](https://github.com/ElderDrivers/EdXposed/files/6011255/EdXposed_Modules_20210219_235858.txt)
[EdXposed_Verbose_20210219_235912.txt](https://github.com/ElderDrivers/EdXposed/files/6011256/EdXposed_Verbose_20210219_235912.txt)

**Comment by MlgmXyysd** [comment]
@SamoZ miui限制了无图标应用(如模块)的双开，hook掉限制的方法即可

**Comment by SamoZ** [comment]
@MlgmXyysd 请教下，怎么hook掉限制的方法，谢谢

**Comment by MlgmXyysd** [comment]
@SamoZ 写个xp模块hook掉这个方法返回true即可，或者找已经有此功能的模块(或者等我咕咕咕)

boolean com.miui.securitycore/com.miui.xspace.XSpaceCompat.pkgHasIcon(Context, String)

**Comment by MlgmXyysd** [comment]
@SamoZ https://repo.xposed.info/module/org.meowcat.xposed.miui
