### ISSUE TITLE
[BUG] 0.5.2.2 breaks module

### ISSUE THREAD

**Issue by fusionneur** [ElderDrivers/EdXposed#837]
Upgrading from 0.5.2.1_4677 to 0.5.2.2_4683 breaks xprivacy lua module

**Comment by fusionneur** [comment]
Android 10, magisk 21.4

**Comment by ltGuillaume** [comment]
Same here!

**Comment by fusionneur** [comment]
I reinstalled everything and still  not working on 0.5.2.2

**Comment by SekiBetu** [comment]
https://github.com/LSPosed/LSPosed/commit/c23e172bac01d8eee86482682949bbb25be35ce1
this change may fix it

**Comment by fusionneur** [comment]
Can we have the issue reopened? Why is it closed?
