### ISSUE TITLE
[BUG] Installation failure on Android 9 saying Android below Oreo

### ISSUE THREAD

**Issue by yuuuxt** [ElderDrivers/EdXposed#840]
**什么情况/What happened?**

Installation failure on Android 9 saying below Oreo

**Xposed模块列表/Xposed Module List**

NA

**Magisk模块列表/Magisk Module List**

Riru only

**版本信息/Versions**

Android:9

Magisk:20.4

Riru:23.6

EdXposed:NA (trying to install 0.5.2.2)

不支持的安卓版本 (Oreo 以下版本)

**Comment by MlgmXyysd** [comment]
Magisk bug and should fix in https://github.com/topjohnwu/Magisk/commit/1426ee2ebd27060b9bb8b415afd8bc5b96bf663e
