### ISSUE TITLE
[BUG] edXposed thinks it's not installed properly but it is working.

### ISSUE THREAD

**Issue by MarcinOrlowski** [ElderDrivers/EdXposed#844]
**什么情况/What happened?**

I upgraded to Magisk 22 and also got recent edXposed and things stopped working properly. Opening edXposed welcomes me with this:

![Screenshot_20210301-204749](https://user-images.githubusercontent.com/8041294/109554341-61f47c00-7ad4-11eb-8300-3630d9d54978.jpg)

However modules do work. Still, checking logs indicates some problems:

```
--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ support group: 855219808
Telegram support group: @Code_Of_MeowCat
Telegram channel: @EdXposed
--------- beginning of information
Manufacturer: OnePlus
Brand:
Device: OnePlus7Pro
Product: OnePlus7Pro
Model: GM1913
Fingerprint:
ROM description: OnePlus7Pro-user 10 QKQ1.190716.003 2007240000 release-keys
Architecture:
Android build: QKQ1.190716.003
Android version: 10
Android sdk: 29
EdXposed version: v0.4.6.2 (4529) (SandHook)
EdXposed api: 91.0
Riru version:  ()
Riru api:
Magisk: 22.0 (22000)
--------- beginning of main
--------- beginning of system
--------- beginning of crash
```

note missing Riru version and Api.

Magisk:

![Screenshot_20210301-071347](https://user-images.githubusercontent.com/8041294/109554565-aed85280-7ad4-11eb-8170-41491a077c3d.jpg)

**版本信息/Versions**

Android: 10
Magisk: 22
Riru: 23.6
EdXposed: 0.5.2.2_4683-master

I am aware of bug #828 and others. Tried all described there with no luck.

**Comment by etmatrix** [comment]
From release 0.5.2.2
Edxposed Manager v4.6.0 or higher is required and is not compatible with previous versions.
