### ISSUE TITLE
Not Loading any modules.

### ISSUE THREAD

**Issue by DrSaad77** [ElderDrivers/EdXposed#847]
I recently updated to most most recent Riru (v.23.8) and EdXposed too (v0.5.2.2_4683 Master Release), and EdXposed is not loading any modules, and it seems even like the EdXposed is not present while EdXposed Manager says it is installed and working!
I tried to reboot a few times, even tryed an old trick: desactivate all modules, reboot, then re-activate them, and reboot again, still the same not loaded.
I even repeated everything from scrach, same issue.
Uninstall everything till Magisk, and re-install everything, Magisk > Riru > EdXposed, then my modules, still same issue ((
On every update of Riru/ EdXposed, I am experiencing this problem. Really a pain ((
Any help please?

**Comment by etmatrix** [comment]
Try to see #844
I think you should be update also Manager now 4.6.2 is required

**Comment by DrSaad77** [comment]
Thx, after a lot of uninstall + re-install, it finally works.
For anyone if it can help:
a lot of clean Dalvik + Cache, in TWRP, and all a lot of reboots, and it finally loads.
Also I removed everything, and re-strarted from zero, un-root, then clean Dalvik&Cache, and re-root, then try the EdXposed part. I also use EdXposed Remover in TWRP... 
After fresh Masgisk Root, install Riru > Reboot, then Riru EdXposed, then install the most recent EdXposed Manager.
