### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kev1nKe** [ElderDrivers/EdXposed#848]
**什么情况/What happened?**
小米11 官方微信分身 微X模块不出来.

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 21.4

Riru: 23.9

EdXposed: 0.5.1.4 sandhook

**相关日志/Related Logs**

**Comment by MlgmXyysd** [comment]
#824
