### ISSUE TITLE
[BUG]  ColorQQ开启后QQ无法正常启动

### ISSUE THREAD

**Issue by Chengzhir** [ElderDrivers/EdXposed#85]
**什么情况/What happened?**

开启ColorQQ后打开QQ，会黑屏一段时间后出现启动图，很快继续黑屏，一段时间后再出现启动图……无法进入QQ。（ColorQQ是一个QQ美化模块，链接：https://pan.baidu.com/s/1rjIQMPHlenmINAHZ8EQieA 提取码：oen1）

**Xposed模块列表/Xposed Module List**

![2019-2-17_19-38-35](https://user-images.githubusercontent.com/47712894/52912389-db551380-32eb-11e9-895a-60864829c360.PNG)

**Magisk模块列表/Magisk Module List**

![2019-2-17_19-44-25](https://user-images.githubusercontent.com/47712894/52912442-8665cd00-32ec-11e9-9920-5dd4b6c2bb22.PNG)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: v0.2.9.8_beta1 （之前版本也一样）

Riru: v11/v13

**相关Logcat/Logcat**

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by hkcnjd** [comment]
我跟你一样，三星9.0系统，不管用哪一个版本的EDXP只要一启用ColorQQ后都会导致QQ无限闪退。

**Comment by solohsu** [comment]
我这边无法定位到问题，需要模块开发者来定位问题并来这边反馈。
