### ISSUE TITLE
[BUG] EdXposed Framework in not (properly) installed after Magisk update

### ISSUE THREAD

**Issue by Dark-Yox** [ElderDrivers/EdXposed#856]
**什么情况/What happened?**

Everything was working fine until I installed the new update of Magisk (22.1)
(Already tried reinstalling both Riru and EdXposed from Magisk, same problem)

**Xposed模块列表/Xposed Module List**

Dark Tricks
GravityBox [R]
HiddenCore Module
Instaprefs
Lucky Patcher

**Magisk模块列表/Magisk Module List**

Busybox for Android NDK
Nano for Android NDK
Riru
Riru - EdXposed
Universal SafetyNet Fix

**版本信息/Versions**

Android: 11
Magisk: 22.1
Riru: 25.3.4
EdXposed: 0.5.2.2

**相关日志/Related Logs**

Log is empty.

**Comment by stupidanon** [comment]
I also get a never ending boot screen when I try to boot with Riru and Edxposed

**Comment by stupidanon** [comment]
I fixed my issue by updating magisk to latest canary version

**Comment by Dark-Yox** [comment]
The canary version is deprecated and archived. It's just a downgrade at this point.

**Comment by stupidanon** [comment]
> 
> 
> The canary version is deprecated and archived. It's just a downgrade at this point.

Isn't canary release meant to be the most recent?

**Comment by Dark-Yox** [comment]
Yes, but as I said it's archived and the last update was a month ago. Look for yourself : https://github.com/topjohnwu/magisk_files/tree/canary

**Comment by stupidanon** [comment]
> Yes, but as I said it's archived and the last update was a month ago. Look for yourself : https://github.com/topjohnwu/magisk_files/tree/canary

I updated from the magisk manager app, does the app pull from that repo?

**Comment by Dark-Yox** [comment]
How did you update from the app? You should only be able to see the Stable and Beta channel

**Comment by Saumer7** [comment]
I have same problem when I update magisk 21.4 to 22
https://github.com/topjohnwu/Magisk/issues/3898
try this once.. this fixed problem on my device

**Comment by Dark-Yox** [comment]
`topjohnwu/Magisk#3898` I don't have the same error in Magisk logs. I think the problem is affecting Riru entirely since I tried another Riru module and it doesn't work.

Downgrading Magisk to 21.4 doesn't solve the problem either, I will try to downgrade Riru.
Downgrading Riru to 23.9 solved the problem. (Work fine with Magisk 22.1 too)
I will close this issue since the culprit isn't EdXposed

**Comment by ktaczek** [comment]
Magisk przestał wspierać edxposed pisali o tym niedawno

**Comment by ktaczek** [comment]
Wystarczy z magisk usunąć riru edxposed
![Uploading Screenshot_20210919-021245.png…]()
