### ISSUE TITLE
EdXposed v0.5.2.2_4683 cannot hook "android" package name in Android 11

### ISSUE THREAD

**Issue by elesbb** [ElderDrivers/EdXposed#858]
Android Version: Android 11
Device: Samsung Galaxy S10 5G
Magisk: 22.0
Riru: v25.3.4.r399.84f7084

I have the following code:

`if (loadPackageParam.packageName.contains("android")) {
            XposedBridge.log("Hooked android");
        }`

But I never get that log in the edxposed manager. It is like its ignoring xposed.

**Comment by HourMafia** [comment]
https://github.com/ElderDrivers/EdXposed/issues/858#issue-855536755

**Comment by elesbb** [comment]
> [#858 (comment)](https://github.com/ElderDrivers/EdXposed/issues/858#issue-855536755)

I upgraded to Canary Magisk and all is fine again. I did a lot of searching since posting this and never came back to post my results. But using canary magisk brings it back.
