### ISSUE TITLE
[BUG] SafetyNet failure since 21/06/2021 google update

### ISSUE THREAD

**Issue by nyakze** [ElderDrivers/EdXposed#866]
**什么情况/What happened?**
Google has updated SafetyNet algorithm and now blocks completing SafetyNet test with EdXposed module installed. Google Pay no longer works.

**Xposed模块列表/Xposed Module List**
any

**Magisk模块列表/Magisk Module List**
any

**版本信息/Versions**

Android: 10 (any)

Magisk: 22.1 and 23

Riru: 22-25

EdXposed: 0.5.2.2

**相关日志/Related Logs**

-

**Comment by JustResurrected** [comment]
Confirm for A11

**Comment by Conan179** [comment]
Confirm broken pass for Note 20 ultra 5g (Android 11), note 9 (android 10) and s5e (android 11), all Samsung Devices.

**Comment by nyakze** [comment]
Currently the only solution seem to be switch to lsposed until it's fixed

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/500
