### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mayank1470** [ElderDrivers/EdXposed#867]
SafetyNet Checks fails here while SafetyNet works on LSPoised

**什么情况/What happened?**

 SafetyNet was working initially and stopped working since last 3 days

**Xposed模块列表/Xposed Module List**
XPrivacyLua

**Magisk模块列表/Magisk Module List**

- Universal SafetyNet Fix
- Riru
- Riru EdXposed

**版本信息/Versions**

Android: 11

Magisk: 23.0

Riru: 25.4

EdXposed: 0.5.2.2

**相关日志/Related Logs**

**Comment by MlgmXyysd** [comment]
#500
