### ISSUE TITLE
[BUG] Google pay contactless not configured

### ISSUE THREAD

**Issue by nyakze** [ElderDrivers/EdXposed#868]
**什么情况/What happened?**
As of 21/06/2021 Google Pay no longer works with edxposed riru module installed - Not configured / Device not compatible with contactless payment

**Xposed模块列表/Xposed Module List**
any

**Magisk模块列表/Magisk Module List**
Riru
Riru-edxposed

**版本信息/Versions**

Android: 10 (or any other)

Magisk: 22.1 and 23

Riru: 22-25

EdXposed: 0.5.2.2

**相关日志/Related Logs**

This bug is not related to SafetyNet test #500 , as Google Pay did work before and now it doesn't. Saying software on your phone doesn't meet the requirements for contactless payments.

**Comment by MlgmXyysd** [comment]
safetynet problem
