### ISSUE TITLE
Canary Install/Update issues

### ISSUE THREAD

**Issue by Accentaro** [ElderDrivers/EdXposed#871]
Issue: Once the latest version of edxposed manager is installed everything works as it should except that it will trigger safety net even using all the built in features or modules to get around it.

So I went to install Canary, once I click Canary the app will just force close and no download will start.

Also checked on the CI page but the artifacts tab shows ''this build job contains no artifacts".

**Comment by MlgmXyysd** [comment]
> Also checked on the CI page but the artifacts tab shows ''this build job contains no artifacts".

CI build will be automatically deleted in a month. Currently, alpha is the same as canary.
