### ISSUE TITLE
[BUG]  Error detect riru

### ISSUE THREAD

**Issue by 9WW7XxHy** [ElderDrivers/EdXposed#873]
Android: 10

Magisk: 21.4

Riru: 26.0

EdXposed: Latest

it doesn't detect riru . Please check

**Comment by MlgmXyysd** [comment]
The author of Riru is very self-righteous, it discards API compatibility again. For the time being, we don't have the energy to follow an API that is extremely unfriendly to development and compatibility, use Riru v25.4.4 instead: https://t.me/EdXposed/136

**Comment by Feda777Feda** [comment]
> Android: 10
> 
> Magisk: 21.4
> 
> Riru: 26.0
> 
> EdXposed: Latest
> 
> it doesn't detect riru . Please check

**Comment by dreamingtech** [comment]
Same as Riru-26.1.3, Solved by install 25.4.4

**Comment by crifan** [comment]
same issue, fixed by install: 

* Riru v25.4.4
  * https://github.com/RikkaApps/Riru/releases
    * https://github.com/RikkaApps/Riru/releases/download/v25.4.4/riru-v25.4.4-release.zip

result:

* Magisk
    * ![D643C199-CE66-4DAB-B547-7A3190BA50FB](https://user-images.githubusercontent.com/2750682/190432774-8db15a3f-d066-4f93-a735-43eb3cf93a55.png)
* EdXposed Manager
  * ![4E45B43F-56C0-4158-B3BB-F9C4C364966D](https://user-images.githubusercontent.com/2750682/190432701-30c5e1a2-b40d-4901-989f-81f5ee52fcdc.png)
