### ISSUE TITLE
[BUG] after update Riru version to "v26.0.1" or "v26.0.2", "EdXposed-v0.5.2.2" can't install success 

### ISSUE THREAD

**Issue by guangdeshishe** [ElderDrivers/EdXposed#875]
**什么情况/What happened?**

not support Riru v_6.0.1 or v6.0.2

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 23.0

Riru: 26.0.2

EdXposed: v0.5.2.2

**相关日志/Related Logs**

`- Copying zip to temp directory
- Installing Riru_EdXposed-v0.5.2.2_4683-master.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***********************
 Riru - EdXposed 
 by solohsu, MlgmXyysd 
***********************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: zh_CN.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: zh_CN.sh.s
- EdXposed 版本 v0.5.2.2_4683-master
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh.s
- 已验证 customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh.s
- 已验证 util_functions.sh
- Android SDK 版本: 30
- Magisk 版本: 23000
*********************************************************
! 未安装
! 请先从 Magisk Manager 中安装 Riru
*********************************************************
! Installation failed`

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/873#issuecomment-884770326
