### ISSUE TITLE
[BUG] 三星s9+国行9.0系统，无太极模块，无法启用

### ISSUE THREAD

**Issue by weisyr** [ElderDrivers/EdXposed#88]
三星s9+国行9.0系统，无太极模块，无法启用

**Comment by solohsu** [comment]
https://github.com/RikkaApps/Riru/pull/18
@weisyr 试试这个

**Comment by weisyr** [comment]
> [RikkaApps/Riru#18](https://github.com/RikkaApps/Riru/pull/18)
> @weisyr 试试这个

用上，成功启用了框架，但是大多插件勾选重启后提示平没有启用插件，最强大的edge也没法启用

**Comment by solohsu** [comment]
试试 v0.2.9.9_beta2
