### ISSUE TITLE
[BUG] Android 11, Riru-Exposed V0.5.2.2 Installation Failed

### ISSUE THREAD

**Issue by megajeffcoding** [ElderDrivers/EdXposed#881]
**什么情况/What happened?**

! 未安装
! 请先从 Magisk Manager 中安装 Riru

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 23.0(230000)

Riru: V26.1.1.r500.45d2706e83

EdXposed: V0.5.2.2_4683-master

**相关日志/Related Logs**

**Comment by gallegonovato** [comment]
Good afternoon:

At the end if it influences Riru to update or install Riru Exposed.

What I did was to remove Riru and Riru Exposed from Magisk. I also uninstalled Exposed and XprivacyLua.

Then I rebooted the phone. Once booted, I ran lte cleanner from fdroid and sd maid. And clear all caches.

Abtes I had seen a video, of a Mr., I think he is Indian. That is https://youtu.be/RoLLTC-Gw-M where you can see that the solution is to disable Riru. But it did not work at all. Xposed and XprivacyLua not hiban.

Then I checked that magisk and magisk manager were in their latest version. They were.

Then I went to https://github.com/RikkaApps/Riru/releases . And I looked for version 25.4.4 release (https://github.com/RikkaApps/Riru/releases/tag/v25.4.4) 

Then from Riru Exposed I installed the one that comes up in the magisk module finder. Here I did tell it to reboot.

Then I downloaded the latest version of exposed https://github.com/ElderDrivers/EdXposedManager/releases

In exposed, it started fine, I checked the afwall+ module in my case. At the top of exposed you look for reboot, system. You are prompted by magisk to give you superuser permission. You accept it. Let it reboot.

Then install XprivacyLua. (In my case). Activate the module in Xposed.

And everything working.

A hug

**Comment by GanHongjie** [comment]
I encountered the same problem. it says i dont install the Riru module

**Comment by MlgmXyysd** [comment]
Hello, we regret that riru is constantly blocking downstream modules during development. Please DO NOT update the new version of riru. For more details, see https://github.com/ElderDrivers/EdXposed/issues/878
