### ISSUE TITLE
can not find riru[BUG] 

### ISSUE THREAD

**Issue by dutccr** [ElderDrivers/EdXposed#882]
can not find riru, however i installed it firstly.

**什么情况/What happened?**
android 10 pix3a, install edxposed v0.5.2.2_4683-master version
 我已经在magisk里装了riru最新版本26.1.1，当我安装edxposed v0.5.2.2_4683-master的时候，提示我安装失败，找不到riru，然后跳转到riru的github页面。

**Comment by MlgmXyysd** [comment]
Hello, we regret that riru is constantly blocking downstream modules during development. Please DO NOT update the new version of riru. For more details, see #878

**Comment by dutccr** [comment]
thank you very much for your quick response!!!!
