### ISSUE TITLE
can't find riru module, however i already installed it successfully

### ISSUE THREAD

**Issue by dutccr** [ElderDrivers/EdXposed#883]
use magisk manager 23.0 , install riru 26.1.1 version, then want to install  edxposed v0.5.2.2_4683, but failed , and show the log that need to install riru from magisk manager firstly. and then change the web ui to riru github.

android 10 
pixel 3a.

help! what happened? I cost too much time on this issue. thanks a lot in advance.

**Comment by MlgmXyysd** [comment]
Hello, we regret that riru is constantly blocking downstream modules during development. Please DO NOT update the new version of riru. For more details, see #878
