### ISSUE TITLE
[BUG] does not support Riru v26.1.1

### ISSUE THREAD

**Issue by timberdai** [ElderDrivers/EdXposed#885]
**什么情况/What happened?**

![image](https://user-images.githubusercontent.com/49051507/131868154-612af9ed-acb0-4cb7-a4ae-2d228f5a1e60.png)

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 23

Riru:26.1.1

EdXposed:4.6.2

**相关日志/Related Logs**

- [ ] 

1. 

- 

>

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/878

**Comment by timberdai** [comment]
> #878

thx~
