### ISSUE TITLE
[BUG] Unable to flash with new Riru Core

### ISSUE THREAD

**Issue by inao-cz** [ElderDrivers/EdXposed#887]
I'm unable to flash EdXposed with a new version of Riru. In logs I'm getting reported: 

! is not installed
! Please install Riru from Magisk Manager

**版本信息/Versions**

Android SDK: 29
Magisk: 23.0
Riru: 26.1.2.r505.c20529bced
EdXposed: -

**Comment by MBRjun** [comment]
使用 25.4.4 版本 Riru
use v25.4.4
