### ISSUE TITLE
[BUG] hook location not working oreo

### ISSUE THREAD

**Issue by erkie24** [ElderDrivers/EdXposed#89]
Hi, hook android location (latitude and longitude) works great on Pie (AOSP Rom). But I got strange bugs on MIUI 10 (Oreo). The error log "E/LocSvc_SystemStatus: PQWM1parser - invalid size=23" shows every times. After that error log show up, the device can't get current location until I force kill app module, and then current location works normal again.

Any suggestions about this error? Thanks so much.

**Comment by solohsu** [comment]
Sorry I am not familiar with GPS framework. Have you checked the source code [here](http://androidxref.com/8.1.0_r33/xref/hardware/qcom/gps/msm8998/core/SystemStatus.cpp#186), maybe it can help you figure out what's going on?

**Comment by erkie24** [comment]
Oh sorry I got it wrong, sometimes after I switch from App A to App B, edxposed failed to hook App A again.
Here's the log : 
2019-02-18 20:56:44.025 1979-3223/? D/ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{6e777d6 com.xxx.xxx
2019-02-18 20:56:44.025 1979-3223/? E/ActivityTrigger: activityStartTrigger: not whiteListed com.xxx.xxx

So I need to force kill App A, and it can hook again.
