### ISSUE TITLE
Xposed wont install, says Riru isnt installed when it is.

### ISSUE THREAD

**Issue by SecondAery** [ElderDrivers/EdXposed#891]
Trying to install closed 5.2.2 and magisk opens the riru github page saying it needs to be installed, however I have Rori 26.1 installed already. This issue started around a month ago. Whether I try and install it directly from magisk, or from the zip provided by the manager I get the same error.

![Screenshot_20210929-064012450__01](https://user-images.githubusercontent.com/71466483/135253366-5c1e11a8-89e6-4204-a2f2-c264fd79210c.jpg)

![Screenshot_20210929-064053872__01](https://user-images.githubusercontent.com/71466483/135253443-2e10ef5b-7619-401a-b90d-16b944e950d8.jpg)

![Screenshot_20210929-064203128__01](https://user-images.githubusercontent.com/71466483/135253631-9cad9301-496b-4d6f-ab11-3bf393eaf724.jpg)

![Screenshot_20210929-064411549__01](https://user-images.githubusercontent.com/71466483/135253866-c967bd0f-b441-4e20-9ceb-9c062c861b36.jpg)

**Comment by ghost** [comment]
Same problem here. Tried to downgrade Riru versiyon but didnt work.

**Comment by delvil95** [comment]
delete riru 26.1.2 then reinstall 25.4.4

**Comment by kuba888** [comment]
i found this https://github.com/ElderDrivers/EdXposed/issues/878 and now i wondering if installed 26.1.2 before ,and i had the same issues with exposed ,what should i do now ,wipe and clean install ROM ,is that version 26.1.2 of riru is danger? What do you suggest, usually delete  from Magisk  that Riru versin 26.1.2 is enough ?

**Comment by delvil95** [comment]
Disable module 26 and then reinstall module 25. No further steps needed

**Comment by elesbb** [comment]
> Disable module 26 and then reinstall module 25. No further steps needed

But why? What is wrong with edxposed and version 26+ of Riru? Did they change how Riru is detected again? I remember this being a problem in the past

**Comment by xiaoxi-ij478** [comment]
seems like 26 riru has no api_version under /data/adb/riru while edxposed requires it.

**Comment by ihipop** [comment]
any update for this issue?

**Comment by Ivaniku** [comment]
The fact that we have to downgrade Riru is actually a really bad security flaw, I think this should be fixed ASAP
