### ISSUE TITLE
[BUG] Can't be installed with Riru 26.1.3

### ISSUE THREAD

**Issue by kppomzh** [ElderDrivers/EdXposed#901]
**什么情况/What happened?**
![Screenshot_20211104-074321_Magisk](https://user-images.githubusercontent.com/16862592/140234169-40dc4bdb-3d16-44e6-a050-cd0b5542b6ae.png)
![Screenshot_20211104-074334_Magisk](https://user-images.githubusercontent.com/16862592/140234172-451e7406-777b-4d76-a014-1845395d092e.png)

install failed

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android: 11

Magisk: 23

Riru: 26.1.3

EdXposed: 0.5.2.2

**相关日志/Related Logs**

**Comment by r-brown-git** [comment]
have the same problem

**Comment by maiavixen** [comment]
Same issue here

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/878

**Comment by aioros57** [comment]
Hello, same problem magisk 23.0 module install riruv26.1.3 and riru LSPsed 1.6.3. Riru edXposed v0.5.2.2_4683-master installation not possible.
Samsung S10 SM-G973F android 11 official firmware no custom root yes
Good evening, following my tests I have installed riru 25.4.4 with magisk and edxposed manager v 4.6.2 activated ok it works. Magisk safetynet problem "attestation not granted", if I change riru to version 26.1.3 attestation granted ok my edxposed turns off.
