### ISSUE TITLE
v0.2.9.9_beta1 - Xposed not installed

### ISSUE THREAD

**Issue by bggold** [ElderDrivers/EdXposed#91]
I just upgraded to v0.2.9.9_beta1 from v0.2.9.8_beta1 and now xposed installer reports xposed framework is not installed.

**Comment by MlgmXyysd** [comment]
It should fixed in a315373de306ec7f87ee81261fd7841ec0795b92.

**Comment by bggold** [comment]
Thanks I will wait for it to post.

**Comment by MlgmXyysd** [comment]
Go to releases to download 0.2.9.9_b1

**Comment by bggold** [comment]
It still shows the one I installed.

**Comment by bggold** [comment]
I downloaded it again and it worked.  Sorry thought it would be a new
version.

**Comment by bggold** [comment]
Also I am not able to view the logs from the installer.  Should I open a
new issue?  I know this was an issue with the original installer by
dvdandroid.

Cannot read
log/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log (No such
file or directory)

**Comment by bggold** [comment]
2.9.9 broke and I removed the modules and reinstalled 2.9.8 and now my
Xposed modules that were working no longer work.

Any help please.

Thanks

**Comment by MlgmXyysd** [comment]
Try re-check module in installer, the difference between 299 and 298 only add log feature.

**Comment by bggold** [comment]
Really weird one module just stopped working after going back to 2.9.8. It
is working in my test device with 2.9.9.  I know it all beta.  Installed
another module that does the same function and it works.

Why was 2.9.9 pulled?  Just courious.

Thanks

**Comment by 2220209876** [comment]
> 转到发布版下载0.2.9.9_b1

发布页没有找到0.2.9.9版本最新的是228

**Comment by manofsteel2017** [comment]
where 2.99?

**Comment by bggold** [comment]
I have not tried the new release from today yet.

**Comment by bggold** [comment]
Sorry thought a new one can down.  Yes 2.9.9 caused problems.

**Comment by bggold** [comment]
I think they pulled it.
