### ISSUE TITLE
NOT ABLE TO FLASH ZIP OF EDXPOSED

### ISSUE THREAD

**Issue by chetanxpatil** [ElderDrivers/EdXposed#912]
![Screenshot_20220202-013311_Settings.png](https://user-images.githubusercontent.com/71105582/152043874-a1a0d46d-61e8-4a93-960a-14f6fa2af224.png)

![Screenshot_20220202-013306_Settings.png](https://user-images.githubusercontent.com/71105582/152043895-87cebc8c-5ad3-438b-a7e0-efaaa941d79c.png)

**Comment by niihari** [comment]
Did you read the announcement #878?
The error message suggests you're trying to use Riru 26+.
