### ISSUE TITLE
[BUG] v0.2.9.9_beta1在三星s9+上开启了框架，但勾选xposed edge pro 提示未安装xposed

### ISSUE THREAD

**Issue by weisyr** [ElderDrivers/EdXposed#92]
v0.2.9.8_beta1版开始，在三星s9+上开启了框架，但勾选xposed edge pro 提示未安装xposed，望作者设配三星9.0系统，谢谢

**Comment by solohsu** [comment]
Riru的适配问题，有人已修复并分享了修复版的riru-core模块
https://github.com/ElderDrivers/EdXposed/issues/39#issuecomment-464584166
