### ISSUE TITLE
[功能请求] 能不能让指定模块对指定app有效？

### ISSUE THREAD

**Issue by lukemin** [ElderDrivers/EdXposed#93]
让指定模块对指定的app生效，对其他app不生效，这样可以减少很多的fc几率，毕竟大多数的模块都是针对单一或几个app的。

**Comment by MlgmXyysd** [comment]
请使用白名单功能。

**Comment by lukemin** [comment]
> 请使用白名单功能。

白名单没有用，因为白名单设置的要生效的app，但是没有限制模块，像现在的微信我加入白名单，所有的启用的模块都会对其生效，但是有些模块会导致点微信钱包功能闪退，而我又想用这些模块，我只能忍受这个bug了！

**Comment by 2220209876** [comment]
感觉挺好的想法，估计有点难以实现。
