### ISSUE TITLE
[BUG] can`nt use new xsharedpreference

### ISSUE THREAD

**Issue by hitwhoyxw** [ElderDrivers/EdXposed#931]
I found the wiki https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences,and follow what it said,add matadata and use 
sharedPreferences=context.getSharedPreferences(configName, Context.MODE_WORLD_READABLE);
when I start my module,it crashed and the log shows java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.larkdemo/com.android.larkdemo.Activity.MainActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
how to solve this problem?

**Comment by MlgmXyysd** [comment]
@hitwhoyxw For module compatibility across frameworks, you should not use so-called new APIs that are only available in one framework.Please refer to the official Xposed documentation when developing modules: https://github.com/rovo89/XposedBridge/wiki
https://api.xposed.info/

We have no support plan for children forks.

**Comment by Dr-TSNG** [comment]
> @hitwhoyxw For module compatibility across frameworks, you should not use so-called new APIs that are only available in one framework.Please refer to the official Xposed documentation when developing modules: https://github.com/rovo89/XposedBridge/wiki https://api.xposed.info/

Amusing. This wiki page is written by yourself.
https://github.com/ElderDrivers/EdXposed/wiki/New-XSharedPreferences

**Comment by Young-Lord** [comment]
Have you enabled the module in manager? If no, enable it before opening the module.

**Comment by hitwhoyxw** [comment]
@MlgmXyysd sry，I made a mistake，this should be issued in lsposed,thank u for your reply

**Comment by hitwhoyxw** [comment]
@Young-Lord yeah,I forget to enable it before open my module ,so it is always crash,just enable module it works
