### ISSUE TITLE
Xposed not installed.

### ISSUE THREAD

**Issue by EthanWang32** [ElderDrivers/EdXposed#95]
EdXposed shows not installed after installing 0.2.9.9.

It even not worked when I reinstall to 0.2.9.8.

Waiting for your solution. 

Thanks.

**Comment by QkiZMR** [comment]
for me also. but after soft reboot, it starts working.

**Comment by EthanWang32** [comment]
Thanks for reply. 

But still not working after soft reboot.  :(

**Comment by QkiZMR** [comment]
Did you try disable all modules and full reboot?

**Comment by EthanWang32** [comment]
I tried the version of 0.2.9.9_alpha2.

It works.
