### ISSUE TITLE
[BUG] Xposed is in active status, but module apps not functioning

### ISSUE THREAD

**Issue by cutesniper22** [ElderDrivers/EdXposed#96]
**什么情况/What happened?**
Xposed is in active status, but module apps not working and keep prompted for install xposed

**Magisk模块列表/Magisk Module List**

允许截图/Screenshot allowed : https://drive.google.com/drive/folders/1Tyn080-FYb0ol6V3wh0XZ06UmzFSo44m

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed: 2.9.8 beta 1

Riru: v13

**相关Logcat/Logcat**

No xposed log (log is empty), only magisk log provided.

**Comment by solohsu** [comment]
The module is detecting Xposed Installer package name, try to install the [original installer](https://drive.google.com/open?id=1nJu1tyMybYyF_1FUMg581axJY2DaolgI) to pass it.

**Comment by Ali-Javadi** [comment]
I had this issue and for that you need to install the original xposed installer. Just that. No need opening that or other things. And Use EdXposed installer as Xposed manager. 
Thank you @solohsu

**Comment by solohsu** [comment]
@Ali-Javadi My pleasure.

**Comment by A2HI2H** [comment]
on v0.2.9.8 and latest EdXposed Installer (modules are not detecting the xposed ) though xposed is active , also xposed installer by dvd android is not detecting xposed 

xposed log (module log) - https://pastebin.com/kvEUwKdK

xposed not able to find the module base apk , but it is availabe in the path , i checked manually
