### ISSUE TITLE
[BUG] 三星9 oneui pie edxposed无效

### ISSUE THREAD

**Issue by j0912h** [ElderDrivers/EdXposed#97]
**什么情况/What happened?**

如无法开机/模块无效等
模块无效
**Xposed模块列表/Xposed Module List**
riru v12 edxposed 0.2.9.9_beta1
允许截图/Screenshot allowed
![screenshot_20190220-161754_manager](https://user-images.githubusercontent.com/47808503/53073349-c2827300-3522-11e9-9686-4e8f7b6424a7.jpg)

**Magisk模块列表/Magisk Module List**
riru v12 edxposed 0.2.9.9_beta1
允许截图/Screenshot allowed
![screenshot_20190220-161833_manager](https://user-images.githubusercontent.com/47808503/53073379-d6c67000-3522-11e9-8e5b-1b34a0e4b8a6.jpg)

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0.2.9.9_beta1

Riru:v13

**相关Logcat/Logcat**
[boot-2019-02-20-16-20-24.log](https://github.com/ElderDrivers/EdXposed/files/2883452/boot-2019-02-20-16-20-24.log)

有助于定位问题，必须使用我们的log抓取模块抓取/It can help us to locate issue, must use our logcat module

**Comment by j0912h** [comment]
最新的日志
[boot-2019-02-20-16-24-48.log](https://github.com/ElderDrivers/EdXposed/files/2883474/boot-2019-02-20-16-24-48.log)

**Comment by solohsu** [comment]
@j0912h 
Riru的适配问题，有人已修复并分享了修复版的riru-core模块
https://github.com/ElderDrivers/EdXposed/issues/39#issuecomment-464584166
