### ISSUE TITLE
wifi and bluetooth devices needs repairing after enabling samsung pie

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposed#99]
Hi my wifi is forgotten and bluetooth devices are gone from saved list after enabling in and rebooting device.

I can forgot and add wifi and repair bluetooth devices but again on next reboot wifi is saved but bluetooth saved devices are again gone from list and after i disable only edxposed not riru from magisk and reboot they are fine so issue is with edxposed on samsung stock pie roms.

Riru v15 now supports samsung stock pie roms nativehooks replacing.

Galaxy s9+
Os 9.0
Security patch feb19

**Comment by Firefds** [comment]
Using galaxy s8 I don't have this issue.

**Comment by Jasi2169** [comment]
I have on feb2019 security update paired devices gone when edxposed enbaled n rebooted and if you disable it in magisk and reboot they are already paired when edxposed disabled dont know why ?

**Comment by solohsu** [comment]
@Jasi2169 Can you confirm if this issue still exists on v0.3.0.0_b2?

**Comment by Jasi2169** [comment]
Bro tested issue is still not fixed, wifi and bluetooth paired connection gone,disabling and rebooting connect all automatically ,dont know how to get the logs for this,does normal logcat will work ? should i give?

**Comment by taboo180** [comment]
I believe I'm experiencing the same issue if I can help.

**Comment by solohsu** [comment]
@Jasi2169 Yes. Boot logs are needed.

**Comment by Jasi2169** [comment]
Yes here are logs kmsg dmseg

For analyzing you can search "JASI FTTH" which is ssid for wifi which never gets connected when edxposed is ON but when disabled automatically connected.

Logs here : https://www.mediafire.com/file/fcab2ndok51h7gj/2019-03-22_00.rar/file

**Comment by solohsu** [comment]
```
03-22 00:36:31.967 E/SupplicantStaNetworkHal( 4951): failed to set psk passphrase, length is too long 76
03-22 00:36:31.967 E/SupplicantStaIfaceHal( 4951): Failed to save variables for: "JASI FTTH"WPA_PSK
03-22 00:36:31.967 E/SupplicantStaIfaceHal( 4951): Failed to add/save network configuration: "JASI FTTH"WPA_PSK
```
I can't figure out why PSK passphrase is too long. If you can write Xposed module, you can hook related methods to check the passphrase string since I don't have Samsung devices.
Anyway, you can do a quick test firstly by setting SELinux mode to permissive via [Magisk SELinux Manager](https://forum.xda-developers.com/apps/magisk/module-magisk-selinux-manager-t3760042) as I guess it may be an SELinux related issue because the wifi configs are loaded from /data/misc/wifi/.

**Comment by Jasi2169** [comment]
Yes i have checked those logs too. The password for wifi is "jasi2169" which doesnot seems like 76chars. Long  when i disable edxposed it can be connected thats strange

**Comment by taboo180** [comment]
For the record, I believe these two issues are related and have to do with encryption and secure storage:

https://github.com/rovo89/Xposed/issues/294#issuecomment-388661616

I've always had Bluetooth issues of devices losing their pairing for a year or so with my S7 and xposed. That thread may point you in the right direction.

**Comment by Firefds** [comment]
For anyone having this issue - you can try and install a Magisk module called "libsecure_storage compantion for rooted Samsung devices".
It's on the magisk downloads list and should this issue (at least the BT, not sure about wifi)

**Comment by Jasi2169** [comment]
issue fixed by disabling secure_storage onboot

**Comment by lemmy04** [comment]
I'm having a similar issue with my bluetooth settings on a Samsung S5e - no xposed stuff on it at all, only mod is magisk.
Gonna try that libsecure companion module.
